# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES.
# All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.



SPDM_MODULE_PLATFORM_SPECIFIC_PATH := corepdk/platforms/mcxn236/spdm/
SPDM_MODULE_LIBSPDM_INCLUDE := corepdk/modules/spdm/src/app/libspdm/include/
SPDM_MODULE_LIBSPDM_INCLUDE_HAL := corepdk/modules/spdm/src/app/libspdm/include/hal/
SPDM_MODULE_INCLUDE := corepdk/modules/spdm/src/app/

# Include the files in the following paths
INCLUDES += $(SPDM_MODULE_PLATFORM_SPECIFIC_PATH)
INCLUDES += $(SPDM_MODULE_LIBSPDM_INCLUDE)
INCLUDES += $(SPDM_MODULE_LIBSPDM_INCLUDE_HAL)
INCLUDES += $(SPDM_MODULE_INCLUDE)

# Add the source files in the following paths
SOURCES += $(shell find $(SPDM_MODULE_INCLUDE) -maxdepth 1 \
			\( -name "*.cpp" -or -name "*.c" \) \
           -not -name "*-test.cpp" -not -name "*-test.c")

SOURCES += $(shell find $(SPDM_MODULE_PLATFORM_SPECIFIC_PATH) \
			\( -name "*.cpp" -or -name "*.c" \) \
           -not -name "*-test.cpp" -not -name "*-test.c")

SOURCES += $(shell find $(SPDM_MODULE_INCLUDE)/crypto  \
			\( -name "*.cpp" -or -name "*.c" \) \
           -not -name "*-test.cpp" -not -name "*-test.c")

SPDM_MODULE_LIBSPDM:= corepdk/modules/spdm/src/app/libspdm

SOURCES += $(shell find $(SPDM_MODULE_LIBSPDM)/library/spdm_common_lib \
			\( -name "*.cpp" -or -name "*.c" \) \
           -not -name "*-test.cpp" -not -name "*-test.c")
		   
SOURCES += $(shell find $(SPDM_MODULE_LIBSPDM)/library/spdm_responder_lib \
			\( -name "*.cpp" -or -name "*.c" \) \
           -not -name "*-test.cpp" -not -name "*-test.c")
		   
SOURCES += $(shell find $(SPDM_MODULE_LIBSPDM)/library/spdm_transport_mctp_lib \
			\( -name "*.cpp" -or -name "*.c" \) \
           -not -name "*-test.cpp" -not -name "*-test.c")
		   
SOURCES += $(shell find $(SPDM_MODULE_LIBSPDM)/library/spdm_crypt_lib \
			\( -name "*.cpp" -or -name "*.c" \) \
           -not -name "*-test.cpp" -not -name "*-test.c")

SOURCES += $(shell find $(SPDM_MODULE_LIBSPDM)/os_stub/memlib \
			\( -name "*.cpp" -or -name "*.c" \) \
           -not -name "*-test.cpp" -not -name "*-test.c")

SOURCES += $(shell find $(SPDM_MODULE_LIBSPDM)/library/spdm_secured_message_lib \
			\( -name "*.cpp" -or -name "*.c" \) \
           -not -name "*-test.cpp" -not -name "*-test.c")

# define the flags for the libspdm
LIB_SPDM_FLAGS := -DLIBSPDM_ENABLE_CAPABILITY_CHAL_CAP=0
LIB_SPDM_FLAGS += -DLIBSPDM_ENABLE_VENDOR_DEFINED_MESSAGES=0
LIB_SPDM_FLAGS += -DLIBSPDM_ENABLE_CAPABILITY_KEY_EX_CAP=0
LIB_SPDM_FLAGS += -DLIBSPDM_ENABLE_CAPABILITY_PSK_CAP=0
LIB_SPDM_FLAGS += -DLIBSPDM_ENABLE_CAPABILITY_HBEAT_CAP=0
LIB_SPDM_FLAGS += -DLIBSPDM_ENABLE_CAPABILITY_MUT_AUTH_CAP=0
LIB_SPDM_FLAGS += -DLIBSPDM_ENABLE_CAPABILITY_ENCAP_CAP=0
LIB_SPDM_FLAGS += -DLIBSPDM_ENABLE_CAPABILITY_CSR_CAP=0
LIB_SPDM_FLAGS += -DLIBSPDM_ENABLE_CAPABILITY_SET_CERT_CAP=0
LIB_SPDM_FLAGS += -DLIBSPDM_ENABLE_CAPABILITY_CHUNK_CAP=0
LIB_SPDM_FLAGS += -DLIBSPDM_ENABLE_CAPABILITY_MEL_CAP=0
LIB_SPDM_FLAGS += -DLIBSPDM_ENABLE_CAPABILITY_EVENT_CAP=0
LIB_SPDM_FLAGS += -DLIBSPDM_ENABLE_CAPABILITY_GET_KEY_PAIR_INFO_CAP=0
LIB_SPDM_FLAGS += -DLIBSPDM_ENABLE_CAPABILITY_SET_KEY_PAIR_INFO_CAP=0
LIB_SPDM_FLAGS += -DLIBSPDM_ENABLE_CAPABILITY_ENDPOINT_INFO_CAP=0
LIB_SPDM_FLAGS += -DLIBSPDM_ENABLE_CAPABILITY_CSR_CAP_EX=0
LIB_SPDM_FLAGS += -DLIBSPDM_SEND_GET_CERTIFICATE_SUPPORT=0
LIB_SPDM_FLAGS += -DLIBSPDM_SEND_CHALLENGE_SUPPORT=0
LIB_SPDM_FLAGS += -DLIBSPDM_EVENT_RECIPIENT_SUPPORT=0
LIB_SPDM_FLAGS += -DLIBSPDM_SEND_GET_ENDPOINT_INFO_SUPPORT=0
LIB_SPDM_FLAGS += -DLIBSPDM_RESPOND_IF_READY_SUPPORT=0
LIB_SPDM_FLAGS += -DLIBSPDM_FIPS_MODE=0
LIB_SPDM_FLAGS += -DLIBSPDM_DEBUG_ENABLE=0
LIB_SPDM_FLAGS += -DLIBSPDM_MAX_VERSION_COUNT=1
LIB_SPDM_FLAGS += -DLIBSPDM_MAX_ROOT_CERT_SUPPORT=0
LIB_SPDM_FLAGS += -DLIBSPDM_MAX_SESSION_COUNT=0
LIB_SPDM_FLAGS += -DLIBSPDM_MAX_CERT_CHAIN_SIZE=0x1000
LIB_SPDM_FLAGS += -DLIBSPDM_MAX_MEASUREMENT_RECORD_SIZE=0x1000
LIB_SPDM_FLAGS += -DLIBSPDM_MAX_MEL_BLOCK_LEN=0x100
LIB_SPDM_FLAGS += -DLIBSPDM_RECORD_TRANSCRIPT_DATA_SUPPORT=0
LIB_SPDM_FLAGS += -DLIBSPDM_MAX_CERT_CHAIN_BLOCK_LEN=0x100
LIB_SPDM_FLAGS += -DLIBSPDM_RSA_SSA_2048_SUPPORT=0
LIB_SPDM_FLAGS += -DLIBSPDM_RSA_SSA_3072_SUPPORT=0
LIB_SPDM_FLAGS += -DLIBSPDM_RSA_SSA_4096_SUPPORT=0
LIB_SPDM_FLAGS += -DLIBSPDM_RSA_PSS_2048_SUPPORT=0
LIB_SPDM_FLAGS += -DLIBSPDM_RSA_PSS_3072_SUPPORT=0
LIB_SPDM_FLAGS += -DLIBSPDM_RSA_PSS_4096_SUPPORT=0
LIB_SPDM_FLAGS += -DLIBSPDM_ECDSA_P256_SUPPORT=0
LIB_SPDM_FLAGS += -DLIBSPDM_ECDSA_P384_SUPPORT=1
LIB_SPDM_FLAGS += -DLIBSPDM_ECDSA_P521_SUPPORT=0
LIB_SPDM_FLAGS += -DLIBSPDM_SM2_DSA_P256_SUPPORT=0
LIB_SPDM_FLAGS += -DLIBSPDM_EDDSA_ED25519_SUPPORT=0
LIB_SPDM_FLAGS += -DLIBSPDM_EDDSA_ED448_SUPPORT=0
LIB_SPDM_FLAGS += -DLIBSPDM_FFDHE_2048_SUPPORT=0
LIB_SPDM_FLAGS += -DLIBSPDM_FFDHE_3072_SUPPORT=0
LIB_SPDM_FLAGS += -DLIBSPDM_FFDHE_4096_SUPPORT=0
LIB_SPDM_FLAGS += -DLIBSPDM_ECDHE_P256_SUPPORT=0
LIB_SPDM_FLAGS += -DLIBSPDM_ECDHE_P384_SUPPORT=0
LIB_SPDM_FLAGS += -DLIBSPDM_ECDHE_P521_SUPPORT=0
LIB_SPDM_FLAGS += -DLIBSPDM_SM2_KEY_EXCHANGE_P256_SUPPORT=0
LIB_SPDM_FLAGS += -DLIBSPDM_AEAD_AES_128_GCM_SUPPORT=0
LIB_SPDM_FLAGS += -DLIBSPDM_AEAD_AES_256_GCM_SUPPORT=0
LIB_SPDM_FLAGS += -DLIBSPDM_AEAD_CHACHA20_POLY1305_SUPPORT=0
LIB_SPDM_FLAGS += -DLIBSPDM_AEAD_SM4_128_GCM_SUPPORT=0
LIB_SPDM_FLAGS += -DLIBSPDM_SHA256_SUPPORT=0
LIB_SPDM_FLAGS += -DLIBSPDM_SHA512_SUPPORT=0
LIB_SPDM_FLAGS += -DLIBSPDM_SHA3_256_SUPPORT=0
LIB_SPDM_FLAGS += -DLIBSPDM_SHA3_384_SUPPORT=0
LIB_SPDM_FLAGS += -DLIBSPDM_SHA3_512_SUPPORT=0
LIB_SPDM_FLAGS += -DLIBSPDM_SM3_256_SUPPORT=0
LIB_SPDM_FLAGS += -DLIBSPDM_CERT_PARSE_SUPPORT=0
LIB_SPDM_FLAGS += -DLIBSPDM_ENABLE_MSG_LOG=0
LIB_SPDM_FLAGS += -DLIBSPDM_CHECK_MACRO=1
LIB_SPDM_FLAGS += -DLIBSPDM_AEAD_AES_256_GCM_SUPPORT=0
LIB_SPDM_FLAGS += -DLIBSPDM_FFDHE_2048_SUPPORT=0

UBS_CC_FLAGS += $(LIB_SPDM_FLAGS)
UBS_CXX_FLAGS += $(LIB_SPDM_FLAGS)