--
--  Generated by RecordFlux 0.6.1.dev1+g8b82b38a0 on 2022-12-02
--
--  Copyright (C) 2018-2022 AdaCore
--
--  SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
--

pragma Style_Checks ("N3aAbcdefhiIklnOprStux");
pragma Warnings (Off, "redundant conversion");

package body RFLX.SPDM.Alg_Struct with
  SPARK_Mode
is

   pragma Unevaluated_Use_Of_Old (Allow);

   procedure Initialize (Ctx : out Context; Buffer : in out RFLX_Types.Bytes_Ptr; Written_Last : RFLX_Types.Bit_Length := 0) is
   begin
      Initialize (Ctx, Buffer, RFLX_Types.To_First_Bit_Index (Buffer'First), RFLX_Types.To_Last_Bit_Index (Buffer'Last), Written_Last);
   end Initialize;

   procedure Initialize (Ctx : out Context; Buffer : in out RFLX_Types.Bytes_Ptr; First : RFLX_Types.Bit_Index; Last : RFLX_Types.Bit_Length; Written_Last : RFLX_Types.Bit_Length := 0) is
      Buffer_First : constant RFLX_Types.Index := Buffer'First;
      Buffer_Last : constant RFLX_Types.Index := Buffer'Last;
   begin
      Ctx := (Buffer_First, Buffer_Last, First, Last, First - 1, (if Written_Last = 0 then First - 1 else Written_Last), Buffer, [F_Alg_Type => (State => S_Invalid, Predecessor => F_Initial), others => (State => S_Invalid, Predecessor => F_Final)]);
      Buffer := null;
   end Initialize;

   procedure Reset (Ctx : in out Context) is
   begin
      Reset (Ctx, RFLX_Types.To_First_Bit_Index (Ctx.Buffer'First), RFLX_Types.To_Last_Bit_Index (Ctx.Buffer'Last));
   end Reset;

   procedure Reset (Ctx : in out Context; First : RFLX_Types.Bit_Index; Last : RFLX_Types.Bit_Length) is
   begin
      Ctx := (Ctx.Buffer_First, Ctx.Buffer_Last, First, Last, First - 1, First - 1, Ctx.Buffer, [F_Alg_Type => (State => S_Invalid, Predecessor => F_Initial), others => (State => S_Invalid, Predecessor => F_Final)]);
   end Reset;

   procedure Take_Buffer (Ctx : in out Context; Buffer : out RFLX_Types.Bytes_Ptr) is
   begin
      Buffer := Ctx.Buffer;
      Ctx.Buffer := null;
   end Take_Buffer;

   procedure Copy (Ctx : Context; Buffer : out RFLX_Types.Bytes) is
   begin
      if Buffer'Length > 0 then
         Buffer := Ctx.Buffer.all (RFLX_Types.To_Index (Ctx.First) .. RFLX_Types.To_Index (Ctx.Verified_Last));
      else
         Buffer := Ctx.Buffer.all (1 .. 0);
      end if;
   end Copy;

   function Read (Ctx : Context) return RFLX_Types.Bytes is
     (Ctx.Buffer.all (RFLX_Types.To_Index (Ctx.First) .. RFLX_Types.To_Index (Ctx.Verified_Last)));

   procedure Generic_Read (Ctx : Context) is
   begin
      Read (Ctx.Buffer.all (RFLX_Types.To_Index (Ctx.First) .. RFLX_Types.To_Index (Ctx.Verified_Last)));
   end Generic_Read;

   procedure Generic_Write (Ctx : in out Context; Offset : RFLX_Types.Length := 0) is
      Length : RFLX_Types.Length;
   begin
      Reset (Ctx, RFLX_Types.To_First_Bit_Index (Ctx.Buffer_First), RFLX_Types.To_Last_Bit_Index (Ctx.Buffer_Last));
      Write (Ctx.Buffer.all (Ctx.Buffer'First + RFLX_Types.Index (Offset + 1) - 1 .. Ctx.Buffer'Last), Length, Ctx.Buffer'Length, Offset);
      pragma Assert (Length <= Ctx.Buffer.all'Length, "Length <= Buffer'Length is not ensured by postcondition of ""Write""");
      Ctx.Written_Last := RFLX_Types.Bit_Index'Max (Ctx.Written_Last, RFLX_Types.To_Last_Bit_Index (RFLX_Types.Length (Ctx.Buffer_First) + Offset + Length - 1));
   end Generic_Write;

   procedure Data (Ctx : Context; Data : out RFLX_Types.Bytes) is
   begin
      Data := Ctx.Buffer.all (RFLX_Types.To_Index (Ctx.First) .. RFLX_Types.To_Index (Ctx.Verified_Last));
   end Data;

   pragma Warnings (Off, "precondition is always False");

   function Successor (Ctx : Context; Fld : Field) return Virtual_Field is
     ((case Fld is
          when F_Alg_Type =>
             F_Fixed_Alg_Count,
          when F_Fixed_Alg_Count =>
             (if Ctx.Cursors (F_Fixed_Alg_Count).Value = 2 then F_Ext_Alg_Count else F_Initial),
          when F_Ext_Alg_Count =>
             (if
                 RFLX_Types.Base_Integer (Ctx.Cursors (F_Alg_Type).Value) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.AEAD_Cipher_Suite))
              then
                 F_AEAD_Reserved_1
              elsif
                 RFLX_Types.Base_Integer (Ctx.Cursors (F_Alg_Type).Value) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.DHE))
              then
                 F_DHE_Reserved_1
              elsif
                 RFLX_Types.Base_Integer (Ctx.Cursors (F_Alg_Type).Value) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Key_Schedule))
              then
                 F_KS_Reserved_1
              elsif
                 RFLX_Types.Base_Integer (Ctx.Cursors (F_Alg_Type).Value) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Req_Base_Asym_Alg))
              then
                 F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P384
              else
                 F_Initial),
          when F_AEAD_Reserved_1 =>
             F_AEAD_ChaCha20_Poly1305,
          when F_DHE_Reserved_1 =>
             F_DHE_SecP521r1,
          when F_KS_Reserved_1 =>
             F_KS_SPDM,
          when F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P384 =>
             F_RBAA_TPM_ALG_RSAPSS_4096,
          when F_AEAD_ChaCha20_Poly1305 =>
             F_AEAD_AES_256_GCM,
          when F_DHE_SecP521r1 =>
             F_DHE_SecP384r1,
          when F_KS_SPDM =>
             F_KS_Reserved_2,
          when F_RBAA_TPM_ALG_RSAPSS_4096 =>
             F_RBAA_TPM_ALG_RSASSA_4096,
          when F_AEAD_AES_256_GCM =>
             F_AEAD_AES_128_GCM,
          when F_DHE_SecP384r1 =>
             F_DHE_SecP256r1,
          when F_KS_Reserved_2 =>
             F_Alg_External,
          when F_RBAA_TPM_ALG_RSASSA_4096 =>
             F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P256,
          when F_AEAD_AES_128_GCM =>
             F_AEAD_Reserved_2,
          when F_DHE_SecP256r1 =>
             F_DHE_FFDHE4096,
          when F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P256 =>
             F_RBAA_TPM_ALG_RSAPSS_3072,
          when F_AEAD_Reserved_2 =>
             F_Alg_External,
          when F_DHE_FFDHE4096 =>
             F_DHE_FFDHE3072,
          when F_RBAA_TPM_ALG_RSAPSS_3072 =>
             F_RBAA_TPM_ALG_RSASSA_3072,
          when F_DHE_FFDHE3072 =>
             F_DHE_FFDHE2048,
          when F_RBAA_TPM_ALG_RSASSA_3072 =>
             F_RBAA_TPM_ALG_RSAPSS_2048,
          when F_DHE_FFDHE2048 =>
             F_DHE_Reserved_2,
          when F_RBAA_TPM_ALG_RSAPSS_2048 =>
             F_RBAA_TPM_ALG_RSASSA_2048,
          when F_DHE_Reserved_2 =>
             F_Alg_External,
          when F_RBAA_TPM_ALG_RSASSA_2048 =>
             F_RBAA_Reserved_1,
          when F_RBAA_Reserved_1 =>
             F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P521,
          when F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P521 =>
             F_Alg_External,
          when F_Alg_External =>
             F_Final))
    with
     Pre =>
       RFLX.SPDM.Alg_Struct.Has_Buffer (Ctx)
       and RFLX.SPDM.Alg_Struct.Structural_Valid (Ctx, Fld)
       and RFLX.SPDM.Alg_Struct.Valid_Predecessor (Ctx, Fld);

   pragma Warnings (On, "precondition is always False");

   function Invalid_Successor (Ctx : Context; Fld : Field) return Boolean is
     ((case Fld is
          when F_Alg_Type =>
             Invalid (Ctx.Cursors (F_Fixed_Alg_Count)),
          when F_Fixed_Alg_Count =>
             Invalid (Ctx.Cursors (F_Ext_Alg_Count)),
          when F_Ext_Alg_Count =>
             Invalid (Ctx.Cursors (F_AEAD_Reserved_1))
             and Invalid (Ctx.Cursors (F_DHE_Reserved_1))
             and Invalid (Ctx.Cursors (F_KS_Reserved_1))
             and Invalid (Ctx.Cursors (F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P384)),
          when F_AEAD_Reserved_1 =>
             Invalid (Ctx.Cursors (F_AEAD_ChaCha20_Poly1305)),
          when F_DHE_Reserved_1 =>
             Invalid (Ctx.Cursors (F_DHE_SecP521r1)),
          when F_KS_Reserved_1 =>
             Invalid (Ctx.Cursors (F_KS_SPDM)),
          when F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P384 =>
             Invalid (Ctx.Cursors (F_RBAA_TPM_ALG_RSAPSS_4096)),
          when F_AEAD_ChaCha20_Poly1305 =>
             Invalid (Ctx.Cursors (F_AEAD_AES_256_GCM)),
          when F_DHE_SecP521r1 =>
             Invalid (Ctx.Cursors (F_DHE_SecP384r1)),
          when F_KS_SPDM =>
             Invalid (Ctx.Cursors (F_KS_Reserved_2)),
          when F_RBAA_TPM_ALG_RSAPSS_4096 =>
             Invalid (Ctx.Cursors (F_RBAA_TPM_ALG_RSASSA_4096)),
          when F_AEAD_AES_256_GCM =>
             Invalid (Ctx.Cursors (F_AEAD_AES_128_GCM)),
          when F_DHE_SecP384r1 =>
             Invalid (Ctx.Cursors (F_DHE_SecP256r1)),
          when F_KS_Reserved_2 =>
             Invalid (Ctx.Cursors (F_Alg_External)),
          when F_RBAA_TPM_ALG_RSASSA_4096 =>
             Invalid (Ctx.Cursors (F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P256)),
          when F_AEAD_AES_128_GCM =>
             Invalid (Ctx.Cursors (F_AEAD_Reserved_2)),
          when F_DHE_SecP256r1 =>
             Invalid (Ctx.Cursors (F_DHE_FFDHE4096)),
          when F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P256 =>
             Invalid (Ctx.Cursors (F_RBAA_TPM_ALG_RSAPSS_3072)),
          when F_AEAD_Reserved_2 =>
             Invalid (Ctx.Cursors (F_Alg_External)),
          when F_DHE_FFDHE4096 =>
             Invalid (Ctx.Cursors (F_DHE_FFDHE3072)),
          when F_RBAA_TPM_ALG_RSAPSS_3072 =>
             Invalid (Ctx.Cursors (F_RBAA_TPM_ALG_RSASSA_3072)),
          when F_DHE_FFDHE3072 =>
             Invalid (Ctx.Cursors (F_DHE_FFDHE2048)),
          when F_RBAA_TPM_ALG_RSASSA_3072 =>
             Invalid (Ctx.Cursors (F_RBAA_TPM_ALG_RSAPSS_2048)),
          when F_DHE_FFDHE2048 =>
             Invalid (Ctx.Cursors (F_DHE_Reserved_2)),
          when F_RBAA_TPM_ALG_RSAPSS_2048 =>
             Invalid (Ctx.Cursors (F_RBAA_TPM_ALG_RSASSA_2048)),
          when F_DHE_Reserved_2 =>
             Invalid (Ctx.Cursors (F_Alg_External)),
          when F_RBAA_TPM_ALG_RSASSA_2048 =>
             Invalid (Ctx.Cursors (F_RBAA_Reserved_1)),
          when F_RBAA_Reserved_1 =>
             Invalid (Ctx.Cursors (F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P521)),
          when F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P521 =>
             Invalid (Ctx.Cursors (F_Alg_External)),
          when F_Alg_External =>
             True));

   function Sufficient_Buffer_Length (Ctx : Context; Fld : Field) return Boolean is
     (Ctx.Buffer /= null
      and Field_First (Ctx, Fld) + Field_Size (Ctx, Fld) < RFLX_Types.Bit_Length'Last
      and Ctx.First <= Field_First (Ctx, Fld)
      and Field_First (Ctx, Fld) + Field_Size (Ctx, Fld) - 1 <= Ctx.Written_Last)
    with
     Pre =>
       RFLX.SPDM.Alg_Struct.Has_Buffer (Ctx)
       and RFLX.SPDM.Alg_Struct.Valid_Next (Ctx, Fld);

   function Equal (Ctx : Context; Fld : Field; Data : RFLX_Types.Bytes) return Boolean is
     (Sufficient_Buffer_Length (Ctx, Fld)
      and then (case Fld is
                   when F_Alg_External =>
                      Data'Length = RFLX_Types.To_Index (Field_Last (Ctx, Fld)) - RFLX_Types.To_Index (Field_First (Ctx, Fld)) + 1
                      and then (for all I in RFLX_Types.Index range RFLX_Types.To_Index (Field_First (Ctx, Fld)) .. RFLX_Types.To_Index (Field_Last (Ctx, Fld)) =>
                                   Ctx.Buffer.all (I) = Data (Data'First + (I - RFLX_Types.To_Index (Field_First (Ctx, Fld))))),
                   when others =>
                      False));

   procedure Reset_Dependent_Fields (Ctx : in out Context; Fld : Field) with
     Pre =>
       RFLX.SPDM.Alg_Struct.Valid_Next (Ctx, Fld),
     Post =>
       Valid_Next (Ctx, Fld)
       and Invalid (Ctx.Cursors (Fld))
       and Invalid_Successor (Ctx, Fld)
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = Ctx.First'Old
       and Ctx.Last = Ctx.Last'Old
       and Ctx.Cursors (Fld).Predecessor = Ctx.Cursors (Fld).Predecessor'Old
       and Has_Buffer (Ctx) = Has_Buffer (Ctx)'Old
       and Field_First (Ctx, Fld) = Field_First (Ctx, Fld)'Old
       and Field_Size (Ctx, Fld) = Field_Size (Ctx, Fld)'Old
       and (for all F in Field =>
               (if F < Fld then Ctx.Cursors (F) = Ctx.Cursors'Old (F) else Invalid (Ctx, F)))
   is
      First : constant RFLX_Types.Bit_Length := Field_First (Ctx, Fld) with
        Ghost;
      Size : constant RFLX_Types.Bit_Length := Field_Size (Ctx, Fld) with
        Ghost;
   begin
      pragma Assert (Field_First (Ctx, Fld) = First
                     and Field_Size (Ctx, Fld) = Size);
      for Fld_Loop in reverse Field'Succ (Fld) .. Field'Last loop
         Ctx.Cursors (Fld_Loop) := (S_Invalid, F_Final);
         pragma Loop_Invariant (Field_First (Ctx, Fld) = First
                                and Field_Size (Ctx, Fld) = Size);
         pragma Loop_Invariant ((for all F in Field =>
                                    (if F < Fld_Loop then Ctx.Cursors (F) = Ctx.Cursors'Loop_Entry (F) else Invalid (Ctx, F))));
      end loop;
      pragma Assert (Field_First (Ctx, Fld) = First
                     and Field_Size (Ctx, Fld) = Size);
      Ctx.Cursors (Fld) := (S_Invalid, Ctx.Cursors (Fld).Predecessor);
      pragma Assert (Field_First (Ctx, Fld) = First
                     and Field_Size (Ctx, Fld) = Size);
   end Reset_Dependent_Fields;

   function Composite_Field (Fld : Field) return Boolean is
     (Fld in F_Alg_External);

   function Get (Ctx : Context; Fld : Field) return RFLX_Types.Base_Integer with
     Pre =>
       RFLX.SPDM.Alg_Struct.Has_Buffer (Ctx)
       and then RFLX.SPDM.Alg_Struct.Valid_Next (Ctx, Fld)
       and then RFLX.SPDM.Alg_Struct.Sufficient_Buffer_Length (Ctx, Fld)
       and then not RFLX.SPDM.Alg_Struct.Composite_Field (Fld)
   is
      First : constant RFLX_Types.Bit_Index := Field_First (Ctx, Fld);
      Last : constant RFLX_Types.Bit_Index := Field_Last (Ctx, Fld);
      Buffer_First : constant RFLX_Types.Index := RFLX_Types.To_Index (First);
      Buffer_Last : constant RFLX_Types.Index := RFLX_Types.To_Index (Last);
      Offset : constant RFLX_Types.Offset := RFLX_Types.Offset ((RFLX_Types.Byte'Size - Last mod RFLX_Types.Byte'Size) mod RFLX_Types.Byte'Size);
      Size : constant Positive := (case Fld is
          when F_Alg_Type =>
             8,
          when F_Fixed_Alg_Count | F_Ext_Alg_Count =>
             4,
          when F_AEAD_Reserved_1 =>
             5,
          when F_DHE_Reserved_1 =>
             2,
          when F_KS_Reserved_1 =>
             7,
          when F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P384 | F_AEAD_ChaCha20_Poly1305 | F_DHE_SecP521r1 | F_KS_SPDM | F_RBAA_TPM_ALG_RSAPSS_4096 | F_AEAD_AES_256_GCM | F_DHE_SecP384r1 =>
             1,
          when F_KS_Reserved_2 =>
             8,
          when F_RBAA_TPM_ALG_RSASSA_4096 | F_AEAD_AES_128_GCM | F_DHE_SecP256r1 | F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P256 =>
             1,
          when F_AEAD_Reserved_2 =>
             8,
          when F_DHE_FFDHE4096 | F_RBAA_TPM_ALG_RSAPSS_3072 | F_DHE_FFDHE3072 | F_RBAA_TPM_ALG_RSASSA_3072 | F_DHE_FFDHE2048 | F_RBAA_TPM_ALG_RSAPSS_2048 =>
             1,
          when F_DHE_Reserved_2 =>
             8,
          when F_RBAA_TPM_ALG_RSASSA_2048 =>
             1,
          when F_RBAA_Reserved_1 =>
             7,
          when F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P521 =>
             1,
          when others =>
             Positive'Last);
      Byte_Order : constant RFLX_Types.Byte_Order := RFLX_Types.High_Order_First;
   begin
      return RFLX_Types.Extract (Ctx.Buffer, Buffer_First, Buffer_Last, Offset, Size, Byte_Order);
   end Get;

   procedure Verify (Ctx : in out Context; Fld : Field) is
      Value : RFLX_Types.Base_Integer;
   begin
      if
         Invalid (Ctx.Cursors (Fld))
         and then Valid_Predecessor (Ctx, Fld)
         and then Path_Condition (Ctx, Fld)
      then
         if Sufficient_Buffer_Length (Ctx, Fld) then
            Value := (if Composite_Field (Fld) then 0 else Get (Ctx, Fld));
            if
               Valid_Value (Fld, Value)
               and then Field_Condition (Ctx, Fld, Value)
            then
               pragma Assert ((if Fld = F_Alg_External then Field_Last (Ctx, Fld) mod RFLX_Types.Byte'Size = 0));
               pragma Assert ((((Field_Last (Ctx, Fld) + RFLX_Types.Byte'Size - 1) / RFLX_Types.Byte'Size) * RFLX_Types.Byte'Size) mod RFLX_Types.Byte'Size = 0);
               Ctx.Verified_Last := ((Field_Last (Ctx, Fld) + RFLX_Types.Byte'Size - 1) / RFLX_Types.Byte'Size) * RFLX_Types.Byte'Size;
               pragma Assert (Field_Last (Ctx, Fld) <= Ctx.Verified_Last);
               if Composite_Field (Fld) then
                  Ctx.Cursors (Fld) := (State => S_Structural_Valid, First => Field_First (Ctx, Fld), Last => Field_Last (Ctx, Fld), Value => Value, Predecessor => Ctx.Cursors (Fld).Predecessor);
               else
                  Ctx.Cursors (Fld) := (State => S_Valid, First => Field_First (Ctx, Fld), Last => Field_Last (Ctx, Fld), Value => Value, Predecessor => Ctx.Cursors (Fld).Predecessor);
               end if;
               Ctx.Cursors (Successor (Ctx, Fld)) := (State => S_Invalid, Predecessor => Fld);
            else
               Ctx.Cursors (Fld) := (State => S_Invalid, Predecessor => F_Final);
            end if;
         else
            Ctx.Cursors (Fld) := (State => S_Incomplete, Predecessor => F_Final);
         end if;
      end if;
   end Verify;

   procedure Verify_Message (Ctx : in out Context) is
   begin
      for F in Field loop
         pragma Loop_Invariant (Has_Buffer (Ctx)
                                and Ctx.Buffer_First = Ctx.Buffer_First'Loop_Entry
                                and Ctx.Buffer_Last = Ctx.Buffer_Last'Loop_Entry
                                and Ctx.First = Ctx.First'Loop_Entry
                                and Ctx.Last = Ctx.Last'Loop_Entry);
         Verify (Ctx, F);
      end loop;
   end Verify_Message;

   procedure Set (Ctx : in out Context; Fld : Field; Val : RFLX_Types.Base_Integer; Size : RFLX_Types.Bit_Length; State_Valid : Boolean; Buffer_First : out RFLX_Types.Index; Buffer_Last : out RFLX_Types.Index; Offset : out RFLX_Types.Offset) with
     Pre =>
       RFLX.SPDM.Alg_Struct.Has_Buffer (Ctx)
       and then RFLX.SPDM.Alg_Struct.Valid_Next (Ctx, Fld)
       and then RFLX.SPDM.Alg_Struct.Valid_Value (Fld, Val)
       and then RFLX.SPDM.Alg_Struct.Valid_Size (Ctx, Fld, Size)
       and then Size <= RFLX.SPDM.Alg_Struct.Available_Space (Ctx, Fld)
       and then (if
                    RFLX.SPDM.Alg_Struct.Composite_Field (Fld)
                 then
                    Size mod RFLX_Types.Byte'Size = 0
                 else
                    State_Valid),
     Post =>
       Valid_Next (Ctx, Fld)
       and then Invalid_Successor (Ctx, Fld)
       and then Buffer_First = RFLX_Types.To_Index (Field_First (Ctx, Fld))
       and then Buffer_Last = RFLX_Types.To_Index (Field_First (Ctx, Fld) + Size - 1)
       and then Offset = RFLX_Types.Offset ((RFLX_Types.Byte'Size - (Field_First (Ctx, Fld) + Size - 1) mod RFLX_Types.Byte'Size) mod RFLX_Types.Byte'Size)
       and then Ctx.Buffer_First = Ctx.Buffer_First'Old
       and then Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and then Ctx.First = Ctx.First'Old
       and then Ctx.Last = Ctx.Last'Old
       and then Ctx.Buffer_First = Ctx.Buffer_First'Old
       and then Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and then Ctx.First = Ctx.First'Old
       and then Ctx.Last = Ctx.Last'Old
       and then Has_Buffer (Ctx) = Has_Buffer (Ctx)'Old
       and then Predecessor (Ctx, Fld) = Predecessor (Ctx, Fld)'Old
       and then Field_First (Ctx, Fld) = Field_First (Ctx, Fld)'Old
       and then Sufficient_Space (Ctx, Fld)
       and then (if State_Valid and Size > 0 then Valid (Ctx, Fld) else Structural_Valid (Ctx, Fld))
       and then (case Fld is
                    when F_Alg_Type =>
                       Get_Alg_Type (Ctx) = To_Actual (Val)
                       and (Predecessor (Ctx, F_Fixed_Alg_Count) = F_Alg_Type
                            and Valid_Next (Ctx, F_Fixed_Alg_Count)),
                    when F_Fixed_Alg_Count =>
                       Get_Fixed_Alg_Count (Ctx) = To_Actual (Val)
                       and (if
                               Get_Fixed_Alg_Count (Ctx) = 2
                            then
                               Predecessor (Ctx, F_Ext_Alg_Count) = F_Fixed_Alg_Count
                               and Valid_Next (Ctx, F_Ext_Alg_Count)),
                    when F_Ext_Alg_Count =>
                       Get_Ext_Alg_Count (Ctx) = To_Actual (Val)
                       and (if
                               RFLX_Types.Base_Integer (To_Base_Integer (Get_Alg_Type (Ctx))) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.AEAD_Cipher_Suite))
                            then
                               Predecessor (Ctx, F_AEAD_Reserved_1) = F_Ext_Alg_Count
                               and Valid_Next (Ctx, F_AEAD_Reserved_1))
                       and (if
                               RFLX_Types.Base_Integer (To_Base_Integer (Get_Alg_Type (Ctx))) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.DHE))
                            then
                               Predecessor (Ctx, F_DHE_Reserved_1) = F_Ext_Alg_Count
                               and Valid_Next (Ctx, F_DHE_Reserved_1))
                       and (if
                               RFLX_Types.Base_Integer (To_Base_Integer (Get_Alg_Type (Ctx))) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Key_Schedule))
                            then
                               Predecessor (Ctx, F_KS_Reserved_1) = F_Ext_Alg_Count
                               and Valid_Next (Ctx, F_KS_Reserved_1))
                       and (if
                               RFLX_Types.Base_Integer (To_Base_Integer (Get_Alg_Type (Ctx))) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Req_Base_Asym_Alg))
                            then
                               Predecessor (Ctx, F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P384) = F_Ext_Alg_Count
                               and Valid_Next (Ctx, F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P384)),
                    when F_AEAD_Reserved_1 =>
                       (Predecessor (Ctx, F_AEAD_ChaCha20_Poly1305) = F_AEAD_Reserved_1
                        and Valid_Next (Ctx, F_AEAD_ChaCha20_Poly1305)),
                    when F_DHE_Reserved_1 =>
                       (Predecessor (Ctx, F_DHE_SecP521r1) = F_DHE_Reserved_1
                        and Valid_Next (Ctx, F_DHE_SecP521r1)),
                    when F_KS_Reserved_1 =>
                       (Predecessor (Ctx, F_KS_SPDM) = F_KS_Reserved_1
                        and Valid_Next (Ctx, F_KS_SPDM)),
                    when F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P384 =>
                       Get_RBAA_TPM_ALG_ECDSA_ECC_NIST_P384 (Ctx) = To_Actual (Val)
                       and (Predecessor (Ctx, F_RBAA_TPM_ALG_RSAPSS_4096) = F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P384
                            and Valid_Next (Ctx, F_RBAA_TPM_ALG_RSAPSS_4096)),
                    when F_AEAD_ChaCha20_Poly1305 =>
                       Get_AEAD_ChaCha20_Poly1305 (Ctx) = To_Actual (Val)
                       and (Predecessor (Ctx, F_AEAD_AES_256_GCM) = F_AEAD_ChaCha20_Poly1305
                            and Valid_Next (Ctx, F_AEAD_AES_256_GCM)),
                    when F_DHE_SecP521r1 =>
                       Get_DHE_SecP521r1 (Ctx) = To_Actual (Val)
                       and (Predecessor (Ctx, F_DHE_SecP384r1) = F_DHE_SecP521r1
                            and Valid_Next (Ctx, F_DHE_SecP384r1)),
                    when F_KS_SPDM =>
                       Get_KS_SPDM (Ctx) = To_Actual (Val)
                       and (Predecessor (Ctx, F_KS_Reserved_2) = F_KS_SPDM
                            and Valid_Next (Ctx, F_KS_Reserved_2)),
                    when F_RBAA_TPM_ALG_RSAPSS_4096 =>
                       Get_RBAA_TPM_ALG_RSAPSS_4096 (Ctx) = To_Actual (Val)
                       and (Predecessor (Ctx, F_RBAA_TPM_ALG_RSASSA_4096) = F_RBAA_TPM_ALG_RSAPSS_4096
                            and Valid_Next (Ctx, F_RBAA_TPM_ALG_RSASSA_4096)),
                    when F_AEAD_AES_256_GCM =>
                       Get_AEAD_AES_256_GCM (Ctx) = To_Actual (Val)
                       and (Predecessor (Ctx, F_AEAD_AES_128_GCM) = F_AEAD_AES_256_GCM
                            and Valid_Next (Ctx, F_AEAD_AES_128_GCM)),
                    when F_DHE_SecP384r1 =>
                       Get_DHE_SecP384r1 (Ctx) = To_Actual (Val)
                       and (Predecessor (Ctx, F_DHE_SecP256r1) = F_DHE_SecP384r1
                            and Valid_Next (Ctx, F_DHE_SecP256r1)),
                    when F_KS_Reserved_2 =>
                       (Predecessor (Ctx, F_Alg_External) = F_KS_Reserved_2
                        and Valid_Next (Ctx, F_Alg_External)),
                    when F_RBAA_TPM_ALG_RSASSA_4096 =>
                       Get_RBAA_TPM_ALG_RSASSA_4096 (Ctx) = To_Actual (Val)
                       and (Predecessor (Ctx, F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P256) = F_RBAA_TPM_ALG_RSASSA_4096
                            and Valid_Next (Ctx, F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P256)),
                    when F_AEAD_AES_128_GCM =>
                       Get_AEAD_AES_128_GCM (Ctx) = To_Actual (Val)
                       and (Predecessor (Ctx, F_AEAD_Reserved_2) = F_AEAD_AES_128_GCM
                            and Valid_Next (Ctx, F_AEAD_Reserved_2)),
                    when F_DHE_SecP256r1 =>
                       Get_DHE_SecP256r1 (Ctx) = To_Actual (Val)
                       and (Predecessor (Ctx, F_DHE_FFDHE4096) = F_DHE_SecP256r1
                            and Valid_Next (Ctx, F_DHE_FFDHE4096)),
                    when F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P256 =>
                       Get_RBAA_TPM_ALG_ECDSA_ECC_NIST_P256 (Ctx) = To_Actual (Val)
                       and (Predecessor (Ctx, F_RBAA_TPM_ALG_RSAPSS_3072) = F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P256
                            and Valid_Next (Ctx, F_RBAA_TPM_ALG_RSAPSS_3072)),
                    when F_AEAD_Reserved_2 =>
                       (Predecessor (Ctx, F_Alg_External) = F_AEAD_Reserved_2
                        and Valid_Next (Ctx, F_Alg_External)),
                    when F_DHE_FFDHE4096 =>
                       Get_DHE_FFDHE4096 (Ctx) = To_Actual (Val)
                       and (Predecessor (Ctx, F_DHE_FFDHE3072) = F_DHE_FFDHE4096
                            and Valid_Next (Ctx, F_DHE_FFDHE3072)),
                    when F_RBAA_TPM_ALG_RSAPSS_3072 =>
                       Get_RBAA_TPM_ALG_RSAPSS_3072 (Ctx) = To_Actual (Val)
                       and (Predecessor (Ctx, F_RBAA_TPM_ALG_RSASSA_3072) = F_RBAA_TPM_ALG_RSAPSS_3072
                            and Valid_Next (Ctx, F_RBAA_TPM_ALG_RSASSA_3072)),
                    when F_DHE_FFDHE3072 =>
                       Get_DHE_FFDHE3072 (Ctx) = To_Actual (Val)
                       and (Predecessor (Ctx, F_DHE_FFDHE2048) = F_DHE_FFDHE3072
                            and Valid_Next (Ctx, F_DHE_FFDHE2048)),
                    when F_RBAA_TPM_ALG_RSASSA_3072 =>
                       Get_RBAA_TPM_ALG_RSASSA_3072 (Ctx) = To_Actual (Val)
                       and (Predecessor (Ctx, F_RBAA_TPM_ALG_RSAPSS_2048) = F_RBAA_TPM_ALG_RSASSA_3072
                            and Valid_Next (Ctx, F_RBAA_TPM_ALG_RSAPSS_2048)),
                    when F_DHE_FFDHE2048 =>
                       Get_DHE_FFDHE2048 (Ctx) = To_Actual (Val)
                       and (Predecessor (Ctx, F_DHE_Reserved_2) = F_DHE_FFDHE2048
                            and Valid_Next (Ctx, F_DHE_Reserved_2)),
                    when F_RBAA_TPM_ALG_RSAPSS_2048 =>
                       Get_RBAA_TPM_ALG_RSAPSS_2048 (Ctx) = To_Actual (Val)
                       and (Predecessor (Ctx, F_RBAA_TPM_ALG_RSASSA_2048) = F_RBAA_TPM_ALG_RSAPSS_2048
                            and Valid_Next (Ctx, F_RBAA_TPM_ALG_RSASSA_2048)),
                    when F_DHE_Reserved_2 =>
                       (Predecessor (Ctx, F_Alg_External) = F_DHE_Reserved_2
                        and Valid_Next (Ctx, F_Alg_External)),
                    when F_RBAA_TPM_ALG_RSASSA_2048 =>
                       Get_RBAA_TPM_ALG_RSASSA_2048 (Ctx) = To_Actual (Val)
                       and (Predecessor (Ctx, F_RBAA_Reserved_1) = F_RBAA_TPM_ALG_RSASSA_2048
                            and Valid_Next (Ctx, F_RBAA_Reserved_1)),
                    when F_RBAA_Reserved_1 =>
                       (Predecessor (Ctx, F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P521) = F_RBAA_Reserved_1
                        and Valid_Next (Ctx, F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P521)),
                    when F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P521 =>
                       Get_RBAA_TPM_ALG_ECDSA_ECC_NIST_P521 (Ctx) = To_Actual (Val)
                       and (Predecessor (Ctx, F_Alg_External) = F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P521
                            and Valid_Next (Ctx, F_Alg_External)),
                    when F_Alg_External =>
                       (if Structural_Valid_Message (Ctx) then Message_Last (Ctx) = Field_Last (Ctx, Fld)))
       and then (for all F in Field =>
                    (if F < Fld then Ctx.Cursors (F) = Ctx.Cursors'Old (F)))
   is
      First : RFLX_Types.Bit_Index;
      Last : RFLX_Types.Bit_Length;
   begin
      Reset_Dependent_Fields (Ctx, Fld);
      First := Field_First (Ctx, Fld);
      Last := Field_First (Ctx, Fld) + Size - 1;
      Offset := RFLX_Types.Offset ((RFLX_Types.Byte'Size - Last mod RFLX_Types.Byte'Size) mod RFLX_Types.Byte'Size);
      Buffer_First := RFLX_Types.To_Index (First);
      Buffer_Last := RFLX_Types.To_Index (Last);
      pragma Assert ((((Last + RFLX_Types.Byte'Size - 1) / RFLX_Types.Byte'Size) * RFLX_Types.Byte'Size) mod RFLX_Types.Byte'Size = 0);
      pragma Warnings (Off, "attribute Update is an obsolescent feature");
      Ctx := Ctx'Update (Verified_Last => ((Last + RFLX_Types.Byte'Size - 1) / RFLX_Types.Byte'Size) * RFLX_Types.Byte'Size, Written_Last => ((Last + RFLX_Types.Byte'Size - 1) / RFLX_Types.Byte'Size) * RFLX_Types.Byte'Size);
      pragma Warnings (On, "attribute Update is an obsolescent feature");
      pragma Assert (Size = (case Fld is
                         when F_Alg_Type =>
                            8,
                         when F_Fixed_Alg_Count | F_Ext_Alg_Count =>
                            4,
                         when F_AEAD_Reserved_1 =>
                            5,
                         when F_DHE_Reserved_1 =>
                            2,
                         when F_KS_Reserved_1 =>
                            7,
                         when F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P384 | F_AEAD_ChaCha20_Poly1305 | F_DHE_SecP521r1 | F_KS_SPDM | F_RBAA_TPM_ALG_RSAPSS_4096 | F_AEAD_AES_256_GCM | F_DHE_SecP384r1 =>
                            1,
                         when F_KS_Reserved_2 =>
                            8,
                         when F_RBAA_TPM_ALG_RSASSA_4096 | F_AEAD_AES_128_GCM | F_DHE_SecP256r1 | F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P256 =>
                            1,
                         when F_AEAD_Reserved_2 =>
                            8,
                         when F_DHE_FFDHE4096 | F_RBAA_TPM_ALG_RSAPSS_3072 | F_DHE_FFDHE3072 | F_RBAA_TPM_ALG_RSASSA_3072 | F_DHE_FFDHE2048 | F_RBAA_TPM_ALG_RSAPSS_2048 =>
                            1,
                         when F_DHE_Reserved_2 =>
                            8,
                         when F_RBAA_TPM_ALG_RSASSA_2048 =>
                            1,
                         when F_RBAA_Reserved_1 =>
                            7,
                         when F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P521 =>
                            1,
                         when F_Alg_External =>
                            (if
                                Ctx.Cursors (Fld).Predecessor = F_AEAD_Reserved_2
                             then
                                RFLX_Types.Bit_Length (Ctx.Cursors (F_Ext_Alg_Count).Value) * 32
                             elsif
                                Ctx.Cursors (Fld).Predecessor = F_DHE_Reserved_2
                             then
                                RFLX_Types.Bit_Length (Ctx.Cursors (F_Ext_Alg_Count).Value) * 32
                             elsif
                                Ctx.Cursors (Fld).Predecessor = F_KS_Reserved_2
                             then
                                RFLX_Types.Bit_Length (Ctx.Cursors (F_Ext_Alg_Count).Value) * 32
                             elsif
                                Ctx.Cursors (Fld).Predecessor = F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P521
                             then
                                RFLX_Types.Bit_Length (Ctx.Cursors (F_Ext_Alg_Count).Value) * 32
                             else
                                RFLX_Types.Unreachable)));
      if State_Valid then
         Ctx.Cursors (Fld) := (State => S_Valid, First => First, Last => Last, Value => Val, Predecessor => Ctx.Cursors (Fld).Predecessor);
      else
         Ctx.Cursors (Fld) := (State => S_Structural_Valid, First => First, Last => Last, Value => Val, Predecessor => Ctx.Cursors (Fld).Predecessor);
      end if;
      Ctx.Cursors (Successor (Ctx, Fld)) := (State => S_Invalid, Predecessor => Fld);
      pragma Assert (Last = (Field_First (Ctx, Fld) + Size) - 1);
   end Set;

   procedure Set_Scalar (Ctx : in out Context; Fld : Field; Val : RFLX_Types.Base_Integer) with
     Pre =>
       not Ctx'Constrained
       and then RFLX.SPDM.Alg_Struct.Has_Buffer (Ctx)
       and then RFLX.SPDM.Alg_Struct.Valid_Next (Ctx, Fld)
       and then Fld in F_Alg_Type | F_Fixed_Alg_Count | F_Ext_Alg_Count | F_AEAD_Reserved_1 | F_DHE_Reserved_1 | F_KS_Reserved_1 | F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P384 | F_AEAD_ChaCha20_Poly1305 | F_DHE_SecP521r1 | F_KS_SPDM | F_RBAA_TPM_ALG_RSAPSS_4096 | F_AEAD_AES_256_GCM | F_DHE_SecP384r1 | F_KS_Reserved_2 | F_RBAA_TPM_ALG_RSASSA_4096 | F_AEAD_AES_128_GCM | F_DHE_SecP256r1 | F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P256 | F_AEAD_Reserved_2 | F_DHE_FFDHE4096 | F_RBAA_TPM_ALG_RSAPSS_3072 | F_DHE_FFDHE3072 | F_RBAA_TPM_ALG_RSASSA_3072 | F_DHE_FFDHE2048 | F_RBAA_TPM_ALG_RSAPSS_2048 | F_DHE_Reserved_2 | F_RBAA_TPM_ALG_RSASSA_2048 | F_RBAA_Reserved_1 | F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P521
       and then RFLX.SPDM.Alg_Struct.Valid_Value (Fld, Val)
       and then RFLX.SPDM.Alg_Struct.Valid_Size (Ctx, Fld, RFLX.SPDM.Alg_Struct.Field_Size (Ctx, Fld))
       and then RFLX.SPDM.Alg_Struct.Available_Space (Ctx, Fld) >= RFLX.SPDM.Alg_Struct.Field_Size (Ctx, Fld)
       and then RFLX.SPDM.Alg_Struct.Field_Size (Ctx, Fld) in 1 .. RFLX_Types.Base_Integer'Size
       and then RFLX_Types.Fits_Into (Val, Natural (RFLX.SPDM.Alg_Struct.Field_Size (Ctx, Fld))),
     Post =>
       Has_Buffer (Ctx)
       and Valid (Ctx, Fld)
       and Invalid_Successor (Ctx, Fld)
       and (case Fld is
               when F_Alg_Type =>
                  Get_Alg_Type (Ctx) = To_Actual (Val)
                  and (Predecessor (Ctx, F_Fixed_Alg_Count) = F_Alg_Type
                       and Valid_Next (Ctx, F_Fixed_Alg_Count)),
               when F_Fixed_Alg_Count =>
                  Get_Fixed_Alg_Count (Ctx) = To_Actual (Val)
                  and (if
                          Get_Fixed_Alg_Count (Ctx) = 2
                       then
                          Predecessor (Ctx, F_Ext_Alg_Count) = F_Fixed_Alg_Count
                          and Valid_Next (Ctx, F_Ext_Alg_Count)),
               when F_Ext_Alg_Count =>
                  Get_Ext_Alg_Count (Ctx) = To_Actual (Val)
                  and (if
                          RFLX_Types.Base_Integer (To_Base_Integer (Get_Alg_Type (Ctx))) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.AEAD_Cipher_Suite))
                       then
                          Predecessor (Ctx, F_AEAD_Reserved_1) = F_Ext_Alg_Count
                          and Valid_Next (Ctx, F_AEAD_Reserved_1))
                  and (if
                          RFLX_Types.Base_Integer (To_Base_Integer (Get_Alg_Type (Ctx))) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.DHE))
                       then
                          Predecessor (Ctx, F_DHE_Reserved_1) = F_Ext_Alg_Count
                          and Valid_Next (Ctx, F_DHE_Reserved_1))
                  and (if
                          RFLX_Types.Base_Integer (To_Base_Integer (Get_Alg_Type (Ctx))) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Key_Schedule))
                       then
                          Predecessor (Ctx, F_KS_Reserved_1) = F_Ext_Alg_Count
                          and Valid_Next (Ctx, F_KS_Reserved_1))
                  and (if
                          RFLX_Types.Base_Integer (To_Base_Integer (Get_Alg_Type (Ctx))) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Req_Base_Asym_Alg))
                       then
                          Predecessor (Ctx, F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P384) = F_Ext_Alg_Count
                          and Valid_Next (Ctx, F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P384)),
               when F_AEAD_Reserved_1 =>
                  (Predecessor (Ctx, F_AEAD_ChaCha20_Poly1305) = F_AEAD_Reserved_1
                   and Valid_Next (Ctx, F_AEAD_ChaCha20_Poly1305)),
               when F_DHE_Reserved_1 =>
                  (Predecessor (Ctx, F_DHE_SecP521r1) = F_DHE_Reserved_1
                   and Valid_Next (Ctx, F_DHE_SecP521r1)),
               when F_KS_Reserved_1 =>
                  (Predecessor (Ctx, F_KS_SPDM) = F_KS_Reserved_1
                   and Valid_Next (Ctx, F_KS_SPDM)),
               when F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P384 =>
                  Get_RBAA_TPM_ALG_ECDSA_ECC_NIST_P384 (Ctx) = To_Actual (Val)
                  and (Predecessor (Ctx, F_RBAA_TPM_ALG_RSAPSS_4096) = F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P384
                       and Valid_Next (Ctx, F_RBAA_TPM_ALG_RSAPSS_4096)),
               when F_AEAD_ChaCha20_Poly1305 =>
                  Get_AEAD_ChaCha20_Poly1305 (Ctx) = To_Actual (Val)
                  and (Predecessor (Ctx, F_AEAD_AES_256_GCM) = F_AEAD_ChaCha20_Poly1305
                       and Valid_Next (Ctx, F_AEAD_AES_256_GCM)),
               when F_DHE_SecP521r1 =>
                  Get_DHE_SecP521r1 (Ctx) = To_Actual (Val)
                  and (Predecessor (Ctx, F_DHE_SecP384r1) = F_DHE_SecP521r1
                       and Valid_Next (Ctx, F_DHE_SecP384r1)),
               when F_KS_SPDM =>
                  Get_KS_SPDM (Ctx) = To_Actual (Val)
                  and (Predecessor (Ctx, F_KS_Reserved_2) = F_KS_SPDM
                       and Valid_Next (Ctx, F_KS_Reserved_2)),
               when F_RBAA_TPM_ALG_RSAPSS_4096 =>
                  Get_RBAA_TPM_ALG_RSAPSS_4096 (Ctx) = To_Actual (Val)
                  and (Predecessor (Ctx, F_RBAA_TPM_ALG_RSASSA_4096) = F_RBAA_TPM_ALG_RSAPSS_4096
                       and Valid_Next (Ctx, F_RBAA_TPM_ALG_RSASSA_4096)),
               when F_AEAD_AES_256_GCM =>
                  Get_AEAD_AES_256_GCM (Ctx) = To_Actual (Val)
                  and (Predecessor (Ctx, F_AEAD_AES_128_GCM) = F_AEAD_AES_256_GCM
                       and Valid_Next (Ctx, F_AEAD_AES_128_GCM)),
               when F_DHE_SecP384r1 =>
                  Get_DHE_SecP384r1 (Ctx) = To_Actual (Val)
                  and (Predecessor (Ctx, F_DHE_SecP256r1) = F_DHE_SecP384r1
                       and Valid_Next (Ctx, F_DHE_SecP256r1)),
               when F_KS_Reserved_2 =>
                  (Predecessor (Ctx, F_Alg_External) = F_KS_Reserved_2
                   and Valid_Next (Ctx, F_Alg_External)),
               when F_RBAA_TPM_ALG_RSASSA_4096 =>
                  Get_RBAA_TPM_ALG_RSASSA_4096 (Ctx) = To_Actual (Val)
                  and (Predecessor (Ctx, F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P256) = F_RBAA_TPM_ALG_RSASSA_4096
                       and Valid_Next (Ctx, F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P256)),
               when F_AEAD_AES_128_GCM =>
                  Get_AEAD_AES_128_GCM (Ctx) = To_Actual (Val)
                  and (Predecessor (Ctx, F_AEAD_Reserved_2) = F_AEAD_AES_128_GCM
                       and Valid_Next (Ctx, F_AEAD_Reserved_2)),
               when F_DHE_SecP256r1 =>
                  Get_DHE_SecP256r1 (Ctx) = To_Actual (Val)
                  and (Predecessor (Ctx, F_DHE_FFDHE4096) = F_DHE_SecP256r1
                       and Valid_Next (Ctx, F_DHE_FFDHE4096)),
               when F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P256 =>
                  Get_RBAA_TPM_ALG_ECDSA_ECC_NIST_P256 (Ctx) = To_Actual (Val)
                  and (Predecessor (Ctx, F_RBAA_TPM_ALG_RSAPSS_3072) = F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P256
                       and Valid_Next (Ctx, F_RBAA_TPM_ALG_RSAPSS_3072)),
               when F_AEAD_Reserved_2 =>
                  (Predecessor (Ctx, F_Alg_External) = F_AEAD_Reserved_2
                   and Valid_Next (Ctx, F_Alg_External)),
               when F_DHE_FFDHE4096 =>
                  Get_DHE_FFDHE4096 (Ctx) = To_Actual (Val)
                  and (Predecessor (Ctx, F_DHE_FFDHE3072) = F_DHE_FFDHE4096
                       and Valid_Next (Ctx, F_DHE_FFDHE3072)),
               when F_RBAA_TPM_ALG_RSAPSS_3072 =>
                  Get_RBAA_TPM_ALG_RSAPSS_3072 (Ctx) = To_Actual (Val)
                  and (Predecessor (Ctx, F_RBAA_TPM_ALG_RSASSA_3072) = F_RBAA_TPM_ALG_RSAPSS_3072
                       and Valid_Next (Ctx, F_RBAA_TPM_ALG_RSASSA_3072)),
               when F_DHE_FFDHE3072 =>
                  Get_DHE_FFDHE3072 (Ctx) = To_Actual (Val)
                  and (Predecessor (Ctx, F_DHE_FFDHE2048) = F_DHE_FFDHE3072
                       and Valid_Next (Ctx, F_DHE_FFDHE2048)),
               when F_RBAA_TPM_ALG_RSASSA_3072 =>
                  Get_RBAA_TPM_ALG_RSASSA_3072 (Ctx) = To_Actual (Val)
                  and (Predecessor (Ctx, F_RBAA_TPM_ALG_RSAPSS_2048) = F_RBAA_TPM_ALG_RSASSA_3072
                       and Valid_Next (Ctx, F_RBAA_TPM_ALG_RSAPSS_2048)),
               when F_DHE_FFDHE2048 =>
                  Get_DHE_FFDHE2048 (Ctx) = To_Actual (Val)
                  and (Predecessor (Ctx, F_DHE_Reserved_2) = F_DHE_FFDHE2048
                       and Valid_Next (Ctx, F_DHE_Reserved_2)),
               when F_RBAA_TPM_ALG_RSAPSS_2048 =>
                  Get_RBAA_TPM_ALG_RSAPSS_2048 (Ctx) = To_Actual (Val)
                  and (Predecessor (Ctx, F_RBAA_TPM_ALG_RSASSA_2048) = F_RBAA_TPM_ALG_RSAPSS_2048
                       and Valid_Next (Ctx, F_RBAA_TPM_ALG_RSASSA_2048)),
               when F_DHE_Reserved_2 =>
                  (Predecessor (Ctx, F_Alg_External) = F_DHE_Reserved_2
                   and Valid_Next (Ctx, F_Alg_External)),
               when F_RBAA_TPM_ALG_RSASSA_2048 =>
                  Get_RBAA_TPM_ALG_RSASSA_2048 (Ctx) = To_Actual (Val)
                  and (Predecessor (Ctx, F_RBAA_Reserved_1) = F_RBAA_TPM_ALG_RSASSA_2048
                       and Valid_Next (Ctx, F_RBAA_Reserved_1)),
               when F_RBAA_Reserved_1 =>
                  (Predecessor (Ctx, F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P521) = F_RBAA_Reserved_1
                   and Valid_Next (Ctx, F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P521)),
               when F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P521 =>
                  Get_RBAA_TPM_ALG_ECDSA_ECC_NIST_P521 (Ctx) = To_Actual (Val)
                  and (Predecessor (Ctx, F_Alg_External) = F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P521
                       and Valid_Next (Ctx, F_Alg_External)),
               when F_Alg_External =>
                  (if Structural_Valid_Message (Ctx) then Message_Last (Ctx) = Field_Last (Ctx, Fld)))
       and (for all F in Field =>
               (if F < Fld then Ctx.Cursors (F) = Ctx.Cursors'Old (F)))
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = Ctx.First'Old
       and Ctx.Last = Ctx.Last'Old
       and Has_Buffer (Ctx) = Has_Buffer (Ctx)'Old
       and Predecessor (Ctx, Fld) = Predecessor (Ctx, Fld)'Old
       and Field_First (Ctx, Fld) = Field_First (Ctx, Fld)'Old
   is
      Buffer_First, Buffer_Last : RFLX_Types.Index;
      Offset : RFLX_Types.Offset;
      Size : constant RFLX_Types.Bit_Length := Field_Size (Ctx, Fld);
   begin
      Set (Ctx, Fld, Val, Size, True, Buffer_First, Buffer_Last, Offset);
      RFLX_Types.Lemma_Size (Val, Positive (Size));
      RFLX_Types.Insert (Val, Ctx.Buffer, Buffer_First, Buffer_Last, Offset, Positive (Size), RFLX_Types.High_Order_First);
   end Set_Scalar;

   procedure Set_Alg_Type (Ctx : in out Context; Val : RFLX.SPDM.Alg_Type) is
   begin
      Set_Scalar (Ctx, F_Alg_Type, RFLX.SPDM.To_Base_Integer (Val));
   end Set_Alg_Type;

   procedure Set_Fixed_Alg_Count (Ctx : in out Context; Val : RFLX.SPDM.Alg_Count) is
   begin
      Set_Scalar (Ctx, F_Fixed_Alg_Count, RFLX.SPDM.To_Base_Integer (Val));
   end Set_Fixed_Alg_Count;

   procedure Set_Ext_Alg_Count (Ctx : in out Context; Val : RFLX.SPDM.Alg_Count) is
   begin
      Set_Scalar (Ctx, F_Ext_Alg_Count, RFLX.SPDM.To_Base_Integer (Val));
   end Set_Ext_Alg_Count;

   procedure Set_AEAD_Reserved_1 (Ctx : in out Context; Val : RFLX.SPDM.Reserved_5) is
   begin
      Set_Scalar (Ctx, F_AEAD_Reserved_1, RFLX.SPDM.To_Base_Integer (Val));
   end Set_AEAD_Reserved_1;

   procedure Set_DHE_Reserved_1 (Ctx : in out Context; Val : RFLX.SPDM.Reserved_2) is
   begin
      Set_Scalar (Ctx, F_DHE_Reserved_1, RFLX.SPDM.To_Base_Integer (Val));
   end Set_DHE_Reserved_1;

   procedure Set_KS_Reserved_1 (Ctx : in out Context; Val : RFLX.SPDM.Reserved_7) is
   begin
      Set_Scalar (Ctx, F_KS_Reserved_1, RFLX.SPDM.To_Base_Integer (Val));
   end Set_KS_Reserved_1;

   procedure Set_RBAA_TPM_ALG_ECDSA_ECC_NIST_P384 (Ctx : in out Context; Val : Boolean) is
   begin
      Set_Scalar (Ctx, F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P384, To_Base_Integer (Val));
   end Set_RBAA_TPM_ALG_ECDSA_ECC_NIST_P384;

   procedure Set_AEAD_ChaCha20_Poly1305 (Ctx : in out Context; Val : Boolean) is
   begin
      Set_Scalar (Ctx, F_AEAD_ChaCha20_Poly1305, To_Base_Integer (Val));
   end Set_AEAD_ChaCha20_Poly1305;

   procedure Set_DHE_SecP521r1 (Ctx : in out Context; Val : Boolean) is
   begin
      Set_Scalar (Ctx, F_DHE_SecP521r1, To_Base_Integer (Val));
   end Set_DHE_SecP521r1;

   procedure Set_KS_SPDM (Ctx : in out Context; Val : Boolean) is
   begin
      Set_Scalar (Ctx, F_KS_SPDM, To_Base_Integer (Val));
   end Set_KS_SPDM;

   procedure Set_RBAA_TPM_ALG_RSAPSS_4096 (Ctx : in out Context; Val : Boolean) is
   begin
      Set_Scalar (Ctx, F_RBAA_TPM_ALG_RSAPSS_4096, To_Base_Integer (Val));
   end Set_RBAA_TPM_ALG_RSAPSS_4096;

   procedure Set_AEAD_AES_256_GCM (Ctx : in out Context; Val : Boolean) is
   begin
      Set_Scalar (Ctx, F_AEAD_AES_256_GCM, To_Base_Integer (Val));
   end Set_AEAD_AES_256_GCM;

   procedure Set_DHE_SecP384r1 (Ctx : in out Context; Val : Boolean) is
   begin
      Set_Scalar (Ctx, F_DHE_SecP384r1, To_Base_Integer (Val));
   end Set_DHE_SecP384r1;

   procedure Set_KS_Reserved_2 (Ctx : in out Context; Val : RFLX.SPDM.Reserved_8) is
   begin
      Set_Scalar (Ctx, F_KS_Reserved_2, RFLX.SPDM.To_Base_Integer (Val));
   end Set_KS_Reserved_2;

   procedure Set_RBAA_TPM_ALG_RSASSA_4096 (Ctx : in out Context; Val : Boolean) is
   begin
      Set_Scalar (Ctx, F_RBAA_TPM_ALG_RSASSA_4096, To_Base_Integer (Val));
   end Set_RBAA_TPM_ALG_RSASSA_4096;

   procedure Set_AEAD_AES_128_GCM (Ctx : in out Context; Val : Boolean) is
   begin
      Set_Scalar (Ctx, F_AEAD_AES_128_GCM, To_Base_Integer (Val));
   end Set_AEAD_AES_128_GCM;

   procedure Set_DHE_SecP256r1 (Ctx : in out Context; Val : Boolean) is
   begin
      Set_Scalar (Ctx, F_DHE_SecP256r1, To_Base_Integer (Val));
   end Set_DHE_SecP256r1;

   procedure Set_RBAA_TPM_ALG_ECDSA_ECC_NIST_P256 (Ctx : in out Context; Val : Boolean) is
   begin
      Set_Scalar (Ctx, F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P256, To_Base_Integer (Val));
   end Set_RBAA_TPM_ALG_ECDSA_ECC_NIST_P256;

   procedure Set_AEAD_Reserved_2 (Ctx : in out Context; Val : RFLX.SPDM.Reserved_8) is
   begin
      Set_Scalar (Ctx, F_AEAD_Reserved_2, RFLX.SPDM.To_Base_Integer (Val));
   end Set_AEAD_Reserved_2;

   procedure Set_DHE_FFDHE4096 (Ctx : in out Context; Val : Boolean) is
   begin
      Set_Scalar (Ctx, F_DHE_FFDHE4096, To_Base_Integer (Val));
   end Set_DHE_FFDHE4096;

   procedure Set_RBAA_TPM_ALG_RSAPSS_3072 (Ctx : in out Context; Val : Boolean) is
   begin
      Set_Scalar (Ctx, F_RBAA_TPM_ALG_RSAPSS_3072, To_Base_Integer (Val));
   end Set_RBAA_TPM_ALG_RSAPSS_3072;

   procedure Set_DHE_FFDHE3072 (Ctx : in out Context; Val : Boolean) is
   begin
      Set_Scalar (Ctx, F_DHE_FFDHE3072, To_Base_Integer (Val));
   end Set_DHE_FFDHE3072;

   procedure Set_RBAA_TPM_ALG_RSASSA_3072 (Ctx : in out Context; Val : Boolean) is
   begin
      Set_Scalar (Ctx, F_RBAA_TPM_ALG_RSASSA_3072, To_Base_Integer (Val));
   end Set_RBAA_TPM_ALG_RSASSA_3072;

   procedure Set_DHE_FFDHE2048 (Ctx : in out Context; Val : Boolean) is
   begin
      Set_Scalar (Ctx, F_DHE_FFDHE2048, To_Base_Integer (Val));
   end Set_DHE_FFDHE2048;

   procedure Set_RBAA_TPM_ALG_RSAPSS_2048 (Ctx : in out Context; Val : Boolean) is
   begin
      Set_Scalar (Ctx, F_RBAA_TPM_ALG_RSAPSS_2048, To_Base_Integer (Val));
   end Set_RBAA_TPM_ALG_RSAPSS_2048;

   procedure Set_DHE_Reserved_2 (Ctx : in out Context; Val : RFLX.SPDM.Reserved_8) is
   begin
      Set_Scalar (Ctx, F_DHE_Reserved_2, RFLX.SPDM.To_Base_Integer (Val));
   end Set_DHE_Reserved_2;

   procedure Set_RBAA_TPM_ALG_RSASSA_2048 (Ctx : in out Context; Val : Boolean) is
   begin
      Set_Scalar (Ctx, F_RBAA_TPM_ALG_RSASSA_2048, To_Base_Integer (Val));
   end Set_RBAA_TPM_ALG_RSASSA_2048;

   procedure Set_RBAA_Reserved_1 (Ctx : in out Context; Val : RFLX.SPDM.Reserved_7) is
   begin
      Set_Scalar (Ctx, F_RBAA_Reserved_1, RFLX.SPDM.To_Base_Integer (Val));
   end Set_RBAA_Reserved_1;

   procedure Set_RBAA_TPM_ALG_ECDSA_ECC_NIST_P521 (Ctx : in out Context; Val : Boolean) is
   begin
      Set_Scalar (Ctx, F_RBAA_TPM_ALG_ECDSA_ECC_NIST_P521, To_Base_Integer (Val));
   end Set_RBAA_TPM_ALG_ECDSA_ECC_NIST_P521;

   procedure Set_Alg_External_Empty (Ctx : in out Context) is
      Unused_Buffer_First, Unused_Buffer_Last : RFLX_Types.Index;
      Unused_Offset : RFLX_Types.Offset;
   begin
      Set (Ctx, F_Alg_External, 0, 0, True, Unused_Buffer_First, Unused_Buffer_Last, Unused_Offset);
   end Set_Alg_External_Empty;

   procedure Set_Alg_External (Ctx : in out Context; Seq_Ctx : RFLX.SPDM.Ext_Algs.Context) is
      Size : constant RFLX_Types.Bit_Length := RFLX_Types.To_Bit_Length (RFLX.SPDM.Ext_Algs.Byte_Size (Seq_Ctx));
      Unused_First, Unused_Last : RFLX_Types.Bit_Index;
      Buffer_First, Buffer_Last : RFLX_Types.Index;
      Unused_Offset : RFLX_Types.Offset;
   begin
      Set (Ctx, F_Alg_External, 0, Size, True, Buffer_First, Buffer_Last, Unused_Offset);
      RFLX.SPDM.Ext_Algs.Copy (Seq_Ctx, Ctx.Buffer.all (Buffer_First .. Buffer_Last));
   end Set_Alg_External;

   procedure Initialize_Alg_External_Private (Ctx : in out Context; Length : RFLX_Types.Length) with
     Pre =>
       not Ctx'Constrained
       and then RFLX.SPDM.Alg_Struct.Has_Buffer (Ctx)
       and then RFLX.SPDM.Alg_Struct.Valid_Next (Ctx, RFLX.SPDM.Alg_Struct.F_Alg_External)
       and then RFLX.SPDM.Alg_Struct.Valid_Length (Ctx, RFLX.SPDM.Alg_Struct.F_Alg_External, Length)
       and then RFLX_Types.To_Length (RFLX.SPDM.Alg_Struct.Available_Space (Ctx, RFLX.SPDM.Alg_Struct.F_Alg_External)) >= Length
       and then RFLX.SPDM.Alg_Struct.Field_First (Ctx, RFLX.SPDM.Alg_Struct.F_Alg_External) mod RFLX_Types.Byte'Size = 1,
     Post =>
       Has_Buffer (Ctx)
       and Structural_Valid (Ctx, F_Alg_External)
       and Field_Size (Ctx, F_Alg_External) = RFLX_Types.To_Bit_Length (Length)
       and Ctx.Verified_Last = Field_Last (Ctx, F_Alg_External)
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = Ctx.First'Old
       and Ctx.Last = Ctx.Last'Old
       and Predecessor (Ctx, F_Alg_External) = Predecessor (Ctx, F_Alg_External)'Old
       and Valid_Next (Ctx, F_Alg_External) = Valid_Next (Ctx, F_Alg_External)'Old
       and Get_Alg_Type (Ctx) = Get_Alg_Type (Ctx)'Old
       and Get_Fixed_Alg_Count (Ctx) = Get_Fixed_Alg_Count (Ctx)'Old
       and Get_Ext_Alg_Count (Ctx) = Get_Ext_Alg_Count (Ctx)'Old
       and Field_First (Ctx, F_Alg_External) = Field_First (Ctx, F_Alg_External)'Old
       and Field_Last (Ctx, F_Alg_External) = Field_Last (Ctx, Predecessor (Ctx, F_Alg_External)) + Field_Size (Ctx, F_Alg_External)
   is
      First : constant RFLX_Types.Bit_Index := Field_First (Ctx, F_Alg_External);
      Last : constant RFLX_Types.Bit_Index := Field_First (Ctx, F_Alg_External) + RFLX_Types.Bit_Length (Length) * RFLX_Types.Byte'Size - 1;
   begin
      pragma Assert (Last mod RFLX_Types.Byte'Size = 0);
      Reset_Dependent_Fields (Ctx, F_Alg_External);
      pragma Warnings (Off, "attribute Update is an obsolescent feature");
      Ctx := Ctx'Update (Verified_Last => Last, Written_Last => Last);
      pragma Warnings (On, "attribute Update is an obsolescent feature");
      Ctx.Cursors (F_Alg_External) := (State => S_Structural_Valid, First => First, Last => Last, Value => 0, Predecessor => Ctx.Cursors (F_Alg_External).Predecessor);
      Ctx.Cursors (Successor (Ctx, F_Alg_External)) := (State => S_Invalid, Predecessor => F_Alg_External);
   end Initialize_Alg_External_Private;

   procedure Initialize_Alg_External (Ctx : in out Context) is
   begin
      Initialize_Alg_External_Private (Ctx, RFLX_Types.To_Length (Field_Size (Ctx, F_Alg_External)));
   end Initialize_Alg_External;

   procedure Switch_To_Alg_External (Ctx : in out Context; Seq_Ctx : out RFLX.SPDM.Ext_Algs.Context) is
      First : constant RFLX_Types.Bit_Index := Field_First (Ctx, F_Alg_External);
      Last : constant RFLX_Types.Bit_Index := Field_Last (Ctx, F_Alg_External);
      Buffer : RFLX_Types.Bytes_Ptr;
   begin
      if Invalid (Ctx, F_Alg_External) then
         Reset_Dependent_Fields (Ctx, F_Alg_External);
         pragma Warnings (Off, "attribute Update is an obsolescent feature");
         Ctx := Ctx'Update (Verified_Last => Last, Written_Last => RFLX_Types.Bit_Length'Max (Ctx.Written_Last, Last));
         pragma Warnings (On, "attribute Update is an obsolescent feature");
         Ctx.Cursors (F_Alg_External) := (State => S_Structural_Valid, First => First, Last => Last, Value => 0, Predecessor => Ctx.Cursors (F_Alg_External).Predecessor);
         Ctx.Cursors (Successor (Ctx, F_Alg_External)) := (State => S_Invalid, Predecessor => F_Alg_External);
      end if;
      Take_Buffer (Ctx, Buffer);
      pragma Warnings (Off, "unused assignment to ""Buffer""");
      RFLX.SPDM.Ext_Algs.Initialize (Seq_Ctx, Buffer, First, Last);
      pragma Warnings (On, "unused assignment to ""Buffer""");
   end Switch_To_Alg_External;

   procedure Update_Alg_External (Ctx : in out Context; Seq_Ctx : in out RFLX.SPDM.Ext_Algs.Context) is
      Valid_Sequence : constant Boolean := RFLX.SPDM.Ext_Algs.Valid (Seq_Ctx);
      Buffer : RFLX_Types.Bytes_Ptr;
   begin
      RFLX.SPDM.Ext_Algs.Take_Buffer (Seq_Ctx, Buffer);
      Ctx.Buffer := Buffer;
      if Valid_Sequence then
         Ctx.Cursors (F_Alg_External) := (State => S_Valid, First => Ctx.Cursors (F_Alg_External).First, Last => Ctx.Cursors (F_Alg_External).Last, Value => Ctx.Cursors (F_Alg_External).Value, Predecessor => Ctx.Cursors (F_Alg_External).Predecessor);
      end if;
   end Update_Alg_External;

end RFLX.SPDM.Alg_Struct;
