--
--  Generated by RecordFlux 0.6.1.dev1+g8b82b38a0 on 2022-12-02
--
--  Copyright (C) 2018-2022 AdaCore
--
--  SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
--

pragma Style_Checks ("N3aAbcdefhiIklnOprStux");
pragma Warnings (Off, "redundant conversion");
pragma SPARK_Mode;
with RFLX.RFLX_Message_Sequence;
with RFLX.SPDM.Version_Number_Entry;
pragma Warnings (Off, "unit ""*RFLX_Types"" is not referenced");
with RFLX.RFLX_Types;
pragma Warnings (On, "unit ""*RFLX_Types"" is not referenced");

package RFLX.SPDM.Version_Number_Entries is new RFLX.RFLX_Message_Sequence (RFLX.SPDM.Version_Number_Entry.Context, RFLX.SPDM.Version_Number_Entry.Initialize, RFLX.SPDM.Version_Number_Entry.Take_Buffer, RFLX.SPDM.Version_Number_Entry.Copy, RFLX.SPDM.Version_Number_Entry.Has_Buffer, RFLX.SPDM.Version_Number_Entry.Size, RFLX.SPDM.Version_Number_Entry.Message_Last, RFLX.SPDM.Version_Number_Entry.Initialized, RFLX.SPDM.Version_Number_Entry.Structural_Valid_Message);
