--
--  Generated by RecordFlux 0.6.1.dev1+g8b82b38a0 on 2022-12-02
--
--  Copyright (C) 2018-2022 AdaCore
--
--  SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
--

pragma Restrictions (No_Streams);
pragma Style_Checks ("N3aAbcdefhiIklnOprStux");
pragma Warnings (Off, "redundant conversion");
with RFLX.SPDM_Responder.Session_Allocator;
with RFLX.RFLX_Types;
with RFLX.SPDM;
with RFLX.SPDM.Request;
with RFLX.SPDM.Response;
with RFLX.SPDM.Version_Number_Entries;
with RFLX.SPDM.Resp_Alg_Structs;
with RFLX.SPDM.Alg_Struct;
with RFLX.SPDM.Measurement_Record;
with RFLX.SPDM_Responder.Digests_Data;
with RFLX.SPDM.Certificate_Response;
with RFLX.SPDM.Nonce;
with RFLX.SPDM.DMTF_Measurement_Field;
with RFLX.SPDM_Responder.Opaque_Data;
with RFLX.SPDM_Responder.Signature;

package RFLX.SPDM_Responder.Session with
  SPARK_Mode
is

   use type RFLX.RFLX_Types.Index;

   use type RFLX.RFLX_Types.Length;

   type Channel is (C_Transport);

   type State is (S_Init, S_Receive_Get_Version, S_Prepare_Version, S_Send_Version, S_Receive_Get_Capabilities, S_Prepare_Capabilities, S_Send_Capabilities, S_Receive_Negotiate_Algorithms, S_Check_Algorithms_Req_Base_Asym_Alg, S_Prepare_Algorithms_Req_Base_Asym_Alg, S_Prepare_Algorithms, S_Send_Idle, S_Reset_Idle, S_Receive_Idle, S_Prepare_Digests, S_Check_Certificate, S_Prepare_Certificate, S_Reset_Measurements_Hash, S_Prepare_Measurements, S_Prepare_Measurements_Number_Of_Indices, S_Prepare_Measurements_All, S_Prepare_Measurements_Records, S_Prepare_Measurements_Slot, S_Prepare_Measurements_Response, S_Prepare_Measurements_Sign, S_Update_Measurement_Signature, S_Error_Unsupported_Request, S_Error_Invalid_Request, S_Error_Unspecified, S_Prepare_Error, S_Prepare_Zero_Data_Error, S_Prepare_Unexpected_Request_Error, S_Send_Error, S_End_Session);

   type Private_Context is private;

   type Context is abstract tagged limited
      record
         P : Private_Context;
      end record;

   procedure Plat_Cfg_CT_Exponent (Ctx : in out Context; RFLX_Result : out RFLX.SPDM.CT_Exponent) is abstract;

   procedure Plat_Cfg_Cap_Meas_Fresh (Ctx : in out Context; RFLX_Result : out Boolean) is abstract;

   procedure Plat_Cfg_Cap_Meas (Ctx : in out Context; RFLX_Result : out RFLX.SPDM.Meas_Cap) is abstract;

   procedure Plat_Cfg_Cap_Chal (Ctx : in out Context; RFLX_Result : out Boolean) is abstract;

   procedure Plat_Cfg_Cap_Cert (Ctx : in out Context; RFLX_Result : out Boolean) is abstract;

   procedure Plat_Cfg_Cap_Cache (Ctx : in out Context; RFLX_Result : out Boolean) is abstract;

   procedure Plat_Cfg_Cap_Key_Upd (Ctx : in out Context; RFLX_Result : out Boolean) is abstract;

   procedure Plat_Cfg_Cap_Hbeat (Ctx : in out Context; RFLX_Result : out Boolean) is abstract;

   procedure Plat_Cfg_Cap_Encap (Ctx : in out Context; RFLX_Result : out Boolean) is abstract;

   procedure Plat_Cfg_Cap_Mut_Auth (Ctx : in out Context; RFLX_Result : out Boolean) is abstract;

   procedure Plat_Cfg_Cap_Pub_Key_ID (Ctx : in out Context; RFLX_Result : out Boolean) is abstract;

   procedure Plat_Cfg_Sel_Measurement_Hash_Algo (Ctx : in out Context; TPM_ALG_SHA_256 : Boolean; TPM_ALG_SHA_384 : Boolean; TPM_ALG_SHA_512 : Boolean; TPM_ALG_SHA3_256 : Boolean; TPM_ALG_SHA3_384 : Boolean; TPM_ALG_SHA3_512 : Boolean; Raw_Bit_Streams_Only : Boolean; RFLX_Result : out RFLX.SPDM.Measurement_Hash_Algo) is abstract;

   procedure Plat_Cfg_Sel_Base_Asym_Algo (Ctx : in out Context; TPM_ALG_ECDSA_ECC_NIST_P384 : Boolean; TPM_ALG_RSAPSS_4096 : Boolean; TPM_ALG_RSASSA_4096 : Boolean; TPM_ALG_ECDSA_ECC_NIST_P256 : Boolean; TPM_ALG_RSAPSS_3072 : Boolean; TPM_ALG_RSASSA_3072 : Boolean; TPM_ALG_RSAPSS_2048 : Boolean; TPM_ALG_RSASSA_2048 : Boolean; TPM_ALG_ECDSA_ECC_NIST_P521 : Boolean; RFLX_Result : out RFLX.SPDM.Base_Asym_Algo) is abstract;

   procedure Plat_Cfg_Sel_Base_Hash_Algo (Ctx : in out Context; TPM_ALG_SHA_256 : Boolean; TPM_ALG_SHA_384 : Boolean; TPM_ALG_SHA_512 : Boolean; TPM_ALG_SHA3_256 : Boolean; TPM_ALG_SHA3_384 : Boolean; TPM_ALG_SHA3_512 : Boolean; RFLX_Result : out RFLX.SPDM.Base_Hash_Algo) is abstract;

   procedure Plat_Cfg_Sel_RBAA (Ctx : in out Context; Req_TPM_ALG_ECDSA_ECC_NIST_P384 : Boolean; Req_TPM_ALG_RSAPSS_4096 : Boolean; Req_TPM_ALG_RSASSA_4096 : Boolean; Req_TPM_ALG_ECDSA_ECC_NIST_P256 : Boolean; Req_TPM_ALG_RSAPSS_3072 : Boolean; Req_TPM_ALG_RSASSA_3072 : Boolean; Req_TPM_ALG_RSAPSS_2048 : Boolean; Req_TPM_ALG_RSASSA_2048 : Boolean; Req_TPM_ALG_ECDSA_ECC_NIST_P521 : Boolean; RFLX_Result : out RFLX.SPDM.Base_Asym_Algo) is abstract;

   procedure Plat_Get_Digests_Data (Ctx : in out Context; RFLX_Result : out RFLX.SPDM_Responder.Digests_Data.Structure) is abstract;

   procedure Plat_Valid_Certificate_Request (Ctx : in out Context; Slot : RFLX.SPDM.Slot; Offset : RFLX.SPDM.Offset; Length : RFLX.SPDM.Cert_Length; RFLX_Result : out Boolean) is abstract;

   procedure Plat_Get_Certificate_Response (Ctx : in out Context; Slot : RFLX.SPDM.Slot; Offset : RFLX.SPDM.Offset; Length : RFLX.SPDM.Cert_Length; RFLX_Result : out RFLX.SPDM.Certificate_Response.Structure) is abstract;

   procedure Plat_Get_Number_Of_Indices (Ctx : in out Context; RFLX_Result : out RFLX.SPDM.Measurement_Count) is abstract;

   procedure Plat_Get_Nonce (Ctx : in out Context; RFLX_Result : out RFLX.SPDM.Nonce.Structure) is abstract;

   procedure Plat_Get_DMTF_Measurement_Field (Ctx : in out Context; Index : RFLX.SPDM.Index; RFLX_Result : out RFLX.SPDM.DMTF_Measurement_Field.Structure) is abstract;

   procedure Plat_Get_Meas_Opaque_Data (Ctx : in out Context; RFLX_Result : out RFLX.SPDM_Responder.Opaque_Data.Structure) is abstract;

   procedure Plat_Get_New_Transcript (Ctx : in out Context; Kind : RFLX.SPDM_Responder.Transcript_Kind; RFLX_Result : out RFLX.SPDM_Responder.Transcript_ID) is abstract;

   procedure Plat_Valid_Transcript_ID (Ctx : in out Context; Transcript : RFLX.SPDM_Responder.Transcript_ID; RFLX_Result : out Boolean) is abstract;

   procedure Plat_Reset_Transcript (Ctx : in out Context; Transcript : RFLX.SPDM_Responder.Transcript_ID; Kind : RFLX.SPDM_Responder.Transcript_Kind; RFLX_Result : out RFLX.SPDM_Responder.Transcript_ID) is abstract;

   procedure Plat_Update_Transcript (Ctx : in out Context; Transcript : RFLX.SPDM_Responder.Transcript_ID; Data : RFLX_Types.Bytes; Offset : RFLX.SPDM.Length_16; Length : RFLX.SPDM.Length_16; RFLX_Result : out Boolean) is abstract;

   procedure Plat_Update_Transcript_Nonce (Ctx : in out Context; Transcript : RFLX.SPDM_Responder.Transcript_ID; RFLX_Result : out Boolean) is abstract;

   procedure Plat_Get_Signature (Ctx : in out Context; Transcript : RFLX.SPDM_Responder.Transcript_ID; Slot : RFLX.SPDM.Slot; RFLX_Result : out RFLX.SPDM_Responder.Signature.Structure) is abstract;

   procedure Null_Signature (Ctx : in out Context; Length : RFLX.SPDM.Signature_Length; RFLX_Result : out RFLX.SPDM_Responder.Signature.Structure) is abstract;

   function Uninitialized (Ctx : Context'Class) return Boolean;

   function Initialized (Ctx : Context'Class) return Boolean;

   function Active (Ctx : Context'Class) return Boolean;

   procedure Initialize (Ctx : in out Context'Class) with
     Pre =>
       Uninitialized (Ctx),
     Post =>
       Initialized (Ctx)
       and Active (Ctx);

   procedure Finalize (Ctx : in out Context'Class) with
     Pre =>
       Initialized (Ctx),
     Post =>
       Uninitialized (Ctx)
       and not Active (Ctx);

   pragma Warnings (Off, "subprogram ""Tick"" has no effect");

   procedure Tick (Ctx : in out Context'Class) with
     Pre =>
       Initialized (Ctx),
     Post =>
       Initialized (Ctx);

   pragma Warnings (On, "subprogram ""Tick"" has no effect");

   function In_IO_State (Ctx : Context'Class) return Boolean;

   pragma Warnings (Off, "subprogram ""Run"" has no effect");

   procedure Run (Ctx : in out Context'Class) with
     Pre =>
       Initialized (Ctx),
     Post =>
       Initialized (Ctx);

   pragma Warnings (On, "subprogram ""Run"" has no effect");

   function Next_State (Ctx : Context'Class) return State;

   function Has_Data (Ctx : Context'Class; Chan : Channel) return Boolean with
     Pre =>
       Initialized (Ctx);

   function Read_Buffer_Size (Ctx : Context'Class; Chan : Channel) return RFLX_Types.Length with
     Pre =>
       Initialized (Ctx)
       and then Has_Data (Ctx, Chan);

   procedure Read (Ctx : Context'Class; Chan : Channel; Buffer : out RFLX_Types.Bytes; Offset : RFLX_Types.Length := 0) with
     Pre =>
       Initialized (Ctx)
       and then Has_Data (Ctx, Chan)
       and then Buffer'Length > 0
       and then Offset <= RFLX_Types.Length'Last - Buffer'Length
       and then Buffer'Length + Offset <= Read_Buffer_Size (Ctx, Chan),
     Post =>
       Initialized (Ctx);

   function Needs_Data (Ctx : Context'Class; Chan : Channel) return Boolean with
     Pre =>
       Initialized (Ctx);

   function Write_Buffer_Size (Ctx : Context'Class; Chan : Channel) return RFLX_Types.Length with
     Pre =>
       Initialized (Ctx)
       and then Needs_Data (Ctx, Chan);

   procedure Write (Ctx : in out Context'Class; Chan : Channel; Buffer : RFLX_Types.Bytes; Offset : RFLX_Types.Length := 0) with
     Pre =>
       Initialized (Ctx)
       and then Needs_Data (Ctx, Chan)
       and then Buffer'Length > 0
       and then Offset <= RFLX_Types.Length'Last - Buffer'Length
       and then Buffer'Length + Offset <= Write_Buffer_Size (Ctx, Chan),
     Post =>
       Initialized (Ctx);

private

   type Private_Context is
      record
         Next_State : State := S_Init;
         Request_Ctx : SPDM.Request.Context;
         Response_Ctx : SPDM.Response.Context;
         Supp_Versions_Ctx : SPDM.Version_Number_Entries.Context;
         Measurement_Hash_Algo : SPDM.Measurement_Hash_Algo := SPDM.Measurement_Hash_Algo'First;
         Hash_Length : SPDM.Hash_Length := 32;
         Signature_Length : SPDM.Signature_Length := 0;
         Slot : SPDM.Slot := SPDM.Slot'First;
         Offset : SPDM.Offset := SPDM.Offset'First;
         Length : SPDM.Cert_Length := SPDM.Cert_Length'First;
         Resp_Alg_Structs_Ctx : SPDM.Resp_Alg_Structs.Context;
         Resp_Alg_Struct_Ctx : SPDM.Alg_Struct.Context;
         Resp_Alg_Struct_Count : SPDM.Alg_Struct_Count := SPDM.Alg_Struct_Count'First;
         Reset_Measurement_Sig : Boolean := True;
         Measurement_Slot : SPDM.Narrow_Slot := SPDM.Narrow_Slot'First;
         Measurement_Record_Ctx : SPDM.Measurement_Record.Context;
         Transcript_Meas : SPDM_Responder.Transcript_ID := SPDM_Responder.Transcript_ID'First;
         Current_Measurement : SPDM.Index := SPDM.Index'First;
         Last_Measurement : SPDM.Index := SPDM.Index'First;
         Number_Of_Indices : SPDM.Measurement_Count := SPDM.Measurement_Count'First;
         Number_Of_Blocks : SPDM.Block_Count := SPDM.Block_Count'First;
         Error_Code : SPDM.Error_Code := SPDM.Error_Code'First;
         CT_Exponent : SPDM.CT_Exponent := 0;
         Cap_MAC : Boolean := False;
         Cap_Encrypt : Boolean := False;
         Cap_Meas_Fresh : Boolean := False;
         Cap_Meas : SPDM.Meas_Cap := SPDM.Meas_Unsupported;
         Cap_Chal : Boolean := False;
         Cap_Cert : Boolean := False;
         Cap_Cache : Boolean := False;
         Cap_Handshake_In_The_Clear : Boolean := False;
         Cap_Key_Upd : Boolean := False;
         Cap_Hbeat : Boolean := False;
         Cap_Encap : Boolean := False;
         Cap_PSK : SPDM.PSK_Resp_Cap := SPDM.PSK_Resp_Unsupported;
         Cap_Key_Ex : Boolean := False;
         Cap_Mut_Auth : Boolean := False;
         Cap_Pub_Key_ID : Boolean := False;
         Slots : SPDM_Responder.Session_Allocator.Slots;
         Memory : SPDM_Responder.Session_Allocator.Memory;
      end record;

   function Uninitialized (Ctx : Context'Class) return Boolean is
     (not SPDM.Request.Has_Buffer (Ctx.P.Request_Ctx)
      and not SPDM.Response.Has_Buffer (Ctx.P.Response_Ctx)
      and not SPDM.Version_Number_Entries.Has_Buffer (Ctx.P.Supp_Versions_Ctx)
      and not SPDM.Resp_Alg_Structs.Has_Buffer (Ctx.P.Resp_Alg_Structs_Ctx)
      and not SPDM.Alg_Struct.Has_Buffer (Ctx.P.Resp_Alg_Struct_Ctx)
      and not SPDM.Measurement_Record.Has_Buffer (Ctx.P.Measurement_Record_Ctx)
      and SPDM_Responder.Session_Allocator.Uninitialized (Ctx.P.Slots));

   function Global_Initialized (Ctx : Context'Class) return Boolean is
     (SPDM.Request.Has_Buffer (Ctx.P.Request_Ctx)
      and then Ctx.P.Request_Ctx.Buffer_First = RFLX_Types.Index'First
      and then Ctx.P.Request_Ctx.Buffer_Last = RFLX_Types.Index'First + 127
      and then SPDM.Response.Has_Buffer (Ctx.P.Response_Ctx)
      and then Ctx.P.Response_Ctx.Buffer_First = RFLX_Types.Index'First
      and then Ctx.P.Response_Ctx.Buffer_Last = RFLX_Types.Index'First + 2049
      and then SPDM.Version_Number_Entries.Has_Buffer (Ctx.P.Supp_Versions_Ctx)
      and then Ctx.P.Supp_Versions_Ctx.Buffer_First = RFLX_Types.Index'First
      and then Ctx.P.Supp_Versions_Ctx.Buffer_Last = RFLX_Types.Index'First + 1
      and then SPDM.Resp_Alg_Structs.Has_Buffer (Ctx.P.Resp_Alg_Structs_Ctx)
      and then Ctx.P.Resp_Alg_Structs_Ctx.Buffer_First = RFLX_Types.Index'First
      and then Ctx.P.Resp_Alg_Structs_Ctx.Buffer_Last = RFLX_Types.Index'First + 99
      and then SPDM.Alg_Struct.Has_Buffer (Ctx.P.Resp_Alg_Struct_Ctx)
      and then Ctx.P.Resp_Alg_Struct_Ctx.Buffer_First = RFLX_Types.Index'First
      and then Ctx.P.Resp_Alg_Struct_Ctx.Buffer_Last = RFLX_Types.Index'First + 15
      and then SPDM.Measurement_Record.Has_Buffer (Ctx.P.Measurement_Record_Ctx)
      and then Ctx.P.Measurement_Record_Ctx.Buffer_First = RFLX_Types.Index'First
      and then Ctx.P.Measurement_Record_Ctx.Buffer_Last = RFLX_Types.Index'First + 2049);

   function Initialized (Ctx : Context'Class) return Boolean is
     (Global_Initialized (Ctx)
      and then SPDM_Responder.Session_Allocator.Global_Allocated (Ctx.P.Slots));

   function Active (Ctx : Context'Class) return Boolean is
     (Ctx.P.Next_State /= S_End_Session);

   function Next_State (Ctx : Context'Class) return State is
     (Ctx.P.Next_State);

   function Has_Data (Ctx : Context'Class; Chan : Channel) return Boolean is
     ((case Chan is
          when C_Transport =>
             (case Ctx.P.Next_State is
                 when S_Send_Version | S_Send_Capabilities | S_Send_Idle | S_Send_Error =>
                    SPDM.Response.Structural_Valid_Message (Ctx.P.Response_Ctx)
                    and SPDM.Response.Byte_Size (Ctx.P.Response_Ctx) > 0,
                 when others =>
                    False)));

   function Read_Buffer_Size (Ctx : Context'Class; Chan : Channel) return RFLX_Types.Length is
     ((case Chan is
          when C_Transport =>
             (case Ctx.P.Next_State is
                 when S_Send_Version | S_Send_Capabilities | S_Send_Idle | S_Send_Error =>
                    SPDM.Response.Byte_Size (Ctx.P.Response_Ctx),
                 when others =>
                    RFLX_Types.Unreachable)));

   function Needs_Data (Ctx : Context'Class; Chan : Channel) return Boolean is
     ((case Chan is
          when C_Transport =>
             (case Ctx.P.Next_State is
                 when S_Receive_Get_Version | S_Receive_Get_Capabilities | S_Receive_Negotiate_Algorithms | S_Receive_Idle =>
                    True,
                 when others =>
                    False)));

   function Write_Buffer_Size (Ctx : Context'Class; Chan : Channel) return RFLX_Types.Length is
     ((case Chan is
          when C_Transport =>
             (case Ctx.P.Next_State is
                 when S_Receive_Get_Version | S_Receive_Get_Capabilities | S_Receive_Negotiate_Algorithms | S_Receive_Idle =>
                    SPDM.Request.Buffer_Length (Ctx.P.Request_Ctx),
                 when others =>
                    RFLX_Types.Unreachable)));

end RFLX.SPDM_Responder.Session;
