--
--  Generated by RecordFlux 0.6.1.dev1+g8b82b38a0 on 2022-12-02
--
--  Copyright (C) 2018-2022 AdaCore
--
--  SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
--

pragma Style_Checks ("N3aAbcdefhiIklnOprStux");
pragma Warnings (Off, "redundant conversion");
with RFLX.RFLX_Types;

package RFLX.SPDM with
  SPARK_Mode
is

   type Length_16 is range 0 .. 4095 with
     Size =>
       16;

   use type RFLX.RFLX_Types.Base_Integer;

   function Valid_Length_16 (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val <= 4095);

   function To_Base_Integer (Val : RFLX.SPDM.Length_16) return RFLX.RFLX_Types.Base_Integer is
     (RFLX.RFLX_Types.Base_Integer (Val));

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Length_16 is
     (RFLX.SPDM.Length_16 (Val))
    with
     Pre =>
       Valid_Length_16 (Val);

   type Length_24 is mod 2**24 with
     Size =>
       24;

   function Valid_Length_24 (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val <= 1677722);

   function To_Base_Integer (Val : RFLX.SPDM.Length_24) return RFLX.RFLX_Types.Base_Integer is
     (RFLX.RFLX_Types.Base_Integer (Val));

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Length_24 is
     (RFLX.SPDM.Length_24 (Val))
    with
     Pre =>
       Valid_Length_24 (Val);

   type Index is range 0 .. 2**8 - 1 with
     Size =>
       8;

   function Valid_Index (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val <= 255);

   function To_Base_Integer (Val : RFLX.SPDM.Index) return RFLX.RFLX_Types.Base_Integer is
     (RFLX.RFLX_Types.Base_Integer (Val));

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Index is
     (RFLX.SPDM.Index (Val))
    with
     Pre =>
       Valid_Index (Val);

   type Signature_Length is range 0 .. 512 with
     Size =>
       16;

   function Valid_Signature_Length (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val <= 512);

   function To_Base_Integer (Val : RFLX.SPDM.Signature_Length) return RFLX.RFLX_Types.Base_Integer is
     (RFLX.RFLX_Types.Base_Integer (Val));

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Signature_Length is
     (RFLX.SPDM.Signature_Length (Val))
    with
     Pre =>
       Valid_Signature_Length (Val);

   type Exchange_Data_Length is range 0 .. 512 with
     Size =>
       10;

   function Valid_Exchange_Data_Length (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val <= 512);

   function To_Base_Integer (Val : RFLX.SPDM.Exchange_Data_Length) return RFLX.RFLX_Types.Base_Integer is
     (RFLX.RFLX_Types.Base_Integer (Val));

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Exchange_Data_Length is
     (RFLX.SPDM.Exchange_Data_Length (Val))
    with
     Pre =>
       Valid_Exchange_Data_Length (Val);

   type Hash_Length is range 0 .. 64 with
     Size =>
       8;

   function Valid_Hash_Length (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val <= 64);

   function To_Base_Integer (Val : RFLX.SPDM.Hash_Length) return RFLX.RFLX_Types.Base_Integer is
     (RFLX.RFLX_Types.Base_Integer (Val));

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Hash_Length is
     (RFLX.SPDM.Hash_Length (Val))
    with
     Pre =>
       Valid_Hash_Length (Val);

   type Reserved_1 is range 0 .. 0 with
     Size =>
       1;

   function Valid_Reserved_1 (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val = 0);

   function To_Base_Integer (Val : RFLX.SPDM.Reserved_1) return RFLX.RFLX_Types.Base_Integer is
     (RFLX.RFLX_Types.Base_Integer (Val));

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Reserved_1 is
     (RFLX.SPDM.Reserved_1 (Val))
    with
     Pre =>
       Valid_Reserved_1 (Val);

   type Reserved_2 is range 0 .. 0 with
     Size =>
       2;

   function Valid_Reserved_2 (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val = 0);

   function To_Base_Integer (Val : RFLX.SPDM.Reserved_2) return RFLX.RFLX_Types.Base_Integer is
     (RFLX.RFLX_Types.Base_Integer (Val));

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Reserved_2 is
     (RFLX.SPDM.Reserved_2 (Val))
    with
     Pre =>
       Valid_Reserved_2 (Val);

   type Reserved_3 is range 0 .. 0 with
     Size =>
       3;

   function Valid_Reserved_3 (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val = 0);

   function To_Base_Integer (Val : RFLX.SPDM.Reserved_3) return RFLX.RFLX_Types.Base_Integer is
     (RFLX.RFLX_Types.Base_Integer (Val));

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Reserved_3 is
     (RFLX.SPDM.Reserved_3 (Val))
    with
     Pre =>
       Valid_Reserved_3 (Val);

   type Reserved_4 is range 0 .. 0 with
     Size =>
       4;

   function Valid_Reserved_4 (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val = 0);

   function To_Base_Integer (Val : RFLX.SPDM.Reserved_4) return RFLX.RFLX_Types.Base_Integer is
     (RFLX.RFLX_Types.Base_Integer (Val));

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Reserved_4 is
     (RFLX.SPDM.Reserved_4 (Val))
    with
     Pre =>
       Valid_Reserved_4 (Val);

   type Reserved_5 is range 0 .. 0 with
     Size =>
       5;

   function Valid_Reserved_5 (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val = 0);

   function To_Base_Integer (Val : RFLX.SPDM.Reserved_5) return RFLX.RFLX_Types.Base_Integer is
     (RFLX.RFLX_Types.Base_Integer (Val));

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Reserved_5 is
     (RFLX.SPDM.Reserved_5 (Val))
    with
     Pre =>
       Valid_Reserved_5 (Val);

   type Reserved_6 is range 0 .. 0 with
     Size =>
       6;

   function Valid_Reserved_6 (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val = 0);

   function To_Base_Integer (Val : RFLX.SPDM.Reserved_6) return RFLX.RFLX_Types.Base_Integer is
     (RFLX.RFLX_Types.Base_Integer (Val));

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Reserved_6 is
     (RFLX.SPDM.Reserved_6 (Val))
    with
     Pre =>
       Valid_Reserved_6 (Val);

   type Reserved_7 is range 0 .. 0 with
     Size =>
       7;

   function Valid_Reserved_7 (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val = 0);

   function To_Base_Integer (Val : RFLX.SPDM.Reserved_7) return RFLX.RFLX_Types.Base_Integer is
     (RFLX.RFLX_Types.Base_Integer (Val));

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Reserved_7 is
     (RFLX.SPDM.Reserved_7 (Val))
    with
     Pre =>
       Valid_Reserved_7 (Val);

   type Reserved_8 is range 0 .. 0 with
     Size =>
       8;

   function Valid_Reserved_8 (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val = 0);

   function To_Base_Integer (Val : RFLX.SPDM.Reserved_8) return RFLX.RFLX_Types.Base_Integer is
     (RFLX.RFLX_Types.Base_Integer (Val));

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Reserved_8 is
     (RFLX.SPDM.Reserved_8 (Val))
    with
     Pre =>
       Valid_Reserved_8 (Val);

   type Reserved_15 is range 0 .. 0 with
     Size =>
       15;

   function Valid_Reserved_15 (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val = 0);

   function To_Base_Integer (Val : RFLX.SPDM.Reserved_15) return RFLX.RFLX_Types.Base_Integer is
     (RFLX.RFLX_Types.Base_Integer (Val));

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Reserved_15 is
     (RFLX.SPDM.Reserved_15 (Val))
    with
     Pre =>
       Valid_Reserved_15 (Val);

   type Reserved_16 is range 0 .. 0 with
     Size =>
       16;

   function Valid_Reserved_16 (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val = 0);

   function To_Base_Integer (Val : RFLX.SPDM.Reserved_16) return RFLX.RFLX_Types.Base_Integer is
     (RFLX.RFLX_Types.Base_Integer (Val));

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Reserved_16 is
     (RFLX.SPDM.Reserved_16 (Val))
    with
     Pre =>
       Valid_Reserved_16 (Val);

   type Reserved_24 is range 0 .. 0 with
     Size =>
       24;

   function Valid_Reserved_24 (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val = 0);

   function To_Base_Integer (Val : RFLX.SPDM.Reserved_24) return RFLX.RFLX_Types.Base_Integer is
     (RFLX.RFLX_Types.Base_Integer (Val));

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Reserved_24 is
     (RFLX.SPDM.Reserved_24 (Val))
    with
     Pre =>
       Valid_Reserved_24 (Val);

   type Reserved_32 is range 0 .. 0 with
     Size =>
       32;

   function Valid_Reserved_32 (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val = 0);

   function To_Base_Integer (Val : RFLX.SPDM.Reserved_32) return RFLX.RFLX_Types.Base_Integer is
     (RFLX.RFLX_Types.Base_Integer (Val));

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Reserved_32 is
     (RFLX.SPDM.Reserved_32 (Val))
    with
     Pre =>
       Valid_Reserved_32 (Val);

   type Major_Version is range 0 .. 2**4 - 1 with
     Size =>
       4;

   function Valid_Major_Version (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val <= 15);

   function To_Base_Integer (Val : RFLX.SPDM.Major_Version) return RFLX.RFLX_Types.Base_Integer is
     (RFLX.RFLX_Types.Base_Integer (Val));

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Major_Version is
     (RFLX.SPDM.Major_Version (Val))
    with
     Pre =>
       Valid_Major_Version (Val);

   type Minor_Version is range 0 .. 2**4 - 1 with
     Size =>
       4;

   function Valid_Minor_Version (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val <= 15);

   function To_Base_Integer (Val : RFLX.SPDM.Minor_Version) return RFLX.RFLX_Types.Base_Integer is
     (RFLX.RFLX_Types.Base_Integer (Val));

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Minor_Version is
     (RFLX.SPDM.Minor_Version (Val))
    with
     Pre =>
       Valid_Minor_Version (Val);

   type Update_Version_Number is range 0 .. 2**4 - 1 with
     Size =>
       4;

   function Valid_Update_Version_Number (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val <= 15);

   function To_Base_Integer (Val : RFLX.SPDM.Update_Version_Number) return RFLX.RFLX_Types.Base_Integer is
     (RFLX.RFLX_Types.Base_Integer (Val));

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Update_Version_Number is
     (RFLX.SPDM.Update_Version_Number (Val))
    with
     Pre =>
       Valid_Update_Version_Number (Val);

   type Alpha is range 0 .. 2**4 - 1 with
     Size =>
       4;

   function Valid_Alpha (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val <= 15);

   function To_Base_Integer (Val : RFLX.SPDM.Alpha) return RFLX.RFLX_Types.Base_Integer is
     (RFLX.RFLX_Types.Base_Integer (Val));

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Alpha is
     (RFLX.SPDM.Alpha (Val))
    with
     Pre =>
       Valid_Alpha (Val);

   type Request_Code is (Get_Digests, Get_Certificate, Challenge, Get_Version, Get_Measurements, Get_Capabilities, Negotiate_Algorithms, Key_Exchange, Finish, PSK_Exchange, PSK_Finish, Heartbeat, Key_Update, Get_Encapsulated_Request, Deliver_Encapsulated_Response, End_Session, Vendor_Defined_Request, Respond_If_Ready) with
     Size =>
       8;
   for Request_Code use (Get_Digests => 129, Get_Certificate => 130, Challenge => 131, Get_Version => 132, Get_Measurements => 224, Get_Capabilities => 225, Negotiate_Algorithms => 227, Key_Exchange => 228, Finish => 229, PSK_Exchange => 230, PSK_Finish => 231, Heartbeat => 232, Key_Update => 233, Get_Encapsulated_Request => 234, Deliver_Encapsulated_Response => 235, End_Session => 236, Vendor_Defined_Request => 254, Respond_If_Ready => 255);

   function Valid_Request_Code (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val in 16#81# | 16#82# | 16#83# | 16#84# | 16#E0# | 16#E1# | 16#E3# | 16#E4# | 16#E5# | 16#E6# | 16#E7# | 16#E8# | 16#E9# | 16#EA# | 16#EB# | 16#EC# | 16#FF# | 16#FE#);

   function To_Base_Integer (Enum : RFLX.SPDM.Request_Code) return RFLX.RFLX_Types.Base_Integer is
     ((case Enum is
          when Get_Digests =>
             16#81#,
          when Get_Certificate =>
             16#82#,
          when Challenge =>
             16#83#,
          when Get_Version =>
             16#84#,
          when Get_Measurements =>
             16#E0#,
          when Get_Capabilities =>
             16#E1#,
          when Negotiate_Algorithms =>
             16#E3#,
          when Key_Exchange =>
             16#E4#,
          when Finish =>
             16#E5#,
          when PSK_Exchange =>
             16#E6#,
          when PSK_Finish =>
             16#E7#,
          when Heartbeat =>
             16#E8#,
          when Key_Update =>
             16#E9#,
          when Get_Encapsulated_Request =>
             16#EA#,
          when Deliver_Encapsulated_Response =>
             16#EB#,
          when End_Session =>
             16#EC#,
          when Respond_If_Ready =>
             16#FF#,
          when Vendor_Defined_Request =>
             16#FE#));

   pragma Warnings (Off, "unreachable branch");

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Request_Code is
     ((case Val is
          when 16#81# =>
             Get_Digests,
          when 16#82# =>
             Get_Certificate,
          when 16#83# =>
             Challenge,
          when 16#84# =>
             Get_Version,
          when 16#E0# =>
             Get_Measurements,
          when 16#E1# =>
             Get_Capabilities,
          when 16#E3# =>
             Negotiate_Algorithms,
          when 16#E4# =>
             Key_Exchange,
          when 16#E5# =>
             Finish,
          when 16#E6# =>
             PSK_Exchange,
          when 16#E7# =>
             PSK_Finish,
          when 16#E8# =>
             Heartbeat,
          when 16#E9# =>
             Key_Update,
          when 16#EA# =>
             Get_Encapsulated_Request,
          when 16#EB# =>
             Deliver_Encapsulated_Response,
          when 16#EC# =>
             End_Session,
          when 16#FF# =>
             Respond_If_Ready,
          when 16#FE# =>
             Vendor_Defined_Request,
          when others =>
             RFLX.SPDM.Request_Code'Last))
    with
     Pre =>
       Valid_Request_Code (Val);

   pragma Warnings (On, "unreachable branch");

   type Response_Code is (Digests, Certificate, Challenge_Auth, Version, Measurements, Capabilities, Algorithms, Key_Exchange_RSP, Finish_RSP, PSK_Exchange_RSP, PSK_Finish_RSP, Heartbeat_ACK, Key_Update_ACK, Encapsulated_Request, Encapsulated_Response_ACK, End_Session_ACK, Vendor_Defined_Response, Error) with
     Size =>
       8;
   for Response_Code use (Digests => 1, Certificate => 2, Challenge_Auth => 3, Version => 4, Measurements => 96, Capabilities => 97, Algorithms => 99, Key_Exchange_RSP => 100, Finish_RSP => 101, PSK_Exchange_RSP => 102, PSK_Finish_RSP => 103, Heartbeat_ACK => 104, Key_Update_ACK => 105, Encapsulated_Request => 106, Encapsulated_Response_ACK => 107, End_Session_ACK => 108, Vendor_Defined_Response => 126, Error => 127);

   function Valid_Response_Code (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val in 16#1# | 16#2# | 16#3# | 16#4# | 16#60# | 16#61# | 16#63# | 16#64# | 16#65# | 16#66# | 16#67# | 16#68# | 16#69# | 16#6A# | 16#6B# | 16#6C# | 16#7E# | 16#7F#);

   function To_Base_Integer (Enum : RFLX.SPDM.Response_Code) return RFLX.RFLX_Types.Base_Integer is
     ((case Enum is
          when Digests =>
             16#1#,
          when Certificate =>
             16#2#,
          when Challenge_Auth =>
             16#3#,
          when Version =>
             16#4#,
          when Measurements =>
             16#60#,
          when Capabilities =>
             16#61#,
          when Algorithms =>
             16#63#,
          when Key_Exchange_RSP =>
             16#64#,
          when Finish_RSP =>
             16#65#,
          when PSK_Exchange_RSP =>
             16#66#,
          when PSK_Finish_RSP =>
             16#67#,
          when Heartbeat_ACK =>
             16#68#,
          when Key_Update_ACK =>
             16#69#,
          when Encapsulated_Request =>
             16#6A#,
          when Encapsulated_Response_ACK =>
             16#6B#,
          when End_Session_ACK =>
             16#6C#,
          when Vendor_Defined_Response =>
             16#7E#,
          when Error =>
             16#7F#));

   pragma Warnings (Off, "unreachable branch");

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Response_Code is
     ((case Val is
          when 16#1# =>
             Digests,
          when 16#2# =>
             Certificate,
          when 16#3# =>
             Challenge_Auth,
          when 16#4# =>
             Version,
          when 16#60# =>
             Measurements,
          when 16#61# =>
             Capabilities,
          when 16#63# =>
             Algorithms,
          when 16#64# =>
             Key_Exchange_RSP,
          when 16#65# =>
             Finish_RSP,
          when 16#66# =>
             PSK_Exchange_RSP,
          when 16#67# =>
             PSK_Finish_RSP,
          when 16#68# =>
             Heartbeat_ACK,
          when 16#69# =>
             Key_Update_ACK,
          when 16#6A# =>
             Encapsulated_Request,
          when 16#6B# =>
             Encapsulated_Response_ACK,
          when 16#6C# =>
             End_Session_ACK,
          when 16#7E# =>
             Vendor_Defined_Response,
          when 16#7F# =>
             Error,
          when others =>
             RFLX.SPDM.Response_Code'Last))
    with
     Pre =>
       Valid_Response_Code (Val);

   pragma Warnings (On, "unreachable branch");

   type Slot_Present is range 0 .. 1 with
     Size =>
       1;

   function Valid_Slot_Present (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val <= 1);

   function To_Base_Integer (Val : RFLX.SPDM.Slot_Present) return RFLX.RFLX_Types.Base_Integer is
     (RFLX.RFLX_Types.Base_Integer (Val));

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Slot_Present is
     (RFLX.SPDM.Slot_Present (Val))
    with
     Pre =>
       Valid_Slot_Present (Val);

   type Version_Number_Entry_Count is range 1 .. 2**8 - 1 with
     Size =>
       8;

   function Valid_Version_Number_Entry_Count (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val >= 1
      and Val <= 255);

   function To_Base_Integer (Val : RFLX.SPDM.Version_Number_Entry_Count) return RFLX.RFLX_Types.Base_Integer is
     (RFLX.RFLX_Types.Base_Integer (Val));

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Version_Number_Entry_Count is
     (RFLX.SPDM.Version_Number_Entry_Count (Val))
    with
     Pre =>
       Valid_Version_Number_Entry_Count (Val);

   type CT_Exponent is range 0 .. 2**8 - 1 with
     Size =>
       8;

   function Valid_CT_Exponent (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val <= 255);

   function To_Base_Integer (Val : RFLX.SPDM.CT_Exponent) return RFLX.RFLX_Types.Base_Integer is
     (RFLX.RFLX_Types.Base_Integer (Val));

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.CT_Exponent is
     (RFLX.SPDM.CT_Exponent (Val))
    with
     Pre =>
       Valid_CT_Exponent (Val);

   type PSK_Request_Cap is (PSK_Req_Unsupported, PSK_Req_Supported) with
     Size =>
       2;
   for PSK_Request_Cap use (PSK_Req_Unsupported => 0, PSK_Req_Supported => 1);

   function Valid_PSK_Request_Cap (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val in 0 | 1);

   function To_Base_Integer (Enum : RFLX.SPDM.PSK_Request_Cap) return RFLX.RFLX_Types.Base_Integer is
     ((case Enum is
          when PSK_Req_Unsupported =>
             0,
          when PSK_Req_Supported =>
             1));

   pragma Warnings (Off, "unreachable branch");

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.PSK_Request_Cap is
     ((case Val is
          when 0 =>
             PSK_Req_Unsupported,
          when 1 =>
             PSK_Req_Supported,
          when others =>
             RFLX.SPDM.PSK_Request_Cap'Last))
    with
     Pre =>
       Valid_PSK_Request_Cap (Val);

   pragma Warnings (On, "unreachable branch");

   type Meas_Cap is (Meas_Unsupported, Meas_Plain, Meas_Signed) with
     Size =>
       2;
   for Meas_Cap use (Meas_Unsupported => 0, Meas_Plain => 1, Meas_Signed => 2);

   function Valid_Meas_Cap (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val in 0 | 1 | 2);

   function To_Base_Integer (Enum : RFLX.SPDM.Meas_Cap) return RFLX.RFLX_Types.Base_Integer is
     ((case Enum is
          when Meas_Unsupported =>
             0,
          when Meas_Plain =>
             1,
          when Meas_Signed =>
             2));

   pragma Warnings (Off, "unreachable branch");

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Meas_Cap is
     ((case Val is
          when 0 =>
             Meas_Unsupported,
          when 1 =>
             Meas_Plain,
          when 2 =>
             Meas_Signed,
          when others =>
             RFLX.SPDM.Meas_Cap'Last))
    with
     Pre =>
       Valid_Meas_Cap (Val);

   pragma Warnings (On, "unreachable branch");

   type PSK_Resp_Cap is (PSK_Resp_Unsupported, PSK_Resp_Without_Context, PSK_Resp_With_Context) with
     Size =>
       2;
   for PSK_Resp_Cap use (PSK_Resp_Unsupported => 0, PSK_Resp_Without_Context => 1, PSK_Resp_With_Context => 2);

   function Valid_PSK_Resp_Cap (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val in 0 | 1 | 2);

   function To_Base_Integer (Enum : RFLX.SPDM.PSK_Resp_Cap) return RFLX.RFLX_Types.Base_Integer is
     ((case Enum is
          when PSK_Resp_Unsupported =>
             0,
          when PSK_Resp_Without_Context =>
             1,
          when PSK_Resp_With_Context =>
             2));

   pragma Warnings (Off, "unreachable branch");

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.PSK_Resp_Cap is
     ((case Val is
          when 0 =>
             PSK_Resp_Unsupported,
          when 1 =>
             PSK_Resp_Without_Context,
          when 2 =>
             PSK_Resp_With_Context,
          when others =>
             RFLX.SPDM.PSK_Resp_Cap'Last))
    with
     Pre =>
       Valid_PSK_Resp_Cap (Val);

   pragma Warnings (On, "unreachable branch");

   type Narrow_Slot is (NS_0, NS_1, NS_2, NS_3, NS_4, NS_5, NS_6, NS_7, NS_Trusted_Environment) with
     Size =>
       4;
   for Narrow_Slot use (NS_0 => 0, NS_1 => 1, NS_2 => 2, NS_3 => 3, NS_4 => 4, NS_5 => 5, NS_6 => 6, NS_7 => 7, NS_Trusted_Environment => 15);

   function Valid_Narrow_Slot (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val in 16#0# | 16#1# | 16#2# | 16#3# | 16#4# | 16#5# | 16#6# | 16#7# | 16#F#);

   function To_Base_Integer (Enum : RFLX.SPDM.Narrow_Slot) return RFLX.RFLX_Types.Base_Integer is
     ((case Enum is
          when NS_0 =>
             16#0#,
          when NS_1 =>
             16#1#,
          when NS_2 =>
             16#2#,
          when NS_3 =>
             16#3#,
          when NS_4 =>
             16#4#,
          when NS_5 =>
             16#5#,
          when NS_6 =>
             16#6#,
          when NS_7 =>
             16#7#,
          when NS_Trusted_Environment =>
             16#F#));

   pragma Warnings (Off, "unreachable branch");

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Narrow_Slot is
     ((case Val is
          when 16#0# =>
             NS_0,
          when 16#1# =>
             NS_1,
          when 16#2# =>
             NS_2,
          when 16#3# =>
             NS_3,
          when 16#4# =>
             NS_4,
          when 16#5# =>
             NS_5,
          when 16#6# =>
             NS_6,
          when 16#7# =>
             NS_7,
          when 16#F# =>
             NS_Trusted_Environment,
          when others =>
             RFLX.SPDM.Narrow_Slot'Last))
    with
     Pre =>
       Valid_Narrow_Slot (Val);

   pragma Warnings (On, "unreachable branch");

   type Measurement_Specification is (DMTF) with
     Size =>
       8;
   for Measurement_Specification use (DMTF => 1);

   function Valid_Measurement_Specification (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val in 1);

   function To_Base_Integer (Enum : RFLX.SPDM.Measurement_Specification) return RFLX.RFLX_Types.Base_Integer is
     ((case Enum is
          when DMTF =>
             1));

   pragma Warnings (Off, "unreachable branch");

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Measurement_Specification is
     ((case Val is
          when 1 =>
             DMTF,
          when others =>
             RFLX.SPDM.Measurement_Specification'Last))
    with
     Pre =>
       Valid_Measurement_Specification (Val);

   pragma Warnings (On, "unreachable branch");

   type DMTF_Spec_Measurement_Value_Representation is (Digest, Raw_Bit_Stream) with
     Size =>
       1;
   for DMTF_Spec_Measurement_Value_Representation use (Digest => 0, Raw_Bit_Stream => 1);

   function Valid_DMTF_Spec_Measurement_Value_Representation (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val in 0 | 1);

   function To_Base_Integer (Enum : RFLX.SPDM.DMTF_Spec_Measurement_Value_Representation) return RFLX.RFLX_Types.Base_Integer is
     ((case Enum is
          when Digest =>
             0,
          when Raw_Bit_Stream =>
             1));

   pragma Warnings (Off, "unreachable branch");

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.DMTF_Spec_Measurement_Value_Representation is
     ((case Val is
          when 0 =>
             Digest,
          when 1 =>
             Raw_Bit_Stream,
          when others =>
             RFLX.SPDM.DMTF_Spec_Measurement_Value_Representation'Last))
    with
     Pre =>
       Valid_DMTF_Spec_Measurement_Value_Representation (Val);

   pragma Warnings (On, "unreachable branch");

   type DMTF_Spec_Measurement_Value_Type is (Immutable_ROM, Mutable_Firmware, Hardware_Configuration, Firmware_Configuration, Measured_Manifest) with
     Size =>
       7;
   for DMTF_Spec_Measurement_Value_Type use (Immutable_ROM => 0, Mutable_Firmware => 1, Hardware_Configuration => 2, Firmware_Configuration => 3, Measured_Manifest => 4);

   function Valid_DMTF_Spec_Measurement_Value_Type (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val in 0 | 1 | 2 | 3 | 4);

   function To_Base_Integer (Enum : RFLX.SPDM.DMTF_Spec_Measurement_Value_Type) return RFLX.RFLX_Types.Base_Integer is
     ((case Enum is
          when Immutable_ROM =>
             0,
          when Mutable_Firmware =>
             1,
          when Hardware_Configuration =>
             2,
          when Firmware_Configuration =>
             3,
          when Measured_Manifest =>
             4));

   pragma Warnings (Off, "unreachable branch");

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.DMTF_Spec_Measurement_Value_Type is
     ((case Val is
          when 0 =>
             Immutable_ROM,
          when 1 =>
             Mutable_Firmware,
          when 2 =>
             Hardware_Configuration,
          when 3 =>
             Firmware_Configuration,
          when 4 =>
             Measured_Manifest,
          when others =>
             RFLX.SPDM.DMTF_Spec_Measurement_Value_Type'Last))
    with
     Pre =>
       Valid_DMTF_Spec_Measurement_Value_Type (Val);

   pragma Warnings (On, "unreachable branch");

   type Measurement_Count is range 0 .. 2**8 - 1 with
     Size =>
       8;

   function Valid_Measurement_Count (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val <= 255);

   function To_Base_Integer (Val : RFLX.SPDM.Measurement_Count) return RFLX.RFLX_Types.Base_Integer is
     (RFLX.RFLX_Types.Base_Integer (Val));

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Measurement_Count is
     (RFLX.SPDM.Measurement_Count (Val))
    with
     Pre =>
       Valid_Measurement_Count (Val);

   type Block_Count is range 0 .. 2**8 - 1 with
     Size =>
       8;

   function Valid_Block_Count (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val <= 255);

   function To_Base_Integer (Val : RFLX.SPDM.Block_Count) return RFLX.RFLX_Types.Base_Integer is
     (RFLX.RFLX_Types.Base_Integer (Val));

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Block_Count is
     (RFLX.SPDM.Block_Count (Val))
    with
     Pre =>
       Valid_Block_Count (Val);

   type Registry_ID is (Reg_DMTF, Reg_TCG, Reg_USB, Reg_PCI_SIG, Reg_IANA, Reg_HD_Base_T, Reg_MIPI, Reg_CXL, Reg_JEDEC) with
     Size =>
       8;
   for Registry_ID use (Reg_DMTF => 0, Reg_TCG => 1, Reg_USB => 2, Reg_PCI_SIG => 3, Reg_IANA => 4, Reg_HD_Base_T => 5, Reg_MIPI => 6, Reg_CXL => 7, Reg_JEDEC => 8);

   function Valid_Registry_ID (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val in 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8);

   function To_Base_Integer (Enum : RFLX.SPDM.Registry_ID) return RFLX.RFLX_Types.Base_Integer is
     ((case Enum is
          when Reg_DMTF =>
             0,
          when Reg_TCG =>
             1,
          when Reg_USB =>
             2,
          when Reg_PCI_SIG =>
             3,
          when Reg_IANA =>
             4,
          when Reg_HD_Base_T =>
             5,
          when Reg_MIPI =>
             6,
          when Reg_CXL =>
             7,
          when Reg_JEDEC =>
             8));

   pragma Warnings (Off, "unreachable branch");

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Registry_ID is
     ((case Val is
          when 0 =>
             Reg_DMTF,
          when 1 =>
             Reg_TCG,
          when 2 =>
             Reg_USB,
          when 3 =>
             Reg_PCI_SIG,
          when 4 =>
             Reg_IANA,
          when 5 =>
             Reg_HD_Base_T,
          when 6 =>
             Reg_MIPI,
          when 7 =>
             Reg_CXL,
          when 8 =>
             Reg_JEDEC,
          when others =>
             RFLX.SPDM.Registry_ID'Last))
    with
     Pre =>
       Valid_Registry_ID (Val);

   pragma Warnings (On, "unreachable branch");

   type Algorithm_ID_16 is mod 2**16 with
     Size =>
       16;

   function Valid_Algorithm_ID_16 (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val <= 65535);

   function To_Base_Integer (Val : RFLX.SPDM.Algorithm_ID_16) return RFLX.RFLX_Types.Base_Integer is
     (RFLX.RFLX_Types.Base_Integer (Val));

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Algorithm_ID_16 is
     (RFLX.SPDM.Algorithm_ID_16 (Val))
    with
     Pre =>
       Valid_Algorithm_ID_16 (Val);

   type Algorithm_ID_32 is mod 2**32 with
     Size =>
       32;

   function Valid_Algorithm_ID_32 (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val <= 4294967295);

   function To_Base_Integer (Val : RFLX.SPDM.Algorithm_ID_32) return RFLX.RFLX_Types.Base_Integer is
     (RFLX.RFLX_Types.Base_Integer (Val));

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Algorithm_ID_32 is
     (RFLX.SPDM.Algorithm_ID_32 (Val))
    with
     Pre =>
       Valid_Algorithm_ID_32 (Val);

   type Alg_Type is (DHE, AEAD_Cipher_Suite, Req_Base_Asym_Alg, Key_Schedule) with
     Size =>
       8;
   for Alg_Type use (DHE => 2, AEAD_Cipher_Suite => 3, Req_Base_Asym_Alg => 4, Key_Schedule => 5);

   function Valid_Alg_Type (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val in 2 | 3 | 4 | 5);

   function To_Base_Integer (Enum : RFLX.SPDM.Alg_Type) return RFLX.RFLX_Types.Base_Integer is
     ((case Enum is
          when DHE =>
             2,
          when AEAD_Cipher_Suite =>
             3,
          when Req_Base_Asym_Alg =>
             4,
          when Key_Schedule =>
             5));

   pragma Warnings (Off, "unreachable branch");

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Alg_Type is
     ((case Val is
          when 2 =>
             DHE,
          when 3 =>
             AEAD_Cipher_Suite,
          when 4 =>
             Req_Base_Asym_Alg,
          when 5 =>
             Key_Schedule,
          when others =>
             RFLX.SPDM.Alg_Type'Last))
    with
     Pre =>
       Valid_Alg_Type (Val);

   pragma Warnings (On, "unreachable branch");

   type Alg_Count is range 0 .. 2**4 - 1 with
     Size =>
       4;

   function Valid_Alg_Count (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val <= 15);

   function To_Base_Integer (Val : RFLX.SPDM.Alg_Count) return RFLX.RFLX_Types.Base_Integer is
     (RFLX.RFLX_Types.Base_Integer (Val));

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Alg_Count is
     (RFLX.SPDM.Alg_Count (Val))
    with
     Pre =>
       Valid_Alg_Count (Val);

   type Alg_Struct_Count is range 0 .. 2**8 - 1 with
     Size =>
       8;

   function Valid_Alg_Struct_Count (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val <= 255);

   function To_Base_Integer (Val : RFLX.SPDM.Alg_Struct_Count) return RFLX.RFLX_Types.Base_Integer is
     (RFLX.RFLX_Types.Base_Integer (Val));

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Alg_Struct_Count is
     (RFLX.SPDM.Alg_Struct_Count (Val))
    with
     Pre =>
       Valid_Alg_Struct_Count (Val);

   type Ext_Asym_Count is range 0 .. 2**8 - 1 with
     Size =>
       8;

   function Valid_Ext_Asym_Count (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val <= 255);

   function To_Base_Integer (Val : RFLX.SPDM.Ext_Asym_Count) return RFLX.RFLX_Types.Base_Integer is
     (RFLX.RFLX_Types.Base_Integer (Val));

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Ext_Asym_Count is
     (RFLX.SPDM.Ext_Asym_Count (Val))
    with
     Pre =>
       Valid_Ext_Asym_Count (Val);

   type Ext_Hash_Count is range 0 .. 2**8 - 1 with
     Size =>
       8;

   function Valid_Ext_Hash_Count (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val <= 255);

   function To_Base_Integer (Val : RFLX.SPDM.Ext_Hash_Count) return RFLX.RFLX_Types.Base_Integer is
     (RFLX.RFLX_Types.Base_Integer (Val));

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Ext_Hash_Count is
     (RFLX.SPDM.Ext_Hash_Count (Val))
    with
     Pre =>
       Valid_Ext_Hash_Count (Val);

   type Measurement_Hash_Algo is (MH_Unsupported, MH_Raw_Bit_Streams_Only, MH_TPM_ALG_SHA_256, MH_TPM_ALG_SHA_384, MH_TPM_ALG_SHA_512, MH_TPM_ALG_SHA3_256, MH_TPM_ALG_SHA3_384, MH_TPM_ALG_SHA3_512) with
     Size =>
       32;
   for Measurement_Hash_Algo use (MH_Unsupported => 0, MH_Raw_Bit_Streams_Only => 1, MH_TPM_ALG_SHA_256 => 2, MH_TPM_ALG_SHA_384 => 4, MH_TPM_ALG_SHA_512 => 8, MH_TPM_ALG_SHA3_256 => 16, MH_TPM_ALG_SHA3_384 => 32, MH_TPM_ALG_SHA3_512 => 64);

   function Valid_Measurement_Hash_Algo (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val in 0 | 1 | 2 | 4 | 8 | 16 | 32 | 64);

   function To_Base_Integer (Enum : RFLX.SPDM.Measurement_Hash_Algo) return RFLX.RFLX_Types.Base_Integer is
     ((case Enum is
          when MH_Unsupported =>
             0,
          when MH_Raw_Bit_Streams_Only =>
             1,
          when MH_TPM_ALG_SHA_256 =>
             2,
          when MH_TPM_ALG_SHA_384 =>
             4,
          when MH_TPM_ALG_SHA_512 =>
             8,
          when MH_TPM_ALG_SHA3_256 =>
             16,
          when MH_TPM_ALG_SHA3_384 =>
             32,
          when MH_TPM_ALG_SHA3_512 =>
             64));

   pragma Warnings (Off, "unreachable branch");

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Measurement_Hash_Algo is
     ((case Val is
          when 0 =>
             MH_Unsupported,
          when 1 =>
             MH_Raw_Bit_Streams_Only,
          when 2 =>
             MH_TPM_ALG_SHA_256,
          when 4 =>
             MH_TPM_ALG_SHA_384,
          when 8 =>
             MH_TPM_ALG_SHA_512,
          when 16 =>
             MH_TPM_ALG_SHA3_256,
          when 32 =>
             MH_TPM_ALG_SHA3_384,
          when 64 =>
             MH_TPM_ALG_SHA3_512,
          when others =>
             RFLX.SPDM.Measurement_Hash_Algo'Last))
    with
     Pre =>
       Valid_Measurement_Hash_Algo (Val);

   pragma Warnings (On, "unreachable branch");

   type Base_Asym_Algo is (BA_Unsupported, BA_TPM_ALG_RSASSA_2048, BA_TPM_ALG_RSAPSS_2048, BA_TPM_ALG_RSASSA_3072, BA_TPM_ALG_RSAPSS_3072, BA_TPM_ALG_ECDSA_ECC_NIST_P256, BA_TPM_ALG_RSASSA_4096, BA_TPM_ALG_RSAPSS_4096, BA_TPM_ALG_ECDSA_ECC_NIST_P384, BA_TPM_ALG_ECDSA_ECC_NIST_P521) with
     Size =>
       32;
   for Base_Asym_Algo use (BA_Unsupported => 0, BA_TPM_ALG_RSASSA_2048 => 1, BA_TPM_ALG_RSAPSS_2048 => 2, BA_TPM_ALG_RSASSA_3072 => 4, BA_TPM_ALG_RSAPSS_3072 => 8, BA_TPM_ALG_ECDSA_ECC_NIST_P256 => 16, BA_TPM_ALG_RSASSA_4096 => 32, BA_TPM_ALG_RSAPSS_4096 => 64, BA_TPM_ALG_ECDSA_ECC_NIST_P384 => 128, BA_TPM_ALG_ECDSA_ECC_NIST_P521 => 256);

   function Valid_Base_Asym_Algo (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val in 0 | 1 | 2 | 4 | 8 | 16 | 32 | 64 | 128 | 256);

   function To_Base_Integer (Enum : RFLX.SPDM.Base_Asym_Algo) return RFLX.RFLX_Types.Base_Integer is
     ((case Enum is
          when BA_Unsupported =>
             0,
          when BA_TPM_ALG_RSASSA_2048 =>
             1,
          when BA_TPM_ALG_RSAPSS_2048 =>
             2,
          when BA_TPM_ALG_RSASSA_3072 =>
             4,
          when BA_TPM_ALG_RSAPSS_3072 =>
             8,
          when BA_TPM_ALG_ECDSA_ECC_NIST_P256 =>
             16,
          when BA_TPM_ALG_RSASSA_4096 =>
             32,
          when BA_TPM_ALG_RSAPSS_4096 =>
             64,
          when BA_TPM_ALG_ECDSA_ECC_NIST_P384 =>
             128,
          when BA_TPM_ALG_ECDSA_ECC_NIST_P521 =>
             256));

   pragma Warnings (Off, "unreachable branch");

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Base_Asym_Algo is
     ((case Val is
          when 0 =>
             BA_Unsupported,
          when 1 =>
             BA_TPM_ALG_RSASSA_2048,
          when 2 =>
             BA_TPM_ALG_RSAPSS_2048,
          when 4 =>
             BA_TPM_ALG_RSASSA_3072,
          when 8 =>
             BA_TPM_ALG_RSAPSS_3072,
          when 16 =>
             BA_TPM_ALG_ECDSA_ECC_NIST_P256,
          when 32 =>
             BA_TPM_ALG_RSASSA_4096,
          when 64 =>
             BA_TPM_ALG_RSAPSS_4096,
          when 128 =>
             BA_TPM_ALG_ECDSA_ECC_NIST_P384,
          when 256 =>
             BA_TPM_ALG_ECDSA_ECC_NIST_P521,
          when others =>
             RFLX.SPDM.Base_Asym_Algo'Last))
    with
     Pre =>
       Valid_Base_Asym_Algo (Val);

   pragma Warnings (On, "unreachable branch");

   type Base_Hash_Algo is (BH_Unsupported, BH_TPM_ALG_SHA_256, BH_TPM_ALG_SHA_384, BH_TPM_ALG_SHA_512, BH_TPM_ALG_SHA3_256, BH_TPM_ALG_SHA3_384, BH_TPM_ALG_SHA3_512) with
     Size =>
       32;
   for Base_Hash_Algo use (BH_Unsupported => 0, BH_TPM_ALG_SHA_256 => 1, BH_TPM_ALG_SHA_384 => 2, BH_TPM_ALG_SHA_512 => 4, BH_TPM_ALG_SHA3_256 => 8, BH_TPM_ALG_SHA3_384 => 16, BH_TPM_ALG_SHA3_512 => 32);

   function Valid_Base_Hash_Algo (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val in 0 | 1 | 2 | 4 | 8 | 16 | 32);

   function To_Base_Integer (Enum : RFLX.SPDM.Base_Hash_Algo) return RFLX.RFLX_Types.Base_Integer is
     ((case Enum is
          when BH_Unsupported =>
             0,
          when BH_TPM_ALG_SHA_256 =>
             1,
          when BH_TPM_ALG_SHA_384 =>
             2,
          when BH_TPM_ALG_SHA_512 =>
             4,
          when BH_TPM_ALG_SHA3_256 =>
             8,
          when BH_TPM_ALG_SHA3_384 =>
             16,
          when BH_TPM_ALG_SHA3_512 =>
             32));

   pragma Warnings (Off, "unreachable branch");

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Base_Hash_Algo is
     ((case Val is
          when 0 =>
             BH_Unsupported,
          when 1 =>
             BH_TPM_ALG_SHA_256,
          when 2 =>
             BH_TPM_ALG_SHA_384,
          when 4 =>
             BH_TPM_ALG_SHA_512,
          when 8 =>
             BH_TPM_ALG_SHA3_256,
          when 16 =>
             BH_TPM_ALG_SHA3_384,
          when 32 =>
             BH_TPM_ALG_SHA3_512,
          when others =>
             RFLX.SPDM.Base_Hash_Algo'Last))
    with
     Pre =>
       Valid_Base_Hash_Algo (Val);

   pragma Warnings (On, "unreachable branch");

   type Slot is (Slot_0, Slot_1, Slot_2, Slot_3, Slot_4, Slot_5, Slot_6, Slot_7, Trusted_Environment) with
     Size =>
       8;
   for Slot use (Slot_0 => 0, Slot_1 => 1, Slot_2 => 2, Slot_3 => 3, Slot_4 => 4, Slot_5 => 5, Slot_6 => 6, Slot_7 => 7, Trusted_Environment => 255);

   function Valid_Slot (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val in 16#0# | 16#1# | 16#2# | 16#3# | 16#4# | 16#5# | 16#6# | 16#7# | 16#FF#);

   function To_Base_Integer (Enum : RFLX.SPDM.Slot) return RFLX.RFLX_Types.Base_Integer is
     ((case Enum is
          when Slot_0 =>
             16#0#,
          when Slot_1 =>
             16#1#,
          when Slot_2 =>
             16#2#,
          when Slot_3 =>
             16#3#,
          when Slot_4 =>
             16#4#,
          when Slot_5 =>
             16#5#,
          when Slot_6 =>
             16#6#,
          when Slot_7 =>
             16#7#,
          when Trusted_Environment =>
             16#FF#));

   pragma Warnings (Off, "unreachable branch");

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Slot is
     ((case Val is
          when 16#0# =>
             Slot_0,
          when 16#1# =>
             Slot_1,
          when 16#2# =>
             Slot_2,
          when 16#3# =>
             Slot_3,
          when 16#4# =>
             Slot_4,
          when 16#5# =>
             Slot_5,
          when 16#6# =>
             Slot_6,
          when 16#7# =>
             Slot_7,
          when 16#FF# =>
             Trusted_Environment,
          when others =>
             RFLX.SPDM.Slot'Last))
    with
     Pre =>
       Valid_Slot (Val);

   pragma Warnings (On, "unreachable branch");

   type Offset is mod 2**16 with
     Size =>
       16;

   function Valid_Offset (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val <= 65535);

   function To_Base_Integer (Val : RFLX.SPDM.Offset) return RFLX.RFLX_Types.Base_Integer is
     (RFLX.RFLX_Types.Base_Integer (Val));

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Offset is
     (RFLX.SPDM.Offset (Val))
    with
     Pre =>
       Valid_Offset (Val);

   type Cert_Length is mod 2**16 with
     Size =>
       16;

   function Valid_Cert_Length (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val <= 65535);

   function To_Base_Integer (Val : RFLX.SPDM.Cert_Length) return RFLX.RFLX_Types.Base_Integer is
     (RFLX.RFLX_Types.Base_Integer (Val));

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Cert_Length is
     (RFLX.SPDM.Cert_Length (Val))
    with
     Pre =>
       Valid_Cert_Length (Val);

   type Portion_Length_16 is range 0 .. 1024 with
     Size =>
       16;

   function Valid_Portion_Length_16 (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val <= 1024);

   function To_Base_Integer (Val : RFLX.SPDM.Portion_Length_16) return RFLX.RFLX_Types.Base_Integer is
     (RFLX.RFLX_Types.Base_Integer (Val));

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Portion_Length_16 is
     (RFLX.SPDM.Portion_Length_16 (Val))
    with
     Pre =>
       Valid_Portion_Length_16 (Val);

   type Measurement_Summary_Hash_Type is (No_Measurement, TCB_Measurement, All_Measurements) with
     Size =>
       8;
   for Measurement_Summary_Hash_Type use (No_Measurement => 0, TCB_Measurement => 1, All_Measurements => 255);

   function Valid_Measurement_Summary_Hash_Type (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val in 16#0# | 16#1# | 16#FF#);

   function To_Base_Integer (Enum : RFLX.SPDM.Measurement_Summary_Hash_Type) return RFLX.RFLX_Types.Base_Integer is
     ((case Enum is
          when No_Measurement =>
             16#0#,
          when TCB_Measurement =>
             16#1#,
          when All_Measurements =>
             16#FF#));

   pragma Warnings (Off, "unreachable branch");

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Measurement_Summary_Hash_Type is
     ((case Val is
          when 16#0# =>
             No_Measurement,
          when 16#1# =>
             TCB_Measurement,
          when 16#FF# =>
             All_Measurements,
          when others =>
             RFLX.SPDM.Measurement_Summary_Hash_Type'Last))
    with
     Pre =>
       Valid_Measurement_Summary_Hash_Type (Val);

   pragma Warnings (On, "unreachable branch");

   type Error_Code is (Invalid_Request, Invalid_Session, Busy, Unexpected_Request, Unspecified, Decrypt_Error, Unsupported_Request, Request_In_Flight, Invalid_Response_Code, Session_Limit_Exceeded, Major_Version_Mismatch, Response_Not_Ready, Request_Resynch, Vendor) with
     Size =>
       8;
   for Error_Code use (Invalid_Request => 1, Invalid_Session => 2, Busy => 3, Unexpected_Request => 4, Unspecified => 5, Decrypt_Error => 6, Unsupported_Request => 7, Request_In_Flight => 8, Invalid_Response_Code => 9, Session_Limit_Exceeded => 10, Major_Version_Mismatch => 65, Response_Not_Ready => 66, Request_Resynch => 67, Vendor => 255);

   function Valid_Error_Code (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val in 16#1# | 16#2# | 16#3# | 16#4# | 16#5# | 16#6# | 16#7# | 16#8# | 16#9# | 16#A# | 16#41# | 16#42# | 16#43# | 16#FF#);

   function To_Base_Integer (Enum : RFLX.SPDM.Error_Code) return RFLX.RFLX_Types.Base_Integer is
     ((case Enum is
          when Invalid_Request =>
             16#1#,
          when Invalid_Session =>
             16#2#,
          when Busy =>
             16#3#,
          when Unexpected_Request =>
             16#4#,
          when Unspecified =>
             16#5#,
          when Decrypt_Error =>
             16#6#,
          when Unsupported_Request =>
             16#7#,
          when Request_In_Flight =>
             16#8#,
          when Invalid_Response_Code =>
             16#9#,
          when Session_Limit_Exceeded =>
             16#A#,
          when Major_Version_Mismatch =>
             16#41#,
          when Response_Not_Ready =>
             16#42#,
          when Request_Resynch =>
             16#43#,
          when Vendor =>
             16#FF#));

   pragma Warnings (Off, "unreachable branch");

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Error_Code is
     ((case Val is
          when 16#1# =>
             Invalid_Request,
          when 16#2# =>
             Invalid_Session,
          when 16#3# =>
             Busy,
          when 16#4# =>
             Unexpected_Request,
          when 16#5# =>
             Unspecified,
          when 16#6# =>
             Decrypt_Error,
          when 16#7# =>
             Unsupported_Request,
          when 16#8# =>
             Request_In_Flight,
          when 16#9# =>
             Invalid_Response_Code,
          when 16#A# =>
             Session_Limit_Exceeded,
          when 16#41# =>
             Major_Version_Mismatch,
          when 16#42# =>
             Response_Not_Ready,
          when 16#43# =>
             Request_Resynch,
          when 16#FF# =>
             Vendor,
          when others =>
             RFLX.SPDM.Error_Code'Last))
    with
     Pre =>
       Valid_Error_Code (Val);

   pragma Warnings (On, "unreachable branch");

   type Error_Session_ID is mod 2**8 with
     Size =>
       8;

   function Valid_Error_Session_ID (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val <= 255);

   function To_Base_Integer (Val : RFLX.SPDM.Error_Session_ID) return RFLX.RFLX_Types.Base_Integer is
     (RFLX.RFLX_Types.Base_Integer (Val));

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Error_Session_ID is
     (RFLX.SPDM.Error_Session_ID (Val))
    with
     Pre =>
       Valid_Error_Session_ID (Val);

   type RDT_Exponent is mod 2**8 with
     Size =>
       8;

   function Valid_RDT_Exponent (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val <= 255);

   function To_Base_Integer (Val : RFLX.SPDM.RDT_Exponent) return RFLX.RFLX_Types.Base_Integer is
     (RFLX.RFLX_Types.Base_Integer (Val));

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.RDT_Exponent is
     (RFLX.SPDM.RDT_Exponent (Val))
    with
     Pre =>
       Valid_RDT_Exponent (Val);

   type Token is mod 2**8 with
     Size =>
       8;

   function Valid_Token (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val <= 255);

   function To_Base_Integer (Val : RFLX.SPDM.Token) return RFLX.RFLX_Types.Base_Integer is
     (RFLX.RFLX_Types.Base_Integer (Val));

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Token is
     (RFLX.SPDM.Token (Val))
    with
     Pre =>
       Valid_Token (Val);

   type RDTM is range 1 .. 2**8 - 1 with
     Size =>
       8;

   function Valid_RDTM (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val >= 1
      and Val <= 255);

   function To_Base_Integer (Val : RFLX.SPDM.RDTM) return RFLX.RFLX_Types.Base_Integer is
     (RFLX.RFLX_Types.Base_Integer (Val));

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.RDTM is
     (RFLX.SPDM.RDTM (Val))
    with
     Pre =>
       Valid_RDTM (Val);

   type Zero_Error_Data is range 0 .. 0 with
     Size =>
       8;

   function Valid_Zero_Error_Data (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val = 0);

   function To_Base_Integer (Val : RFLX.SPDM.Zero_Error_Data) return RFLX.RFLX_Types.Base_Integer is
     (RFLX.RFLX_Types.Base_Integer (Val));

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Zero_Error_Data is
     (RFLX.SPDM.Zero_Error_Data (Val))
    with
     Pre =>
       Valid_Zero_Error_Data (Val);

   type Vendor_ID_Len is mod 2**8 with
     Size =>
       8;

   function Valid_Vendor_ID_Len (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val <= 255);

   function To_Base_Integer (Val : RFLX.SPDM.Vendor_ID_Len) return RFLX.RFLX_Types.Base_Integer is
     (RFLX.RFLX_Types.Base_Integer (Val));

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Vendor_ID_Len is
     (RFLX.SPDM.Vendor_ID_Len (Val))
    with
     Pre =>
       Valid_Vendor_ID_Len (Val);

   type Vendor_ID_Double is mod 2**16 with
     Size =>
       16;

   function Valid_Vendor_ID_Double (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val <= 65535);

   function To_Base_Integer (Val : RFLX.SPDM.Vendor_ID_Double) return RFLX.RFLX_Types.Base_Integer is
     (RFLX.RFLX_Types.Base_Integer (Val));

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Vendor_ID_Double is
     (RFLX.SPDM.Vendor_ID_Double (Val))
    with
     Pre =>
       Valid_Vendor_ID_Double (Val);

   type Vendor_ID_Quad is mod 2**32 with
     Size =>
       32;

   function Valid_Vendor_ID_Quad (Val : RFLX.RFLX_Types.Base_Integer) return Boolean is
     (Val <= 4294967295);

   function To_Base_Integer (Val : RFLX.SPDM.Vendor_ID_Quad) return RFLX.RFLX_Types.Base_Integer is
     (RFLX.RFLX_Types.Base_Integer (Val));

   function To_Actual (Val : RFLX.RFLX_Types.Base_Integer) return RFLX.SPDM.Vendor_ID_Quad is
     (RFLX.SPDM.Vendor_ID_Quad (Val))
    with
     Pre =>
       Valid_Vendor_ID_Quad (Val);

end RFLX.SPDM;
