--
--  Generated by RecordFlux 0.6.1.dev1+g8b82b38a0 on 2022-12-02
--
--  Copyright (C) 2018-2022 AdaCore
--
--  SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
--

pragma Style_Checks ("N3aAbcdefhiIklnOprStux");
pragma Warnings (Off, "redundant conversion");
with RFLX.RFLX_Types;

package RFLX.SPDM.Ext_Alg with
  SPARK_Mode,
  Annotate =>
    (GNATprove, Always_Return)
is

   pragma Warnings (Off, "use clause for type ""Base_Integer"" * has no effect");

   pragma Warnings (Off, "use clause for type ""Bytes"" * has no effect");

   pragma Warnings (Off, """BASE_INTEGER"" is already use-visible through previous use_type_clause");

   pragma Warnings (Off, """LENGTH"" is already use-visible through previous use_type_clause");

   use type RFLX_Types.Bytes_Ptr;

   use type RFLX_Types.Length;

   use type RFLX_Types.Index;

   use type RFLX_Types.Bit_Index;

   use type RFLX_Types.Base_Integer;

   use type RFLX_Types.Offset;

   pragma Warnings (On, """LENGTH"" is already use-visible through previous use_type_clause");

   pragma Warnings (On, """BASE_INTEGER"" is already use-visible through previous use_type_clause");

   pragma Warnings (On, "use clause for type ""Base_Integer"" * has no effect");

   pragma Warnings (On, "use clause for type ""Bytes"" * has no effect");

   pragma Unevaluated_Use_Of_Old (Allow);

   type Virtual_Field is (F_Initial, F_Registry_ID, F_Reserved, F_Algorithm_ID_16, F_Algorithm_ID_32, F_Final);

   subtype Field is Virtual_Field range F_Registry_ID .. F_Algorithm_ID_32;

   type Field_Cursor is private with
     Default_Initial_Condition =>
       False;

   type Field_Cursors is private with
     Default_Initial_Condition =>
       False;

   type Context (Buffer_First, Buffer_Last : RFLX_Types.Index := RFLX_Types.Index'First; First : RFLX_Types.Bit_Index := RFLX_Types.Bit_Index'First; Last : RFLX_Types.Bit_Length := RFLX_Types.Bit_Length'First) is private with
     Default_Initial_Condition =>
       RFLX_Types.To_Index (First) >= Buffer_First
       and RFLX_Types.To_Index (Last) <= Buffer_Last
       and Buffer_Last < RFLX_Types.Index'Last
       and First <= Last + 1
       and Last < RFLX_Types.Bit_Index'Last
       and First rem RFLX_Types.Byte'Size = 1
       and Last rem RFLX_Types.Byte'Size = 0;

   procedure Initialize (Ctx : out Context; Buffer : in out RFLX_Types.Bytes_Ptr; Written_Last : RFLX_Types.Bit_Length := 0) with
     Pre =>
       not Ctx'Constrained
       and then Buffer /= null
       and then Buffer'Length > 0
       and then Buffer'Last < RFLX_Types.Index'Last
       and then (Written_Last = 0
                 or (Written_Last >= RFLX_Types.To_First_Bit_Index (Buffer'First) - 1
                     and Written_Last <= RFLX_Types.To_Last_Bit_Index (Buffer'Last)))
       and then Written_Last mod RFLX_Types.Byte'Size = 0,
     Post =>
       Has_Buffer (Ctx)
       and Buffer = null
       and Ctx.Buffer_First = Buffer'First'Old
       and Ctx.Buffer_Last = Buffer'Last'Old
       and Ctx.First = RFLX_Types.To_First_Bit_Index (Ctx.Buffer_First)
       and Ctx.Last = RFLX_Types.To_Last_Bit_Index (Ctx.Buffer_Last)
       and Initialized (Ctx),
     Depends =>
       (Ctx => (Buffer, Written_Last), Buffer => null);

   procedure Initialize (Ctx : out Context; Buffer : in out RFLX_Types.Bytes_Ptr; First : RFLX_Types.Bit_Index; Last : RFLX_Types.Bit_Length; Written_Last : RFLX_Types.Bit_Length := 0) with
     Pre =>
       not Ctx'Constrained
       and then Buffer /= null
       and then Buffer'Length > 0
       and then Buffer'Last < RFLX_Types.Index'Last
       and then RFLX_Types.To_Index (First) >= Buffer'First
       and then RFLX_Types.To_Index (Last) <= Buffer'Last
       and then First <= Last + 1
       and then Last < RFLX_Types.Bit_Index'Last
       and then First rem RFLX_Types.Byte'Size = 1
       and then Last rem RFLX_Types.Byte'Size = 0
       and then (Written_Last = 0
                 or (Written_Last >= First - 1
                     and Written_Last <= Last))
       and then Written_Last rem RFLX_Types.Byte'Size = 0,
     Post =>
       Buffer = null
       and Has_Buffer (Ctx)
       and Ctx.Buffer_First = Buffer'First'Old
       and Ctx.Buffer_Last = Buffer'Last'Old
       and Ctx.First = First
       and Ctx.Last = Last
       and Initialized (Ctx),
     Depends =>
       (Ctx => (Buffer, First, Last, Written_Last), Buffer => null);

   pragma Warnings (Off, "postcondition does not mention function result");

   function Initialized (Ctx : Context) return Boolean with
     Post =>
       True;

   pragma Warnings (On, "postcondition does not mention function result");

   procedure Reset (Ctx : in out Context) with
     Pre =>
       not Ctx'Constrained
       and RFLX.SPDM.Ext_Alg.Has_Buffer (Ctx),
     Post =>
       Has_Buffer (Ctx)
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = RFLX_Types.To_First_Bit_Index (Ctx.Buffer_First)
       and Ctx.Last = RFLX_Types.To_Last_Bit_Index (Ctx.Buffer_Last)
       and Initialized (Ctx);

   procedure Reset (Ctx : in out Context; First : RFLX_Types.Bit_Index; Last : RFLX_Types.Bit_Length) with
     Pre =>
       not Ctx'Constrained
       and RFLX.SPDM.Ext_Alg.Has_Buffer (Ctx)
       and RFLX_Types.To_Index (First) >= Ctx.Buffer_First
       and RFLX_Types.To_Index (Last) <= Ctx.Buffer_Last
       and First <= Last + 1
       and Last < RFLX_Types.Bit_Length'Last
       and First rem RFLX_Types.Byte'Size = 1
       and Last rem RFLX_Types.Byte'Size = 0,
     Post =>
       Has_Buffer (Ctx)
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = First
       and Ctx.Last = Last
       and Initialized (Ctx);

   procedure Take_Buffer (Ctx : in out Context; Buffer : out RFLX_Types.Bytes_Ptr) with
     Pre =>
       RFLX.SPDM.Ext_Alg.Has_Buffer (Ctx),
     Post =>
       not Has_Buffer (Ctx)
       and Buffer /= null
       and Ctx.Buffer_First = Buffer'First
       and Ctx.Buffer_Last = Buffer'Last
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = Ctx.First'Old
       and Ctx.Last = Ctx.Last'Old
       and Context_Cursors (Ctx) = Context_Cursors (Ctx)'Old,
     Depends =>
       (Ctx => Ctx, Buffer => Ctx);

   procedure Copy (Ctx : Context; Buffer : out RFLX_Types.Bytes) with
     Pre =>
       RFLX.SPDM.Ext_Alg.Has_Buffer (Ctx)
       and then RFLX.SPDM.Ext_Alg.Structural_Valid_Message (Ctx)
       and then RFLX.SPDM.Ext_Alg.Byte_Size (Ctx) = Buffer'Length;

   function Read (Ctx : Context) return RFLX_Types.Bytes with
     Ghost,
     Pre =>
       RFLX.SPDM.Ext_Alg.Has_Buffer (Ctx)
       and then RFLX.SPDM.Ext_Alg.Structural_Valid_Message (Ctx);

   pragma Warnings (Off, "formal parameter ""*"" is not referenced");

   function Always_Valid (Buffer : RFLX_Types.Bytes) return Boolean is
     (True);

   pragma Warnings (On, "formal parameter ""*"" is not referenced");

   generic
      with procedure Read (Buffer : RFLX_Types.Bytes);
      with function Pre (Buffer : RFLX_Types.Bytes) return Boolean is Always_Valid;
   procedure Generic_Read (Ctx : Context) with
     Pre =>
       RFLX.SPDM.Ext_Alg.Has_Buffer (Ctx)
       and then RFLX.SPDM.Ext_Alg.Structural_Valid_Message (Ctx)
       and then Pre (Read (Ctx));

   pragma Warnings (Off, "formal parameter ""*"" is not referenced");

   function Always_Valid (Context_Buffer_Length : RFLX_Types.Length; Offset : RFLX_Types.Length) return Boolean is
     (True);

   pragma Warnings (On, "formal parameter ""*"" is not referenced");

   generic
      with procedure Write (Buffer : out RFLX_Types.Bytes; Length : out RFLX_Types.Length; Context_Buffer_Length : RFLX_Types.Length; Offset : RFLX_Types.Length);
      with function Pre (Context_Buffer_Length : RFLX_Types.Length; Offset : RFLX_Types.Length) return Boolean is Always_Valid;
   procedure Generic_Write (Ctx : in out Context; Offset : RFLX_Types.Length := 0) with
     Pre =>
       not Ctx'Constrained
       and then RFLX.SPDM.Ext_Alg.Has_Buffer (Ctx)
       and then Offset < RFLX.SPDM.Ext_Alg.Buffer_Length (Ctx)
       and then Pre (RFLX.SPDM.Ext_Alg.Buffer_Length (Ctx), Offset),
     Post =>
       Has_Buffer (Ctx)
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = RFLX_Types.To_First_Bit_Index (Ctx.Buffer_First)
       and Initialized (Ctx);

   function Has_Buffer (Ctx : Context) return Boolean;

   function Buffer_Length (Ctx : Context) return RFLX_Types.Length with
     Pre =>
       RFLX.SPDM.Ext_Alg.Has_Buffer (Ctx);

   function Size (Ctx : Context) return RFLX_Types.Bit_Length with
     Post =>
       Size'Result rem RFLX_Types.Byte'Size = 0;

   function Byte_Size (Ctx : Context) return RFLX_Types.Length;

   function Message_Last (Ctx : Context) return RFLX_Types.Bit_Length with
     Pre =>
       RFLX.SPDM.Ext_Alg.Has_Buffer (Ctx)
       and then RFLX.SPDM.Ext_Alg.Structural_Valid_Message (Ctx);

   function Written_Last (Ctx : Context) return RFLX_Types.Bit_Length;

   procedure Data (Ctx : Context; Data : out RFLX_Types.Bytes) with
     Pre =>
       RFLX.SPDM.Ext_Alg.Has_Buffer (Ctx)
       and then RFLX.SPDM.Ext_Alg.Structural_Valid_Message (Ctx)
       and then Data'Length = RFLX.SPDM.Ext_Alg.Byte_Size (Ctx);

   pragma Warnings (Off, "postcondition does not mention function result");

   function Valid_Value (Fld : Field; Val : RFLX_Types.Base_Integer) return Boolean with
     Post =>
       True;

   pragma Warnings (On, "postcondition does not mention function result");

   pragma Warnings (Off, "postcondition does not mention function result");

   function Path_Condition (Ctx : Context; Fld : Field) return Boolean with
     Pre =>
       RFLX.SPDM.Ext_Alg.Valid_Predecessor (Ctx, Fld),
     Post =>
       True;

   pragma Warnings (On, "postcondition does not mention function result");

   pragma Warnings (Off, "postcondition does not mention function result");

   function Field_Condition (Ctx : Context; Fld : Field; Val : RFLX_Types.Base_Integer) return Boolean with
     Pre =>
       RFLX.SPDM.Ext_Alg.Has_Buffer (Ctx)
       and then RFLX.SPDM.Ext_Alg.Valid_Predecessor (Ctx, Fld)
       and then RFLX.SPDM.Ext_Alg.Valid_Value (Fld, Val)
       and then RFLX.SPDM.Ext_Alg.Valid_Next (Ctx, Fld)
       and then RFLX.SPDM.Ext_Alg.Sufficient_Space (Ctx, Fld),
     Post =>
       True;

   pragma Warnings (On, "postcondition does not mention function result");

   function Field_Size (Ctx : Context; Fld : Field) return RFLX_Types.Bit_Length with
     Pre =>
       RFLX.SPDM.Ext_Alg.Valid_Next (Ctx, Fld);

   pragma Warnings (Off, "postcondition does not mention function result");

   function Field_First (Ctx : Context; Fld : Field) return RFLX_Types.Bit_Index with
     Pre =>
       RFLX.SPDM.Ext_Alg.Valid_Next (Ctx, Fld),
     Post =>
       True;

   pragma Warnings (On, "postcondition does not mention function result");

   function Field_Last (Ctx : Context; Fld : Field) return RFLX_Types.Bit_Length with
     Pre =>
       RFLX.SPDM.Ext_Alg.Valid_Next (Ctx, Fld)
       and then RFLX.SPDM.Ext_Alg.Sufficient_Space (Ctx, Fld);

   pragma Warnings (Off, "postcondition does not mention function result");

   function Predecessor (Ctx : Context; Fld : Virtual_Field) return Virtual_Field with
     Post =>
       True;

   pragma Warnings (On, "postcondition does not mention function result");

   pragma Warnings (Off, "postcondition does not mention function result");

   function Valid_Predecessor (Ctx : Context; Fld : Virtual_Field) return Boolean with
     Post =>
       True;

   pragma Warnings (On, "postcondition does not mention function result");

   function Valid_Next (Ctx : Context; Fld : Field) return Boolean;

   function Available_Space (Ctx : Context; Fld : Field) return RFLX_Types.Bit_Length with
     Pre =>
       RFLX.SPDM.Ext_Alg.Valid_Next (Ctx, Fld);

   function Sufficient_Space (Ctx : Context; Fld : Field) return Boolean with
     Pre =>
       RFLX.SPDM.Ext_Alg.Valid_Next (Ctx, Fld);

   procedure Verify (Ctx : in out Context; Fld : Field) with
     Pre =>
       RFLX.SPDM.Ext_Alg.Has_Buffer (Ctx),
     Post =>
       Has_Buffer (Ctx)
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = Ctx.First'Old
       and Ctx.Last = Ctx.Last'Old;

   procedure Verify_Message (Ctx : in out Context) with
     Pre =>
       RFLX.SPDM.Ext_Alg.Has_Buffer (Ctx),
     Post =>
       Has_Buffer (Ctx)
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = Ctx.First'Old
       and Ctx.Last = Ctx.Last'Old;

   function Present (Ctx : Context; Fld : Field) return Boolean;

   function Structural_Valid (Ctx : Context; Fld : Field) return Boolean;

   function Valid (Ctx : Context; Fld : Field) return Boolean with
     Post =>
       (if Valid'Result then Structural_Valid (Ctx, Fld) and Present (Ctx, Fld));

   function Incomplete (Ctx : Context; Fld : Field) return Boolean;

   function Invalid (Ctx : Context; Fld : Field) return Boolean;

   function Structural_Valid_Message (Ctx : Context) return Boolean with
     Pre =>
       RFLX.SPDM.Ext_Alg.Has_Buffer (Ctx);

   function Valid_Message (Ctx : Context) return Boolean with
     Pre =>
       RFLX.SPDM.Ext_Alg.Has_Buffer (Ctx);

   pragma Warnings (Off, "postcondition does not mention function result");

   function Incomplete_Message (Ctx : Context) return Boolean with
     Post =>
       True;

   pragma Warnings (On, "postcondition does not mention function result");

   pragma Warnings (Off, "precondition is always False");

   function Get_Registry_ID (Ctx : Context) return RFLX.SPDM.Registry_ID with
     Pre =>
       RFLX.SPDM.Ext_Alg.Valid (Ctx, RFLX.SPDM.Ext_Alg.F_Registry_ID);

   function Get_Reserved (Ctx : Context) return RFLX.SPDM.Reserved_8 with
     Pre =>
       RFLX.SPDM.Ext_Alg.Valid (Ctx, RFLX.SPDM.Ext_Alg.F_Reserved);

   function Get_Algorithm_ID_16 (Ctx : Context) return RFLX.SPDM.Algorithm_ID_16 with
     Pre =>
       RFLX.SPDM.Ext_Alg.Valid (Ctx, RFLX.SPDM.Ext_Alg.F_Algorithm_ID_16);

   function Get_Algorithm_ID_32 (Ctx : Context) return RFLX.SPDM.Algorithm_ID_32 with
     Pre =>
       RFLX.SPDM.Ext_Alg.Valid (Ctx, RFLX.SPDM.Ext_Alg.F_Algorithm_ID_32);

   pragma Warnings (On, "precondition is always False");

   pragma Warnings (Off, "postcondition does not mention function result");

   function Valid_Length (Ctx : Context; Fld : Field; Length : RFLX_Types.Length) return Boolean with
     Pre =>
       RFLX.SPDM.Ext_Alg.Valid_Next (Ctx, Fld),
     Post =>
       True;

   pragma Warnings (On, "postcondition does not mention function result");

   pragma Warnings (Off, "aspect ""*"" not enforced on inlined subprogram ""*""");

   procedure Set_Registry_ID (Ctx : in out Context; Val : RFLX.SPDM.Registry_ID) with
     Inline_Always,
     Pre =>
       not Ctx'Constrained
       and then RFLX.SPDM.Ext_Alg.Has_Buffer (Ctx)
       and then RFLX.SPDM.Ext_Alg.Valid_Next (Ctx, RFLX.SPDM.Ext_Alg.F_Registry_ID)
       and then RFLX.SPDM.Valid_Registry_ID (RFLX.SPDM.To_Base_Integer (Val))
       and then RFLX.SPDM.Ext_Alg.Available_Space (Ctx, RFLX.SPDM.Ext_Alg.F_Registry_ID) >= RFLX.SPDM.Ext_Alg.Field_Size (Ctx, RFLX.SPDM.Ext_Alg.F_Registry_ID)
       and then RFLX.SPDM.Ext_Alg.Field_Condition (Ctx, RFLX.SPDM.Ext_Alg.F_Registry_ID, RFLX.SPDM.To_Base_Integer (Val)),
     Post =>
       Has_Buffer (Ctx)
       and Valid (Ctx, F_Registry_ID)
       and Get_Registry_ID (Ctx) = Val
       and Invalid (Ctx, F_Reserved)
       and Invalid (Ctx, F_Algorithm_ID_16)
       and Invalid (Ctx, F_Algorithm_ID_32)
       and (Predecessor (Ctx, F_Reserved) = F_Registry_ID
            and Valid_Next (Ctx, F_Reserved))
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = Ctx.First'Old
       and Ctx.Last = Ctx.Last'Old
       and Predecessor (Ctx, F_Registry_ID) = Predecessor (Ctx, F_Registry_ID)'Old
       and Valid_Next (Ctx, F_Registry_ID) = Valid_Next (Ctx, F_Registry_ID)'Old
       and Field_First (Ctx, F_Registry_ID) = Field_First (Ctx, F_Registry_ID)'Old;

   procedure Set_Reserved (Ctx : in out Context; Val : RFLX.SPDM.Reserved_8) with
     Inline_Always,
     Pre =>
       not Ctx'Constrained
       and then RFLX.SPDM.Ext_Alg.Has_Buffer (Ctx)
       and then RFLX.SPDM.Ext_Alg.Valid_Next (Ctx, RFLX.SPDM.Ext_Alg.F_Reserved)
       and then RFLX.SPDM.Valid_Reserved_8 (RFLX.SPDM.To_Base_Integer (Val))
       and then RFLX.SPDM.Ext_Alg.Available_Space (Ctx, RFLX.SPDM.Ext_Alg.F_Reserved) >= RFLX.SPDM.Ext_Alg.Field_Size (Ctx, RFLX.SPDM.Ext_Alg.F_Reserved)
       and then RFLX.SPDM.Ext_Alg.Field_Condition (Ctx, RFLX.SPDM.Ext_Alg.F_Reserved, RFLX.SPDM.To_Base_Integer (Val)),
     Post =>
       Has_Buffer (Ctx)
       and Valid (Ctx, F_Reserved)
       and (if Structural_Valid_Message (Ctx) then Message_Last (Ctx) = Field_Last (Ctx, F_Reserved))
       and Invalid (Ctx, F_Algorithm_ID_16)
       and Invalid (Ctx, F_Algorithm_ID_32)
       and (if
               RFLX_Types.Base_Integer (To_Base_Integer (Get_Registry_ID (Ctx))) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Reg_JEDEC))
               or RFLX_Types.Base_Integer (To_Base_Integer (Get_Registry_ID (Ctx))) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Reg_CXL))
               or RFLX_Types.Base_Integer (To_Base_Integer (Get_Registry_ID (Ctx))) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Reg_MIPI))
               or RFLX_Types.Base_Integer (To_Base_Integer (Get_Registry_ID (Ctx))) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Reg_PCI_SIG))
               or RFLX_Types.Base_Integer (To_Base_Integer (Get_Registry_ID (Ctx))) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Reg_TCG))
               or RFLX_Types.Base_Integer (To_Base_Integer (Get_Registry_ID (Ctx))) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Reg_USB))
            then
               Predecessor (Ctx, F_Algorithm_ID_16) = F_Reserved
               and Valid_Next (Ctx, F_Algorithm_ID_16))
       and (if
               RFLX_Types.Base_Integer (To_Base_Integer (Get_Registry_ID (Ctx))) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Reg_IANA))
               or RFLX_Types.Base_Integer (To_Base_Integer (Get_Registry_ID (Ctx))) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Reg_HD_Base_T))
            then
               Predecessor (Ctx, F_Algorithm_ID_32) = F_Reserved
               and Valid_Next (Ctx, F_Algorithm_ID_32))
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = Ctx.First'Old
       and Ctx.Last = Ctx.Last'Old
       and Predecessor (Ctx, F_Reserved) = Predecessor (Ctx, F_Reserved)'Old
       and Valid_Next (Ctx, F_Reserved) = Valid_Next (Ctx, F_Reserved)'Old
       and Get_Registry_ID (Ctx) = Get_Registry_ID (Ctx)'Old
       and Field_First (Ctx, F_Reserved) = Field_First (Ctx, F_Reserved)'Old
       and Field_Last (Ctx, F_Reserved) = Field_Last (Ctx, Predecessor (Ctx, F_Reserved)) + Field_Size (Ctx, F_Reserved)
       and (for all F in Field range F_Registry_ID .. F_Registry_ID =>
               Context_Cursors_Index (Context_Cursors (Ctx), F) = Context_Cursors_Index (Context_Cursors (Ctx)'Old, F));

   procedure Set_Algorithm_ID_16 (Ctx : in out Context; Val : RFLX.SPDM.Algorithm_ID_16) with
     Inline_Always,
     Pre =>
       not Ctx'Constrained
       and then RFLX.SPDM.Ext_Alg.Has_Buffer (Ctx)
       and then RFLX.SPDM.Ext_Alg.Valid_Next (Ctx, RFLX.SPDM.Ext_Alg.F_Algorithm_ID_16)
       and then RFLX.SPDM.Valid_Algorithm_ID_16 (RFLX.SPDM.To_Base_Integer (Val))
       and then RFLX.SPDM.Ext_Alg.Available_Space (Ctx, RFLX.SPDM.Ext_Alg.F_Algorithm_ID_16) >= RFLX.SPDM.Ext_Alg.Field_Size (Ctx, RFLX.SPDM.Ext_Alg.F_Algorithm_ID_16)
       and then RFLX.SPDM.Ext_Alg.Field_Condition (Ctx, RFLX.SPDM.Ext_Alg.F_Algorithm_ID_16, RFLX.SPDM.To_Base_Integer (Val)),
     Post =>
       Has_Buffer (Ctx)
       and Valid (Ctx, F_Algorithm_ID_16)
       and Get_Algorithm_ID_16 (Ctx) = Val
       and (if Structural_Valid_Message (Ctx) then Message_Last (Ctx) = Field_Last (Ctx, F_Algorithm_ID_16))
       and Invalid (Ctx, F_Algorithm_ID_32)
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = Ctx.First'Old
       and Ctx.Last = Ctx.Last'Old
       and Predecessor (Ctx, F_Algorithm_ID_16) = Predecessor (Ctx, F_Algorithm_ID_16)'Old
       and Valid_Next (Ctx, F_Algorithm_ID_16) = Valid_Next (Ctx, F_Algorithm_ID_16)'Old
       and Get_Registry_ID (Ctx) = Get_Registry_ID (Ctx)'Old
       and Field_First (Ctx, F_Algorithm_ID_16) = Field_First (Ctx, F_Algorithm_ID_16)'Old
       and Field_Last (Ctx, F_Algorithm_ID_16) = Field_Last (Ctx, Predecessor (Ctx, F_Algorithm_ID_16)) + Field_Size (Ctx, F_Algorithm_ID_16)
       and (for all F in Field range F_Registry_ID .. F_Reserved =>
               Context_Cursors_Index (Context_Cursors (Ctx), F) = Context_Cursors_Index (Context_Cursors (Ctx)'Old, F));

   procedure Set_Algorithm_ID_32 (Ctx : in out Context; Val : RFLX.SPDM.Algorithm_ID_32) with
     Inline_Always,
     Pre =>
       not Ctx'Constrained
       and then RFLX.SPDM.Ext_Alg.Has_Buffer (Ctx)
       and then RFLX.SPDM.Ext_Alg.Valid_Next (Ctx, RFLX.SPDM.Ext_Alg.F_Algorithm_ID_32)
       and then RFLX.SPDM.Valid_Algorithm_ID_32 (RFLX.SPDM.To_Base_Integer (Val))
       and then RFLX.SPDM.Ext_Alg.Available_Space (Ctx, RFLX.SPDM.Ext_Alg.F_Algorithm_ID_32) >= RFLX.SPDM.Ext_Alg.Field_Size (Ctx, RFLX.SPDM.Ext_Alg.F_Algorithm_ID_32)
       and then RFLX.SPDM.Ext_Alg.Field_Condition (Ctx, RFLX.SPDM.Ext_Alg.F_Algorithm_ID_32, RFLX.SPDM.To_Base_Integer (Val)),
     Post =>
       Has_Buffer (Ctx)
       and Valid (Ctx, F_Algorithm_ID_32)
       and Get_Algorithm_ID_32 (Ctx) = Val
       and (if Structural_Valid_Message (Ctx) then Message_Last (Ctx) = Field_Last (Ctx, F_Algorithm_ID_32))
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = Ctx.First'Old
       and Ctx.Last = Ctx.Last'Old
       and Predecessor (Ctx, F_Algorithm_ID_32) = Predecessor (Ctx, F_Algorithm_ID_32)'Old
       and Valid_Next (Ctx, F_Algorithm_ID_32) = Valid_Next (Ctx, F_Algorithm_ID_32)'Old
       and Get_Registry_ID (Ctx) = Get_Registry_ID (Ctx)'Old
       and Field_First (Ctx, F_Algorithm_ID_32) = Field_First (Ctx, F_Algorithm_ID_32)'Old
       and Field_Last (Ctx, F_Algorithm_ID_32) = Field_Last (Ctx, Predecessor (Ctx, F_Algorithm_ID_32)) + Field_Size (Ctx, F_Algorithm_ID_32)
       and (for all F in Field range F_Registry_ID .. F_Algorithm_ID_16 =>
               Context_Cursors_Index (Context_Cursors (Ctx), F) = Context_Cursors_Index (Context_Cursors (Ctx)'Old, F));

   pragma Warnings (On, "aspect ""*"" not enforced on inlined subprogram ""*""");

   function Context_Cursor (Ctx : Context; Fld : Field) return Field_Cursor with
     Annotate =>
       (GNATprove, Inline_For_Proof),
     Ghost;

   function Context_Cursors (Ctx : Context) return Field_Cursors with
     Annotate =>
       (GNATprove, Inline_For_Proof),
     Ghost;

   function Context_Cursors_Index (Cursors : Field_Cursors; Fld : Field) return Field_Cursor with
     Annotate =>
       (GNATprove, Inline_For_Proof),
     Ghost;

private

   type Cursor_State is (S_Valid, S_Structural_Valid, S_Invalid, S_Incomplete);

   type Field_Cursor (State : Cursor_State := S_Invalid) is
      record
         Predecessor : Virtual_Field := F_Final;
         case State is
            when S_Valid | S_Structural_Valid =>
               First : RFLX_Types.Bit_Index := RFLX_Types.Bit_Index'First;
               Last : RFLX_Types.Bit_Length := RFLX_Types.Bit_Length'First;
               Value : RFLX_Types.Base_Integer := 0;
            when S_Invalid | S_Incomplete =>
               null;
         end case;
      end record;

   type Field_Cursors is array (Virtual_Field) of Field_Cursor;

   function Structural_Valid (Cursor : Field_Cursor) return Boolean is
     (Cursor.State = S_Valid
      or Cursor.State = S_Structural_Valid);

   function Valid (Cursor : Field_Cursor) return Boolean is
     (Cursor.State = S_Valid);

   function Invalid (Cursor : Field_Cursor) return Boolean is
     (Cursor.State = S_Invalid
      or Cursor.State = S_Incomplete);

   pragma Warnings (Off, """Buffer"" is not modified, could be of access constant type");

   pragma Warnings (Off, "postcondition does not mention function result");

   function Valid_Context (Buffer_First, Buffer_Last : RFLX_Types.Index; First : RFLX_Types.Bit_Index; Last : RFLX_Types.Bit_Length; Verified_Last : RFLX_Types.Bit_Length; Written_Last : RFLX_Types.Bit_Length; Buffer : RFLX_Types.Bytes_Ptr; Cursors : Field_Cursors) return Boolean is
     ((if Buffer /= null then Buffer'First = Buffer_First and Buffer'Last = Buffer_Last)
      and then (RFLX_Types.To_Index (First) >= Buffer_First
                and RFLX_Types.To_Index (Last) <= Buffer_Last
                and Buffer_Last < RFLX_Types.Index'Last
                and First <= Last + 1
                and Last < RFLX_Types.Bit_Index'Last
                and First rem RFLX_Types.Byte'Size = 1
                and Last rem RFLX_Types.Byte'Size = 0)
      and then First - 1 <= Verified_Last
      and then First - 1 <= Written_Last
      and then Verified_Last <= Written_Last
      and then Written_Last <= Last
      and then First rem RFLX_Types.Byte'Size = 1
      and then Last rem RFLX_Types.Byte'Size = 0
      and then Verified_Last rem RFLX_Types.Byte'Size = 0
      and then Written_Last rem RFLX_Types.Byte'Size = 0
      and then (for all F in Field =>
                   (if
                       Structural_Valid (Cursors (F))
                    then
                       Cursors (F).First >= First
                       and Cursors (F).Last <= Verified_Last
                       and Cursors (F).First <= Cursors (F).Last + 1
                       and Valid_Value (F, Cursors (F).Value)))
      and then ((if
                    Structural_Valid (Cursors (F_Reserved))
                 then
                    (Valid (Cursors (F_Registry_ID))
                     and then Cursors (F_Reserved).Predecessor = F_Registry_ID))
                and then (if
                             Structural_Valid (Cursors (F_Algorithm_ID_16))
                          then
                             (Valid (Cursors (F_Reserved))
                              and then Cursors (F_Algorithm_ID_16).Predecessor = F_Reserved
                              and then (RFLX_Types.Base_Integer (Cursors (F_Registry_ID).Value) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Reg_JEDEC))
                                        or RFLX_Types.Base_Integer (Cursors (F_Registry_ID).Value) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Reg_CXL))
                                        or RFLX_Types.Base_Integer (Cursors (F_Registry_ID).Value) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Reg_MIPI))
                                        or RFLX_Types.Base_Integer (Cursors (F_Registry_ID).Value) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Reg_PCI_SIG))
                                        or RFLX_Types.Base_Integer (Cursors (F_Registry_ID).Value) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Reg_TCG))
                                        or RFLX_Types.Base_Integer (Cursors (F_Registry_ID).Value) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Reg_USB)))))
                and then (if
                             Structural_Valid (Cursors (F_Algorithm_ID_32))
                          then
                             (Valid (Cursors (F_Reserved))
                              and then Cursors (F_Algorithm_ID_32).Predecessor = F_Reserved
                              and then (RFLX_Types.Base_Integer (Cursors (F_Registry_ID).Value) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Reg_IANA))
                                        or RFLX_Types.Base_Integer (Cursors (F_Registry_ID).Value) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Reg_HD_Base_T))))))
      and then ((if Invalid (Cursors (F_Registry_ID)) then Invalid (Cursors (F_Reserved)))
                and then (if Invalid (Cursors (F_Reserved)) then Invalid (Cursors (F_Algorithm_ID_16)))
                and then (if Invalid (Cursors (F_Reserved)) then Invalid (Cursors (F_Algorithm_ID_32))))
      and then (if
                   Structural_Valid (Cursors (F_Registry_ID))
                then
                   Cursors (F_Registry_ID).Last - Cursors (F_Registry_ID).First + 1 = 8
                   and then Cursors (F_Registry_ID).Predecessor = F_Initial
                   and then Cursors (F_Registry_ID).First = First
                   and then (if
                                Structural_Valid (Cursors (F_Reserved))
                             then
                                Cursors (F_Reserved).Last - Cursors (F_Reserved).First + 1 = 8
                                and then Cursors (F_Reserved).Predecessor = F_Registry_ID
                                and then Cursors (F_Reserved).First = Cursors (F_Registry_ID).Last + 1
                                and then (if
                                             Structural_Valid (Cursors (F_Algorithm_ID_16))
                                             and then (RFLX_Types.Base_Integer (Cursors (F_Registry_ID).Value) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Reg_JEDEC))
                                                       or RFLX_Types.Base_Integer (Cursors (F_Registry_ID).Value) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Reg_CXL))
                                                       or RFLX_Types.Base_Integer (Cursors (F_Registry_ID).Value) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Reg_MIPI))
                                                       or RFLX_Types.Base_Integer (Cursors (F_Registry_ID).Value) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Reg_PCI_SIG))
                                                       or RFLX_Types.Base_Integer (Cursors (F_Registry_ID).Value) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Reg_TCG))
                                                       or RFLX_Types.Base_Integer (Cursors (F_Registry_ID).Value) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Reg_USB)))
                                          then
                                             Cursors (F_Algorithm_ID_16).Last - Cursors (F_Algorithm_ID_16).First + 1 = 16
                                             and then Cursors (F_Algorithm_ID_16).Predecessor = F_Reserved
                                             and then Cursors (F_Algorithm_ID_16).First = Cursors (F_Reserved).Last + 1)
                                and then (if
                                             Structural_Valid (Cursors (F_Algorithm_ID_32))
                                             and then (RFLX_Types.Base_Integer (Cursors (F_Registry_ID).Value) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Reg_IANA))
                                                       or RFLX_Types.Base_Integer (Cursors (F_Registry_ID).Value) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Reg_HD_Base_T)))
                                          then
                                             Cursors (F_Algorithm_ID_32).Last - Cursors (F_Algorithm_ID_32).First + 1 = 32
                                             and then Cursors (F_Algorithm_ID_32).Predecessor = F_Reserved
                                             and then Cursors (F_Algorithm_ID_32).First = Cursors (F_Reserved).Last + 1))));

   pragma Warnings (On, """Buffer"" is not modified, could be of access constant type");

   pragma Warnings (On, "postcondition does not mention function result");

   type Context (Buffer_First, Buffer_Last : RFLX_Types.Index := RFLX_Types.Index'First; First : RFLX_Types.Bit_Index := RFLX_Types.Bit_Index'First; Last : RFLX_Types.Bit_Length := RFLX_Types.Bit_Length'First) is
      record
         Verified_Last : RFLX_Types.Bit_Length := First - 1;
         Written_Last : RFLX_Types.Bit_Length := First - 1;
         Buffer : RFLX_Types.Bytes_Ptr := null;
         Cursors : Field_Cursors := [others => (State => S_Invalid, Predecessor => F_Final)];
      end record with
     Dynamic_Predicate =>
       Valid_Context (Context.Buffer_First, Context.Buffer_Last, Context.First, Context.Last, Context.Verified_Last, Context.Written_Last, Context.Buffer, Context.Cursors);

   function Initialized (Ctx : Context) return Boolean is
     (Ctx.Verified_Last = Ctx.First - 1
      and then Valid_Next (Ctx, F_Registry_ID)
      and then RFLX.SPDM.Ext_Alg.Field_First (Ctx, RFLX.SPDM.Ext_Alg.F_Registry_ID) rem RFLX_Types.Byte'Size = 1
      and then Available_Space (Ctx, F_Registry_ID) = Ctx.Last - Ctx.First + 1
      and then (for all F in Field =>
                   Invalid (Ctx, F)));

   function Has_Buffer (Ctx : Context) return Boolean is
     (Ctx.Buffer /= null);

   function Buffer_Length (Ctx : Context) return RFLX_Types.Length is
     (Ctx.Buffer'Length);

   function Size (Ctx : Context) return RFLX_Types.Bit_Length is
     (Ctx.Verified_Last - Ctx.First + 1);

   function Byte_Size (Ctx : Context) return RFLX_Types.Length is
     (RFLX_Types.To_Length (Size (Ctx)));

   function Message_Last (Ctx : Context) return RFLX_Types.Bit_Length is
     (Ctx.Verified_Last);

   function Written_Last (Ctx : Context) return RFLX_Types.Bit_Length is
     (Ctx.Written_Last);

   function Valid_Value (Fld : Field; Val : RFLX_Types.Base_Integer) return Boolean is
     ((case Fld is
          when F_Registry_ID =>
             RFLX.SPDM.Valid_Registry_ID (Val),
          when F_Reserved =>
             RFLX.SPDM.Valid_Reserved_8 (Val),
          when F_Algorithm_ID_16 =>
             RFLX.SPDM.Valid_Algorithm_ID_16 (Val),
          when F_Algorithm_ID_32 =>
             RFLX.SPDM.Valid_Algorithm_ID_32 (Val)));

   function Path_Condition (Ctx : Context; Fld : Field) return Boolean is
     ((case Ctx.Cursors (Fld).Predecessor is
          when F_Initial | F_Registry_ID | F_Algorithm_ID_16 | F_Algorithm_ID_32 | F_Final =>
             True,
          when F_Reserved =>
             (case Fld is
                 when F_Algorithm_ID_16 =>
                    RFLX_Types.Base_Integer (Ctx.Cursors (F_Registry_ID).Value) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Reg_JEDEC))
                    or RFLX_Types.Base_Integer (Ctx.Cursors (F_Registry_ID).Value) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Reg_CXL))
                    or RFLX_Types.Base_Integer (Ctx.Cursors (F_Registry_ID).Value) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Reg_MIPI))
                    or RFLX_Types.Base_Integer (Ctx.Cursors (F_Registry_ID).Value) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Reg_PCI_SIG))
                    or RFLX_Types.Base_Integer (Ctx.Cursors (F_Registry_ID).Value) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Reg_TCG))
                    or RFLX_Types.Base_Integer (Ctx.Cursors (F_Registry_ID).Value) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Reg_USB)),
                 when F_Algorithm_ID_32 =>
                    RFLX_Types.Base_Integer (Ctx.Cursors (F_Registry_ID).Value) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Reg_IANA))
                    or RFLX_Types.Base_Integer (Ctx.Cursors (F_Registry_ID).Value) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Reg_HD_Base_T)),
                 when others =>
                    False)));

   function Field_Condition (Ctx : Context; Fld : Field; Val : RFLX_Types.Base_Integer) return Boolean is
     ((case Fld is
          when F_Registry_ID =>
             True,
          when F_Reserved =>
             RFLX_Types.Base_Integer (Ctx.Cursors (F_Registry_ID).Value) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Reg_DMTF))
             or RFLX_Types.Base_Integer (Ctx.Cursors (F_Registry_ID).Value) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Reg_JEDEC))
             or RFLX_Types.Base_Integer (Ctx.Cursors (F_Registry_ID).Value) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Reg_CXL))
             or RFLX_Types.Base_Integer (Ctx.Cursors (F_Registry_ID).Value) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Reg_MIPI))
             or RFLX_Types.Base_Integer (Ctx.Cursors (F_Registry_ID).Value) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Reg_PCI_SIG))
             or RFLX_Types.Base_Integer (Ctx.Cursors (F_Registry_ID).Value) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Reg_TCG))
             or RFLX_Types.Base_Integer (Ctx.Cursors (F_Registry_ID).Value) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Reg_USB))
             or RFLX_Types.Base_Integer (Ctx.Cursors (F_Registry_ID).Value) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Reg_IANA))
             or RFLX_Types.Base_Integer (Ctx.Cursors (F_Registry_ID).Value) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Reg_HD_Base_T)),
          when F_Algorithm_ID_16 | F_Algorithm_ID_32 =>
             True));

   function Field_Size (Ctx : Context; Fld : Field) return RFLX_Types.Bit_Length is
     ((case Fld is
          when F_Registry_ID | F_Reserved =>
             8,
          when F_Algorithm_ID_16 =>
             16,
          when F_Algorithm_ID_32 =>
             32));

   function Field_First (Ctx : Context; Fld : Field) return RFLX_Types.Bit_Index is
     ((if Fld = F_Registry_ID then Ctx.First else Ctx.Cursors (Ctx.Cursors (Fld).Predecessor).Last + 1));

   function Field_Last (Ctx : Context; Fld : Field) return RFLX_Types.Bit_Length is
     (Field_First (Ctx, Fld) + Field_Size (Ctx, Fld) - 1);

   function Predecessor (Ctx : Context; Fld : Virtual_Field) return Virtual_Field is
     ((case Fld is
          when F_Initial =>
             F_Initial,
          when others =>
             Ctx.Cursors (Fld).Predecessor));

   function Valid_Predecessor (Ctx : Context; Fld : Virtual_Field) return Boolean is
     ((case Fld is
          when F_Initial =>
             True,
          when F_Registry_ID =>
             Ctx.Cursors (Fld).Predecessor = F_Initial,
          when F_Reserved =>
             (Valid (Ctx.Cursors (F_Registry_ID))
              and Ctx.Cursors (Fld).Predecessor = F_Registry_ID),
          when F_Algorithm_ID_16 | F_Algorithm_ID_32 =>
             (Valid (Ctx.Cursors (F_Reserved))
              and Ctx.Cursors (Fld).Predecessor = F_Reserved),
          when F_Final =>
             (Valid (Ctx.Cursors (F_Algorithm_ID_16))
              and Ctx.Cursors (Fld).Predecessor = F_Algorithm_ID_16)
             or (Valid (Ctx.Cursors (F_Algorithm_ID_32))
                 and Ctx.Cursors (Fld).Predecessor = F_Algorithm_ID_32)
             or (Valid (Ctx.Cursors (F_Reserved))
                 and Ctx.Cursors (Fld).Predecessor = F_Reserved)));

   function Valid_Next (Ctx : Context; Fld : Field) return Boolean is
     (Valid_Predecessor (Ctx, Fld)
      and then Path_Condition (Ctx, Fld));

   function Available_Space (Ctx : Context; Fld : Field) return RFLX_Types.Bit_Length is
     (Ctx.Last - Field_First (Ctx, Fld) + 1);

   function Sufficient_Space (Ctx : Context; Fld : Field) return Boolean is
     (Available_Space (Ctx, Fld) >= Field_Size (Ctx, Fld));

   function Present (Ctx : Context; Fld : Field) return Boolean is
     (Structural_Valid (Ctx.Cursors (Fld))
      and then Ctx.Cursors (Fld).First < Ctx.Cursors (Fld).Last + 1);

   function Structural_Valid (Ctx : Context; Fld : Field) return Boolean is
     (Ctx.Cursors (Fld).State = S_Valid
      or Ctx.Cursors (Fld).State = S_Structural_Valid);

   function Valid (Ctx : Context; Fld : Field) return Boolean is
     (Ctx.Cursors (Fld).State = S_Valid
      and then Ctx.Cursors (Fld).First < Ctx.Cursors (Fld).Last + 1);

   function Incomplete (Ctx : Context; Fld : Field) return Boolean is
     (Ctx.Cursors (Fld).State = S_Incomplete);

   function Invalid (Ctx : Context; Fld : Field) return Boolean is
     (Ctx.Cursors (Fld).State = S_Invalid
      or Ctx.Cursors (Fld).State = S_Incomplete);

   function Structural_Valid_Message (Ctx : Context) return Boolean is
     (Valid (Ctx, F_Algorithm_ID_16)
      or Valid (Ctx, F_Algorithm_ID_32)
      or (Valid (Ctx, F_Reserved)
          and then RFLX_Types.Base_Integer (Ctx.Cursors (F_Registry_ID).Value) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Reg_DMTF))));

   function Valid_Message (Ctx : Context) return Boolean is
     (Valid (Ctx, F_Algorithm_ID_16)
      or Valid (Ctx, F_Algorithm_ID_32)
      or (Valid (Ctx, F_Reserved)
          and then RFLX_Types.Base_Integer (Ctx.Cursors (F_Registry_ID).Value) = RFLX_Types.Base_Integer (To_Base_Integer (RFLX.SPDM.Reg_DMTF))));

   function Incomplete_Message (Ctx : Context) return Boolean is
     ((for some F in Field =>
          Incomplete (Ctx, F)));

   function Get_Registry_ID (Ctx : Context) return RFLX.SPDM.Registry_ID is
     (To_Actual (Ctx.Cursors (F_Registry_ID).Value));

   function Get_Reserved (Ctx : Context) return RFLX.SPDM.Reserved_8 is
     (To_Actual (Ctx.Cursors (F_Reserved).Value));

   function Get_Algorithm_ID_16 (Ctx : Context) return RFLX.SPDM.Algorithm_ID_16 is
     (To_Actual (Ctx.Cursors (F_Algorithm_ID_16).Value));

   function Get_Algorithm_ID_32 (Ctx : Context) return RFLX.SPDM.Algorithm_ID_32 is
     (To_Actual (Ctx.Cursors (F_Algorithm_ID_32).Value));

   function Valid_Size (Ctx : Context; Fld : Field; Size : RFLX_Types.Bit_Length) return Boolean is
     (Size = Field_Size (Ctx, Fld))
    with
     Pre =>
       RFLX.SPDM.Ext_Alg.Valid_Next (Ctx, Fld);

   function Valid_Length (Ctx : Context; Fld : Field; Length : RFLX_Types.Length) return Boolean is
     (Valid_Size (Ctx, Fld, RFLX_Types.To_Bit_Length (Length)));

   function Context_Cursor (Ctx : Context; Fld : Field) return Field_Cursor is
     (Ctx.Cursors (Fld));

   function Context_Cursors (Ctx : Context) return Field_Cursors is
     (Ctx.Cursors);

   function Context_Cursors_Index (Cursors : Field_Cursors; Fld : Field) return Field_Cursor is
     (Cursors (Fld));

end RFLX.SPDM.Ext_Alg;
