--
--  Generated by RecordFlux 0.6.1.dev1+g8b82b38a0 on 2022-12-02
--
--  Copyright (C) 2018-2022 AdaCore
--
--  SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
--

pragma Style_Checks ("N3aAbcdefhiIklnOprStux");
pragma Warnings (Off, "redundant conversion");

package body RFLX.SPDM.Algorithms_Response with
  SPARK_Mode
is

   pragma Unevaluated_Use_Of_Old (Allow);

   procedure Initialize (Ctx : out Context; Buffer : in out RFLX_Types.Bytes_Ptr; Written_Last : RFLX_Types.Bit_Length := 0) is
   begin
      Initialize (Ctx, Buffer, RFLX_Types.To_First_Bit_Index (Buffer'First), RFLX_Types.To_Last_Bit_Index (Buffer'Last), Written_Last);
   end Initialize;

   procedure Initialize (Ctx : out Context; Buffer : in out RFLX_Types.Bytes_Ptr; First : RFLX_Types.Bit_Index; Last : RFLX_Types.Bit_Length; Written_Last : RFLX_Types.Bit_Length := 0) is
      Buffer_First : constant RFLX_Types.Index := Buffer'First;
      Buffer_Last : constant RFLX_Types.Index := Buffer'Last;
   begin
      Ctx := (Buffer_First, Buffer_Last, First, Last, First - 1, (if Written_Last = 0 then First - 1 else Written_Last), Buffer, [F_Resp_Alg_Struct_Count => (State => S_Invalid, Predecessor => F_Initial), others => (State => S_Invalid, Predecessor => F_Final)]);
      Buffer := null;
   end Initialize;

   procedure Reset (Ctx : in out Context) is
   begin
      Reset (Ctx, RFLX_Types.To_First_Bit_Index (Ctx.Buffer'First), RFLX_Types.To_Last_Bit_Index (Ctx.Buffer'Last));
   end Reset;

   procedure Reset (Ctx : in out Context; First : RFLX_Types.Bit_Index; Last : RFLX_Types.Bit_Length) is
   begin
      Ctx := (Ctx.Buffer_First, Ctx.Buffer_Last, First, Last, First - 1, First - 1, Ctx.Buffer, [F_Resp_Alg_Struct_Count => (State => S_Invalid, Predecessor => F_Initial), others => (State => S_Invalid, Predecessor => F_Final)]);
   end Reset;

   procedure Take_Buffer (Ctx : in out Context; Buffer : out RFLX_Types.Bytes_Ptr) is
   begin
      Buffer := Ctx.Buffer;
      Ctx.Buffer := null;
   end Take_Buffer;

   procedure Copy (Ctx : Context; Buffer : out RFLX_Types.Bytes) is
   begin
      if Buffer'Length > 0 then
         Buffer := Ctx.Buffer.all (RFLX_Types.To_Index (Ctx.First) .. RFLX_Types.To_Index (Ctx.Verified_Last));
      else
         Buffer := Ctx.Buffer.all (1 .. 0);
      end if;
   end Copy;

   function Read (Ctx : Context) return RFLX_Types.Bytes is
     (Ctx.Buffer.all (RFLX_Types.To_Index (Ctx.First) .. RFLX_Types.To_Index (Ctx.Verified_Last)));

   procedure Generic_Read (Ctx : Context) is
   begin
      Read (Ctx.Buffer.all (RFLX_Types.To_Index (Ctx.First) .. RFLX_Types.To_Index (Ctx.Verified_Last)));
   end Generic_Read;

   procedure Generic_Write (Ctx : in out Context; Offset : RFLX_Types.Length := 0) is
      Length : RFLX_Types.Length;
   begin
      Reset (Ctx, RFLX_Types.To_First_Bit_Index (Ctx.Buffer_First), RFLX_Types.To_Last_Bit_Index (Ctx.Buffer_Last));
      Write (Ctx.Buffer.all (Ctx.Buffer'First + RFLX_Types.Index (Offset + 1) - 1 .. Ctx.Buffer'Last), Length, Ctx.Buffer'Length, Offset);
      pragma Assert (Length <= Ctx.Buffer.all'Length, "Length <= Buffer'Length is not ensured by postcondition of ""Write""");
      Ctx.Written_Last := RFLX_Types.Bit_Index'Max (Ctx.Written_Last, RFLX_Types.To_Last_Bit_Index (RFLX_Types.Length (Ctx.Buffer_First) + Offset + Length - 1));
   end Generic_Write;

   procedure Data (Ctx : Context; Data : out RFLX_Types.Bytes) is
   begin
      Data := Ctx.Buffer.all (RFLX_Types.To_Index (Ctx.First) .. RFLX_Types.To_Index (Ctx.Verified_Last));
   end Data;

   pragma Warnings (Off, "precondition is always False");

   function Successor (Ctx : Context; Fld : Field) return Virtual_Field is
     ((case Fld is
          when F_Resp_Alg_Struct_Count =>
             F_Param_2,
          when F_Param_2 =>
             F_Length,
          when F_Length =>
             F_Measurement_Specification_Sel,
          when F_Measurement_Specification_Sel =>
             F_Reserved_1,
          when F_Reserved_1 =>
             F_Measurement_Hash_Algo,
          when F_Measurement_Hash_Algo =>
             F_Base_Asym_Sel,
          when F_Base_Asym_Sel =>
             F_Base_Hash_Sel,
          when F_Base_Hash_Sel =>
             F_Reserved_2,
          when F_Reserved_2 =>
             F_Reserved_3,
          when F_Reserved_3 =>
             F_Reserved_4,
          when F_Reserved_4 =>
             F_Ext_Asym_Sel_Count,
          when F_Ext_Asym_Sel_Count =>
             (if Ctx.Cursors (F_Ext_Asym_Sel_Count).Value <= 1 then F_Ext_Hash_Sel_Count else F_Initial),
          when F_Ext_Hash_Sel_Count =>
             (if Ctx.Cursors (F_Ext_Hash_Sel_Count).Value <= 1 then F_Reserved_5 else F_Initial),
          when F_Reserved_5 =>
             F_Ext_Asym,
          when F_Ext_Asym =>
             F_Ext_Hash,
          when F_Ext_Hash =>
             (if
                 RFLX_Types.Base_Integer (Ctx.Cursors (F_Length).Value) * 8 >= RFLX_Types.Base_Integer (Ctx.Cursors (F_Ext_Hash).Last) - RFLX_Types.Base_Integer (Ctx.Cursors (F_Resp_Alg_Struct_Count).First) + 17
              then
                 F_Resp_Alg_Structs
              else
                 F_Initial),
          when F_Resp_Alg_Structs =>
             F_Final))
    with
     Pre =>
       RFLX.SPDM.Algorithms_Response.Has_Buffer (Ctx)
       and RFLX.SPDM.Algorithms_Response.Structural_Valid (Ctx, Fld)
       and RFLX.SPDM.Algorithms_Response.Valid_Predecessor (Ctx, Fld);

   pragma Warnings (On, "precondition is always False");

   function Invalid_Successor (Ctx : Context; Fld : Field) return Boolean is
     ((case Fld is
          when F_Resp_Alg_Struct_Count =>
             Invalid (Ctx.Cursors (F_Param_2)),
          when F_Param_2 =>
             Invalid (Ctx.Cursors (F_Length)),
          when F_Length =>
             Invalid (Ctx.Cursors (F_Measurement_Specification_Sel)),
          when F_Measurement_Specification_Sel =>
             Invalid (Ctx.Cursors (F_Reserved_1)),
          when F_Reserved_1 =>
             Invalid (Ctx.Cursors (F_Measurement_Hash_Algo)),
          when F_Measurement_Hash_Algo =>
             Invalid (Ctx.Cursors (F_Base_Asym_Sel)),
          when F_Base_Asym_Sel =>
             Invalid (Ctx.Cursors (F_Base_Hash_Sel)),
          when F_Base_Hash_Sel =>
             Invalid (Ctx.Cursors (F_Reserved_2)),
          when F_Reserved_2 =>
             Invalid (Ctx.Cursors (F_Reserved_3)),
          when F_Reserved_3 =>
             Invalid (Ctx.Cursors (F_Reserved_4)),
          when F_Reserved_4 =>
             Invalid (Ctx.Cursors (F_Ext_Asym_Sel_Count)),
          when F_Ext_Asym_Sel_Count =>
             Invalid (Ctx.Cursors (F_Ext_Hash_Sel_Count)),
          when F_Ext_Hash_Sel_Count =>
             Invalid (Ctx.Cursors (F_Reserved_5)),
          when F_Reserved_5 =>
             Invalid (Ctx.Cursors (F_Ext_Asym)),
          when F_Ext_Asym =>
             Invalid (Ctx.Cursors (F_Ext_Hash)),
          when F_Ext_Hash =>
             Invalid (Ctx.Cursors (F_Resp_Alg_Structs)),
          when F_Resp_Alg_Structs =>
             True));

   function Sufficient_Buffer_Length (Ctx : Context; Fld : Field) return Boolean is
     (Ctx.Buffer /= null
      and Field_First (Ctx, Fld) + Field_Size (Ctx, Fld) < RFLX_Types.Bit_Length'Last
      and Ctx.First <= Field_First (Ctx, Fld)
      and Field_First (Ctx, Fld) + Field_Size (Ctx, Fld) - 1 <= Ctx.Written_Last)
    with
     Pre =>
       RFLX.SPDM.Algorithms_Response.Has_Buffer (Ctx)
       and RFLX.SPDM.Algorithms_Response.Valid_Next (Ctx, Fld);

   function Equal (Ctx : Context; Fld : Field; Data : RFLX_Types.Bytes) return Boolean is
     (Sufficient_Buffer_Length (Ctx, Fld)
      and then (case Fld is
                   when F_Ext_Asym | F_Ext_Hash | F_Resp_Alg_Structs =>
                      Data'Length = RFLX_Types.To_Index (Field_Last (Ctx, Fld)) - RFLX_Types.To_Index (Field_First (Ctx, Fld)) + 1
                      and then (for all I in RFLX_Types.Index range RFLX_Types.To_Index (Field_First (Ctx, Fld)) .. RFLX_Types.To_Index (Field_Last (Ctx, Fld)) =>
                                   Ctx.Buffer.all (I) = Data (Data'First + (I - RFLX_Types.To_Index (Field_First (Ctx, Fld))))),
                   when others =>
                      False));

   procedure Reset_Dependent_Fields (Ctx : in out Context; Fld : Field) with
     Pre =>
       RFLX.SPDM.Algorithms_Response.Valid_Next (Ctx, Fld),
     Post =>
       Valid_Next (Ctx, Fld)
       and Invalid (Ctx.Cursors (Fld))
       and Invalid_Successor (Ctx, Fld)
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = Ctx.First'Old
       and Ctx.Last = Ctx.Last'Old
       and Ctx.Cursors (Fld).Predecessor = Ctx.Cursors (Fld).Predecessor'Old
       and Has_Buffer (Ctx) = Has_Buffer (Ctx)'Old
       and Field_First (Ctx, Fld) = Field_First (Ctx, Fld)'Old
       and Field_Size (Ctx, Fld) = Field_Size (Ctx, Fld)'Old
       and (for all F in Field =>
               (if F < Fld then Ctx.Cursors (F) = Ctx.Cursors'Old (F) else Invalid (Ctx, F)))
   is
      First : constant RFLX_Types.Bit_Length := Field_First (Ctx, Fld) with
        Ghost;
      Size : constant RFLX_Types.Bit_Length := Field_Size (Ctx, Fld) with
        Ghost;
   begin
      pragma Assert (Field_First (Ctx, Fld) = First
                     and Field_Size (Ctx, Fld) = Size);
      for Fld_Loop in reverse Field'Succ (Fld) .. Field'Last loop
         Ctx.Cursors (Fld_Loop) := (S_Invalid, F_Final);
         pragma Loop_Invariant (Field_First (Ctx, Fld) = First
                                and Field_Size (Ctx, Fld) = Size);
         pragma Loop_Invariant ((for all F in Field =>
                                    (if F < Fld_Loop then Ctx.Cursors (F) = Ctx.Cursors'Loop_Entry (F) else Invalid (Ctx, F))));
      end loop;
      pragma Assert (Field_First (Ctx, Fld) = First
                     and Field_Size (Ctx, Fld) = Size);
      Ctx.Cursors (Fld) := (S_Invalid, Ctx.Cursors (Fld).Predecessor);
      pragma Assert (Field_First (Ctx, Fld) = First
                     and Field_Size (Ctx, Fld) = Size);
   end Reset_Dependent_Fields;

   function Composite_Field (Fld : Field) return Boolean is
     (Fld in F_Ext_Asym | F_Ext_Hash | F_Resp_Alg_Structs);

   function Get (Ctx : Context; Fld : Field) return RFLX_Types.Base_Integer with
     Pre =>
       RFLX.SPDM.Algorithms_Response.Has_Buffer (Ctx)
       and then RFLX.SPDM.Algorithms_Response.Valid_Next (Ctx, Fld)
       and then RFLX.SPDM.Algorithms_Response.Sufficient_Buffer_Length (Ctx, Fld)
       and then not RFLX.SPDM.Algorithms_Response.Composite_Field (Fld)
   is
      First : constant RFLX_Types.Bit_Index := Field_First (Ctx, Fld);
      Last : constant RFLX_Types.Bit_Index := Field_Last (Ctx, Fld);
      Buffer_First : constant RFLX_Types.Index := RFLX_Types.To_Index (First);
      Buffer_Last : constant RFLX_Types.Index := RFLX_Types.To_Index (Last);
      Offset : constant RFLX_Types.Offset := RFLX_Types.Offset ((RFLX_Types.Byte'Size - Last mod RFLX_Types.Byte'Size) mod RFLX_Types.Byte'Size);
      Size : constant Positive := (case Fld is
          when F_Resp_Alg_Struct_Count | F_Param_2 =>
             8,
          when F_Length =>
             16,
          when F_Measurement_Specification_Sel | F_Reserved_1 =>
             8,
          when F_Measurement_Hash_Algo | F_Base_Asym_Sel | F_Base_Hash_Sel | F_Reserved_2 | F_Reserved_3 | F_Reserved_4 =>
             32,
          when F_Ext_Asym_Sel_Count | F_Ext_Hash_Sel_Count =>
             8,
          when F_Reserved_5 =>
             16,
          when others =>
             Positive'Last);
      Byte_Order : constant RFLX_Types.Byte_Order := RFLX_Types.Low_Order_First;
   begin
      return RFLX_Types.Extract (Ctx.Buffer, Buffer_First, Buffer_Last, Offset, Size, Byte_Order);
   end Get;

   procedure Verify (Ctx : in out Context; Fld : Field) is
      Value : RFLX_Types.Base_Integer;
   begin
      if
         Invalid (Ctx.Cursors (Fld))
         and then Valid_Predecessor (Ctx, Fld)
         and then Path_Condition (Ctx, Fld)
      then
         if Sufficient_Buffer_Length (Ctx, Fld) then
            Value := (if Composite_Field (Fld) then 0 else Get (Ctx, Fld));
            if
               Valid_Value (Fld, Value)
               and then Field_Condition (Ctx, Fld, Value)
            then
               pragma Assert ((if Fld = F_Resp_Alg_Structs then Field_Last (Ctx, Fld) mod RFLX_Types.Byte'Size = 0));
               pragma Assert ((((Field_Last (Ctx, Fld) + RFLX_Types.Byte'Size - 1) / RFLX_Types.Byte'Size) * RFLX_Types.Byte'Size) mod RFLX_Types.Byte'Size = 0);
               Ctx.Verified_Last := ((Field_Last (Ctx, Fld) + RFLX_Types.Byte'Size - 1) / RFLX_Types.Byte'Size) * RFLX_Types.Byte'Size;
               pragma Assert (Field_Last (Ctx, Fld) <= Ctx.Verified_Last);
               if Composite_Field (Fld) then
                  Ctx.Cursors (Fld) := (State => S_Structural_Valid, First => Field_First (Ctx, Fld), Last => Field_Last (Ctx, Fld), Value => Value, Predecessor => Ctx.Cursors (Fld).Predecessor);
               else
                  Ctx.Cursors (Fld) := (State => S_Valid, First => Field_First (Ctx, Fld), Last => Field_Last (Ctx, Fld), Value => Value, Predecessor => Ctx.Cursors (Fld).Predecessor);
               end if;
               Ctx.Cursors (Successor (Ctx, Fld)) := (State => S_Invalid, Predecessor => Fld);
            else
               Ctx.Cursors (Fld) := (State => S_Invalid, Predecessor => F_Final);
            end if;
         else
            Ctx.Cursors (Fld) := (State => S_Incomplete, Predecessor => F_Final);
         end if;
      end if;
   end Verify;

   procedure Verify_Message (Ctx : in out Context) is
   begin
      for F in Field loop
         pragma Loop_Invariant (Has_Buffer (Ctx)
                                and Ctx.Buffer_First = Ctx.Buffer_First'Loop_Entry
                                and Ctx.Buffer_Last = Ctx.Buffer_Last'Loop_Entry
                                and Ctx.First = Ctx.First'Loop_Entry
                                and Ctx.Last = Ctx.Last'Loop_Entry);
         Verify (Ctx, F);
      end loop;
   end Verify_Message;

   procedure Set (Ctx : in out Context; Fld : Field; Val : RFLX_Types.Base_Integer; Size : RFLX_Types.Bit_Length; State_Valid : Boolean; Buffer_First : out RFLX_Types.Index; Buffer_Last : out RFLX_Types.Index; Offset : out RFLX_Types.Offset) with
     Pre =>
       RFLX.SPDM.Algorithms_Response.Has_Buffer (Ctx)
       and then RFLX.SPDM.Algorithms_Response.Valid_Next (Ctx, Fld)
       and then RFLX.SPDM.Algorithms_Response.Valid_Value (Fld, Val)
       and then RFLX.SPDM.Algorithms_Response.Valid_Size (Ctx, Fld, Size)
       and then Size <= RFLX.SPDM.Algorithms_Response.Available_Space (Ctx, Fld)
       and then (if
                    RFLX.SPDM.Algorithms_Response.Composite_Field (Fld)
                 then
                    Size mod RFLX_Types.Byte'Size = 0
                 else
                    State_Valid),
     Post =>
       Valid_Next (Ctx, Fld)
       and then Invalid_Successor (Ctx, Fld)
       and then Buffer_First = RFLX_Types.To_Index (Field_First (Ctx, Fld))
       and then Buffer_Last = RFLX_Types.To_Index (Field_First (Ctx, Fld) + Size - 1)
       and then Offset = RFLX_Types.Offset ((RFLX_Types.Byte'Size - (Field_First (Ctx, Fld) + Size - 1) mod RFLX_Types.Byte'Size) mod RFLX_Types.Byte'Size)
       and then Ctx.Buffer_First = Ctx.Buffer_First'Old
       and then Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and then Ctx.First = Ctx.First'Old
       and then Ctx.Last = Ctx.Last'Old
       and then Ctx.Buffer_First = Ctx.Buffer_First'Old
       and then Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and then Ctx.First = Ctx.First'Old
       and then Ctx.Last = Ctx.Last'Old
       and then Has_Buffer (Ctx) = Has_Buffer (Ctx)'Old
       and then Predecessor (Ctx, Fld) = Predecessor (Ctx, Fld)'Old
       and then Field_First (Ctx, Fld) = Field_First (Ctx, Fld)'Old
       and then Sufficient_Space (Ctx, Fld)
       and then (if State_Valid and Size > 0 then Valid (Ctx, Fld) else Structural_Valid (Ctx, Fld))
       and then (case Fld is
                    when F_Resp_Alg_Struct_Count =>
                       Get_Resp_Alg_Struct_Count (Ctx) = To_Actual (Val)
                       and (Predecessor (Ctx, F_Param_2) = F_Resp_Alg_Struct_Count
                            and Valid_Next (Ctx, F_Param_2)),
                    when F_Param_2 =>
                       (Predecessor (Ctx, F_Length) = F_Param_2
                        and Valid_Next (Ctx, F_Length)),
                    when F_Length =>
                       Get_Length (Ctx) = To_Actual (Val)
                       and (Predecessor (Ctx, F_Measurement_Specification_Sel) = F_Length
                            and Valid_Next (Ctx, F_Measurement_Specification_Sel)),
                    when F_Measurement_Specification_Sel =>
                       (Predecessor (Ctx, F_Reserved_1) = F_Measurement_Specification_Sel
                        and Valid_Next (Ctx, F_Reserved_1)),
                    when F_Reserved_1 =>
                       (Predecessor (Ctx, F_Measurement_Hash_Algo) = F_Reserved_1
                        and Valid_Next (Ctx, F_Measurement_Hash_Algo)),
                    when F_Measurement_Hash_Algo =>
                       Get_Measurement_Hash_Algo (Ctx) = To_Actual (Val)
                       and (Predecessor (Ctx, F_Base_Asym_Sel) = F_Measurement_Hash_Algo
                            and Valid_Next (Ctx, F_Base_Asym_Sel)),
                    when F_Base_Asym_Sel =>
                       Get_Base_Asym_Sel (Ctx) = To_Actual (Val)
                       and (Predecessor (Ctx, F_Base_Hash_Sel) = F_Base_Asym_Sel
                            and Valid_Next (Ctx, F_Base_Hash_Sel)),
                    when F_Base_Hash_Sel =>
                       Get_Base_Hash_Sel (Ctx) = To_Actual (Val)
                       and (Predecessor (Ctx, F_Reserved_2) = F_Base_Hash_Sel
                            and Valid_Next (Ctx, F_Reserved_2)),
                    when F_Reserved_2 =>
                       (Predecessor (Ctx, F_Reserved_3) = F_Reserved_2
                        and Valid_Next (Ctx, F_Reserved_3)),
                    when F_Reserved_3 =>
                       (Predecessor (Ctx, F_Reserved_4) = F_Reserved_3
                        and Valid_Next (Ctx, F_Reserved_4)),
                    when F_Reserved_4 =>
                       (Predecessor (Ctx, F_Ext_Asym_Sel_Count) = F_Reserved_4
                        and Valid_Next (Ctx, F_Ext_Asym_Sel_Count)),
                    when F_Ext_Asym_Sel_Count =>
                       Get_Ext_Asym_Sel_Count (Ctx) = To_Actual (Val)
                       and (if
                               Get_Ext_Asym_Sel_Count (Ctx) <= 1
                            then
                               Predecessor (Ctx, F_Ext_Hash_Sel_Count) = F_Ext_Asym_Sel_Count
                               and Valid_Next (Ctx, F_Ext_Hash_Sel_Count)),
                    when F_Ext_Hash_Sel_Count =>
                       Get_Ext_Hash_Sel_Count (Ctx) = To_Actual (Val)
                       and (if
                               Get_Ext_Hash_Sel_Count (Ctx) <= 1
                            then
                               Predecessor (Ctx, F_Reserved_5) = F_Ext_Hash_Sel_Count
                               and Valid_Next (Ctx, F_Reserved_5)),
                    when F_Reserved_5 =>
                       (Predecessor (Ctx, F_Ext_Asym) = F_Reserved_5
                        and Valid_Next (Ctx, F_Ext_Asym)),
                    when F_Ext_Asym =>
                       (Predecessor (Ctx, F_Ext_Hash) = F_Ext_Asym
                        and Valid_Next (Ctx, F_Ext_Hash)),
                    when F_Ext_Hash =>
                       (if
                           RFLX_Types.Base_Integer (Get_Length (Ctx)) * 8 >= RFLX_Types.Base_Integer (Field_Last (Ctx, F_Ext_Hash)) - RFLX_Types.Base_Integer (Field_First (Ctx, F_Resp_Alg_Struct_Count)) + 17
                        then
                           Predecessor (Ctx, F_Resp_Alg_Structs) = F_Ext_Hash
                           and Valid_Next (Ctx, F_Resp_Alg_Structs)),
                    when F_Resp_Alg_Structs =>
                       (if Structural_Valid_Message (Ctx) then Message_Last (Ctx) = Field_Last (Ctx, Fld)))
       and then (for all F in Field =>
                    (if F < Fld then Ctx.Cursors (F) = Ctx.Cursors'Old (F)))
   is
      First : RFLX_Types.Bit_Index;
      Last : RFLX_Types.Bit_Length;
   begin
      Reset_Dependent_Fields (Ctx, Fld);
      First := Field_First (Ctx, Fld);
      Last := Field_First (Ctx, Fld) + Size - 1;
      Offset := RFLX_Types.Offset ((RFLX_Types.Byte'Size - Last mod RFLX_Types.Byte'Size) mod RFLX_Types.Byte'Size);
      Buffer_First := RFLX_Types.To_Index (First);
      Buffer_Last := RFLX_Types.To_Index (Last);
      pragma Assert ((((Last + RFLX_Types.Byte'Size - 1) / RFLX_Types.Byte'Size) * RFLX_Types.Byte'Size) mod RFLX_Types.Byte'Size = 0);
      pragma Warnings (Off, "attribute Update is an obsolescent feature");
      Ctx := Ctx'Update (Verified_Last => ((Last + RFLX_Types.Byte'Size - 1) / RFLX_Types.Byte'Size) * RFLX_Types.Byte'Size, Written_Last => ((Last + RFLX_Types.Byte'Size - 1) / RFLX_Types.Byte'Size) * RFLX_Types.Byte'Size);
      pragma Warnings (On, "attribute Update is an obsolescent feature");
      pragma Assert (Size = (case Fld is
                         when F_Resp_Alg_Struct_Count | F_Param_2 =>
                            8,
                         when F_Length =>
                            16,
                         when F_Measurement_Specification_Sel | F_Reserved_1 =>
                            8,
                         when F_Measurement_Hash_Algo | F_Base_Asym_Sel | F_Base_Hash_Sel | F_Reserved_2 | F_Reserved_3 | F_Reserved_4 =>
                            32,
                         when F_Ext_Asym_Sel_Count | F_Ext_Hash_Sel_Count =>
                            8,
                         when F_Reserved_5 =>
                            16,
                         when F_Ext_Asym =>
                            RFLX_Types.Bit_Length (Ctx.Cursors (F_Ext_Asym_Sel_Count).Value) * 32,
                         when F_Ext_Hash =>
                            RFLX_Types.Bit_Length (Ctx.Cursors (F_Ext_Hash_Sel_Count).Value) * 32,
                         when F_Resp_Alg_Structs =>
                            RFLX_Types.Bit_Length (Ctx.Cursors (F_Length).Value) * 8 - 16 + ((-RFLX_Types.Bit_Length (Ctx.Cursors (F_Ext_Hash).Last)) + RFLX_Types.Bit_Length (Ctx.Cursors (F_Resp_Alg_Struct_Count).First) - 1)));
      if State_Valid then
         Ctx.Cursors (Fld) := (State => S_Valid, First => First, Last => Last, Value => Val, Predecessor => Ctx.Cursors (Fld).Predecessor);
      else
         Ctx.Cursors (Fld) := (State => S_Structural_Valid, First => First, Last => Last, Value => Val, Predecessor => Ctx.Cursors (Fld).Predecessor);
      end if;
      Ctx.Cursors (Successor (Ctx, Fld)) := (State => S_Invalid, Predecessor => Fld);
      pragma Assert (Last = (Field_First (Ctx, Fld) + Size) - 1);
   end Set;

   procedure Set_Scalar (Ctx : in out Context; Fld : Field; Val : RFLX_Types.Base_Integer) with
     Pre =>
       not Ctx'Constrained
       and then RFLX.SPDM.Algorithms_Response.Has_Buffer (Ctx)
       and then RFLX.SPDM.Algorithms_Response.Valid_Next (Ctx, Fld)
       and then Fld in F_Resp_Alg_Struct_Count | F_Param_2 | F_Length | F_Measurement_Specification_Sel | F_Reserved_1 | F_Measurement_Hash_Algo | F_Base_Asym_Sel | F_Base_Hash_Sel | F_Reserved_2 | F_Reserved_3 | F_Reserved_4 | F_Ext_Asym_Sel_Count | F_Ext_Hash_Sel_Count | F_Reserved_5
       and then RFLX.SPDM.Algorithms_Response.Valid_Value (Fld, Val)
       and then RFLX.SPDM.Algorithms_Response.Valid_Size (Ctx, Fld, RFLX.SPDM.Algorithms_Response.Field_Size (Ctx, Fld))
       and then RFLX.SPDM.Algorithms_Response.Available_Space (Ctx, Fld) >= RFLX.SPDM.Algorithms_Response.Field_Size (Ctx, Fld)
       and then RFLX.SPDM.Algorithms_Response.Field_Size (Ctx, Fld) in 1 .. RFLX_Types.Base_Integer'Size
       and then RFLX_Types.Fits_Into (Val, Natural (RFLX.SPDM.Algorithms_Response.Field_Size (Ctx, Fld))),
     Post =>
       Has_Buffer (Ctx)
       and Valid (Ctx, Fld)
       and Invalid_Successor (Ctx, Fld)
       and (case Fld is
               when F_Resp_Alg_Struct_Count =>
                  Get_Resp_Alg_Struct_Count (Ctx) = To_Actual (Val)
                  and (Predecessor (Ctx, F_Param_2) = F_Resp_Alg_Struct_Count
                       and Valid_Next (Ctx, F_Param_2)),
               when F_Param_2 =>
                  (Predecessor (Ctx, F_Length) = F_Param_2
                   and Valid_Next (Ctx, F_Length)),
               when F_Length =>
                  Get_Length (Ctx) = To_Actual (Val)
                  and (Predecessor (Ctx, F_Measurement_Specification_Sel) = F_Length
                       and Valid_Next (Ctx, F_Measurement_Specification_Sel)),
               when F_Measurement_Specification_Sel =>
                  (Predecessor (Ctx, F_Reserved_1) = F_Measurement_Specification_Sel
                   and Valid_Next (Ctx, F_Reserved_1)),
               when F_Reserved_1 =>
                  (Predecessor (Ctx, F_Measurement_Hash_Algo) = F_Reserved_1
                   and Valid_Next (Ctx, F_Measurement_Hash_Algo)),
               when F_Measurement_Hash_Algo =>
                  Get_Measurement_Hash_Algo (Ctx) = To_Actual (Val)
                  and (Predecessor (Ctx, F_Base_Asym_Sel) = F_Measurement_Hash_Algo
                       and Valid_Next (Ctx, F_Base_Asym_Sel)),
               when F_Base_Asym_Sel =>
                  Get_Base_Asym_Sel (Ctx) = To_Actual (Val)
                  and (Predecessor (Ctx, F_Base_Hash_Sel) = F_Base_Asym_Sel
                       and Valid_Next (Ctx, F_Base_Hash_Sel)),
               when F_Base_Hash_Sel =>
                  Get_Base_Hash_Sel (Ctx) = To_Actual (Val)
                  and (Predecessor (Ctx, F_Reserved_2) = F_Base_Hash_Sel
                       and Valid_Next (Ctx, F_Reserved_2)),
               when F_Reserved_2 =>
                  (Predecessor (Ctx, F_Reserved_3) = F_Reserved_2
                   and Valid_Next (Ctx, F_Reserved_3)),
               when F_Reserved_3 =>
                  (Predecessor (Ctx, F_Reserved_4) = F_Reserved_3
                   and Valid_Next (Ctx, F_Reserved_4)),
               when F_Reserved_4 =>
                  (Predecessor (Ctx, F_Ext_Asym_Sel_Count) = F_Reserved_4
                   and Valid_Next (Ctx, F_Ext_Asym_Sel_Count)),
               when F_Ext_Asym_Sel_Count =>
                  Get_Ext_Asym_Sel_Count (Ctx) = To_Actual (Val)
                  and (if
                          Get_Ext_Asym_Sel_Count (Ctx) <= 1
                       then
                          Predecessor (Ctx, F_Ext_Hash_Sel_Count) = F_Ext_Asym_Sel_Count
                          and Valid_Next (Ctx, F_Ext_Hash_Sel_Count)),
               when F_Ext_Hash_Sel_Count =>
                  Get_Ext_Hash_Sel_Count (Ctx) = To_Actual (Val)
                  and (if
                          Get_Ext_Hash_Sel_Count (Ctx) <= 1
                       then
                          Predecessor (Ctx, F_Reserved_5) = F_Ext_Hash_Sel_Count
                          and Valid_Next (Ctx, F_Reserved_5)),
               when F_Reserved_5 =>
                  (Predecessor (Ctx, F_Ext_Asym) = F_Reserved_5
                   and Valid_Next (Ctx, F_Ext_Asym)),
               when F_Ext_Asym =>
                  (Predecessor (Ctx, F_Ext_Hash) = F_Ext_Asym
                   and Valid_Next (Ctx, F_Ext_Hash)),
               when F_Ext_Hash =>
                  (if
                      RFLX_Types.Base_Integer (Get_Length (Ctx)) * 8 >= RFLX_Types.Base_Integer (Field_Last (Ctx, F_Ext_Hash)) - RFLX_Types.Base_Integer (Field_First (Ctx, F_Resp_Alg_Struct_Count)) + 17
                   then
                      Predecessor (Ctx, F_Resp_Alg_Structs) = F_Ext_Hash
                      and Valid_Next (Ctx, F_Resp_Alg_Structs)),
               when F_Resp_Alg_Structs =>
                  (if Structural_Valid_Message (Ctx) then Message_Last (Ctx) = Field_Last (Ctx, Fld)))
       and (for all F in Field =>
               (if F < Fld then Ctx.Cursors (F) = Ctx.Cursors'Old (F)))
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = Ctx.First'Old
       and Ctx.Last = Ctx.Last'Old
       and Has_Buffer (Ctx) = Has_Buffer (Ctx)'Old
       and Predecessor (Ctx, Fld) = Predecessor (Ctx, Fld)'Old
       and Field_First (Ctx, Fld) = Field_First (Ctx, Fld)'Old
   is
      Buffer_First, Buffer_Last : RFLX_Types.Index;
      Offset : RFLX_Types.Offset;
      Size : constant RFLX_Types.Bit_Length := Field_Size (Ctx, Fld);
   begin
      Set (Ctx, Fld, Val, Size, True, Buffer_First, Buffer_Last, Offset);
      RFLX_Types.Lemma_Size (Val, Positive (Size));
      RFLX_Types.Insert (Val, Ctx.Buffer, Buffer_First, Buffer_Last, Offset, Positive (Size), RFLX_Types.Low_Order_First);
   end Set_Scalar;

   procedure Set_Resp_Alg_Struct_Count (Ctx : in out Context; Val : RFLX.SPDM.Alg_Struct_Count) is
   begin
      Set_Scalar (Ctx, F_Resp_Alg_Struct_Count, RFLX.SPDM.To_Base_Integer (Val));
   end Set_Resp_Alg_Struct_Count;

   procedure Set_Param_2 (Ctx : in out Context; Val : RFLX.SPDM.Reserved_8) is
   begin
      Set_Scalar (Ctx, F_Param_2, RFLX.SPDM.To_Base_Integer (Val));
   end Set_Param_2;

   procedure Set_Length (Ctx : in out Context; Val : RFLX.SPDM.Length_16) is
   begin
      Set_Scalar (Ctx, F_Length, RFLX.SPDM.To_Base_Integer (Val));
   end Set_Length;

   procedure Set_Measurement_Specification_Sel (Ctx : in out Context; Val : RFLX.SPDM.Measurement_Specification) is
   begin
      Set_Scalar (Ctx, F_Measurement_Specification_Sel, RFLX.SPDM.To_Base_Integer (Val));
   end Set_Measurement_Specification_Sel;

   procedure Set_Reserved_1 (Ctx : in out Context; Val : RFLX.SPDM.Reserved_8) is
   begin
      Set_Scalar (Ctx, F_Reserved_1, RFLX.SPDM.To_Base_Integer (Val));
   end Set_Reserved_1;

   procedure Set_Measurement_Hash_Algo (Ctx : in out Context; Val : RFLX.SPDM.Measurement_Hash_Algo) is
   begin
      Set_Scalar (Ctx, F_Measurement_Hash_Algo, RFLX.SPDM.To_Base_Integer (Val));
   end Set_Measurement_Hash_Algo;

   procedure Set_Base_Asym_Sel (Ctx : in out Context; Val : RFLX.SPDM.Base_Asym_Algo) is
   begin
      Set_Scalar (Ctx, F_Base_Asym_Sel, RFLX.SPDM.To_Base_Integer (Val));
   end Set_Base_Asym_Sel;

   procedure Set_Base_Hash_Sel (Ctx : in out Context; Val : RFLX.SPDM.Base_Hash_Algo) is
   begin
      Set_Scalar (Ctx, F_Base_Hash_Sel, RFLX.SPDM.To_Base_Integer (Val));
   end Set_Base_Hash_Sel;

   procedure Set_Reserved_2 (Ctx : in out Context; Val : RFLX.SPDM.Reserved_32) is
   begin
      Set_Scalar (Ctx, F_Reserved_2, RFLX.SPDM.To_Base_Integer (Val));
   end Set_Reserved_2;

   procedure Set_Reserved_3 (Ctx : in out Context; Val : RFLX.SPDM.Reserved_32) is
   begin
      Set_Scalar (Ctx, F_Reserved_3, RFLX.SPDM.To_Base_Integer (Val));
   end Set_Reserved_3;

   procedure Set_Reserved_4 (Ctx : in out Context; Val : RFLX.SPDM.Reserved_32) is
   begin
      Set_Scalar (Ctx, F_Reserved_4, RFLX.SPDM.To_Base_Integer (Val));
   end Set_Reserved_4;

   procedure Set_Ext_Asym_Sel_Count (Ctx : in out Context; Val : RFLX.SPDM.Ext_Asym_Count) is
   begin
      Set_Scalar (Ctx, F_Ext_Asym_Sel_Count, RFLX.SPDM.To_Base_Integer (Val));
   end Set_Ext_Asym_Sel_Count;

   procedure Set_Ext_Hash_Sel_Count (Ctx : in out Context; Val : RFLX.SPDM.Ext_Hash_Count) is
   begin
      Set_Scalar (Ctx, F_Ext_Hash_Sel_Count, RFLX.SPDM.To_Base_Integer (Val));
   end Set_Ext_Hash_Sel_Count;

   procedure Set_Reserved_5 (Ctx : in out Context; Val : RFLX.SPDM.Reserved_16) is
   begin
      Set_Scalar (Ctx, F_Reserved_5, RFLX.SPDM.To_Base_Integer (Val));
   end Set_Reserved_5;

   procedure Set_Ext_Asym_Empty (Ctx : in out Context) is
      Unused_Buffer_First, Unused_Buffer_Last : RFLX_Types.Index;
      Unused_Offset : RFLX_Types.Offset;
   begin
      Set (Ctx, F_Ext_Asym, 0, 0, True, Unused_Buffer_First, Unused_Buffer_Last, Unused_Offset);
   end Set_Ext_Asym_Empty;

   procedure Set_Ext_Hash_Empty (Ctx : in out Context) is
      Unused_Buffer_First, Unused_Buffer_Last : RFLX_Types.Index;
      Unused_Offset : RFLX_Types.Offset;
   begin
      Set (Ctx, F_Ext_Hash, 0, 0, True, Unused_Buffer_First, Unused_Buffer_Last, Unused_Offset);
   end Set_Ext_Hash_Empty;

   procedure Set_Resp_Alg_Structs_Empty (Ctx : in out Context) is
      Unused_Buffer_First, Unused_Buffer_Last : RFLX_Types.Index;
      Unused_Offset : RFLX_Types.Offset;
   begin
      Set (Ctx, F_Resp_Alg_Structs, 0, 0, True, Unused_Buffer_First, Unused_Buffer_Last, Unused_Offset);
   end Set_Resp_Alg_Structs_Empty;

   procedure Set_Ext_Asym (Ctx : in out Context; Seq_Ctx : RFLX.SPDM.Ext_Algs.Context) is
      Size : constant RFLX_Types.Bit_Length := RFLX_Types.To_Bit_Length (RFLX.SPDM.Ext_Algs.Byte_Size (Seq_Ctx));
      Unused_First, Unused_Last : RFLX_Types.Bit_Index;
      Buffer_First, Buffer_Last : RFLX_Types.Index;
      Unused_Offset : RFLX_Types.Offset;
   begin
      Set (Ctx, F_Ext_Asym, 0, Size, True, Buffer_First, Buffer_Last, Unused_Offset);
      RFLX.SPDM.Ext_Algs.Copy (Seq_Ctx, Ctx.Buffer.all (Buffer_First .. Buffer_Last));
   end Set_Ext_Asym;

   procedure Set_Ext_Hash (Ctx : in out Context; Seq_Ctx : RFLX.SPDM.Ext_Algs.Context) is
      Size : constant RFLX_Types.Bit_Length := RFLX_Types.To_Bit_Length (RFLX.SPDM.Ext_Algs.Byte_Size (Seq_Ctx));
      Unused_First, Unused_Last : RFLX_Types.Bit_Index;
      Buffer_First, Buffer_Last : RFLX_Types.Index;
      Unused_Offset : RFLX_Types.Offset;
   begin
      Set (Ctx, F_Ext_Hash, 0, Size, True, Buffer_First, Buffer_Last, Unused_Offset);
      RFLX.SPDM.Ext_Algs.Copy (Seq_Ctx, Ctx.Buffer.all (Buffer_First .. Buffer_Last));
   end Set_Ext_Hash;

   procedure Set_Resp_Alg_Structs (Ctx : in out Context; Seq_Ctx : RFLX.SPDM.Resp_Alg_Structs.Context) is
      Size : constant RFLX_Types.Bit_Length := RFLX_Types.To_Bit_Length (RFLX.SPDM.Resp_Alg_Structs.Byte_Size (Seq_Ctx));
      Unused_First, Unused_Last : RFLX_Types.Bit_Index;
      Buffer_First, Buffer_Last : RFLX_Types.Index;
      Unused_Offset : RFLX_Types.Offset;
   begin
      Set (Ctx, F_Resp_Alg_Structs, 0, Size, True, Buffer_First, Buffer_Last, Unused_Offset);
      RFLX.SPDM.Resp_Alg_Structs.Copy (Seq_Ctx, Ctx.Buffer.all (Buffer_First .. Buffer_Last));
   end Set_Resp_Alg_Structs;

   procedure Initialize_Ext_Asym_Private (Ctx : in out Context; Length : RFLX_Types.Length) with
     Pre =>
       not Ctx'Constrained
       and then RFLX.SPDM.Algorithms_Response.Has_Buffer (Ctx)
       and then RFLX.SPDM.Algorithms_Response.Valid_Next (Ctx, RFLX.SPDM.Algorithms_Response.F_Ext_Asym)
       and then RFLX.SPDM.Algorithms_Response.Valid_Length (Ctx, RFLX.SPDM.Algorithms_Response.F_Ext_Asym, Length)
       and then RFLX_Types.To_Length (RFLX.SPDM.Algorithms_Response.Available_Space (Ctx, RFLX.SPDM.Algorithms_Response.F_Ext_Asym)) >= Length
       and then RFLX.SPDM.Algorithms_Response.Field_First (Ctx, RFLX.SPDM.Algorithms_Response.F_Ext_Asym) mod RFLX_Types.Byte'Size = 1,
     Post =>
       Has_Buffer (Ctx)
       and Structural_Valid (Ctx, F_Ext_Asym)
       and Field_Size (Ctx, F_Ext_Asym) = RFLX_Types.To_Bit_Length (Length)
       and Ctx.Verified_Last = Field_Last (Ctx, F_Ext_Asym)
       and Invalid (Ctx, F_Ext_Hash)
       and Invalid (Ctx, F_Resp_Alg_Structs)
       and (Predecessor (Ctx, F_Ext_Hash) = F_Ext_Asym
            and Valid_Next (Ctx, F_Ext_Hash))
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = Ctx.First'Old
       and Ctx.Last = Ctx.Last'Old
       and Predecessor (Ctx, F_Ext_Asym) = Predecessor (Ctx, F_Ext_Asym)'Old
       and Valid_Next (Ctx, F_Ext_Asym) = Valid_Next (Ctx, F_Ext_Asym)'Old
       and Get_Resp_Alg_Struct_Count (Ctx) = Get_Resp_Alg_Struct_Count (Ctx)'Old
       and Get_Length (Ctx) = Get_Length (Ctx)'Old
       and Get_Measurement_Hash_Algo (Ctx) = Get_Measurement_Hash_Algo (Ctx)'Old
       and Get_Base_Asym_Sel (Ctx) = Get_Base_Asym_Sel (Ctx)'Old
       and Get_Base_Hash_Sel (Ctx) = Get_Base_Hash_Sel (Ctx)'Old
       and Get_Ext_Asym_Sel_Count (Ctx) = Get_Ext_Asym_Sel_Count (Ctx)'Old
       and Get_Ext_Hash_Sel_Count (Ctx) = Get_Ext_Hash_Sel_Count (Ctx)'Old
       and Field_First (Ctx, F_Ext_Asym) = Field_First (Ctx, F_Ext_Asym)'Old
       and Field_Last (Ctx, F_Ext_Asym) = Field_Last (Ctx, Predecessor (Ctx, F_Ext_Asym)) + Field_Size (Ctx, F_Ext_Asym)
   is
      First : constant RFLX_Types.Bit_Index := Field_First (Ctx, F_Ext_Asym);
      Last : constant RFLX_Types.Bit_Index := Field_First (Ctx, F_Ext_Asym) + RFLX_Types.Bit_Length (Length) * RFLX_Types.Byte'Size - 1;
   begin
      pragma Assert (Last mod RFLX_Types.Byte'Size = 0);
      Reset_Dependent_Fields (Ctx, F_Ext_Asym);
      pragma Warnings (Off, "attribute Update is an obsolescent feature");
      Ctx := Ctx'Update (Verified_Last => Last, Written_Last => Last);
      pragma Warnings (On, "attribute Update is an obsolescent feature");
      Ctx.Cursors (F_Ext_Asym) := (State => S_Structural_Valid, First => First, Last => Last, Value => 0, Predecessor => Ctx.Cursors (F_Ext_Asym).Predecessor);
      Ctx.Cursors (Successor (Ctx, F_Ext_Asym)) := (State => S_Invalid, Predecessor => F_Ext_Asym);
   end Initialize_Ext_Asym_Private;

   procedure Initialize_Ext_Asym (Ctx : in out Context) is
   begin
      Initialize_Ext_Asym_Private (Ctx, RFLX_Types.To_Length (Field_Size (Ctx, F_Ext_Asym)));
   end Initialize_Ext_Asym;

   procedure Initialize_Ext_Hash_Private (Ctx : in out Context; Length : RFLX_Types.Length) with
     Pre =>
       not Ctx'Constrained
       and then RFLX.SPDM.Algorithms_Response.Has_Buffer (Ctx)
       and then RFLX.SPDM.Algorithms_Response.Valid_Next (Ctx, RFLX.SPDM.Algorithms_Response.F_Ext_Hash)
       and then RFLX.SPDM.Algorithms_Response.Valid_Length (Ctx, RFLX.SPDM.Algorithms_Response.F_Ext_Hash, Length)
       and then RFLX_Types.To_Length (RFLX.SPDM.Algorithms_Response.Available_Space (Ctx, RFLX.SPDM.Algorithms_Response.F_Ext_Hash)) >= Length
       and then RFLX.SPDM.Algorithms_Response.Field_First (Ctx, RFLX.SPDM.Algorithms_Response.F_Ext_Hash) mod RFLX_Types.Byte'Size = 1,
     Post =>
       Has_Buffer (Ctx)
       and Structural_Valid (Ctx, F_Ext_Hash)
       and Field_Size (Ctx, F_Ext_Hash) = RFLX_Types.To_Bit_Length (Length)
       and Ctx.Verified_Last = Field_Last (Ctx, F_Ext_Hash)
       and Invalid (Ctx, F_Resp_Alg_Structs)
       and (if
               RFLX_Types.Base_Integer (Get_Length (Ctx)) * 8 >= RFLX_Types.Base_Integer (Field_Last (Ctx, F_Ext_Hash)) - RFLX_Types.Base_Integer (Field_First (Ctx, F_Resp_Alg_Struct_Count)) + 17
            then
               Predecessor (Ctx, F_Resp_Alg_Structs) = F_Ext_Hash
               and Valid_Next (Ctx, F_Resp_Alg_Structs))
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = Ctx.First'Old
       and Ctx.Last = Ctx.Last'Old
       and Predecessor (Ctx, F_Ext_Hash) = Predecessor (Ctx, F_Ext_Hash)'Old
       and Valid_Next (Ctx, F_Ext_Hash) = Valid_Next (Ctx, F_Ext_Hash)'Old
       and Get_Resp_Alg_Struct_Count (Ctx) = Get_Resp_Alg_Struct_Count (Ctx)'Old
       and Get_Length (Ctx) = Get_Length (Ctx)'Old
       and Get_Measurement_Hash_Algo (Ctx) = Get_Measurement_Hash_Algo (Ctx)'Old
       and Get_Base_Asym_Sel (Ctx) = Get_Base_Asym_Sel (Ctx)'Old
       and Get_Base_Hash_Sel (Ctx) = Get_Base_Hash_Sel (Ctx)'Old
       and Get_Ext_Asym_Sel_Count (Ctx) = Get_Ext_Asym_Sel_Count (Ctx)'Old
       and Get_Ext_Hash_Sel_Count (Ctx) = Get_Ext_Hash_Sel_Count (Ctx)'Old
       and Field_First (Ctx, F_Ext_Hash) = Field_First (Ctx, F_Ext_Hash)'Old
       and Field_Last (Ctx, F_Ext_Hash) = Field_Last (Ctx, Predecessor (Ctx, F_Ext_Hash)) + Field_Size (Ctx, F_Ext_Hash)
   is
      First : constant RFLX_Types.Bit_Index := Field_First (Ctx, F_Ext_Hash);
      Last : constant RFLX_Types.Bit_Index := Field_First (Ctx, F_Ext_Hash) + RFLX_Types.Bit_Length (Length) * RFLX_Types.Byte'Size - 1;
   begin
      pragma Assert (Last mod RFLX_Types.Byte'Size = 0);
      Reset_Dependent_Fields (Ctx, F_Ext_Hash);
      pragma Warnings (Off, "attribute Update is an obsolescent feature");
      Ctx := Ctx'Update (Verified_Last => Last, Written_Last => Last);
      pragma Warnings (On, "attribute Update is an obsolescent feature");
      Ctx.Cursors (F_Ext_Hash) := (State => S_Structural_Valid, First => First, Last => Last, Value => 0, Predecessor => Ctx.Cursors (F_Ext_Hash).Predecessor);
      Ctx.Cursors (Successor (Ctx, F_Ext_Hash)) := (State => S_Invalid, Predecessor => F_Ext_Hash);
   end Initialize_Ext_Hash_Private;

   procedure Initialize_Ext_Hash (Ctx : in out Context) is
   begin
      Initialize_Ext_Hash_Private (Ctx, RFLX_Types.To_Length (Field_Size (Ctx, F_Ext_Hash)));
   end Initialize_Ext_Hash;

   procedure Initialize_Resp_Alg_Structs_Private (Ctx : in out Context; Length : RFLX_Types.Length) with
     Pre =>
       not Ctx'Constrained
       and then RFLX.SPDM.Algorithms_Response.Has_Buffer (Ctx)
       and then RFLX.SPDM.Algorithms_Response.Valid_Next (Ctx, RFLX.SPDM.Algorithms_Response.F_Resp_Alg_Structs)
       and then RFLX.SPDM.Algorithms_Response.Valid_Length (Ctx, RFLX.SPDM.Algorithms_Response.F_Resp_Alg_Structs, Length)
       and then RFLX_Types.To_Length (RFLX.SPDM.Algorithms_Response.Available_Space (Ctx, RFLX.SPDM.Algorithms_Response.F_Resp_Alg_Structs)) >= Length
       and then RFLX.SPDM.Algorithms_Response.Field_First (Ctx, RFLX.SPDM.Algorithms_Response.F_Resp_Alg_Structs) mod RFLX_Types.Byte'Size = 1,
     Post =>
       Has_Buffer (Ctx)
       and Structural_Valid (Ctx, F_Resp_Alg_Structs)
       and Field_Size (Ctx, F_Resp_Alg_Structs) = RFLX_Types.To_Bit_Length (Length)
       and Ctx.Verified_Last = Field_Last (Ctx, F_Resp_Alg_Structs)
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = Ctx.First'Old
       and Ctx.Last = Ctx.Last'Old
       and Predecessor (Ctx, F_Resp_Alg_Structs) = Predecessor (Ctx, F_Resp_Alg_Structs)'Old
       and Valid_Next (Ctx, F_Resp_Alg_Structs) = Valid_Next (Ctx, F_Resp_Alg_Structs)'Old
       and Get_Resp_Alg_Struct_Count (Ctx) = Get_Resp_Alg_Struct_Count (Ctx)'Old
       and Get_Length (Ctx) = Get_Length (Ctx)'Old
       and Get_Measurement_Hash_Algo (Ctx) = Get_Measurement_Hash_Algo (Ctx)'Old
       and Get_Base_Asym_Sel (Ctx) = Get_Base_Asym_Sel (Ctx)'Old
       and Get_Base_Hash_Sel (Ctx) = Get_Base_Hash_Sel (Ctx)'Old
       and Get_Ext_Asym_Sel_Count (Ctx) = Get_Ext_Asym_Sel_Count (Ctx)'Old
       and Get_Ext_Hash_Sel_Count (Ctx) = Get_Ext_Hash_Sel_Count (Ctx)'Old
       and Field_First (Ctx, F_Resp_Alg_Structs) = Field_First (Ctx, F_Resp_Alg_Structs)'Old
       and Field_Last (Ctx, F_Resp_Alg_Structs) = Field_Last (Ctx, Predecessor (Ctx, F_Resp_Alg_Structs)) + Field_Size (Ctx, F_Resp_Alg_Structs)
   is
      First : constant RFLX_Types.Bit_Index := Field_First (Ctx, F_Resp_Alg_Structs);
      Last : constant RFLX_Types.Bit_Index := Field_First (Ctx, F_Resp_Alg_Structs) + RFLX_Types.Bit_Length (Length) * RFLX_Types.Byte'Size - 1;
   begin
      pragma Assert (Last mod RFLX_Types.Byte'Size = 0);
      Reset_Dependent_Fields (Ctx, F_Resp_Alg_Structs);
      pragma Warnings (Off, "attribute Update is an obsolescent feature");
      Ctx := Ctx'Update (Verified_Last => Last, Written_Last => Last);
      pragma Warnings (On, "attribute Update is an obsolescent feature");
      Ctx.Cursors (F_Resp_Alg_Structs) := (State => S_Structural_Valid, First => First, Last => Last, Value => 0, Predecessor => Ctx.Cursors (F_Resp_Alg_Structs).Predecessor);
      Ctx.Cursors (Successor (Ctx, F_Resp_Alg_Structs)) := (State => S_Invalid, Predecessor => F_Resp_Alg_Structs);
   end Initialize_Resp_Alg_Structs_Private;

   procedure Initialize_Resp_Alg_Structs (Ctx : in out Context) is
   begin
      Initialize_Resp_Alg_Structs_Private (Ctx, RFLX_Types.To_Length (Field_Size (Ctx, F_Resp_Alg_Structs)));
   end Initialize_Resp_Alg_Structs;

   procedure Switch_To_Ext_Asym (Ctx : in out Context; Seq_Ctx : out RFLX.SPDM.Ext_Algs.Context) is
      First : constant RFLX_Types.Bit_Index := Field_First (Ctx, F_Ext_Asym);
      Last : constant RFLX_Types.Bit_Index := Field_Last (Ctx, F_Ext_Asym);
      Buffer : RFLX_Types.Bytes_Ptr;
   begin
      if Invalid (Ctx, F_Ext_Asym) then
         Reset_Dependent_Fields (Ctx, F_Ext_Asym);
         pragma Warnings (Off, "attribute Update is an obsolescent feature");
         Ctx := Ctx'Update (Verified_Last => Last, Written_Last => RFLX_Types.Bit_Length'Max (Ctx.Written_Last, Last));
         pragma Warnings (On, "attribute Update is an obsolescent feature");
         Ctx.Cursors (F_Ext_Asym) := (State => S_Structural_Valid, First => First, Last => Last, Value => 0, Predecessor => Ctx.Cursors (F_Ext_Asym).Predecessor);
         Ctx.Cursors (Successor (Ctx, F_Ext_Asym)) := (State => S_Invalid, Predecessor => F_Ext_Asym);
      end if;
      Take_Buffer (Ctx, Buffer);
      pragma Warnings (Off, "unused assignment to ""Buffer""");
      RFLX.SPDM.Ext_Algs.Initialize (Seq_Ctx, Buffer, First, Last);
      pragma Warnings (On, "unused assignment to ""Buffer""");
   end Switch_To_Ext_Asym;

   procedure Switch_To_Ext_Hash (Ctx : in out Context; Seq_Ctx : out RFLX.SPDM.Ext_Algs.Context) is
      First : constant RFLX_Types.Bit_Index := Field_First (Ctx, F_Ext_Hash);
      Last : constant RFLX_Types.Bit_Index := Field_Last (Ctx, F_Ext_Hash);
      Buffer : RFLX_Types.Bytes_Ptr;
   begin
      if Invalid (Ctx, F_Ext_Hash) then
         Reset_Dependent_Fields (Ctx, F_Ext_Hash);
         pragma Warnings (Off, "attribute Update is an obsolescent feature");
         Ctx := Ctx'Update (Verified_Last => Last, Written_Last => RFLX_Types.Bit_Length'Max (Ctx.Written_Last, Last));
         pragma Warnings (On, "attribute Update is an obsolescent feature");
         Ctx.Cursors (F_Ext_Hash) := (State => S_Structural_Valid, First => First, Last => Last, Value => 0, Predecessor => Ctx.Cursors (F_Ext_Hash).Predecessor);
         Ctx.Cursors (Successor (Ctx, F_Ext_Hash)) := (State => S_Invalid, Predecessor => F_Ext_Hash);
      end if;
      Take_Buffer (Ctx, Buffer);
      pragma Warnings (Off, "unused assignment to ""Buffer""");
      RFLX.SPDM.Ext_Algs.Initialize (Seq_Ctx, Buffer, First, Last);
      pragma Warnings (On, "unused assignment to ""Buffer""");
   end Switch_To_Ext_Hash;

   procedure Switch_To_Resp_Alg_Structs (Ctx : in out Context; Seq_Ctx : out RFLX.SPDM.Resp_Alg_Structs.Context) is
      First : constant RFLX_Types.Bit_Index := Field_First (Ctx, F_Resp_Alg_Structs);
      Last : constant RFLX_Types.Bit_Index := Field_Last (Ctx, F_Resp_Alg_Structs);
      Buffer : RFLX_Types.Bytes_Ptr;
   begin
      if Invalid (Ctx, F_Resp_Alg_Structs) then
         Reset_Dependent_Fields (Ctx, F_Resp_Alg_Structs);
         pragma Warnings (Off, "attribute Update is an obsolescent feature");
         Ctx := Ctx'Update (Verified_Last => Last, Written_Last => RFLX_Types.Bit_Length'Max (Ctx.Written_Last, Last));
         pragma Warnings (On, "attribute Update is an obsolescent feature");
         Ctx.Cursors (F_Resp_Alg_Structs) := (State => S_Structural_Valid, First => First, Last => Last, Value => 0, Predecessor => Ctx.Cursors (F_Resp_Alg_Structs).Predecessor);
         Ctx.Cursors (Successor (Ctx, F_Resp_Alg_Structs)) := (State => S_Invalid, Predecessor => F_Resp_Alg_Structs);
      end if;
      Take_Buffer (Ctx, Buffer);
      pragma Warnings (Off, "unused assignment to ""Buffer""");
      RFLX.SPDM.Resp_Alg_Structs.Initialize (Seq_Ctx, Buffer, First, Last);
      pragma Warnings (On, "unused assignment to ""Buffer""");
   end Switch_To_Resp_Alg_Structs;

   procedure Update_Ext_Asym (Ctx : in out Context; Seq_Ctx : in out RFLX.SPDM.Ext_Algs.Context) is
      Valid_Sequence : constant Boolean := RFLX.SPDM.Ext_Algs.Valid (Seq_Ctx);
      Buffer : RFLX_Types.Bytes_Ptr;
   begin
      RFLX.SPDM.Ext_Algs.Take_Buffer (Seq_Ctx, Buffer);
      Ctx.Buffer := Buffer;
      if Valid_Sequence then
         Ctx.Cursors (F_Ext_Asym) := (State => S_Valid, First => Ctx.Cursors (F_Ext_Asym).First, Last => Ctx.Cursors (F_Ext_Asym).Last, Value => Ctx.Cursors (F_Ext_Asym).Value, Predecessor => Ctx.Cursors (F_Ext_Asym).Predecessor);
      end if;
   end Update_Ext_Asym;

   procedure Update_Ext_Hash (Ctx : in out Context; Seq_Ctx : in out RFLX.SPDM.Ext_Algs.Context) is
      Valid_Sequence : constant Boolean := RFLX.SPDM.Ext_Algs.Valid (Seq_Ctx);
      Buffer : RFLX_Types.Bytes_Ptr;
   begin
      RFLX.SPDM.Ext_Algs.Take_Buffer (Seq_Ctx, Buffer);
      Ctx.Buffer := Buffer;
      if Valid_Sequence then
         Ctx.Cursors (F_Ext_Hash) := (State => S_Valid, First => Ctx.Cursors (F_Ext_Hash).First, Last => Ctx.Cursors (F_Ext_Hash).Last, Value => Ctx.Cursors (F_Ext_Hash).Value, Predecessor => Ctx.Cursors (F_Ext_Hash).Predecessor);
      end if;
   end Update_Ext_Hash;

   procedure Update_Resp_Alg_Structs (Ctx : in out Context; Seq_Ctx : in out RFLX.SPDM.Resp_Alg_Structs.Context) is
      Valid_Sequence : constant Boolean := RFLX.SPDM.Resp_Alg_Structs.Valid (Seq_Ctx);
      Buffer : RFLX_Types.Bytes_Ptr;
   begin
      RFLX.SPDM.Resp_Alg_Structs.Take_Buffer (Seq_Ctx, Buffer);
      Ctx.Buffer := Buffer;
      if Valid_Sequence then
         Ctx.Cursors (F_Resp_Alg_Structs) := (State => S_Valid, First => Ctx.Cursors (F_Resp_Alg_Structs).First, Last => Ctx.Cursors (F_Resp_Alg_Structs).Last, Value => Ctx.Cursors (F_Resp_Alg_Structs).Value, Predecessor => Ctx.Cursors (F_Resp_Alg_Structs).Predecessor);
      end if;
   end Update_Resp_Alg_Structs;

end RFLX.SPDM.Algorithms_Response;
