--
--  Generated by RecordFlux 0.6.1.dev1+g8b82b38a0 on 2022-12-02
--
--  Copyright (C) 2018-2022 AdaCore
--
--  SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
--

pragma Restrictions (No_Streams);
pragma Style_Checks ("N3aAbcdefhiIklnOprStux");
pragma Warnings (Off, "redundant conversion");

package body RFLX.SPDM_Proxy.Proxy with
  SPARK_Mode
is

   use type RFLX.RFLX_Types.Bytes_Ptr;

   use type RFLX.SPDM_Emu.Size;

   use type RFLX.SPDM_Emu.Command;

   use type RFLX.RFLX_Types.Bit_Length;

   procedure Proxy_Receive_Request (Ctx : in out Context'Class) with
     Pre =>
       Initialized (Ctx),
     Post =>
       Initialized (Ctx)
   is
      function Proxy_Receive_Request_Invariant return Boolean is
        (Ctx.P.Slots.Slot_Ptr_1 = null
         and Ctx.P.Slots.Slot_Ptr_2 = null)
       with
        Annotate =>
          (GNATprove, Inline_For_Proof),
        Ghost;
   begin
      pragma Assert (Proxy_Receive_Request_Invariant);
      --  build/specs/CHALLENGE_AUTH=False,KEY_EXCHANGE=False,RESPOND_IF_READY=False/spdm_proxy.rflx:23:10
      SPDM_Emu.Platform_Port.Verify_Message (Ctx.P.Emu_Packet_Ctx);
      if
         (SPDM_Emu.Platform_Port.Structural_Valid_Message (Ctx.P.Emu_Packet_Ctx)
          and then SPDM_Emu.Platform_Port.Get_Size (Ctx.P.Emu_Packet_Ctx) > 0)
         and then SPDM_Emu.Platform_Port.Get_Command (Ctx.P.Emu_Packet_Ctx) = SPDM_Emu.Normal
      then
         Ctx.P.Next_State := S_Proxy_Prepare_Request;
      elsif
         SPDM_Emu.Platform_Port.Structural_Valid_Message (Ctx.P.Emu_Packet_Ctx)
         and then SPDM_Emu.Platform_Port.Get_Command (Ctx.P.Emu_Packet_Ctx) = SPDM_Emu.Shutdown
      then
         Ctx.P.Next_State := S_Proxy_Prepare_Shutdown;
      else
         Ctx.P.Next_State := S_Proxy_Error;
      end if;
      pragma Assert (Proxy_Receive_Request_Invariant);
   end Proxy_Receive_Request;

   procedure Proxy_Prepare_Request (Ctx : in out Context'Class) with
     Pre =>
       Initialized (Ctx),
     Post =>
       Initialized (Ctx)
   is
      function Proxy_Prepare_Request_Invariant return Boolean is
        (Ctx.P.Slots.Slot_Ptr_1 = null
         and Ctx.P.Slots.Slot_Ptr_2 = null)
       with
        Annotate =>
          (GNATprove, Inline_For_Proof),
        Ghost;
   begin
      pragma Assert (Proxy_Prepare_Request_Invariant);
      --  build/specs/CHALLENGE_AUTH=False,KEY_EXCHANGE=False,RESPOND_IF_READY=False/spdm_proxy.rflx:36:10
      SPDM_Proxy.Packet.Reset (Ctx.P.SPDM_Packet_Ctx);
      if
         not (SPDM_Emu.Platform_Port.Size (Ctx.P.Emu_Packet_Ctx) <= 32768
          and then SPDM_Emu.Platform_Port.Size (Ctx.P.Emu_Packet_Ctx) mod RFLX_Types.Byte'Size = 0
          and then SPDM_Emu.Platform_Port.Structural_Valid (Ctx.P.Emu_Packet_Ctx, SPDM_Emu.Platform_Port.F_SPDM_Payload))
      then
         Ctx.P.Next_State := S_Proxy_Error;
         pragma Assert (Proxy_Prepare_Request_Invariant);
         goto Finalize_Proxy_Prepare_Request;
      end if;
      if SPDM_Proxy.Packet.Available_Space (Ctx.P.SPDM_Packet_Ctx, SPDM_Proxy.Packet.F_Data) < SPDM_Emu.Platform_Port.Field_Size (Ctx.P.Emu_Packet_Ctx, SPDM_Emu.Platform_Port.F_SPDM_Payload) then
         Ctx.P.Next_State := S_Proxy_Error;
         pragma Assert (Proxy_Prepare_Request_Invariant);
         goto Finalize_Proxy_Prepare_Request;
      end if;
      if SPDM_Emu.Platform_Port.Valid_Next (Ctx.P.Emu_Packet_Ctx, SPDM_Emu.Platform_Port.F_SPDM_Payload) then
         if SPDM_Proxy.Packet.Valid_Length (Ctx.P.SPDM_Packet_Ctx, SPDM_Proxy.Packet.F_Data, RFLX_Types.To_Length (SPDM_Emu.Platform_Port.Field_Size (Ctx.P.Emu_Packet_Ctx, SPDM_Emu.Platform_Port.F_SPDM_Payload))) then
            if SPDM_Emu.Platform_Port.Structural_Valid (Ctx.P.Emu_Packet_Ctx, SPDM_Emu.Platform_Port.F_SPDM_Payload) then
               declare
                  pragma Warnings (Off, "is not modified, could be declared constant");
                  RFLX_Ctx_P_Emu_Packet_Ctx_Tmp : SPDM_Emu.Platform_Port.Context := Ctx.P.Emu_Packet_Ctx;
                  pragma Warnings (On, "is not modified, could be declared constant");
                  function RFLX_Process_Data_Pre (Length : RFLX_Types.Length) return Boolean is
                    (SPDM_Emu.Platform_Port.Has_Buffer (RFLX_Ctx_P_Emu_Packet_Ctx_Tmp)
                     and then SPDM_Emu.Platform_Port.Structural_Valid (RFLX_Ctx_P_Emu_Packet_Ctx_Tmp, SPDM_Emu.Platform_Port.F_SPDM_Payload)
                     and then Length = RFLX_Types.To_Length (SPDM_Emu.Platform_Port.Field_Size (RFLX_Ctx_P_Emu_Packet_Ctx_Tmp, SPDM_Emu.Platform_Port.F_SPDM_Payload)));
                  procedure RFLX_Process_Data (Data : out RFLX_Types.Bytes) with
                    Pre =>
                      RFLX_Process_Data_Pre (Data'Length)
                  is
                  begin
                     SPDM_Emu.Platform_Port.Get_SPDM_Payload (RFLX_Ctx_P_Emu_Packet_Ctx_Tmp, Data);
                  end RFLX_Process_Data;
                  procedure RFLX_SPDM_Proxy_Packet_Set_Data is new SPDM_Proxy.Packet.Generic_Set_Data (RFLX_Process_Data, RFLX_Process_Data_Pre);
               begin
                  RFLX_SPDM_Proxy_Packet_Set_Data (Ctx.P.SPDM_Packet_Ctx, RFLX_Types.To_Length (SPDM_Emu.Platform_Port.Field_Size (RFLX_Ctx_P_Emu_Packet_Ctx_Tmp, SPDM_Emu.Platform_Port.F_SPDM_Payload)));
                  Ctx.P.Emu_Packet_Ctx := RFLX_Ctx_P_Emu_Packet_Ctx_Tmp;
               end;
            else
               Ctx.P.Next_State := S_Proxy_Error;
               pragma Assert (Proxy_Prepare_Request_Invariant);
               goto Finalize_Proxy_Prepare_Request;
            end if;
         else
            Ctx.P.Next_State := S_Proxy_Error;
            pragma Assert (Proxy_Prepare_Request_Invariant);
            goto Finalize_Proxy_Prepare_Request;
         end if;
      else
         Ctx.P.Next_State := S_Proxy_Error;
         pragma Assert (Proxy_Prepare_Request_Invariant);
         goto Finalize_Proxy_Prepare_Request;
      end if;
      Ctx.P.Next_State := S_Proxy_Send_Request;
      pragma Assert (Proxy_Prepare_Request_Invariant);
      <<Finalize_Proxy_Prepare_Request>>
   end Proxy_Prepare_Request;

   procedure Proxy_Send_Request (Ctx : in out Context'Class) with
     Pre =>
       Initialized (Ctx),
     Post =>
       Initialized (Ctx)
   is
      function Proxy_Send_Request_Invariant return Boolean is
        (Ctx.P.Slots.Slot_Ptr_1 = null
         and Ctx.P.Slots.Slot_Ptr_2 = null)
       with
        Annotate =>
          (GNATprove, Inline_For_Proof),
        Ghost;
   begin
      pragma Assert (Proxy_Send_Request_Invariant);
      --  build/specs/CHALLENGE_AUTH=False,KEY_EXCHANGE=False,RESPOND_IF_READY=False/spdm_proxy.rflx:46:10
      Ctx.P.Next_State := S_Proxy_Receive_Response;
      pragma Assert (Proxy_Send_Request_Invariant);
   end Proxy_Send_Request;

   procedure Proxy_Receive_Response (Ctx : in out Context'Class) with
     Pre =>
       Initialized (Ctx),
     Post =>
       Initialized (Ctx)
   is
      function Proxy_Receive_Response_Invariant return Boolean is
        (Ctx.P.Slots.Slot_Ptr_1 = null
         and Ctx.P.Slots.Slot_Ptr_2 = null)
       with
        Annotate =>
          (GNATprove, Inline_For_Proof),
        Ghost;
   begin
      pragma Assert (Proxy_Receive_Response_Invariant);
      --  build/specs/CHALLENGE_AUTH=False,KEY_EXCHANGE=False,RESPOND_IF_READY=False/spdm_proxy.rflx:54:10
      SPDM_Proxy.Packet.Verify_Message (Ctx.P.SPDM_Packet_Ctx);
      if SPDM_Proxy.Packet.Structural_Valid_Message (Ctx.P.SPDM_Packet_Ctx) then
         Ctx.P.Next_State := S_Proxy_Prepare_Response;
      else
         Ctx.P.Next_State := S_Proxy_Error;
      end if;
      pragma Assert (Proxy_Receive_Response_Invariant);
   end Proxy_Receive_Response;

   procedure Proxy_Prepare_Response (Ctx : in out Context'Class) with
     Pre =>
       Initialized (Ctx),
     Post =>
       Initialized (Ctx)
   is
      function Proxy_Prepare_Response_Invariant return Boolean is
        (Ctx.P.Slots.Slot_Ptr_1 = null
         and Ctx.P.Slots.Slot_Ptr_2 = null)
       with
        Annotate =>
          (GNATprove, Inline_For_Proof),
        Ghost;
   begin
      pragma Assert (Proxy_Prepare_Response_Invariant);
      --  build/specs/CHALLENGE_AUTH=False,KEY_EXCHANGE=False,RESPOND_IF_READY=False/spdm_proxy.rflx:64:10
      SPDM_Emu.Platform_Port.Reset (Ctx.P.Emu_Packet_Ctx);
      if
         not (SPDM_Proxy.Packet.Size (Ctx.P.SPDM_Packet_Ctx) <= 32768
          and then SPDM_Proxy.Packet.Size (Ctx.P.SPDM_Packet_Ctx) mod RFLX_Types.Byte'Size = 0
          and then SPDM_Proxy.Packet.Structural_Valid (Ctx.P.SPDM_Packet_Ctx, SPDM_Proxy.Packet.F_Data))
      then
         Ctx.P.Next_State := S_Proxy_Error;
         pragma Assert (Proxy_Prepare_Response_Invariant);
         goto Finalize_Proxy_Prepare_Response;
      end if;
      if SPDM_Emu.Platform_Port.Available_Space (Ctx.P.Emu_Packet_Ctx, SPDM_Emu.Platform_Port.F_Command) < SPDM_Proxy.Packet.Field_Size (Ctx.P.SPDM_Packet_Ctx, SPDM_Proxy.Packet.F_Data) + 96 then
         Ctx.P.Next_State := S_Proxy_Error;
         pragma Assert (Proxy_Prepare_Response_Invariant);
         goto Finalize_Proxy_Prepare_Response;
      end if;
      pragma Assert (SPDM_Emu.Platform_Port.Sufficient_Space (Ctx.P.Emu_Packet_Ctx, SPDM_Emu.Platform_Port.F_Command));
      SPDM_Emu.Platform_Port.Set_Command (Ctx.P.Emu_Packet_Ctx, SPDM_Emu.Normal);
      pragma Assert (SPDM_Emu.Platform_Port.Sufficient_Space (Ctx.P.Emu_Packet_Ctx, SPDM_Emu.Platform_Port.F_Transport_Type));
      SPDM_Emu.Platform_Port.Set_Transport_Type (Ctx.P.Emu_Packet_Ctx, SPDM_Emu.None);
      pragma Assert (SPDM_Emu.Platform_Port.Sufficient_Space (Ctx.P.Emu_Packet_Ctx, SPDM_Emu.Platform_Port.F_Size));
      SPDM_Emu.Platform_Port.Set_Size (Ctx.P.Emu_Packet_Ctx, SPDM_Emu.Size (SPDM_Proxy.Packet.Field_Size (Ctx.P.SPDM_Packet_Ctx, SPDM_Proxy.Packet.F_Data) / 8));
      if SPDM_Proxy.Packet.Valid_Next (Ctx.P.SPDM_Packet_Ctx, SPDM_Proxy.Packet.F_Data) then
         if SPDM_Emu.Platform_Port.Valid_Length (Ctx.P.Emu_Packet_Ctx, SPDM_Emu.Platform_Port.F_SPDM_Payload, RFLX_Types.To_Length (SPDM_Proxy.Packet.Field_Size (Ctx.P.SPDM_Packet_Ctx, SPDM_Proxy.Packet.F_Data))) then
            if SPDM_Proxy.Packet.Structural_Valid (Ctx.P.SPDM_Packet_Ctx, SPDM_Proxy.Packet.F_Data) then
               declare
                  pragma Warnings (Off, "is not modified, could be declared constant");
                  RFLX_Ctx_P_SPDM_Packet_Ctx_Tmp : SPDM_Proxy.Packet.Context := Ctx.P.SPDM_Packet_Ctx;
                  pragma Warnings (On, "is not modified, could be declared constant");
                  function RFLX_Process_Data_Pre (Length : RFLX_Types.Length) return Boolean is
                    (SPDM_Proxy.Packet.Has_Buffer (RFLX_Ctx_P_SPDM_Packet_Ctx_Tmp)
                     and then SPDM_Proxy.Packet.Structural_Valid (RFLX_Ctx_P_SPDM_Packet_Ctx_Tmp, SPDM_Proxy.Packet.F_Data)
                     and then Length = RFLX_Types.To_Length (SPDM_Proxy.Packet.Field_Size (RFLX_Ctx_P_SPDM_Packet_Ctx_Tmp, SPDM_Proxy.Packet.F_Data)));
                  procedure RFLX_Process_Data (Data : out RFLX_Types.Bytes) with
                    Pre =>
                      RFLX_Process_Data_Pre (Data'Length)
                  is
                  begin
                     SPDM_Proxy.Packet.Get_Data (RFLX_Ctx_P_SPDM_Packet_Ctx_Tmp, Data);
                  end RFLX_Process_Data;
                  procedure RFLX_SPDM_Emu_Platform_Port_Set_SPDM_Payload is new SPDM_Emu.Platform_Port.Generic_Set_SPDM_Payload (RFLX_Process_Data, RFLX_Process_Data_Pre);
               begin
                  RFLX_SPDM_Emu_Platform_Port_Set_SPDM_Payload (Ctx.P.Emu_Packet_Ctx, RFLX_Types.To_Length (SPDM_Proxy.Packet.Field_Size (RFLX_Ctx_P_SPDM_Packet_Ctx_Tmp, SPDM_Proxy.Packet.F_Data)));
                  Ctx.P.SPDM_Packet_Ctx := RFLX_Ctx_P_SPDM_Packet_Ctx_Tmp;
               end;
            else
               Ctx.P.Next_State := S_Proxy_Error;
               pragma Assert (Proxy_Prepare_Response_Invariant);
               goto Finalize_Proxy_Prepare_Response;
            end if;
         else
            Ctx.P.Next_State := S_Proxy_Error;
            pragma Assert (Proxy_Prepare_Response_Invariant);
            goto Finalize_Proxy_Prepare_Response;
         end if;
      else
         Ctx.P.Next_State := S_Proxy_Error;
         pragma Assert (Proxy_Prepare_Response_Invariant);
         goto Finalize_Proxy_Prepare_Response;
      end if;
      Ctx.P.Next_State := S_Proxy_Send_Response;
      pragma Assert (Proxy_Prepare_Response_Invariant);
      <<Finalize_Proxy_Prepare_Response>>
   end Proxy_Prepare_Response;

   procedure Proxy_Send_Response (Ctx : in out Context'Class) with
     Pre =>
       Initialized (Ctx),
     Post =>
       Initialized (Ctx)
   is
      function Proxy_Send_Response_Invariant return Boolean is
        (Ctx.P.Slots.Slot_Ptr_1 = null
         and Ctx.P.Slots.Slot_Ptr_2 = null)
       with
        Annotate =>
          (GNATprove, Inline_For_Proof),
        Ghost;
   begin
      pragma Assert (Proxy_Send_Response_Invariant);
      --  build/specs/CHALLENGE_AUTH=False,KEY_EXCHANGE=False,RESPOND_IF_READY=False/spdm_proxy.rflx:77:10
      Ctx.P.Next_State := S_Proxy_Receive_Request;
      pragma Assert (Proxy_Send_Response_Invariant);
   end Proxy_Send_Response;

   procedure Proxy_Prepare_Shutdown (Ctx : in out Context'Class) with
     Pre =>
       Initialized (Ctx),
     Post =>
       Initialized (Ctx)
   is
      function Proxy_Prepare_Shutdown_Invariant return Boolean is
        (Ctx.P.Slots.Slot_Ptr_1 = null
         and Ctx.P.Slots.Slot_Ptr_2 = null)
       with
        Annotate =>
          (GNATprove, Inline_For_Proof),
        Ghost;
   begin
      pragma Assert (Proxy_Prepare_Shutdown_Invariant);
      --  build/specs/CHALLENGE_AUTH=False,KEY_EXCHANGE=False,RESPOND_IF_READY=False/spdm_proxy.rflx:85:10
      SPDM_Emu.Platform_Port.Reset (Ctx.P.Emu_Packet_Ctx);
      if SPDM_Emu.Platform_Port.Available_Space (Ctx.P.Emu_Packet_Ctx, SPDM_Emu.Platform_Port.F_Command) < 96 then
         Ctx.P.Next_State := S_Proxy_Error;
         pragma Assert (Proxy_Prepare_Shutdown_Invariant);
         goto Finalize_Proxy_Prepare_Shutdown;
      end if;
      pragma Assert (SPDM_Emu.Platform_Port.Sufficient_Space (Ctx.P.Emu_Packet_Ctx, SPDM_Emu.Platform_Port.F_Command));
      SPDM_Emu.Platform_Port.Set_Command (Ctx.P.Emu_Packet_Ctx, SPDM_Emu.Shutdown);
      pragma Assert (SPDM_Emu.Platform_Port.Sufficient_Space (Ctx.P.Emu_Packet_Ctx, SPDM_Emu.Platform_Port.F_Transport_Type));
      SPDM_Emu.Platform_Port.Set_Transport_Type (Ctx.P.Emu_Packet_Ctx, SPDM_Emu.None);
      pragma Assert (SPDM_Emu.Platform_Port.Sufficient_Space (Ctx.P.Emu_Packet_Ctx, SPDM_Emu.Platform_Port.F_Size));
      SPDM_Emu.Platform_Port.Set_Size (Ctx.P.Emu_Packet_Ctx, 0);
      if SPDM_Emu.Platform_Port.Valid_Length (Ctx.P.Emu_Packet_Ctx, SPDM_Emu.Platform_Port.F_SPDM_Payload, RFLX_Types.To_Length (0 * RFLX_Types.Byte'Size)) then
         SPDM_Emu.Platform_Port.Set_SPDM_Payload_Empty (Ctx.P.Emu_Packet_Ctx);
      else
         Ctx.P.Next_State := S_Proxy_Error;
         pragma Assert (Proxy_Prepare_Shutdown_Invariant);
         goto Finalize_Proxy_Prepare_Shutdown;
      end if;
      Ctx.P.Next_State := S_Proxy_Send_Shutdown;
      pragma Assert (Proxy_Prepare_Shutdown_Invariant);
      <<Finalize_Proxy_Prepare_Shutdown>>
   end Proxy_Prepare_Shutdown;

   procedure Proxy_Send_Shutdown (Ctx : in out Context'Class) with
     Pre =>
       Initialized (Ctx),
     Post =>
       Initialized (Ctx)
   is
      function Proxy_Send_Shutdown_Invariant return Boolean is
        (Ctx.P.Slots.Slot_Ptr_1 = null
         and Ctx.P.Slots.Slot_Ptr_2 = null)
       with
        Annotate =>
          (GNATprove, Inline_For_Proof),
        Ghost;
   begin
      pragma Assert (Proxy_Send_Shutdown_Invariant);
      --  build/specs/CHALLENGE_AUTH=False,KEY_EXCHANGE=False,RESPOND_IF_READY=False/spdm_proxy.rflx:98:10
      Ctx.P.Next_State := S_Proxy_Shutdown;
      pragma Assert (Proxy_Send_Shutdown_Invariant);
   end Proxy_Send_Shutdown;

   procedure Proxy_Error (Ctx : in out Context'Class) with
     Pre =>
       Initialized (Ctx),
     Post =>
       Initialized (Ctx)
   is
      function Proxy_Error_Invariant return Boolean is
        (Ctx.P.Slots.Slot_Ptr_1 = null
         and Ctx.P.Slots.Slot_Ptr_2 = null)
       with
        Annotate =>
          (GNATprove, Inline_For_Proof),
        Ghost;
   begin
      pragma Assert (Proxy_Error_Invariant);
      Ctx.P.Next_State := S_Proxy_Shutdown;
      pragma Assert (Proxy_Error_Invariant);
   end Proxy_Error;

   procedure Initialize (Ctx : in out Context'Class) is
      Emu_Packet_Buffer : RFLX_Types.Bytes_Ptr;
      SPDM_Packet_Buffer : RFLX_Types.Bytes_Ptr;
   begin
      SPDM_Proxy.Proxy_Allocator.Initialize (Ctx.P.Slots, Ctx.P.Memory);
      Emu_Packet_Buffer := Ctx.P.Slots.Slot_Ptr_1;
      pragma Warnings (Off, "unused assignment");
      Ctx.P.Slots.Slot_Ptr_1 := null;
      pragma Warnings (On, "unused assignment");
      SPDM_Emu.Platform_Port.Initialize (Ctx.P.Emu_Packet_Ctx, Emu_Packet_Buffer);
      SPDM_Packet_Buffer := Ctx.P.Slots.Slot_Ptr_2;
      pragma Warnings (Off, "unused assignment");
      Ctx.P.Slots.Slot_Ptr_2 := null;
      pragma Warnings (On, "unused assignment");
      SPDM_Proxy.Packet.Initialize (Ctx.P.SPDM_Packet_Ctx, SPDM_Packet_Buffer);
      Ctx.P.Next_State := S_Proxy_Receive_Request;
   end Initialize;

   procedure Finalize (Ctx : in out Context'Class) is
      Emu_Packet_Buffer : RFLX_Types.Bytes_Ptr;
      SPDM_Packet_Buffer : RFLX_Types.Bytes_Ptr;
   begin
      pragma Warnings (Off, """Ctx.P.Emu_Packet_Ctx"" is set by ""Take_Buffer"" but not used after the call");
      SPDM_Emu.Platform_Port.Take_Buffer (Ctx.P.Emu_Packet_Ctx, Emu_Packet_Buffer);
      pragma Warnings (On, """Ctx.P.Emu_Packet_Ctx"" is set by ""Take_Buffer"" but not used after the call");
      pragma Assert (Ctx.P.Slots.Slot_Ptr_1 = null);
      pragma Assert (Emu_Packet_Buffer /= null);
      Ctx.P.Slots.Slot_Ptr_1 := Emu_Packet_Buffer;
      pragma Assert (Ctx.P.Slots.Slot_Ptr_1 /= null);
      pragma Warnings (Off, """Ctx.P.SPDM_Packet_Ctx"" is set by ""Take_Buffer"" but not used after the call");
      SPDM_Proxy.Packet.Take_Buffer (Ctx.P.SPDM_Packet_Ctx, SPDM_Packet_Buffer);
      pragma Warnings (On, """Ctx.P.SPDM_Packet_Ctx"" is set by ""Take_Buffer"" but not used after the call");
      pragma Assert (Ctx.P.Slots.Slot_Ptr_2 = null);
      pragma Assert (SPDM_Packet_Buffer /= null);
      Ctx.P.Slots.Slot_Ptr_2 := SPDM_Packet_Buffer;
      pragma Assert (Ctx.P.Slots.Slot_Ptr_2 /= null);
      SPDM_Proxy.Proxy_Allocator.Finalize (Ctx.P.Slots);
      Ctx.P.Next_State := S_Proxy_Shutdown;
   end Finalize;

   procedure Reset_Messages_Before_Write (Ctx : in out Context'Class) with
     Pre =>
       Initialized (Ctx),
     Post =>
       Initialized (Ctx)
   is
   begin
      case Ctx.P.Next_State is
         when S_Proxy_Receive_Request =>
            SPDM_Emu.Platform_Port.Reset (Ctx.P.Emu_Packet_Ctx, Ctx.P.Emu_Packet_Ctx.First, Ctx.P.Emu_Packet_Ctx.First - 1);
         when S_Proxy_Prepare_Request | S_Proxy_Send_Request =>
            null;
         when S_Proxy_Receive_Response =>
            SPDM_Proxy.Packet.Reset (Ctx.P.SPDM_Packet_Ctx, Ctx.P.SPDM_Packet_Ctx.First, Ctx.P.SPDM_Packet_Ctx.First - 1);
         when S_Proxy_Prepare_Response | S_Proxy_Send_Response | S_Proxy_Prepare_Shutdown | S_Proxy_Send_Shutdown | S_Proxy_Error | S_Proxy_Shutdown =>
            null;
      end case;
   end Reset_Messages_Before_Write;

   procedure Tick (Ctx : in out Context'Class) is
   begin
      case Ctx.P.Next_State is
         when S_Proxy_Receive_Request =>
            Proxy_Receive_Request (Ctx);
         when S_Proxy_Prepare_Request =>
            Proxy_Prepare_Request (Ctx);
         when S_Proxy_Send_Request =>
            Proxy_Send_Request (Ctx);
         when S_Proxy_Receive_Response =>
            Proxy_Receive_Response (Ctx);
         when S_Proxy_Prepare_Response =>
            Proxy_Prepare_Response (Ctx);
         when S_Proxy_Send_Response =>
            Proxy_Send_Response (Ctx);
         when S_Proxy_Prepare_Shutdown =>
            Proxy_Prepare_Shutdown (Ctx);
         when S_Proxy_Send_Shutdown =>
            Proxy_Send_Shutdown (Ctx);
         when S_Proxy_Error =>
            Proxy_Error (Ctx);
         when S_Proxy_Shutdown =>
            null;
      end case;
      Reset_Messages_Before_Write (Ctx);
   end Tick;

   function In_IO_State (Ctx : Context'Class) return Boolean is
     (Ctx.P.Next_State in S_Proxy_Receive_Request | S_Proxy_Send_Request | S_Proxy_Receive_Response | S_Proxy_Send_Response | S_Proxy_Send_Shutdown);

   procedure Run (Ctx : in out Context'Class) is
   begin
      Tick (Ctx);
      while
         Active (Ctx)
         and not In_IO_State (Ctx)
      loop
         pragma Loop_Invariant (Initialized (Ctx));
         Tick (Ctx);
      end loop;
   end Run;

   procedure Read (Ctx : Context'Class; Chan : Channel; Buffer : out RFLX_Types.Bytes; Offset : RFLX_Types.Length := 0) is
      function Read_Pre (Message_Buffer : RFLX_Types.Bytes) return Boolean is
        (Buffer'Length > 0
         and then Offset < Message_Buffer'Length);
      procedure Read (Message_Buffer : RFLX_Types.Bytes) with
        Pre =>
          Read_Pre (Message_Buffer)
      is
         Length : constant RFLX_Types.Index := RFLX_Types.Index (RFLX_Types.Length'Min (Buffer'Length, Message_Buffer'Length - Offset));
         Buffer_Last : constant RFLX_Types.Index := Buffer'First - 1 + Length;
      begin
         Buffer (Buffer'First .. RFLX_Types.Index (Buffer_Last)) := Message_Buffer (RFLX_Types.Index (RFLX_Types.Length (Message_Buffer'First) + Offset) .. Message_Buffer'First - 2 + RFLX_Types.Index (Offset + 1) + Length);
      end Read;
      procedure SPDM_Emu_Platform_Port_Read is new SPDM_Emu.Platform_Port.Generic_Read (Read, Read_Pre);
      procedure SPDM_Proxy_Packet_Read is new SPDM_Proxy.Packet.Generic_Read (Read, Read_Pre);
   begin
      Buffer := [others => 0];
      case Chan is
         when C_Emu_Transport =>
            case Ctx.P.Next_State is
               when S_Proxy_Send_Response | S_Proxy_Send_Shutdown =>
                  SPDM_Emu_Platform_Port_Read (Ctx.P.Emu_Packet_Ctx);
               when others =>
                  pragma Warnings (Off, "unreachable code");
                  null;
                  pragma Warnings (On, "unreachable code");
            end case;
         when C_SPDM_Transport =>
            case Ctx.P.Next_State is
               when S_Proxy_Send_Request =>
                  SPDM_Proxy_Packet_Read (Ctx.P.SPDM_Packet_Ctx);
               when others =>
                  pragma Warnings (Off, "unreachable code");
                  null;
                  pragma Warnings (On, "unreachable code");
            end case;
      end case;
   end Read;

   procedure Write (Ctx : in out Context'Class; Chan : Channel; Buffer : RFLX_Types.Bytes; Offset : RFLX_Types.Length := 0) is
      Write_Buffer_Length : constant RFLX_Types.Length := Write_Buffer_Size (Ctx, Chan);
      function Write_Pre (Context_Buffer_Length : RFLX_Types.Length; Offset : RFLX_Types.Length) return Boolean is
        (Buffer'Length > 0
         and then Context_Buffer_Length = Write_Buffer_Length
         and then Offset <= RFLX_Types.Length'Last - Buffer'Length
         and then Buffer'Length + Offset <= Write_Buffer_Length);
      procedure Write (Message_Buffer : out RFLX_Types.Bytes; Length : out RFLX_Types.Length; Context_Buffer_Length : RFLX_Types.Length; Offset : RFLX_Types.Length) with
        Pre =>
          Write_Pre (Context_Buffer_Length, Offset)
          and then Offset <= RFLX_Types.Length'Last - Message_Buffer'Length
          and then Message_Buffer'Length + Offset = Write_Buffer_Length,
        Post =>
          Length <= Message_Buffer'Length
      is
      begin
         Length := Buffer'Length;
         Message_Buffer := [others => 0];
         Message_Buffer (Message_Buffer'First .. RFLX_Types.Index (RFLX_Types.Length (Message_Buffer'First) - 1 + Length)) := Buffer;
      end Write;
      procedure SPDM_Emu_Platform_Port_Write is new SPDM_Emu.Platform_Port.Generic_Write (Write, Write_Pre);
      procedure SPDM_Proxy_Packet_Write is new SPDM_Proxy.Packet.Generic_Write (Write, Write_Pre);
   begin
      case Chan is
         when C_Emu_Transport =>
            case Ctx.P.Next_State is
               when S_Proxy_Receive_Request =>
                  SPDM_Emu_Platform_Port_Write (Ctx.P.Emu_Packet_Ctx, Offset);
               when others =>
                  pragma Warnings (Off, "unreachable code");
                  null;
                  pragma Warnings (On, "unreachable code");
            end case;
         when C_SPDM_Transport =>
            case Ctx.P.Next_State is
               when S_Proxy_Receive_Response =>
                  SPDM_Proxy_Packet_Write (Ctx.P.SPDM_Packet_Ctx, Offset);
               when others =>
                  pragma Warnings (Off, "unreachable code");
                  null;
                  pragma Warnings (On, "unreachable code");
            end case;
      end case;
   end Write;

end RFLX.SPDM_Proxy.Proxy;
