--
--  Generated by RecordFlux 0.6.1.dev1+g8b82b38a0 on 2022-12-02
--
--  Copyright (C) 2018-2022 AdaCore
--
--  SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
--

pragma Style_Checks ("N3aAbcdefhiIklnOprStux");
pragma Warnings (Off, "redundant conversion");
with RFLX.RFLX_Types;
with RFLX.RFLX_Builtin_Types;
with RFLX.RFLX_Builtin_Types.Conversions;
use RFLX.RFLX_Builtin_Types.Conversions;
with RFLX.SPDM.Measurement_Record;

package RFLX.SPDM.Measurements_Response with
  SPARK_Mode,
  Annotate =>
    (GNATprove, Always_Return)
is

   pragma Warnings (Off, "use clause for type ""Base_Integer"" * has no effect");

   pragma Warnings (Off, "use clause for type ""Bytes"" * has no effect");

   pragma Warnings (Off, """BASE_INTEGER"" is already use-visible through previous use_type_clause");

   pragma Warnings (Off, """LENGTH"" is already use-visible through previous use_type_clause");

   use type RFLX_Types.Bytes;

   use type RFLX_Types.Byte;

   use type RFLX_Types.Bytes_Ptr;

   use type RFLX_Types.Length;

   use type RFLX_Types.Index;

   use type RFLX_Types.Bit_Index;

   use type RFLX_Types.Base_Integer;

   use type RFLX_Types.Offset;

   pragma Warnings (On, """LENGTH"" is already use-visible through previous use_type_clause");

   pragma Warnings (On, """BASE_INTEGER"" is already use-visible through previous use_type_clause");

   pragma Warnings (On, "use clause for type ""Base_Integer"" * has no effect");

   pragma Warnings (On, "use clause for type ""Bytes"" * has no effect");

   pragma Unevaluated_Use_Of_Old (Allow);

   type Virtual_Field is (F_Initial, F_Number_Of_Indices, F_Reserved_1, F_Slot_ID, F_Number_Of_Blocks, F_Measurement_Record_Length, F_Measurement_Record, F_Nonce_Data, F_Opaque_Length, F_Opaque_Data, F_Signature, F_Final);

   subtype Field is Virtual_Field range F_Number_Of_Indices .. F_Signature;

   type Field_Cursor is private with
     Default_Initial_Condition =>
       False;

   type Field_Cursors is private with
     Default_Initial_Condition =>
       False;

   type Context (Buffer_First, Buffer_Last : RFLX_Types.Index := RFLX_Types.Index'First; First : RFLX_Types.Bit_Index := RFLX_Types.Bit_Index'First; Last : RFLX_Types.Bit_Length := RFLX_Types.Bit_Length'First; Signature_Length : SPDM.Signature_Length := SPDM.Signature_Length'First; Has_Signature : Boolean := Boolean'First) is private with
     Default_Initial_Condition =>
       RFLX_Types.To_Index (First) >= Buffer_First
       and RFLX_Types.To_Index (Last) <= Buffer_Last
       and Buffer_Last < RFLX_Types.Index'Last
       and First <= Last + 1
       and Last < RFLX_Types.Bit_Index'Last
       and First rem RFLX_Types.Byte'Size = 1
       and Last rem RFLX_Types.Byte'Size = 0;

   procedure Initialize (Ctx : out Context; Buffer : in out RFLX_Types.Bytes_Ptr; Signature_Length : SPDM.Signature_Length; Has_Signature : Boolean; Written_Last : RFLX_Types.Bit_Length := 0) with
     Pre =>
       not Ctx'Constrained
       and then Buffer /= null
       and then Buffer'Length > 0
       and then Buffer'Last < RFLX_Types.Index'Last
       and then (Written_Last = 0
                 or (Written_Last >= RFLX_Types.To_First_Bit_Index (Buffer'First) - 1
                     and Written_Last <= RFLX_Types.To_Last_Bit_Index (Buffer'Last)))
       and then Written_Last mod RFLX_Types.Byte'Size = 0,
     Post =>
       Has_Buffer (Ctx)
       and Buffer = null
       and Ctx.Buffer_First = Buffer'First'Old
       and Ctx.Buffer_Last = Buffer'Last'Old
       and Ctx.First = RFLX_Types.To_First_Bit_Index (Ctx.Buffer_First)
       and Ctx.Last = RFLX_Types.To_Last_Bit_Index (Ctx.Buffer_Last)
       and Ctx.Signature_Length = Signature_Length
       and Ctx.Has_Signature = Has_Signature
       and Initialized (Ctx),
     Depends =>
       (Ctx => (Buffer, Signature_Length, Has_Signature, Written_Last), Buffer => null);

   procedure Initialize (Ctx : out Context; Buffer : in out RFLX_Types.Bytes_Ptr; First : RFLX_Types.Bit_Index; Last : RFLX_Types.Bit_Length; Signature_Length : SPDM.Signature_Length; Has_Signature : Boolean; Written_Last : RFLX_Types.Bit_Length := 0) with
     Pre =>
       not Ctx'Constrained
       and then Buffer /= null
       and then Buffer'Length > 0
       and then Buffer'Last < RFLX_Types.Index'Last
       and then RFLX_Types.To_Index (First) >= Buffer'First
       and then RFLX_Types.To_Index (Last) <= Buffer'Last
       and then First <= Last + 1
       and then Last < RFLX_Types.Bit_Index'Last
       and then First rem RFLX_Types.Byte'Size = 1
       and then Last rem RFLX_Types.Byte'Size = 0
       and then (Written_Last = 0
                 or (Written_Last >= First - 1
                     and Written_Last <= Last))
       and then Written_Last rem RFLX_Types.Byte'Size = 0,
     Post =>
       Buffer = null
       and Has_Buffer (Ctx)
       and Ctx.Buffer_First = Buffer'First'Old
       and Ctx.Buffer_Last = Buffer'Last'Old
       and Ctx.First = First
       and Ctx.Last = Last
       and Ctx.Signature_Length = Signature_Length
       and Ctx.Has_Signature = Has_Signature
       and Initialized (Ctx),
     Depends =>
       (Ctx => (Buffer, First, Last, Signature_Length, Has_Signature, Written_Last), Buffer => null);

   pragma Warnings (Off, "postcondition does not mention function result");

   function Initialized (Ctx : Context) return Boolean with
     Post =>
       True;

   pragma Warnings (On, "postcondition does not mention function result");

   procedure Reset (Ctx : in out Context; Signature_Length : SPDM.Signature_Length; Has_Signature : Boolean) with
     Pre =>
       not Ctx'Constrained
       and RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx),
     Post =>
       Has_Buffer (Ctx)
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = RFLX_Types.To_First_Bit_Index (Ctx.Buffer_First)
       and Ctx.Last = RFLX_Types.To_Last_Bit_Index (Ctx.Buffer_Last)
       and Ctx.Signature_Length = Signature_Length
       and Ctx.Has_Signature = Has_Signature
       and Initialized (Ctx);

   procedure Reset (Ctx : in out Context; First : RFLX_Types.Bit_Index; Last : RFLX_Types.Bit_Length; Signature_Length : SPDM.Signature_Length; Has_Signature : Boolean) with
     Pre =>
       not Ctx'Constrained
       and RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx)
       and RFLX_Types.To_Index (First) >= Ctx.Buffer_First
       and RFLX_Types.To_Index (Last) <= Ctx.Buffer_Last
       and First <= Last + 1
       and Last < RFLX_Types.Bit_Length'Last
       and First rem RFLX_Types.Byte'Size = 1
       and Last rem RFLX_Types.Byte'Size = 0,
     Post =>
       Has_Buffer (Ctx)
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = First
       and Ctx.Last = Last
       and Ctx.Signature_Length = Signature_Length
       and Ctx.Has_Signature = Has_Signature
       and Initialized (Ctx);

   procedure Take_Buffer (Ctx : in out Context; Buffer : out RFLX_Types.Bytes_Ptr) with
     Pre =>
       RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx),
     Post =>
       not Has_Buffer (Ctx)
       and Buffer /= null
       and Ctx.Buffer_First = Buffer'First
       and Ctx.Buffer_Last = Buffer'Last
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = Ctx.First'Old
       and Ctx.Last = Ctx.Last'Old
       and Ctx.Signature_Length = Ctx.Signature_Length'Old
       and Ctx.Has_Signature = Ctx.Has_Signature'Old
       and Context_Cursors (Ctx) = Context_Cursors (Ctx)'Old,
     Depends =>
       (Ctx => Ctx, Buffer => Ctx);

   procedure Copy (Ctx : Context; Buffer : out RFLX_Types.Bytes) with
     Pre =>
       RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx)
       and then RFLX.SPDM.Measurements_Response.Structural_Valid_Message (Ctx)
       and then RFLX.SPDM.Measurements_Response.Byte_Size (Ctx) = Buffer'Length;

   function Read (Ctx : Context) return RFLX_Types.Bytes with
     Ghost,
     Pre =>
       RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx)
       and then RFLX.SPDM.Measurements_Response.Structural_Valid_Message (Ctx);

   pragma Warnings (Off, "formal parameter ""*"" is not referenced");

   function Always_Valid (Buffer : RFLX_Types.Bytes) return Boolean is
     (True);

   pragma Warnings (On, "formal parameter ""*"" is not referenced");

   generic
      with procedure Read (Buffer : RFLX_Types.Bytes);
      with function Pre (Buffer : RFLX_Types.Bytes) return Boolean is Always_Valid;
   procedure Generic_Read (Ctx : Context) with
     Pre =>
       RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx)
       and then RFLX.SPDM.Measurements_Response.Structural_Valid_Message (Ctx)
       and then Pre (Read (Ctx));

   pragma Warnings (Off, "formal parameter ""*"" is not referenced");

   function Always_Valid (Context_Buffer_Length : RFLX_Types.Length; Offset : RFLX_Types.Length) return Boolean is
     (True);

   pragma Warnings (On, "formal parameter ""*"" is not referenced");

   generic
      with procedure Write (Buffer : out RFLX_Types.Bytes; Length : out RFLX_Types.Length; Context_Buffer_Length : RFLX_Types.Length; Offset : RFLX_Types.Length);
      with function Pre (Context_Buffer_Length : RFLX_Types.Length; Offset : RFLX_Types.Length) return Boolean is Always_Valid;
   procedure Generic_Write (Ctx : in out Context; Offset : RFLX_Types.Length := 0) with
     Pre =>
       not Ctx'Constrained
       and then RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx)
       and then Offset < RFLX.SPDM.Measurements_Response.Buffer_Length (Ctx)
       and then Pre (RFLX.SPDM.Measurements_Response.Buffer_Length (Ctx), Offset),
     Post =>
       Has_Buffer (Ctx)
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = RFLX_Types.To_First_Bit_Index (Ctx.Buffer_First)
       and Initialized (Ctx);

   function Has_Buffer (Ctx : Context) return Boolean;

   function Buffer_Length (Ctx : Context) return RFLX_Types.Length with
     Pre =>
       RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx);

   function Size (Ctx : Context) return RFLX_Types.Bit_Length with
     Post =>
       Size'Result rem RFLX_Types.Byte'Size = 0;

   function Byte_Size (Ctx : Context) return RFLX_Types.Length;

   function Message_Last (Ctx : Context) return RFLX_Types.Bit_Length with
     Pre =>
       RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx)
       and then RFLX.SPDM.Measurements_Response.Structural_Valid_Message (Ctx);

   function Written_Last (Ctx : Context) return RFLX_Types.Bit_Length;

   procedure Data (Ctx : Context; Data : out RFLX_Types.Bytes) with
     Pre =>
       RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx)
       and then RFLX.SPDM.Measurements_Response.Structural_Valid_Message (Ctx)
       and then Data'Length = RFLX.SPDM.Measurements_Response.Byte_Size (Ctx);

   pragma Warnings (Off, "postcondition does not mention function result");

   function Valid_Value (Fld : Field; Val : RFLX_Types.Base_Integer) return Boolean with
     Post =>
       True;

   pragma Warnings (On, "postcondition does not mention function result");

   pragma Warnings (Off, "postcondition does not mention function result");

   function Path_Condition (Ctx : Context; Fld : Field) return Boolean with
     Pre =>
       RFLX.SPDM.Measurements_Response.Valid_Predecessor (Ctx, Fld),
     Post =>
       True;

   pragma Warnings (On, "postcondition does not mention function result");

   pragma Warnings (Off, "postcondition does not mention function result");

   function Field_Condition (Ctx : Context; Fld : Field) return Boolean with
     Pre =>
       RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx)
       and then RFLX.SPDM.Measurements_Response.Valid_Predecessor (Ctx, Fld)
       and then RFLX.SPDM.Measurements_Response.Valid_Next (Ctx, Fld)
       and then RFLX.SPDM.Measurements_Response.Sufficient_Space (Ctx, Fld),
     Post =>
       True;

   pragma Warnings (On, "postcondition does not mention function result");

   function Field_Size (Ctx : Context; Fld : Field) return RFLX_Types.Bit_Length with
     Pre =>
       RFLX.SPDM.Measurements_Response.Valid_Next (Ctx, Fld),
     Post =>
       (case Fld is
           when F_Measurement_Record | F_Nonce_Data | F_Opaque_Data | F_Signature =>
              Field_Size'Result rem RFLX_Types.Byte'Size = 0,
           when others =>
              True);

   pragma Warnings (Off, "postcondition does not mention function result");

   function Field_First (Ctx : Context; Fld : Field) return RFLX_Types.Bit_Index with
     Pre =>
       RFLX.SPDM.Measurements_Response.Valid_Next (Ctx, Fld),
     Post =>
       True;

   pragma Warnings (On, "postcondition does not mention function result");

   function Field_Last (Ctx : Context; Fld : Field) return RFLX_Types.Bit_Length with
     Pre =>
       RFLX.SPDM.Measurements_Response.Valid_Next (Ctx, Fld)
       and then RFLX.SPDM.Measurements_Response.Sufficient_Space (Ctx, Fld),
     Post =>
       (case Fld is
           when F_Measurement_Record | F_Nonce_Data | F_Opaque_Data | F_Signature =>
              Field_Last'Result rem RFLX_Types.Byte'Size = 0,
           when others =>
              True);

   pragma Warnings (Off, "postcondition does not mention function result");

   function Predecessor (Ctx : Context; Fld : Virtual_Field) return Virtual_Field with
     Post =>
       True;

   pragma Warnings (On, "postcondition does not mention function result");

   pragma Warnings (Off, "postcondition does not mention function result");

   function Valid_Predecessor (Ctx : Context; Fld : Virtual_Field) return Boolean with
     Post =>
       True;

   pragma Warnings (On, "postcondition does not mention function result");

   function Valid_Next (Ctx : Context; Fld : Field) return Boolean;

   function Available_Space (Ctx : Context; Fld : Field) return RFLX_Types.Bit_Length with
     Pre =>
       RFLX.SPDM.Measurements_Response.Valid_Next (Ctx, Fld);

   function Sufficient_Space (Ctx : Context; Fld : Field) return Boolean with
     Pre =>
       RFLX.SPDM.Measurements_Response.Valid_Next (Ctx, Fld);

   function Equal (Ctx : Context; Fld : Field; Data : RFLX_Types.Bytes) return Boolean with
     Pre =>
       RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx)
       and RFLX.SPDM.Measurements_Response.Valid_Next (Ctx, Fld);

   procedure Verify (Ctx : in out Context; Fld : Field) with
     Pre =>
       RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx),
     Post =>
       Has_Buffer (Ctx)
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = Ctx.First'Old
       and Ctx.Last = Ctx.Last'Old
       and Ctx.Signature_Length = Ctx.Signature_Length'Old
       and Ctx.Has_Signature = Ctx.Has_Signature'Old;

   procedure Verify_Message (Ctx : in out Context) with
     Pre =>
       RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx),
     Post =>
       Has_Buffer (Ctx)
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = Ctx.First'Old
       and Ctx.Last = Ctx.Last'Old
       and Ctx.Signature_Length = Ctx.Signature_Length'Old
       and Ctx.Has_Signature = Ctx.Has_Signature'Old;

   function Present (Ctx : Context; Fld : Field) return Boolean;

   function Structural_Valid (Ctx : Context; Fld : Field) return Boolean;

   function Valid (Ctx : Context; Fld : Field) return Boolean with
     Post =>
       (if Valid'Result then Structural_Valid (Ctx, Fld) and Present (Ctx, Fld));

   function Incomplete (Ctx : Context; Fld : Field) return Boolean;

   function Invalid (Ctx : Context; Fld : Field) return Boolean;

   function Structural_Valid_Message (Ctx : Context) return Boolean with
     Pre =>
       RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx);

   function Valid_Message (Ctx : Context) return Boolean with
     Pre =>
       RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx);

   pragma Warnings (Off, "postcondition does not mention function result");

   function Incomplete_Message (Ctx : Context) return Boolean with
     Post =>
       True;

   pragma Warnings (On, "postcondition does not mention function result");

   pragma Warnings (Off, "precondition is always False");

   function Get_Number_Of_Indices (Ctx : Context) return RFLX.SPDM.Measurement_Count with
     Pre =>
       RFLX.SPDM.Measurements_Response.Valid (Ctx, RFLX.SPDM.Measurements_Response.F_Number_Of_Indices);

   function Get_Reserved_1 (Ctx : Context) return RFLX.SPDM.Reserved_4 with
     Pre =>
       RFLX.SPDM.Measurements_Response.Valid (Ctx, RFLX.SPDM.Measurements_Response.F_Reserved_1);

   function Get_Slot_ID (Ctx : Context) return RFLX.SPDM.Narrow_Slot with
     Pre =>
       RFLX.SPDM.Measurements_Response.Valid (Ctx, RFLX.SPDM.Measurements_Response.F_Slot_ID);

   function Get_Number_Of_Blocks (Ctx : Context) return RFLX.SPDM.Block_Count with
     Pre =>
       RFLX.SPDM.Measurements_Response.Valid (Ctx, RFLX.SPDM.Measurements_Response.F_Number_Of_Blocks);

   function Get_Measurement_Record_Length (Ctx : Context) return RFLX.SPDM.Length_24 with
     Pre =>
       RFLX.SPDM.Measurements_Response.Valid (Ctx, RFLX.SPDM.Measurements_Response.F_Measurement_Record_Length);

   function Get_Opaque_Length (Ctx : Context) return RFLX.SPDM.Length_16 with
     Pre =>
       RFLX.SPDM.Measurements_Response.Valid (Ctx, RFLX.SPDM.Measurements_Response.F_Opaque_Length);

   pragma Warnings (On, "precondition is always False");

   function Get_Nonce_Data (Ctx : Context) return RFLX_Types.Bytes with
     Ghost,
     Pre =>
       RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx)
       and then RFLX.SPDM.Measurements_Response.Structural_Valid (Ctx, RFLX.SPDM.Measurements_Response.F_Nonce_Data)
       and then RFLX.SPDM.Measurements_Response.Valid_Next (Ctx, RFLX.SPDM.Measurements_Response.F_Nonce_Data),
     Post =>
       Get_Nonce_Data'Result'Length = RFLX_Types.To_Length (Field_Size (Ctx, F_Nonce_Data));

   function Get_Opaque_Data (Ctx : Context) return RFLX_Types.Bytes with
     Ghost,
     Pre =>
       RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx)
       and then RFLX.SPDM.Measurements_Response.Structural_Valid (Ctx, RFLX.SPDM.Measurements_Response.F_Opaque_Data)
       and then RFLX.SPDM.Measurements_Response.Valid_Next (Ctx, RFLX.SPDM.Measurements_Response.F_Opaque_Data),
     Post =>
       Get_Opaque_Data'Result'Length = RFLX_Types.To_Length (Field_Size (Ctx, F_Opaque_Data));

   function Get_Signature (Ctx : Context) return RFLX_Types.Bytes with
     Ghost,
     Pre =>
       RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx)
       and then RFLX.SPDM.Measurements_Response.Structural_Valid (Ctx, RFLX.SPDM.Measurements_Response.F_Signature)
       and then RFLX.SPDM.Measurements_Response.Valid_Next (Ctx, RFLX.SPDM.Measurements_Response.F_Signature),
     Post =>
       Get_Signature'Result'Length = RFLX_Types.To_Length (Field_Size (Ctx, F_Signature));

   procedure Get_Nonce_Data (Ctx : Context; Data : out RFLX_Types.Bytes) with
     Pre =>
       RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx)
       and then RFLX.SPDM.Measurements_Response.Structural_Valid (Ctx, RFLX.SPDM.Measurements_Response.F_Nonce_Data)
       and then RFLX.SPDM.Measurements_Response.Valid_Next (Ctx, RFLX.SPDM.Measurements_Response.F_Nonce_Data)
       and then Data'Length = RFLX_Types.To_Length (RFLX.SPDM.Measurements_Response.Field_Size (Ctx, RFLX.SPDM.Measurements_Response.F_Nonce_Data)),
     Post =>
       Equal (Ctx, F_Nonce_Data, Data);

   procedure Get_Opaque_Data (Ctx : Context; Data : out RFLX_Types.Bytes) with
     Pre =>
       RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx)
       and then RFLX.SPDM.Measurements_Response.Structural_Valid (Ctx, RFLX.SPDM.Measurements_Response.F_Opaque_Data)
       and then RFLX.SPDM.Measurements_Response.Valid_Next (Ctx, RFLX.SPDM.Measurements_Response.F_Opaque_Data)
       and then Data'Length = RFLX_Types.To_Length (RFLX.SPDM.Measurements_Response.Field_Size (Ctx, RFLX.SPDM.Measurements_Response.F_Opaque_Data)),
     Post =>
       Equal (Ctx, F_Opaque_Data, Data);

   procedure Get_Signature (Ctx : Context; Data : out RFLX_Types.Bytes) with
     Pre =>
       RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx)
       and then RFLX.SPDM.Measurements_Response.Structural_Valid (Ctx, RFLX.SPDM.Measurements_Response.F_Signature)
       and then RFLX.SPDM.Measurements_Response.Valid_Next (Ctx, RFLX.SPDM.Measurements_Response.F_Signature)
       and then Data'Length = RFLX_Types.To_Length (RFLX.SPDM.Measurements_Response.Field_Size (Ctx, RFLX.SPDM.Measurements_Response.F_Signature)),
     Post =>
       Equal (Ctx, F_Signature, Data);

   generic
      with procedure Process_Nonce_Data (Nonce_Data : RFLX_Types.Bytes);
   procedure Generic_Get_Nonce_Data (Ctx : Context) with
     Pre =>
       RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx)
       and RFLX.SPDM.Measurements_Response.Present (Ctx, RFLX.SPDM.Measurements_Response.F_Nonce_Data);

   generic
      with procedure Process_Opaque_Data (Opaque_Data : RFLX_Types.Bytes);
   procedure Generic_Get_Opaque_Data (Ctx : Context) with
     Pre =>
       RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx)
       and RFLX.SPDM.Measurements_Response.Present (Ctx, RFLX.SPDM.Measurements_Response.F_Opaque_Data);

   generic
      with procedure Process_Signature (Signature : RFLX_Types.Bytes);
   procedure Generic_Get_Signature (Ctx : Context) with
     Pre =>
       RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx)
       and RFLX.SPDM.Measurements_Response.Present (Ctx, RFLX.SPDM.Measurements_Response.F_Signature);

   pragma Warnings (Off, "postcondition does not mention function result");

   function Valid_Length (Ctx : Context; Fld : Field; Length : RFLX_Types.Length) return Boolean with
     Pre =>
       RFLX.SPDM.Measurements_Response.Valid_Next (Ctx, Fld),
     Post =>
       True;

   pragma Warnings (On, "postcondition does not mention function result");

   pragma Warnings (Off, "aspect ""*"" not enforced on inlined subprogram ""*""");

   procedure Set_Number_Of_Indices (Ctx : in out Context; Val : RFLX.SPDM.Measurement_Count) with
     Inline_Always,
     Pre =>
       not Ctx'Constrained
       and then RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx)
       and then RFLX.SPDM.Measurements_Response.Valid_Next (Ctx, RFLX.SPDM.Measurements_Response.F_Number_Of_Indices)
       and then RFLX.SPDM.Valid_Measurement_Count (RFLX.SPDM.To_Base_Integer (Val))
       and then RFLX.SPDM.Measurements_Response.Available_Space (Ctx, RFLX.SPDM.Measurements_Response.F_Number_Of_Indices) >= RFLX.SPDM.Measurements_Response.Field_Size (Ctx, RFLX.SPDM.Measurements_Response.F_Number_Of_Indices)
       and then RFLX.SPDM.Measurements_Response.Field_Condition (Ctx, RFLX.SPDM.Measurements_Response.F_Number_Of_Indices),
     Post =>
       Has_Buffer (Ctx)
       and Valid (Ctx, F_Number_Of_Indices)
       and Get_Number_Of_Indices (Ctx) = Val
       and Invalid (Ctx, F_Reserved_1)
       and Invalid (Ctx, F_Slot_ID)
       and Invalid (Ctx, F_Number_Of_Blocks)
       and Invalid (Ctx, F_Measurement_Record_Length)
       and Invalid (Ctx, F_Measurement_Record)
       and Invalid (Ctx, F_Nonce_Data)
       and Invalid (Ctx, F_Opaque_Length)
       and Invalid (Ctx, F_Opaque_Data)
       and Invalid (Ctx, F_Signature)
       and (Predecessor (Ctx, F_Reserved_1) = F_Number_Of_Indices
            and Valid_Next (Ctx, F_Reserved_1))
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = Ctx.First'Old
       and Ctx.Last = Ctx.Last'Old
       and Ctx.Signature_Length = Ctx.Signature_Length'Old
       and Ctx.Has_Signature = Ctx.Has_Signature'Old
       and Predecessor (Ctx, F_Number_Of_Indices) = Predecessor (Ctx, F_Number_Of_Indices)'Old
       and Valid_Next (Ctx, F_Number_Of_Indices) = Valid_Next (Ctx, F_Number_Of_Indices)'Old
       and Field_First (Ctx, F_Number_Of_Indices) = Field_First (Ctx, F_Number_Of_Indices)'Old;

   procedure Set_Reserved_1 (Ctx : in out Context; Val : RFLX.SPDM.Reserved_4) with
     Inline_Always,
     Pre =>
       not Ctx'Constrained
       and then RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx)
       and then RFLX.SPDM.Measurements_Response.Valid_Next (Ctx, RFLX.SPDM.Measurements_Response.F_Reserved_1)
       and then RFLX.SPDM.Valid_Reserved_4 (RFLX.SPDM.To_Base_Integer (Val))
       and then RFLX.SPDM.Measurements_Response.Available_Space (Ctx, RFLX.SPDM.Measurements_Response.F_Reserved_1) >= RFLX.SPDM.Measurements_Response.Field_Size (Ctx, RFLX.SPDM.Measurements_Response.F_Reserved_1)
       and then RFLX.SPDM.Measurements_Response.Field_Condition (Ctx, RFLX.SPDM.Measurements_Response.F_Reserved_1),
     Post =>
       Has_Buffer (Ctx)
       and Valid (Ctx, F_Reserved_1)
       and Invalid (Ctx, F_Slot_ID)
       and Invalid (Ctx, F_Number_Of_Blocks)
       and Invalid (Ctx, F_Measurement_Record_Length)
       and Invalid (Ctx, F_Measurement_Record)
       and Invalid (Ctx, F_Nonce_Data)
       and Invalid (Ctx, F_Opaque_Length)
       and Invalid (Ctx, F_Opaque_Data)
       and Invalid (Ctx, F_Signature)
       and (Predecessor (Ctx, F_Slot_ID) = F_Reserved_1
            and Valid_Next (Ctx, F_Slot_ID))
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = Ctx.First'Old
       and Ctx.Last = Ctx.Last'Old
       and Ctx.Signature_Length = Ctx.Signature_Length'Old
       and Ctx.Has_Signature = Ctx.Has_Signature'Old
       and Predecessor (Ctx, F_Reserved_1) = Predecessor (Ctx, F_Reserved_1)'Old
       and Valid_Next (Ctx, F_Reserved_1) = Valid_Next (Ctx, F_Reserved_1)'Old
       and Get_Number_Of_Indices (Ctx) = Get_Number_Of_Indices (Ctx)'Old
       and Field_First (Ctx, F_Reserved_1) = Field_First (Ctx, F_Reserved_1)'Old
       and Field_Last (Ctx, F_Reserved_1) = Field_Last (Ctx, Predecessor (Ctx, F_Reserved_1)) + Field_Size (Ctx, F_Reserved_1)
       and (for all F in Field range F_Number_Of_Indices .. F_Number_Of_Indices =>
               Context_Cursors_Index (Context_Cursors (Ctx), F) = Context_Cursors_Index (Context_Cursors (Ctx)'Old, F));

   procedure Set_Slot_ID (Ctx : in out Context; Val : RFLX.SPDM.Narrow_Slot) with
     Inline_Always,
     Pre =>
       not Ctx'Constrained
       and then RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx)
       and then RFLX.SPDM.Measurements_Response.Valid_Next (Ctx, RFLX.SPDM.Measurements_Response.F_Slot_ID)
       and then RFLX.SPDM.Valid_Narrow_Slot (RFLX.SPDM.To_Base_Integer (Val))
       and then RFLX.SPDM.Measurements_Response.Available_Space (Ctx, RFLX.SPDM.Measurements_Response.F_Slot_ID) >= RFLX.SPDM.Measurements_Response.Field_Size (Ctx, RFLX.SPDM.Measurements_Response.F_Slot_ID)
       and then RFLX.SPDM.Measurements_Response.Field_Condition (Ctx, RFLX.SPDM.Measurements_Response.F_Slot_ID),
     Post =>
       Has_Buffer (Ctx)
       and Valid (Ctx, F_Slot_ID)
       and Get_Slot_ID (Ctx) = Val
       and Invalid (Ctx, F_Number_Of_Blocks)
       and Invalid (Ctx, F_Measurement_Record_Length)
       and Invalid (Ctx, F_Measurement_Record)
       and Invalid (Ctx, F_Nonce_Data)
       and Invalid (Ctx, F_Opaque_Length)
       and Invalid (Ctx, F_Opaque_Data)
       and Invalid (Ctx, F_Signature)
       and (Predecessor (Ctx, F_Number_Of_Blocks) = F_Slot_ID
            and Valid_Next (Ctx, F_Number_Of_Blocks))
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = Ctx.First'Old
       and Ctx.Last = Ctx.Last'Old
       and Ctx.Signature_Length = Ctx.Signature_Length'Old
       and Ctx.Has_Signature = Ctx.Has_Signature'Old
       and Predecessor (Ctx, F_Slot_ID) = Predecessor (Ctx, F_Slot_ID)'Old
       and Valid_Next (Ctx, F_Slot_ID) = Valid_Next (Ctx, F_Slot_ID)'Old
       and Get_Number_Of_Indices (Ctx) = Get_Number_Of_Indices (Ctx)'Old
       and Field_First (Ctx, F_Slot_ID) = Field_First (Ctx, F_Slot_ID)'Old
       and Field_Last (Ctx, F_Slot_ID) = Field_Last (Ctx, Predecessor (Ctx, F_Slot_ID)) + Field_Size (Ctx, F_Slot_ID)
       and (for all F in Field range F_Number_Of_Indices .. F_Reserved_1 =>
               Context_Cursors_Index (Context_Cursors (Ctx), F) = Context_Cursors_Index (Context_Cursors (Ctx)'Old, F));

   procedure Set_Number_Of_Blocks (Ctx : in out Context; Val : RFLX.SPDM.Block_Count) with
     Inline_Always,
     Pre =>
       not Ctx'Constrained
       and then RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx)
       and then RFLX.SPDM.Measurements_Response.Valid_Next (Ctx, RFLX.SPDM.Measurements_Response.F_Number_Of_Blocks)
       and then RFLX.SPDM.Valid_Block_Count (RFLX.SPDM.To_Base_Integer (Val))
       and then RFLX.SPDM.Measurements_Response.Available_Space (Ctx, RFLX.SPDM.Measurements_Response.F_Number_Of_Blocks) >= RFLX.SPDM.Measurements_Response.Field_Size (Ctx, RFLX.SPDM.Measurements_Response.F_Number_Of_Blocks)
       and then RFLX.SPDM.Measurements_Response.Field_Condition (Ctx, RFLX.SPDM.Measurements_Response.F_Number_Of_Blocks),
     Post =>
       Has_Buffer (Ctx)
       and Valid (Ctx, F_Number_Of_Blocks)
       and Get_Number_Of_Blocks (Ctx) = Val
       and Invalid (Ctx, F_Measurement_Record_Length)
       and Invalid (Ctx, F_Measurement_Record)
       and Invalid (Ctx, F_Nonce_Data)
       and Invalid (Ctx, F_Opaque_Length)
       and Invalid (Ctx, F_Opaque_Data)
       and Invalid (Ctx, F_Signature)
       and (Predecessor (Ctx, F_Measurement_Record_Length) = F_Number_Of_Blocks
            and Valid_Next (Ctx, F_Measurement_Record_Length))
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = Ctx.First'Old
       and Ctx.Last = Ctx.Last'Old
       and Ctx.Signature_Length = Ctx.Signature_Length'Old
       and Ctx.Has_Signature = Ctx.Has_Signature'Old
       and Predecessor (Ctx, F_Number_Of_Blocks) = Predecessor (Ctx, F_Number_Of_Blocks)'Old
       and Valid_Next (Ctx, F_Number_Of_Blocks) = Valid_Next (Ctx, F_Number_Of_Blocks)'Old
       and Get_Number_Of_Indices (Ctx) = Get_Number_Of_Indices (Ctx)'Old
       and Get_Slot_ID (Ctx) = Get_Slot_ID (Ctx)'Old
       and Field_First (Ctx, F_Number_Of_Blocks) = Field_First (Ctx, F_Number_Of_Blocks)'Old
       and Field_Last (Ctx, F_Number_Of_Blocks) = Field_Last (Ctx, Predecessor (Ctx, F_Number_Of_Blocks)) + Field_Size (Ctx, F_Number_Of_Blocks)
       and (for all F in Field range F_Number_Of_Indices .. F_Slot_ID =>
               Context_Cursors_Index (Context_Cursors (Ctx), F) = Context_Cursors_Index (Context_Cursors (Ctx)'Old, F));

   procedure Set_Measurement_Record_Length (Ctx : in out Context; Val : RFLX.SPDM.Length_24) with
     Inline_Always,
     Pre =>
       not Ctx'Constrained
       and then RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx)
       and then RFLX.SPDM.Measurements_Response.Valid_Next (Ctx, RFLX.SPDM.Measurements_Response.F_Measurement_Record_Length)
       and then RFLX.SPDM.Valid_Length_24 (RFLX.SPDM.To_Base_Integer (Val))
       and then RFLX.SPDM.Measurements_Response.Available_Space (Ctx, RFLX.SPDM.Measurements_Response.F_Measurement_Record_Length) >= RFLX.SPDM.Measurements_Response.Field_Size (Ctx, RFLX.SPDM.Measurements_Response.F_Measurement_Record_Length)
       and then RFLX.SPDM.Measurements_Response.Field_Condition (Ctx, RFLX.SPDM.Measurements_Response.F_Measurement_Record_Length),
     Post =>
       Has_Buffer (Ctx)
       and Valid (Ctx, F_Measurement_Record_Length)
       and Get_Measurement_Record_Length (Ctx) = Val
       and Invalid (Ctx, F_Measurement_Record)
       and Invalid (Ctx, F_Nonce_Data)
       and Invalid (Ctx, F_Opaque_Length)
       and Invalid (Ctx, F_Opaque_Data)
       and Invalid (Ctx, F_Signature)
       and (Predecessor (Ctx, F_Measurement_Record) = F_Measurement_Record_Length
            and Valid_Next (Ctx, F_Measurement_Record))
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = Ctx.First'Old
       and Ctx.Last = Ctx.Last'Old
       and Ctx.Signature_Length = Ctx.Signature_Length'Old
       and Ctx.Has_Signature = Ctx.Has_Signature'Old
       and Predecessor (Ctx, F_Measurement_Record_Length) = Predecessor (Ctx, F_Measurement_Record_Length)'Old
       and Valid_Next (Ctx, F_Measurement_Record_Length) = Valid_Next (Ctx, F_Measurement_Record_Length)'Old
       and Get_Number_Of_Indices (Ctx) = Get_Number_Of_Indices (Ctx)'Old
       and Get_Slot_ID (Ctx) = Get_Slot_ID (Ctx)'Old
       and Get_Number_Of_Blocks (Ctx) = Get_Number_Of_Blocks (Ctx)'Old
       and Field_First (Ctx, F_Measurement_Record_Length) = Field_First (Ctx, F_Measurement_Record_Length)'Old
       and Field_Last (Ctx, F_Measurement_Record_Length) = Field_Last (Ctx, Predecessor (Ctx, F_Measurement_Record_Length)) + Field_Size (Ctx, F_Measurement_Record_Length)
       and (for all F in Field range F_Number_Of_Indices .. F_Number_Of_Blocks =>
               Context_Cursors_Index (Context_Cursors (Ctx), F) = Context_Cursors_Index (Context_Cursors (Ctx)'Old, F));

   procedure Set_Opaque_Length (Ctx : in out Context; Val : RFLX.SPDM.Length_16) with
     Inline_Always,
     Pre =>
       not Ctx'Constrained
       and then RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx)
       and then RFLX.SPDM.Measurements_Response.Valid_Next (Ctx, RFLX.SPDM.Measurements_Response.F_Opaque_Length)
       and then RFLX.SPDM.Valid_Length_16 (RFLX.SPDM.To_Base_Integer (Val))
       and then RFLX.SPDM.Measurements_Response.Available_Space (Ctx, RFLX.SPDM.Measurements_Response.F_Opaque_Length) >= RFLX.SPDM.Measurements_Response.Field_Size (Ctx, RFLX.SPDM.Measurements_Response.F_Opaque_Length)
       and then RFLX.SPDM.Measurements_Response.Field_Condition (Ctx, RFLX.SPDM.Measurements_Response.F_Opaque_Length),
     Post =>
       Has_Buffer (Ctx)
       and Valid (Ctx, F_Opaque_Length)
       and Get_Opaque_Length (Ctx) = Val
       and Invalid (Ctx, F_Opaque_Data)
       and Invalid (Ctx, F_Signature)
       and (Predecessor (Ctx, F_Opaque_Data) = F_Opaque_Length
            and Valid_Next (Ctx, F_Opaque_Data))
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = Ctx.First'Old
       and Ctx.Last = Ctx.Last'Old
       and Ctx.Signature_Length = Ctx.Signature_Length'Old
       and Ctx.Has_Signature = Ctx.Has_Signature'Old
       and Predecessor (Ctx, F_Opaque_Length) = Predecessor (Ctx, F_Opaque_Length)'Old
       and Valid_Next (Ctx, F_Opaque_Length) = Valid_Next (Ctx, F_Opaque_Length)'Old
       and Get_Number_Of_Indices (Ctx) = Get_Number_Of_Indices (Ctx)'Old
       and Get_Slot_ID (Ctx) = Get_Slot_ID (Ctx)'Old
       and Get_Number_Of_Blocks (Ctx) = Get_Number_Of_Blocks (Ctx)'Old
       and Get_Measurement_Record_Length (Ctx) = Get_Measurement_Record_Length (Ctx)'Old
       and Field_First (Ctx, F_Opaque_Length) = Field_First (Ctx, F_Opaque_Length)'Old
       and Field_Last (Ctx, F_Opaque_Length) = Field_Last (Ctx, Predecessor (Ctx, F_Opaque_Length)) + Field_Size (Ctx, F_Opaque_Length)
       and (for all F in Field range F_Number_Of_Indices .. F_Nonce_Data =>
               Context_Cursors_Index (Context_Cursors (Ctx), F) = Context_Cursors_Index (Context_Cursors (Ctx)'Old, F));

   pragma Warnings (On, "aspect ""*"" not enforced on inlined subprogram ""*""");

   procedure Set_Measurement_Record_Empty (Ctx : in out Context) with
     Pre =>
       not Ctx'Constrained
       and then RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx)
       and then RFLX.SPDM.Measurements_Response.Valid_Next (Ctx, RFLX.SPDM.Measurements_Response.F_Measurement_Record)
       and then RFLX.SPDM.Measurements_Response.Available_Space (Ctx, RFLX.SPDM.Measurements_Response.F_Measurement_Record) >= RFLX.SPDM.Measurements_Response.Field_Size (Ctx, RFLX.SPDM.Measurements_Response.F_Measurement_Record)
       and then RFLX.SPDM.Measurements_Response.Field_Condition (Ctx, RFLX.SPDM.Measurements_Response.F_Measurement_Record)
       and then RFLX.SPDM.Measurements_Response.Field_Size (Ctx, RFLX.SPDM.Measurements_Response.F_Measurement_Record) = 0,
     Post =>
       Has_Buffer (Ctx)
       and Structural_Valid (Ctx, F_Measurement_Record)
       and Invalid (Ctx, F_Nonce_Data)
       and Invalid (Ctx, F_Opaque_Length)
       and Invalid (Ctx, F_Opaque_Data)
       and Invalid (Ctx, F_Signature)
       and (Predecessor (Ctx, F_Nonce_Data) = F_Measurement_Record
            and Valid_Next (Ctx, F_Nonce_Data))
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = Ctx.First'Old
       and Ctx.Last = Ctx.Last'Old
       and Ctx.Signature_Length = Ctx.Signature_Length'Old
       and Ctx.Has_Signature = Ctx.Has_Signature'Old
       and Predecessor (Ctx, F_Measurement_Record) = Predecessor (Ctx, F_Measurement_Record)'Old
       and Valid_Next (Ctx, F_Measurement_Record) = Valid_Next (Ctx, F_Measurement_Record)'Old
       and Get_Number_Of_Indices (Ctx) = Get_Number_Of_Indices (Ctx)'Old
       and Get_Slot_ID (Ctx) = Get_Slot_ID (Ctx)'Old
       and Get_Number_Of_Blocks (Ctx) = Get_Number_Of_Blocks (Ctx)'Old
       and Get_Measurement_Record_Length (Ctx) = Get_Measurement_Record_Length (Ctx)'Old
       and Field_First (Ctx, F_Measurement_Record) = Field_First (Ctx, F_Measurement_Record)'Old
       and Field_Last (Ctx, F_Measurement_Record) = Field_Last (Ctx, Predecessor (Ctx, F_Measurement_Record)) + Field_Size (Ctx, F_Measurement_Record);

   procedure Set_Opaque_Data_Empty (Ctx : in out Context) with
     Pre =>
       not Ctx'Constrained
       and then RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx)
       and then RFLX.SPDM.Measurements_Response.Valid_Next (Ctx, RFLX.SPDM.Measurements_Response.F_Opaque_Data)
       and then RFLX.SPDM.Measurements_Response.Available_Space (Ctx, RFLX.SPDM.Measurements_Response.F_Opaque_Data) >= RFLX.SPDM.Measurements_Response.Field_Size (Ctx, RFLX.SPDM.Measurements_Response.F_Opaque_Data)
       and then RFLX.SPDM.Measurements_Response.Field_Condition (Ctx, RFLX.SPDM.Measurements_Response.F_Opaque_Data)
       and then RFLX.SPDM.Measurements_Response.Field_Size (Ctx, RFLX.SPDM.Measurements_Response.F_Opaque_Data) = 0,
     Post =>
       Has_Buffer (Ctx)
       and Structural_Valid (Ctx, F_Opaque_Data)
       and (if Structural_Valid_Message (Ctx) then Message_Last (Ctx) = Field_Last (Ctx, F_Opaque_Data))
       and Invalid (Ctx, F_Signature)
       and (if
               RFLX_Types.Base_Integer (To_Base_Integer (Ctx.Has_Signature)) = RFLX_Types.Base_Integer (To_Base_Integer (True))
            then
               Predecessor (Ctx, F_Signature) = F_Opaque_Data
               and Valid_Next (Ctx, F_Signature))
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = Ctx.First'Old
       and Ctx.Last = Ctx.Last'Old
       and Ctx.Signature_Length = Ctx.Signature_Length'Old
       and Ctx.Has_Signature = Ctx.Has_Signature'Old
       and Predecessor (Ctx, F_Opaque_Data) = Predecessor (Ctx, F_Opaque_Data)'Old
       and Valid_Next (Ctx, F_Opaque_Data) = Valid_Next (Ctx, F_Opaque_Data)'Old
       and Get_Number_Of_Indices (Ctx) = Get_Number_Of_Indices (Ctx)'Old
       and Get_Slot_ID (Ctx) = Get_Slot_ID (Ctx)'Old
       and Get_Number_Of_Blocks (Ctx) = Get_Number_Of_Blocks (Ctx)'Old
       and Get_Measurement_Record_Length (Ctx) = Get_Measurement_Record_Length (Ctx)'Old
       and Get_Opaque_Length (Ctx) = Get_Opaque_Length (Ctx)'Old
       and Field_First (Ctx, F_Opaque_Data) = Field_First (Ctx, F_Opaque_Data)'Old
       and Field_Last (Ctx, F_Opaque_Data) = Field_Last (Ctx, Predecessor (Ctx, F_Opaque_Data)) + Field_Size (Ctx, F_Opaque_Data);

   procedure Set_Signature_Empty (Ctx : in out Context) with
     Pre =>
       not Ctx'Constrained
       and then RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx)
       and then RFLX.SPDM.Measurements_Response.Valid_Next (Ctx, RFLX.SPDM.Measurements_Response.F_Signature)
       and then RFLX.SPDM.Measurements_Response.Available_Space (Ctx, RFLX.SPDM.Measurements_Response.F_Signature) >= RFLX.SPDM.Measurements_Response.Field_Size (Ctx, RFLX.SPDM.Measurements_Response.F_Signature)
       and then RFLX.SPDM.Measurements_Response.Field_Condition (Ctx, RFLX.SPDM.Measurements_Response.F_Signature)
       and then RFLX.SPDM.Measurements_Response.Field_Size (Ctx, RFLX.SPDM.Measurements_Response.F_Signature) = 0,
     Post =>
       Has_Buffer (Ctx)
       and Structural_Valid (Ctx, F_Signature)
       and (if Structural_Valid_Message (Ctx) then Message_Last (Ctx) = Field_Last (Ctx, F_Signature))
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = Ctx.First'Old
       and Ctx.Last = Ctx.Last'Old
       and Ctx.Signature_Length = Ctx.Signature_Length'Old
       and Ctx.Has_Signature = Ctx.Has_Signature'Old
       and Predecessor (Ctx, F_Signature) = Predecessor (Ctx, F_Signature)'Old
       and Valid_Next (Ctx, F_Signature) = Valid_Next (Ctx, F_Signature)'Old
       and Get_Number_Of_Indices (Ctx) = Get_Number_Of_Indices (Ctx)'Old
       and Get_Slot_ID (Ctx) = Get_Slot_ID (Ctx)'Old
       and Get_Number_Of_Blocks (Ctx) = Get_Number_Of_Blocks (Ctx)'Old
       and Get_Measurement_Record_Length (Ctx) = Get_Measurement_Record_Length (Ctx)'Old
       and Get_Opaque_Length (Ctx) = Get_Opaque_Length (Ctx)'Old
       and Field_First (Ctx, F_Signature) = Field_First (Ctx, F_Signature)'Old
       and Field_Last (Ctx, F_Signature) = Field_Last (Ctx, Predecessor (Ctx, F_Signature)) + Field_Size (Ctx, F_Signature);

   procedure Set_Measurement_Record (Ctx : in out Context; Seq_Ctx : RFLX.SPDM.Measurement_Record.Context) with
     Pre =>
       not Ctx'Constrained
       and then RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx)
       and then RFLX.SPDM.Measurements_Response.Valid_Next (Ctx, RFLX.SPDM.Measurements_Response.F_Measurement_Record)
       and then RFLX.SPDM.Measurements_Response.Available_Space (Ctx, RFLX.SPDM.Measurements_Response.F_Measurement_Record) >= RFLX.SPDM.Measurements_Response.Field_Size (Ctx, RFLX.SPDM.Measurements_Response.F_Measurement_Record)
       and then RFLX.SPDM.Measurements_Response.Field_Condition (Ctx, RFLX.SPDM.Measurements_Response.F_Measurement_Record)
       and then RFLX.SPDM.Measurements_Response.Valid_Length (Ctx, RFLX.SPDM.Measurements_Response.F_Measurement_Record, RFLX.SPDM.Measurement_Record.Byte_Size (Seq_Ctx))
       and then RFLX.SPDM.Measurement_Record.Has_Buffer (Seq_Ctx)
       and then RFLX.SPDM.Measurement_Record.Valid (Seq_Ctx),
     Post =>
       Has_Buffer (Ctx)
       and Structural_Valid (Ctx, F_Measurement_Record)
       and Invalid (Ctx, F_Nonce_Data)
       and Invalid (Ctx, F_Opaque_Length)
       and Invalid (Ctx, F_Opaque_Data)
       and Invalid (Ctx, F_Signature)
       and (Predecessor (Ctx, F_Nonce_Data) = F_Measurement_Record
            and Valid_Next (Ctx, F_Nonce_Data))
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = Ctx.First'Old
       and Ctx.Last = Ctx.Last'Old
       and Ctx.Signature_Length = Ctx.Signature_Length'Old
       and Ctx.Has_Signature = Ctx.Has_Signature'Old
       and Predecessor (Ctx, F_Measurement_Record) = Predecessor (Ctx, F_Measurement_Record)'Old
       and Valid_Next (Ctx, F_Measurement_Record) = Valid_Next (Ctx, F_Measurement_Record)'Old
       and Get_Number_Of_Indices (Ctx) = Get_Number_Of_Indices (Ctx)'Old
       and Get_Slot_ID (Ctx) = Get_Slot_ID (Ctx)'Old
       and Get_Number_Of_Blocks (Ctx) = Get_Number_Of_Blocks (Ctx)'Old
       and Get_Measurement_Record_Length (Ctx) = Get_Measurement_Record_Length (Ctx)'Old
       and Field_First (Ctx, F_Measurement_Record) = Field_First (Ctx, F_Measurement_Record)'Old
       and Field_Last (Ctx, F_Measurement_Record) = Field_Last (Ctx, Predecessor (Ctx, F_Measurement_Record)) + Field_Size (Ctx, F_Measurement_Record)
       and (if Field_Size (Ctx, F_Measurement_Record) > 0 then Present (Ctx, F_Measurement_Record));

   procedure Initialize_Measurement_Record (Ctx : in out Context) with
     Pre =>
       not Ctx'Constrained
       and then RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx)
       and then RFLX.SPDM.Measurements_Response.Valid_Next (Ctx, RFLX.SPDM.Measurements_Response.F_Measurement_Record)
       and then RFLX.SPDM.Measurements_Response.Available_Space (Ctx, RFLX.SPDM.Measurements_Response.F_Measurement_Record) >= RFLX.SPDM.Measurements_Response.Field_Size (Ctx, RFLX.SPDM.Measurements_Response.F_Measurement_Record),
     Post =>
       Has_Buffer (Ctx)
       and Structural_Valid (Ctx, F_Measurement_Record)
       and Invalid (Ctx, F_Nonce_Data)
       and Invalid (Ctx, F_Opaque_Length)
       and Invalid (Ctx, F_Opaque_Data)
       and Invalid (Ctx, F_Signature)
       and (Predecessor (Ctx, F_Nonce_Data) = F_Measurement_Record
            and Valid_Next (Ctx, F_Nonce_Data))
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = Ctx.First'Old
       and Ctx.Last = Ctx.Last'Old
       and Ctx.Signature_Length = Ctx.Signature_Length'Old
       and Ctx.Has_Signature = Ctx.Has_Signature'Old
       and Predecessor (Ctx, F_Measurement_Record) = Predecessor (Ctx, F_Measurement_Record)'Old
       and Valid_Next (Ctx, F_Measurement_Record) = Valid_Next (Ctx, F_Measurement_Record)'Old
       and Get_Number_Of_Indices (Ctx) = Get_Number_Of_Indices (Ctx)'Old
       and Get_Slot_ID (Ctx) = Get_Slot_ID (Ctx)'Old
       and Get_Number_Of_Blocks (Ctx) = Get_Number_Of_Blocks (Ctx)'Old
       and Get_Measurement_Record_Length (Ctx) = Get_Measurement_Record_Length (Ctx)'Old
       and Field_First (Ctx, F_Measurement_Record) = Field_First (Ctx, F_Measurement_Record)'Old
       and Field_Last (Ctx, F_Measurement_Record) = Field_Last (Ctx, Predecessor (Ctx, F_Measurement_Record)) + Field_Size (Ctx, F_Measurement_Record);

   procedure Initialize_Nonce_Data (Ctx : in out Context) with
     Pre =>
       not Ctx'Constrained
       and then RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx)
       and then RFLX.SPDM.Measurements_Response.Valid_Next (Ctx, RFLX.SPDM.Measurements_Response.F_Nonce_Data)
       and then RFLX.SPDM.Measurements_Response.Available_Space (Ctx, RFLX.SPDM.Measurements_Response.F_Nonce_Data) >= RFLX.SPDM.Measurements_Response.Field_Size (Ctx, RFLX.SPDM.Measurements_Response.F_Nonce_Data),
     Post =>
       Has_Buffer (Ctx)
       and Structural_Valid (Ctx, F_Nonce_Data)
       and Invalid (Ctx, F_Opaque_Length)
       and Invalid (Ctx, F_Opaque_Data)
       and Invalid (Ctx, F_Signature)
       and (Predecessor (Ctx, F_Opaque_Length) = F_Nonce_Data
            and Valid_Next (Ctx, F_Opaque_Length))
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = Ctx.First'Old
       and Ctx.Last = Ctx.Last'Old
       and Ctx.Signature_Length = Ctx.Signature_Length'Old
       and Ctx.Has_Signature = Ctx.Has_Signature'Old
       and Predecessor (Ctx, F_Nonce_Data) = Predecessor (Ctx, F_Nonce_Data)'Old
       and Valid_Next (Ctx, F_Nonce_Data) = Valid_Next (Ctx, F_Nonce_Data)'Old
       and Get_Number_Of_Indices (Ctx) = Get_Number_Of_Indices (Ctx)'Old
       and Get_Slot_ID (Ctx) = Get_Slot_ID (Ctx)'Old
       and Get_Number_Of_Blocks (Ctx) = Get_Number_Of_Blocks (Ctx)'Old
       and Get_Measurement_Record_Length (Ctx) = Get_Measurement_Record_Length (Ctx)'Old
       and Field_First (Ctx, F_Nonce_Data) = Field_First (Ctx, F_Nonce_Data)'Old
       and Field_Last (Ctx, F_Nonce_Data) = Field_Last (Ctx, Predecessor (Ctx, F_Nonce_Data)) + Field_Size (Ctx, F_Nonce_Data);

   procedure Initialize_Opaque_Data (Ctx : in out Context) with
     Pre =>
       not Ctx'Constrained
       and then RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx)
       and then RFLX.SPDM.Measurements_Response.Valid_Next (Ctx, RFLX.SPDM.Measurements_Response.F_Opaque_Data)
       and then RFLX.SPDM.Measurements_Response.Available_Space (Ctx, RFLX.SPDM.Measurements_Response.F_Opaque_Data) >= RFLX.SPDM.Measurements_Response.Field_Size (Ctx, RFLX.SPDM.Measurements_Response.F_Opaque_Data),
     Post =>
       Has_Buffer (Ctx)
       and Structural_Valid (Ctx, F_Opaque_Data)
       and (if Structural_Valid_Message (Ctx) then Message_Last (Ctx) = Field_Last (Ctx, F_Opaque_Data))
       and Invalid (Ctx, F_Signature)
       and (if
               RFLX_Types.Base_Integer (To_Base_Integer (Ctx.Has_Signature)) = RFLX_Types.Base_Integer (To_Base_Integer (True))
            then
               Predecessor (Ctx, F_Signature) = F_Opaque_Data
               and Valid_Next (Ctx, F_Signature))
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = Ctx.First'Old
       and Ctx.Last = Ctx.Last'Old
       and Ctx.Signature_Length = Ctx.Signature_Length'Old
       and Ctx.Has_Signature = Ctx.Has_Signature'Old
       and Predecessor (Ctx, F_Opaque_Data) = Predecessor (Ctx, F_Opaque_Data)'Old
       and Valid_Next (Ctx, F_Opaque_Data) = Valid_Next (Ctx, F_Opaque_Data)'Old
       and Get_Number_Of_Indices (Ctx) = Get_Number_Of_Indices (Ctx)'Old
       and Get_Slot_ID (Ctx) = Get_Slot_ID (Ctx)'Old
       and Get_Number_Of_Blocks (Ctx) = Get_Number_Of_Blocks (Ctx)'Old
       and Get_Measurement_Record_Length (Ctx) = Get_Measurement_Record_Length (Ctx)'Old
       and Get_Opaque_Length (Ctx) = Get_Opaque_Length (Ctx)'Old
       and Field_First (Ctx, F_Opaque_Data) = Field_First (Ctx, F_Opaque_Data)'Old
       and Field_Last (Ctx, F_Opaque_Data) = Field_Last (Ctx, Predecessor (Ctx, F_Opaque_Data)) + Field_Size (Ctx, F_Opaque_Data);

   procedure Initialize_Signature (Ctx : in out Context) with
     Pre =>
       not Ctx'Constrained
       and then RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx)
       and then RFLX.SPDM.Measurements_Response.Valid_Next (Ctx, RFLX.SPDM.Measurements_Response.F_Signature)
       and then RFLX.SPDM.Measurements_Response.Available_Space (Ctx, RFLX.SPDM.Measurements_Response.F_Signature) >= RFLX.SPDM.Measurements_Response.Field_Size (Ctx, RFLX.SPDM.Measurements_Response.F_Signature),
     Post =>
       Has_Buffer (Ctx)
       and Structural_Valid (Ctx, F_Signature)
       and (if Structural_Valid_Message (Ctx) then Message_Last (Ctx) = Field_Last (Ctx, F_Signature))
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = Ctx.First'Old
       and Ctx.Last = Ctx.Last'Old
       and Ctx.Signature_Length = Ctx.Signature_Length'Old
       and Ctx.Has_Signature = Ctx.Has_Signature'Old
       and Predecessor (Ctx, F_Signature) = Predecessor (Ctx, F_Signature)'Old
       and Valid_Next (Ctx, F_Signature) = Valid_Next (Ctx, F_Signature)'Old
       and Get_Number_Of_Indices (Ctx) = Get_Number_Of_Indices (Ctx)'Old
       and Get_Slot_ID (Ctx) = Get_Slot_ID (Ctx)'Old
       and Get_Number_Of_Blocks (Ctx) = Get_Number_Of_Blocks (Ctx)'Old
       and Get_Measurement_Record_Length (Ctx) = Get_Measurement_Record_Length (Ctx)'Old
       and Get_Opaque_Length (Ctx) = Get_Opaque_Length (Ctx)'Old
       and Field_First (Ctx, F_Signature) = Field_First (Ctx, F_Signature)'Old
       and Field_Last (Ctx, F_Signature) = Field_Last (Ctx, Predecessor (Ctx, F_Signature)) + Field_Size (Ctx, F_Signature);

   procedure Set_Nonce_Data (Ctx : in out Context; Data : RFLX_Types.Bytes) with
     Pre =>
       not Ctx'Constrained
       and then RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx)
       and then RFLX.SPDM.Measurements_Response.Valid_Next (Ctx, RFLX.SPDM.Measurements_Response.F_Nonce_Data)
       and then RFLX.SPDM.Measurements_Response.Available_Space (Ctx, RFLX.SPDM.Measurements_Response.F_Nonce_Data) >= RFLX.SPDM.Measurements_Response.Field_Size (Ctx, RFLX.SPDM.Measurements_Response.F_Nonce_Data)
       and then RFLX.SPDM.Measurements_Response.Valid_Length (Ctx, RFLX.SPDM.Measurements_Response.F_Nonce_Data, Data'Length)
       and then RFLX.SPDM.Measurements_Response.Available_Space (Ctx, RFLX.SPDM.Measurements_Response.F_Nonce_Data) >= Data'Length * RFLX_Types.Byte'Size
       and then RFLX.SPDM.Measurements_Response.Field_Condition (Ctx, RFLX.SPDM.Measurements_Response.F_Nonce_Data),
     Post =>
       Has_Buffer (Ctx)
       and Structural_Valid (Ctx, F_Nonce_Data)
       and Invalid (Ctx, F_Opaque_Length)
       and Invalid (Ctx, F_Opaque_Data)
       and Invalid (Ctx, F_Signature)
       and (Predecessor (Ctx, F_Opaque_Length) = F_Nonce_Data
            and Valid_Next (Ctx, F_Opaque_Length))
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = Ctx.First'Old
       and Ctx.Last = Ctx.Last'Old
       and Ctx.Signature_Length = Ctx.Signature_Length'Old
       and Ctx.Has_Signature = Ctx.Has_Signature'Old
       and Predecessor (Ctx, F_Nonce_Data) = Predecessor (Ctx, F_Nonce_Data)'Old
       and Valid_Next (Ctx, F_Nonce_Data) = Valid_Next (Ctx, F_Nonce_Data)'Old
       and Get_Number_Of_Indices (Ctx) = Get_Number_Of_Indices (Ctx)'Old
       and Get_Slot_ID (Ctx) = Get_Slot_ID (Ctx)'Old
       and Get_Number_Of_Blocks (Ctx) = Get_Number_Of_Blocks (Ctx)'Old
       and Get_Measurement_Record_Length (Ctx) = Get_Measurement_Record_Length (Ctx)'Old
       and Field_First (Ctx, F_Nonce_Data) = Field_First (Ctx, F_Nonce_Data)'Old
       and Field_Last (Ctx, F_Nonce_Data) = Field_Last (Ctx, Predecessor (Ctx, F_Nonce_Data)) + Field_Size (Ctx, F_Nonce_Data)
       and Equal (Ctx, F_Nonce_Data, Data);

   procedure Set_Opaque_Data (Ctx : in out Context; Data : RFLX_Types.Bytes) with
     Pre =>
       not Ctx'Constrained
       and then RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx)
       and then RFLX.SPDM.Measurements_Response.Valid_Next (Ctx, RFLX.SPDM.Measurements_Response.F_Opaque_Data)
       and then RFLX.SPDM.Measurements_Response.Available_Space (Ctx, RFLX.SPDM.Measurements_Response.F_Opaque_Data) >= RFLX.SPDM.Measurements_Response.Field_Size (Ctx, RFLX.SPDM.Measurements_Response.F_Opaque_Data)
       and then RFLX.SPDM.Measurements_Response.Valid_Length (Ctx, RFLX.SPDM.Measurements_Response.F_Opaque_Data, Data'Length)
       and then RFLX.SPDM.Measurements_Response.Available_Space (Ctx, RFLX.SPDM.Measurements_Response.F_Opaque_Data) >= Data'Length * RFLX_Types.Byte'Size
       and then RFLX.SPDM.Measurements_Response.Field_Condition (Ctx, RFLX.SPDM.Measurements_Response.F_Opaque_Data),
     Post =>
       Has_Buffer (Ctx)
       and Structural_Valid (Ctx, F_Opaque_Data)
       and (if Structural_Valid_Message (Ctx) then Message_Last (Ctx) = Field_Last (Ctx, F_Opaque_Data))
       and Invalid (Ctx, F_Signature)
       and (if
               RFLX_Types.Base_Integer (To_Base_Integer (Ctx.Has_Signature)) = RFLX_Types.Base_Integer (To_Base_Integer (True))
            then
               Predecessor (Ctx, F_Signature) = F_Opaque_Data
               and Valid_Next (Ctx, F_Signature))
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = Ctx.First'Old
       and Ctx.Last = Ctx.Last'Old
       and Ctx.Signature_Length = Ctx.Signature_Length'Old
       and Ctx.Has_Signature = Ctx.Has_Signature'Old
       and Predecessor (Ctx, F_Opaque_Data) = Predecessor (Ctx, F_Opaque_Data)'Old
       and Valid_Next (Ctx, F_Opaque_Data) = Valid_Next (Ctx, F_Opaque_Data)'Old
       and Get_Number_Of_Indices (Ctx) = Get_Number_Of_Indices (Ctx)'Old
       and Get_Slot_ID (Ctx) = Get_Slot_ID (Ctx)'Old
       and Get_Number_Of_Blocks (Ctx) = Get_Number_Of_Blocks (Ctx)'Old
       and Get_Measurement_Record_Length (Ctx) = Get_Measurement_Record_Length (Ctx)'Old
       and Get_Opaque_Length (Ctx) = Get_Opaque_Length (Ctx)'Old
       and Field_First (Ctx, F_Opaque_Data) = Field_First (Ctx, F_Opaque_Data)'Old
       and Field_Last (Ctx, F_Opaque_Data) = Field_Last (Ctx, Predecessor (Ctx, F_Opaque_Data)) + Field_Size (Ctx, F_Opaque_Data)
       and Equal (Ctx, F_Opaque_Data, Data);

   procedure Set_Signature (Ctx : in out Context; Data : RFLX_Types.Bytes) with
     Pre =>
       not Ctx'Constrained
       and then RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx)
       and then RFLX.SPDM.Measurements_Response.Valid_Next (Ctx, RFLX.SPDM.Measurements_Response.F_Signature)
       and then RFLX.SPDM.Measurements_Response.Available_Space (Ctx, RFLX.SPDM.Measurements_Response.F_Signature) >= RFLX.SPDM.Measurements_Response.Field_Size (Ctx, RFLX.SPDM.Measurements_Response.F_Signature)
       and then RFLX.SPDM.Measurements_Response.Valid_Length (Ctx, RFLX.SPDM.Measurements_Response.F_Signature, Data'Length)
       and then RFLX.SPDM.Measurements_Response.Available_Space (Ctx, RFLX.SPDM.Measurements_Response.F_Signature) >= Data'Length * RFLX_Types.Byte'Size
       and then RFLX.SPDM.Measurements_Response.Field_Condition (Ctx, RFLX.SPDM.Measurements_Response.F_Signature),
     Post =>
       Has_Buffer (Ctx)
       and Structural_Valid (Ctx, F_Signature)
       and (if Structural_Valid_Message (Ctx) then Message_Last (Ctx) = Field_Last (Ctx, F_Signature))
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = Ctx.First'Old
       and Ctx.Last = Ctx.Last'Old
       and Ctx.Signature_Length = Ctx.Signature_Length'Old
       and Ctx.Has_Signature = Ctx.Has_Signature'Old
       and Predecessor (Ctx, F_Signature) = Predecessor (Ctx, F_Signature)'Old
       and Valid_Next (Ctx, F_Signature) = Valid_Next (Ctx, F_Signature)'Old
       and Get_Number_Of_Indices (Ctx) = Get_Number_Of_Indices (Ctx)'Old
       and Get_Slot_ID (Ctx) = Get_Slot_ID (Ctx)'Old
       and Get_Number_Of_Blocks (Ctx) = Get_Number_Of_Blocks (Ctx)'Old
       and Get_Measurement_Record_Length (Ctx) = Get_Measurement_Record_Length (Ctx)'Old
       and Get_Opaque_Length (Ctx) = Get_Opaque_Length (Ctx)'Old
       and Field_First (Ctx, F_Signature) = Field_First (Ctx, F_Signature)'Old
       and Field_Last (Ctx, F_Signature) = Field_Last (Ctx, Predecessor (Ctx, F_Signature)) + Field_Size (Ctx, F_Signature)
       and Equal (Ctx, F_Signature, Data);

   generic
      with procedure Process_Nonce_Data (Nonce_Data : out RFLX_Types.Bytes);
      with function Process_Data_Pre (Length : RFLX_Types.Length) return Boolean;
   procedure Generic_Set_Nonce_Data (Ctx : in out Context; Length : RFLX_Types.Length) with
     Pre =>
       not Ctx'Constrained
       and then RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx)
       and then RFLX.SPDM.Measurements_Response.Valid_Next (Ctx, RFLX.SPDM.Measurements_Response.F_Nonce_Data)
       and then RFLX.SPDM.Measurements_Response.Available_Space (Ctx, RFLX.SPDM.Measurements_Response.F_Nonce_Data) >= RFLX.SPDM.Measurements_Response.Field_Size (Ctx, RFLX.SPDM.Measurements_Response.F_Nonce_Data)
       and then RFLX.SPDM.Measurements_Response.Valid_Length (Ctx, RFLX.SPDM.Measurements_Response.F_Nonce_Data, Length)
       and then RFLX_Types.To_Length (RFLX.SPDM.Measurements_Response.Available_Space (Ctx, RFLX.SPDM.Measurements_Response.F_Nonce_Data)) >= Length
       and then Process_Data_Pre (Length),
     Post =>
       Has_Buffer (Ctx)
       and Structural_Valid (Ctx, F_Nonce_Data)
       and Invalid (Ctx, F_Opaque_Length)
       and Invalid (Ctx, F_Opaque_Data)
       and Invalid (Ctx, F_Signature)
       and (Predecessor (Ctx, F_Opaque_Length) = F_Nonce_Data
            and Valid_Next (Ctx, F_Opaque_Length))
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = Ctx.First'Old
       and Ctx.Last = Ctx.Last'Old
       and Ctx.Signature_Length = Ctx.Signature_Length'Old
       and Ctx.Has_Signature = Ctx.Has_Signature'Old
       and Predecessor (Ctx, F_Nonce_Data) = Predecessor (Ctx, F_Nonce_Data)'Old
       and Valid_Next (Ctx, F_Nonce_Data) = Valid_Next (Ctx, F_Nonce_Data)'Old
       and Get_Number_Of_Indices (Ctx) = Get_Number_Of_Indices (Ctx)'Old
       and Get_Slot_ID (Ctx) = Get_Slot_ID (Ctx)'Old
       and Get_Number_Of_Blocks (Ctx) = Get_Number_Of_Blocks (Ctx)'Old
       and Get_Measurement_Record_Length (Ctx) = Get_Measurement_Record_Length (Ctx)'Old
       and Field_First (Ctx, F_Nonce_Data) = Field_First (Ctx, F_Nonce_Data)'Old
       and Field_Last (Ctx, F_Nonce_Data) = Field_Last (Ctx, Predecessor (Ctx, F_Nonce_Data)) + Field_Size (Ctx, F_Nonce_Data);

   generic
      with procedure Process_Opaque_Data (Opaque_Data : out RFLX_Types.Bytes);
      with function Process_Data_Pre (Length : RFLX_Types.Length) return Boolean;
   procedure Generic_Set_Opaque_Data (Ctx : in out Context; Length : RFLX_Types.Length) with
     Pre =>
       not Ctx'Constrained
       and then RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx)
       and then RFLX.SPDM.Measurements_Response.Valid_Next (Ctx, RFLX.SPDM.Measurements_Response.F_Opaque_Data)
       and then RFLX.SPDM.Measurements_Response.Available_Space (Ctx, RFLX.SPDM.Measurements_Response.F_Opaque_Data) >= RFLX.SPDM.Measurements_Response.Field_Size (Ctx, RFLX.SPDM.Measurements_Response.F_Opaque_Data)
       and then RFLX.SPDM.Measurements_Response.Valid_Length (Ctx, RFLX.SPDM.Measurements_Response.F_Opaque_Data, Length)
       and then RFLX_Types.To_Length (RFLX.SPDM.Measurements_Response.Available_Space (Ctx, RFLX.SPDM.Measurements_Response.F_Opaque_Data)) >= Length
       and then Process_Data_Pre (Length),
     Post =>
       Has_Buffer (Ctx)
       and Structural_Valid (Ctx, F_Opaque_Data)
       and (if Structural_Valid_Message (Ctx) then Message_Last (Ctx) = Field_Last (Ctx, F_Opaque_Data))
       and Invalid (Ctx, F_Signature)
       and (if
               RFLX_Types.Base_Integer (To_Base_Integer (Ctx.Has_Signature)) = RFLX_Types.Base_Integer (To_Base_Integer (True))
            then
               Predecessor (Ctx, F_Signature) = F_Opaque_Data
               and Valid_Next (Ctx, F_Signature))
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = Ctx.First'Old
       and Ctx.Last = Ctx.Last'Old
       and Ctx.Signature_Length = Ctx.Signature_Length'Old
       and Ctx.Has_Signature = Ctx.Has_Signature'Old
       and Predecessor (Ctx, F_Opaque_Data) = Predecessor (Ctx, F_Opaque_Data)'Old
       and Valid_Next (Ctx, F_Opaque_Data) = Valid_Next (Ctx, F_Opaque_Data)'Old
       and Get_Number_Of_Indices (Ctx) = Get_Number_Of_Indices (Ctx)'Old
       and Get_Slot_ID (Ctx) = Get_Slot_ID (Ctx)'Old
       and Get_Number_Of_Blocks (Ctx) = Get_Number_Of_Blocks (Ctx)'Old
       and Get_Measurement_Record_Length (Ctx) = Get_Measurement_Record_Length (Ctx)'Old
       and Get_Opaque_Length (Ctx) = Get_Opaque_Length (Ctx)'Old
       and Field_First (Ctx, F_Opaque_Data) = Field_First (Ctx, F_Opaque_Data)'Old
       and Field_Last (Ctx, F_Opaque_Data) = Field_Last (Ctx, Predecessor (Ctx, F_Opaque_Data)) + Field_Size (Ctx, F_Opaque_Data);

   generic
      with procedure Process_Signature (Signature : out RFLX_Types.Bytes);
      with function Process_Data_Pre (Length : RFLX_Types.Length) return Boolean;
   procedure Generic_Set_Signature (Ctx : in out Context; Length : RFLX_Types.Length) with
     Pre =>
       not Ctx'Constrained
       and then RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx)
       and then RFLX.SPDM.Measurements_Response.Valid_Next (Ctx, RFLX.SPDM.Measurements_Response.F_Signature)
       and then RFLX.SPDM.Measurements_Response.Available_Space (Ctx, RFLX.SPDM.Measurements_Response.F_Signature) >= RFLX.SPDM.Measurements_Response.Field_Size (Ctx, RFLX.SPDM.Measurements_Response.F_Signature)
       and then RFLX.SPDM.Measurements_Response.Valid_Length (Ctx, RFLX.SPDM.Measurements_Response.F_Signature, Length)
       and then RFLX_Types.To_Length (RFLX.SPDM.Measurements_Response.Available_Space (Ctx, RFLX.SPDM.Measurements_Response.F_Signature)) >= Length
       and then Process_Data_Pre (Length),
     Post =>
       Has_Buffer (Ctx)
       and Structural_Valid (Ctx, F_Signature)
       and (if Structural_Valid_Message (Ctx) then Message_Last (Ctx) = Field_Last (Ctx, F_Signature))
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = Ctx.First'Old
       and Ctx.Last = Ctx.Last'Old
       and Ctx.Signature_Length = Ctx.Signature_Length'Old
       and Ctx.Has_Signature = Ctx.Has_Signature'Old
       and Predecessor (Ctx, F_Signature) = Predecessor (Ctx, F_Signature)'Old
       and Valid_Next (Ctx, F_Signature) = Valid_Next (Ctx, F_Signature)'Old
       and Get_Number_Of_Indices (Ctx) = Get_Number_Of_Indices (Ctx)'Old
       and Get_Slot_ID (Ctx) = Get_Slot_ID (Ctx)'Old
       and Get_Number_Of_Blocks (Ctx) = Get_Number_Of_Blocks (Ctx)'Old
       and Get_Measurement_Record_Length (Ctx) = Get_Measurement_Record_Length (Ctx)'Old
       and Get_Opaque_Length (Ctx) = Get_Opaque_Length (Ctx)'Old
       and Field_First (Ctx, F_Signature) = Field_First (Ctx, F_Signature)'Old
       and Field_Last (Ctx, F_Signature) = Field_Last (Ctx, Predecessor (Ctx, F_Signature)) + Field_Size (Ctx, F_Signature);

   procedure Switch_To_Measurement_Record (Ctx : in out Context; Seq_Ctx : out RFLX.SPDM.Measurement_Record.Context) with
     Pre =>
       not Ctx'Constrained
       and then not Seq_Ctx'Constrained
       and then RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx)
       and then RFLX.SPDM.Measurements_Response.Valid_Next (Ctx, RFLX.SPDM.Measurements_Response.F_Measurement_Record)
       and then RFLX.SPDM.Measurements_Response.Field_Size (Ctx, RFLX.SPDM.Measurements_Response.F_Measurement_Record) > 0
       and then RFLX.SPDM.Measurements_Response.Field_First (Ctx, RFLX.SPDM.Measurements_Response.F_Measurement_Record) rem RFLX_Types.Byte'Size = 1
       and then RFLX.SPDM.Measurements_Response.Available_Space (Ctx, RFLX.SPDM.Measurements_Response.F_Measurement_Record) >= RFLX.SPDM.Measurements_Response.Field_Size (Ctx, RFLX.SPDM.Measurements_Response.F_Measurement_Record)
       and then RFLX.SPDM.Measurements_Response.Field_Condition (Ctx, RFLX.SPDM.Measurements_Response.F_Measurement_Record),
     Post =>
       not RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx)
       and RFLX.SPDM.Measurement_Record.Has_Buffer (Seq_Ctx)
       and Ctx.Buffer_First = Seq_Ctx.Buffer_First
       and Ctx.Buffer_Last = Seq_Ctx.Buffer_Last
       and Seq_Ctx.First = Field_First (Ctx, F_Measurement_Record)
       and Seq_Ctx.Last = Field_Last (Ctx, F_Measurement_Record)
       and RFLX.SPDM.Measurement_Record.Valid (Seq_Ctx)
       and RFLX.SPDM.Measurement_Record.Sequence_Last (Seq_Ctx) = Seq_Ctx.First - 1
       and Present (Ctx, F_Measurement_Record)
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = Ctx.First'Old
       and Ctx.Last = Ctx.Last'Old
       and Ctx.Signature_Length = Ctx.Signature_Length'Old
       and Ctx.Has_Signature = Ctx.Has_Signature'Old
       and Predecessor (Ctx, F_Measurement_Record) = Predecessor (Ctx, F_Measurement_Record)'Old
       and Path_Condition (Ctx, F_Measurement_Record) = Path_Condition (Ctx, F_Measurement_Record)'Old
       and Field_Last (Ctx, F_Measurement_Record) = Field_Last (Ctx, F_Measurement_Record)'Old
       and (for all F in Field range F_Number_Of_Indices .. F_Measurement_Record_Length =>
               Context_Cursors_Index (Context_Cursors (Ctx), F) = Context_Cursors_Index (Context_Cursors (Ctx)'Old, F)),
     Contract_Cases =>
       (Structural_Valid (Ctx, F_Measurement_Record) =>
           (for all F in Field range F_Nonce_Data .. F_Signature =>
               Context_Cursors_Index (Context_Cursors (Ctx), F) = Context_Cursors_Index (Context_Cursors (Ctx)'Old, F)),
        others =>
           (Predecessor (Ctx, F_Nonce_Data) = F_Measurement_Record
            and Valid_Next (Ctx, F_Nonce_Data))
           and Invalid (Ctx, F_Nonce_Data)
           and Invalid (Ctx, F_Opaque_Length)
           and Invalid (Ctx, F_Opaque_Data)
           and Invalid (Ctx, F_Signature));

   function Complete_Measurement_Record (Ctx : Context; Seq_Ctx : RFLX.SPDM.Measurement_Record.Context) return Boolean with
     Pre =>
       RFLX.SPDM.Measurements_Response.Valid_Next (Ctx, RFLX.SPDM.Measurements_Response.F_Measurement_Record);

   procedure Update_Measurement_Record (Ctx : in out Context; Seq_Ctx : in out RFLX.SPDM.Measurement_Record.Context) with
     Pre =>
       RFLX.SPDM.Measurements_Response.Present (Ctx, RFLX.SPDM.Measurements_Response.F_Measurement_Record)
       and then RFLX.SPDM.Measurements_Response.Complete_Measurement_Record (Ctx, Seq_Ctx)
       and then not RFLX.SPDM.Measurements_Response.Has_Buffer (Ctx)
       and then RFLX.SPDM.Measurement_Record.Has_Buffer (Seq_Ctx)
       and then Ctx.Buffer_First = Seq_Ctx.Buffer_First
       and then Ctx.Buffer_Last = Seq_Ctx.Buffer_Last
       and then Seq_Ctx.First = Field_First (Ctx, F_Measurement_Record)
       and then Seq_Ctx.Last = Field_Last (Ctx, F_Measurement_Record),
     Post =>
       Present (Ctx, F_Measurement_Record)
       and Has_Buffer (Ctx)
       and not RFLX.SPDM.Measurement_Record.Has_Buffer (Seq_Ctx)
       and Ctx.Buffer_First = Ctx.Buffer_First'Old
       and Ctx.Buffer_Last = Ctx.Buffer_Last'Old
       and Ctx.First = Ctx.First'Old
       and Ctx.Last = Ctx.Last'Old
       and Ctx.Signature_Length = Ctx.Signature_Length'Old
       and Ctx.Has_Signature = Ctx.Has_Signature'Old
       and Seq_Ctx.First = Seq_Ctx.First'Old
       and Seq_Ctx.Last = Seq_Ctx.Last'Old
       and Field_First (Ctx, F_Measurement_Record) = Field_First (Ctx, F_Measurement_Record)'Old
       and Field_Size (Ctx, F_Measurement_Record) = Field_Size (Ctx, F_Measurement_Record)'Old
       and Context_Cursor (Ctx, F_Number_Of_Indices) = Context_Cursor (Ctx, F_Number_Of_Indices)'Old
       and Context_Cursor (Ctx, F_Reserved_1) = Context_Cursor (Ctx, F_Reserved_1)'Old
       and Context_Cursor (Ctx, F_Slot_ID) = Context_Cursor (Ctx, F_Slot_ID)'Old
       and Context_Cursor (Ctx, F_Number_Of_Blocks) = Context_Cursor (Ctx, F_Number_Of_Blocks)'Old
       and Context_Cursor (Ctx, F_Measurement_Record_Length) = Context_Cursor (Ctx, F_Measurement_Record_Length)'Old
       and Context_Cursor (Ctx, F_Nonce_Data) = Context_Cursor (Ctx, F_Nonce_Data)'Old
       and Context_Cursor (Ctx, F_Opaque_Length) = Context_Cursor (Ctx, F_Opaque_Length)'Old
       and Context_Cursor (Ctx, F_Opaque_Data) = Context_Cursor (Ctx, F_Opaque_Data)'Old
       and Context_Cursor (Ctx, F_Signature) = Context_Cursor (Ctx, F_Signature)'Old,
     Depends =>
       (Ctx => (Ctx, Seq_Ctx), Seq_Ctx => Seq_Ctx);

   function Context_Cursor (Ctx : Context; Fld : Field) return Field_Cursor with
     Annotate =>
       (GNATprove, Inline_For_Proof),
     Ghost;

   function Context_Cursors (Ctx : Context) return Field_Cursors with
     Annotate =>
       (GNATprove, Inline_For_Proof),
     Ghost;

   function Context_Cursors_Index (Cursors : Field_Cursors; Fld : Field) return Field_Cursor with
     Annotate =>
       (GNATprove, Inline_For_Proof),
     Ghost;

private

   type Cursor_State is (S_Valid, S_Structural_Valid, S_Invalid, S_Incomplete);

   type Field_Cursor (State : Cursor_State := S_Invalid) is
      record
         Predecessor : Virtual_Field := F_Final;
         case State is
            when S_Valid | S_Structural_Valid =>
               First : RFLX_Types.Bit_Index := RFLX_Types.Bit_Index'First;
               Last : RFLX_Types.Bit_Length := RFLX_Types.Bit_Length'First;
               Value : RFLX_Types.Base_Integer := 0;
            when S_Invalid | S_Incomplete =>
               null;
         end case;
      end record;

   type Field_Cursors is array (Virtual_Field) of Field_Cursor;

   function Structural_Valid (Cursor : Field_Cursor) return Boolean is
     (Cursor.State = S_Valid
      or Cursor.State = S_Structural_Valid);

   function Valid (Cursor : Field_Cursor) return Boolean is
     (Cursor.State = S_Valid);

   function Invalid (Cursor : Field_Cursor) return Boolean is
     (Cursor.State = S_Invalid
      or Cursor.State = S_Incomplete);

   pragma Warnings (Off, """Buffer"" is not modified, could be of access constant type");

   pragma Warnings (Off, "postcondition does not mention function result");

   function Valid_Context (Buffer_First, Buffer_Last : RFLX_Types.Index; First : RFLX_Types.Bit_Index; Last : RFLX_Types.Bit_Length; Verified_Last : RFLX_Types.Bit_Length; Written_Last : RFLX_Types.Bit_Length; Buffer : RFLX_Types.Bytes_Ptr; Cursors : Field_Cursors; Signature_Length : SPDM.Signature_Length; Has_Signature : Boolean) return Boolean is
     ((if Buffer /= null then Buffer'First = Buffer_First and Buffer'Last = Buffer_Last)
      and then (RFLX_Types.To_Index (First) >= Buffer_First
                and RFLX_Types.To_Index (Last) <= Buffer_Last
                and Buffer_Last < RFLX_Types.Index'Last
                and First <= Last + 1
                and Last < RFLX_Types.Bit_Index'Last
                and First rem RFLX_Types.Byte'Size = 1
                and Last rem RFLX_Types.Byte'Size = 0)
      and then First - 1 <= Verified_Last
      and then First - 1 <= Written_Last
      and then Verified_Last <= Written_Last
      and then Written_Last <= Last
      and then First rem RFLX_Types.Byte'Size = 1
      and then Last rem RFLX_Types.Byte'Size = 0
      and then Verified_Last rem RFLX_Types.Byte'Size = 0
      and then Written_Last rem RFLX_Types.Byte'Size = 0
      and then (for all F in Field =>
                   (if
                       Structural_Valid (Cursors (F))
                    then
                       Cursors (F).First >= First
                       and Cursors (F).Last <= Verified_Last
                       and Cursors (F).First <= Cursors (F).Last + 1
                       and Valid_Value (F, Cursors (F).Value)))
      and then ((if
                    Structural_Valid (Cursors (F_Reserved_1))
                 then
                    (Valid (Cursors (F_Number_Of_Indices))
                     and then Cursors (F_Reserved_1).Predecessor = F_Number_Of_Indices))
                and then (if
                             Structural_Valid (Cursors (F_Slot_ID))
                          then
                             (Valid (Cursors (F_Reserved_1))
                              and then Cursors (F_Slot_ID).Predecessor = F_Reserved_1))
                and then (if
                             Structural_Valid (Cursors (F_Number_Of_Blocks))
                          then
                             (Valid (Cursors (F_Slot_ID))
                              and then Cursors (F_Number_Of_Blocks).Predecessor = F_Slot_ID))
                and then (if
                             Structural_Valid (Cursors (F_Measurement_Record_Length))
                          then
                             (Valid (Cursors (F_Number_Of_Blocks))
                              and then Cursors (F_Measurement_Record_Length).Predecessor = F_Number_Of_Blocks))
                and then (if
                             Structural_Valid (Cursors (F_Measurement_Record))
                          then
                             (Valid (Cursors (F_Measurement_Record_Length))
                              and then Cursors (F_Measurement_Record).Predecessor = F_Measurement_Record_Length))
                and then (if
                             Structural_Valid (Cursors (F_Nonce_Data))
                          then
                             (Structural_Valid (Cursors (F_Measurement_Record))
                              and then Cursors (F_Nonce_Data).Predecessor = F_Measurement_Record))
                and then (if
                             Structural_Valid (Cursors (F_Opaque_Length))
                          then
                             (Structural_Valid (Cursors (F_Nonce_Data))
                              and then Cursors (F_Opaque_Length).Predecessor = F_Nonce_Data))
                and then (if
                             Structural_Valid (Cursors (F_Opaque_Data))
                          then
                             (Valid (Cursors (F_Opaque_Length))
                              and then Cursors (F_Opaque_Data).Predecessor = F_Opaque_Length))
                and then (if
                             Structural_Valid (Cursors (F_Signature))
                          then
                             (Structural_Valid (Cursors (F_Opaque_Data))
                              and then Cursors (F_Signature).Predecessor = F_Opaque_Data
                              and then RFLX_Types.Base_Integer (To_Base_Integer (Has_Signature)) = RFLX_Types.Base_Integer (To_Base_Integer (True)))))
      and then ((if Invalid (Cursors (F_Number_Of_Indices)) then Invalid (Cursors (F_Reserved_1)))
                and then (if Invalid (Cursors (F_Reserved_1)) then Invalid (Cursors (F_Slot_ID)))
                and then (if Invalid (Cursors (F_Slot_ID)) then Invalid (Cursors (F_Number_Of_Blocks)))
                and then (if Invalid (Cursors (F_Number_Of_Blocks)) then Invalid (Cursors (F_Measurement_Record_Length)))
                and then (if Invalid (Cursors (F_Measurement_Record_Length)) then Invalid (Cursors (F_Measurement_Record)))
                and then (if Invalid (Cursors (F_Measurement_Record)) then Invalid (Cursors (F_Nonce_Data)))
                and then (if Invalid (Cursors (F_Nonce_Data)) then Invalid (Cursors (F_Opaque_Length)))
                and then (if Invalid (Cursors (F_Opaque_Length)) then Invalid (Cursors (F_Opaque_Data)))
                and then (if Invalid (Cursors (F_Opaque_Data)) then Invalid (Cursors (F_Signature))))
      and then (if
                   Structural_Valid (Cursors (F_Number_Of_Indices))
                then
                   Cursors (F_Number_Of_Indices).Last - Cursors (F_Number_Of_Indices).First + 1 = 8
                   and then Cursors (F_Number_Of_Indices).Predecessor = F_Initial
                   and then Cursors (F_Number_Of_Indices).First = First
                   and then (if
                                Structural_Valid (Cursors (F_Reserved_1))
                             then
                                Cursors (F_Reserved_1).Last - Cursors (F_Reserved_1).First + 1 = 4
                                and then Cursors (F_Reserved_1).Predecessor = F_Number_Of_Indices
                                and then Cursors (F_Reserved_1).First = Cursors (F_Number_Of_Indices).Last + 1
                                and then (if
                                             Structural_Valid (Cursors (F_Slot_ID))
                                          then
                                             Cursors (F_Slot_ID).Last - Cursors (F_Slot_ID).First + 1 = 4
                                             and then Cursors (F_Slot_ID).Predecessor = F_Reserved_1
                                             and then Cursors (F_Slot_ID).First = Cursors (F_Reserved_1).Last + 1
                                             and then (if
                                                          Structural_Valid (Cursors (F_Number_Of_Blocks))
                                                       then
                                                          Cursors (F_Number_Of_Blocks).Last - Cursors (F_Number_Of_Blocks).First + 1 = 8
                                                          and then Cursors (F_Number_Of_Blocks).Predecessor = F_Slot_ID
                                                          and then Cursors (F_Number_Of_Blocks).First = Cursors (F_Slot_ID).Last + 1
                                                          and then (if
                                                                       Structural_Valid (Cursors (F_Measurement_Record_Length))
                                                                    then
                                                                       Cursors (F_Measurement_Record_Length).Last - Cursors (F_Measurement_Record_Length).First + 1 = 24
                                                                       and then Cursors (F_Measurement_Record_Length).Predecessor = F_Number_Of_Blocks
                                                                       and then Cursors (F_Measurement_Record_Length).First = Cursors (F_Number_Of_Blocks).Last + 1
                                                                       and then (if
                                                                                    Structural_Valid (Cursors (F_Measurement_Record))
                                                                                 then
                                                                                    Cursors (F_Measurement_Record).Last - Cursors (F_Measurement_Record).First + 1 = RFLX_Types.Bit_Length (Cursors (F_Measurement_Record_Length).Value) * 8
                                                                                    and then Cursors (F_Measurement_Record).Predecessor = F_Measurement_Record_Length
                                                                                    and then Cursors (F_Measurement_Record).First = Cursors (F_Measurement_Record_Length).Last + 1
                                                                                    and then (if
                                                                                                 Structural_Valid (Cursors (F_Nonce_Data))
                                                                                              then
                                                                                                 Cursors (F_Nonce_Data).Last - Cursors (F_Nonce_Data).First + 1 = 256
                                                                                                 and then Cursors (F_Nonce_Data).Predecessor = F_Measurement_Record
                                                                                                 and then Cursors (F_Nonce_Data).First = Cursors (F_Measurement_Record).Last + 1
                                                                                                 and then (if
                                                                                                              Structural_Valid (Cursors (F_Opaque_Length))
                                                                                                           then
                                                                                                              Cursors (F_Opaque_Length).Last - Cursors (F_Opaque_Length).First + 1 = 16
                                                                                                              and then Cursors (F_Opaque_Length).Predecessor = F_Nonce_Data
                                                                                                              and then Cursors (F_Opaque_Length).First = Cursors (F_Nonce_Data).Last + 1
                                                                                                              and then (if
                                                                                                                           Structural_Valid (Cursors (F_Opaque_Data))
                                                                                                                        then
                                                                                                                           Cursors (F_Opaque_Data).Last - Cursors (F_Opaque_Data).First + 1 = RFLX_Types.Bit_Length (Cursors (F_Opaque_Length).Value) * 8
                                                                                                                           and then Cursors (F_Opaque_Data).Predecessor = F_Opaque_Length
                                                                                                                           and then Cursors (F_Opaque_Data).First = Cursors (F_Opaque_Length).Last + 1
                                                                                                                           and then (if
                                                                                                                                        Structural_Valid (Cursors (F_Signature))
                                                                                                                                        and then RFLX_Types.Base_Integer (To_Base_Integer (Has_Signature)) = RFLX_Types.Base_Integer (To_Base_Integer (True))
                                                                                                                                     then
                                                                                                                                        Cursors (F_Signature).Last - Cursors (F_Signature).First + 1 = RFLX_Types.Bit_Length (Signature_Length) * 8
                                                                                                                                        and then Cursors (F_Signature).Predecessor = F_Opaque_Data
                                                                                                                                        and then Cursors (F_Signature).First = Cursors (F_Opaque_Data).Last + 1)))))))))));

   pragma Warnings (On, """Buffer"" is not modified, could be of access constant type");

   pragma Warnings (On, "postcondition does not mention function result");

   type Context (Buffer_First, Buffer_Last : RFLX_Types.Index := RFLX_Types.Index'First; First : RFLX_Types.Bit_Index := RFLX_Types.Bit_Index'First; Last : RFLX_Types.Bit_Length := RFLX_Types.Bit_Length'First; Signature_Length : SPDM.Signature_Length := SPDM.Signature_Length'First; Has_Signature : Boolean := Boolean'First) is
      record
         Verified_Last : RFLX_Types.Bit_Length := First - 1;
         Written_Last : RFLX_Types.Bit_Length := First - 1;
         Buffer : RFLX_Types.Bytes_Ptr := null;
         Cursors : Field_Cursors := [others => (State => S_Invalid, Predecessor => F_Final)];
      end record with
     Dynamic_Predicate =>
       Valid_Context (Context.Buffer_First, Context.Buffer_Last, Context.First, Context.Last, Context.Verified_Last, Context.Written_Last, Context.Buffer, Context.Cursors, Context.Signature_Length, Context.Has_Signature);

   function Initialized (Ctx : Context) return Boolean is
     (Ctx.Verified_Last = Ctx.First - 1
      and then Valid_Next (Ctx, F_Number_Of_Indices)
      and then RFLX.SPDM.Measurements_Response.Field_First (Ctx, RFLX.SPDM.Measurements_Response.F_Number_Of_Indices) rem RFLX_Types.Byte'Size = 1
      and then Available_Space (Ctx, F_Number_Of_Indices) = Ctx.Last - Ctx.First + 1
      and then (for all F in Field =>
                   Invalid (Ctx, F)));

   function Has_Buffer (Ctx : Context) return Boolean is
     (Ctx.Buffer /= null);

   function Buffer_Length (Ctx : Context) return RFLX_Types.Length is
     (Ctx.Buffer'Length);

   function Size (Ctx : Context) return RFLX_Types.Bit_Length is
     (Ctx.Verified_Last - Ctx.First + 1);

   function Byte_Size (Ctx : Context) return RFLX_Types.Length is
     (RFLX_Types.To_Length (Size (Ctx)));

   function Message_Last (Ctx : Context) return RFLX_Types.Bit_Length is
     (Ctx.Verified_Last);

   function Written_Last (Ctx : Context) return RFLX_Types.Bit_Length is
     (Ctx.Written_Last);

   function Valid_Value (Fld : Field; Val : RFLX_Types.Base_Integer) return Boolean is
     ((case Fld is
          when F_Number_Of_Indices =>
             RFLX.SPDM.Valid_Measurement_Count (Val),
          when F_Reserved_1 =>
             RFLX.SPDM.Valid_Reserved_4 (Val),
          when F_Slot_ID =>
             RFLX.SPDM.Valid_Narrow_Slot (Val),
          when F_Number_Of_Blocks =>
             RFLX.SPDM.Valid_Block_Count (Val),
          when F_Measurement_Record_Length =>
             RFLX.SPDM.Valid_Length_24 (Val),
          when F_Measurement_Record | F_Nonce_Data =>
             True,
          when F_Opaque_Length =>
             RFLX.SPDM.Valid_Length_16 (Val),
          when F_Opaque_Data | F_Signature =>
             True));

   function Path_Condition (Ctx : Context; Fld : Field) return Boolean is
     ((case Ctx.Cursors (Fld).Predecessor is
          when F_Initial | F_Number_Of_Indices | F_Reserved_1 | F_Slot_ID | F_Number_Of_Blocks | F_Measurement_Record_Length | F_Measurement_Record | F_Nonce_Data | F_Opaque_Length | F_Signature | F_Final =>
             True,
          when F_Opaque_Data =>
             RFLX_Types.Base_Integer (To_Base_Integer (Ctx.Has_Signature)) = RFLX_Types.Base_Integer (To_Base_Integer (True))));

   function Field_Condition (Ctx : Context; Fld : Field) return Boolean is
     ((case Fld is
          when F_Number_Of_Indices | F_Reserved_1 | F_Slot_ID | F_Number_Of_Blocks | F_Measurement_Record_Length | F_Measurement_Record | F_Nonce_Data | F_Opaque_Length =>
             True,
          when F_Opaque_Data =>
             RFLX_Types.Base_Integer (To_Base_Integer (Ctx.Has_Signature)) = RFLX_Types.Base_Integer (To_Base_Integer (False))
             or RFLX_Types.Base_Integer (To_Base_Integer (Ctx.Has_Signature)) = RFLX_Types.Base_Integer (To_Base_Integer (True)),
          when F_Signature =>
             True));

   function Field_Size (Ctx : Context; Fld : Field) return RFLX_Types.Bit_Length is
     ((case Fld is
          when F_Number_Of_Indices =>
             8,
          when F_Reserved_1 | F_Slot_ID =>
             4,
          when F_Number_Of_Blocks =>
             8,
          when F_Measurement_Record_Length =>
             24,
          when F_Measurement_Record =>
             RFLX_Types.Bit_Length (Ctx.Cursors (F_Measurement_Record_Length).Value) * 8,
          when F_Nonce_Data =>
             256,
          when F_Opaque_Length =>
             16,
          when F_Opaque_Data =>
             RFLX_Types.Bit_Length (Ctx.Cursors (F_Opaque_Length).Value) * 8,
          when F_Signature =>
             RFLX_Types.Bit_Length (Ctx.Signature_Length) * 8));

   function Field_First (Ctx : Context; Fld : Field) return RFLX_Types.Bit_Index is
     ((if
          Fld = F_Number_Of_Indices
       then
          Ctx.First
       else
          Ctx.Cursors (Ctx.Cursors (Fld).Predecessor).Last + 1));

   function Field_Last (Ctx : Context; Fld : Field) return RFLX_Types.Bit_Length is
     (Field_First (Ctx, Fld) + Field_Size (Ctx, Fld) - 1);

   function Predecessor (Ctx : Context; Fld : Virtual_Field) return Virtual_Field is
     ((case Fld is
          when F_Initial =>
             F_Initial,
          when others =>
             Ctx.Cursors (Fld).Predecessor));

   function Valid_Predecessor (Ctx : Context; Fld : Virtual_Field) return Boolean is
     ((case Fld is
          when F_Initial =>
             True,
          when F_Number_Of_Indices =>
             Ctx.Cursors (Fld).Predecessor = F_Initial,
          when F_Reserved_1 =>
             (Valid (Ctx.Cursors (F_Number_Of_Indices))
              and Ctx.Cursors (Fld).Predecessor = F_Number_Of_Indices),
          when F_Slot_ID =>
             (Valid (Ctx.Cursors (F_Reserved_1))
              and Ctx.Cursors (Fld).Predecessor = F_Reserved_1),
          when F_Number_Of_Blocks =>
             (Valid (Ctx.Cursors (F_Slot_ID))
              and Ctx.Cursors (Fld).Predecessor = F_Slot_ID),
          when F_Measurement_Record_Length =>
             (Valid (Ctx.Cursors (F_Number_Of_Blocks))
              and Ctx.Cursors (Fld).Predecessor = F_Number_Of_Blocks),
          when F_Measurement_Record =>
             (Valid (Ctx.Cursors (F_Measurement_Record_Length))
              and Ctx.Cursors (Fld).Predecessor = F_Measurement_Record_Length),
          when F_Nonce_Data =>
             (Structural_Valid (Ctx.Cursors (F_Measurement_Record))
              and Ctx.Cursors (Fld).Predecessor = F_Measurement_Record),
          when F_Opaque_Length =>
             (Structural_Valid (Ctx.Cursors (F_Nonce_Data))
              and Ctx.Cursors (Fld).Predecessor = F_Nonce_Data),
          when F_Opaque_Data =>
             (Valid (Ctx.Cursors (F_Opaque_Length))
              and Ctx.Cursors (Fld).Predecessor = F_Opaque_Length),
          when F_Signature =>
             (Structural_Valid (Ctx.Cursors (F_Opaque_Data))
              and Ctx.Cursors (Fld).Predecessor = F_Opaque_Data),
          when F_Final =>
             (Structural_Valid (Ctx.Cursors (F_Opaque_Data))
              and Ctx.Cursors (Fld).Predecessor = F_Opaque_Data)
             or (Structural_Valid (Ctx.Cursors (F_Signature))
                 and Ctx.Cursors (Fld).Predecessor = F_Signature)));

   function Valid_Next (Ctx : Context; Fld : Field) return Boolean is
     (Valid_Predecessor (Ctx, Fld)
      and then Path_Condition (Ctx, Fld));

   function Available_Space (Ctx : Context; Fld : Field) return RFLX_Types.Bit_Length is
     (Ctx.Last - Field_First (Ctx, Fld) + 1);

   function Sufficient_Space (Ctx : Context; Fld : Field) return Boolean is
     (Available_Space (Ctx, Fld) >= Field_Size (Ctx, Fld));

   function Present (Ctx : Context; Fld : Field) return Boolean is
     (Structural_Valid (Ctx.Cursors (Fld))
      and then Ctx.Cursors (Fld).First < Ctx.Cursors (Fld).Last + 1);

   function Structural_Valid (Ctx : Context; Fld : Field) return Boolean is
     (Ctx.Cursors (Fld).State = S_Valid
      or Ctx.Cursors (Fld).State = S_Structural_Valid);

   function Valid (Ctx : Context; Fld : Field) return Boolean is
     (Ctx.Cursors (Fld).State = S_Valid
      and then Ctx.Cursors (Fld).First < Ctx.Cursors (Fld).Last + 1);

   function Incomplete (Ctx : Context; Fld : Field) return Boolean is
     (Ctx.Cursors (Fld).State = S_Incomplete);

   function Invalid (Ctx : Context; Fld : Field) return Boolean is
     (Ctx.Cursors (Fld).State = S_Invalid
      or Ctx.Cursors (Fld).State = S_Incomplete);

   function Structural_Valid_Message (Ctx : Context) return Boolean is
     ((Structural_Valid (Ctx, F_Opaque_Data)
       and then RFLX_Types.Base_Integer (To_Base_Integer (Ctx.Has_Signature)) = RFLX_Types.Base_Integer (To_Base_Integer (False)))
      or Structural_Valid (Ctx, F_Signature));

   function Valid_Message (Ctx : Context) return Boolean is
     ((Valid (Ctx, F_Opaque_Data)
       and then RFLX_Types.Base_Integer (To_Base_Integer (Ctx.Has_Signature)) = RFLX_Types.Base_Integer (To_Base_Integer (False)))
      or Valid (Ctx, F_Signature));

   function Incomplete_Message (Ctx : Context) return Boolean is
     ((for some F in Field =>
          Incomplete (Ctx, F)));

   function Get_Number_Of_Indices (Ctx : Context) return RFLX.SPDM.Measurement_Count is
     (To_Actual (Ctx.Cursors (F_Number_Of_Indices).Value));

   function Get_Reserved_1 (Ctx : Context) return RFLX.SPDM.Reserved_4 is
     (To_Actual (Ctx.Cursors (F_Reserved_1).Value));

   function Get_Slot_ID (Ctx : Context) return RFLX.SPDM.Narrow_Slot is
     (To_Actual (Ctx.Cursors (F_Slot_ID).Value));

   function Get_Number_Of_Blocks (Ctx : Context) return RFLX.SPDM.Block_Count is
     (To_Actual (Ctx.Cursors (F_Number_Of_Blocks).Value));

   function Get_Measurement_Record_Length (Ctx : Context) return RFLX.SPDM.Length_24 is
     (To_Actual (Ctx.Cursors (F_Measurement_Record_Length).Value));

   function Get_Opaque_Length (Ctx : Context) return RFLX.SPDM.Length_16 is
     (To_Actual (Ctx.Cursors (F_Opaque_Length).Value));

   function Valid_Size (Ctx : Context; Fld : Field; Size : RFLX_Types.Bit_Length) return Boolean is
     (Size = Field_Size (Ctx, Fld))
    with
     Pre =>
       RFLX.SPDM.Measurements_Response.Valid_Next (Ctx, Fld);

   function Valid_Length (Ctx : Context; Fld : Field; Length : RFLX_Types.Length) return Boolean is
     (Valid_Size (Ctx, Fld, RFLX_Types.To_Bit_Length (Length)));

   function Complete_Measurement_Record (Ctx : Context; Seq_Ctx : RFLX.SPDM.Measurement_Record.Context) return Boolean is
     (RFLX.SPDM.Measurement_Record.Valid (Seq_Ctx)
      and RFLX.SPDM.Measurement_Record.Size (Seq_Ctx) = Field_Size (Ctx, F_Measurement_Record));

   function Context_Cursor (Ctx : Context; Fld : Field) return Field_Cursor is
     (Ctx.Cursors (Fld));

   function Context_Cursors (Ctx : Context) return Field_Cursors is
     (Ctx.Cursors);

   function Context_Cursors_Index (Cursors : Field_Cursors; Fld : Field) return Field_Cursor is
     (Cursors (Fld));

end RFLX.SPDM.Measurements_Response;
