--
--  Generated by RecordFlux 0.6.1.dev1+g8b82b38a0 on 2022-12-02
--
--  Copyright (C) 2018-2022 AdaCore
--
--  SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
--

pragma Restrictions (No_Streams);
pragma Style_Checks ("N3aAbcdefhiIklnOprStux");
pragma Warnings (Off, "redundant conversion");
with RFLX.SPDM_Proxy.Proxy_Allocator;
with RFLX.RFLX_Types;
with RFLX.SPDM_Emu;
with RFLX.SPDM_Emu.Platform_Port;
with RFLX.SPDM_Proxy.Packet;

package RFLX.SPDM_Proxy.Proxy with
  SPARK_Mode
is

   use type RFLX.RFLX_Types.Index;

   use type RFLX.RFLX_Types.Length;

   type Channel is (C_Emu_Transport, C_SPDM_Transport);

   type State is (S_Proxy_Receive_Request, S_Proxy_Prepare_Request, S_Proxy_Send_Request, S_Proxy_Receive_Response, S_Proxy_Prepare_Response, S_Proxy_Send_Response, S_Proxy_Prepare_Shutdown, S_Proxy_Send_Shutdown, S_Proxy_Error, S_Proxy_Shutdown);

   type Private_Context is private;

   type Context is abstract tagged limited
      record
         P : Private_Context;
      end record;

   function Uninitialized (Ctx : Context'Class) return Boolean;

   function Initialized (Ctx : Context'Class) return Boolean;

   function Active (Ctx : Context'Class) return Boolean;

   procedure Initialize (Ctx : in out Context'Class) with
     Pre =>
       Uninitialized (Ctx),
     Post =>
       Initialized (Ctx)
       and Active (Ctx);

   procedure Finalize (Ctx : in out Context'Class) with
     Pre =>
       Initialized (Ctx),
     Post =>
       Uninitialized (Ctx)
       and not Active (Ctx);

   pragma Warnings (Off, "subprogram ""Tick"" has no effect");

   procedure Tick (Ctx : in out Context'Class) with
     Pre =>
       Initialized (Ctx),
     Post =>
       Initialized (Ctx);

   pragma Warnings (On, "subprogram ""Tick"" has no effect");

   function In_IO_State (Ctx : Context'Class) return Boolean;

   pragma Warnings (Off, "subprogram ""Run"" has no effect");

   procedure Run (Ctx : in out Context'Class) with
     Pre =>
       Initialized (Ctx),
     Post =>
       Initialized (Ctx);

   pragma Warnings (On, "subprogram ""Run"" has no effect");

   function Next_State (Ctx : Context'Class) return State;

   function Has_Data (Ctx : Context'Class; Chan : Channel) return Boolean with
     Pre =>
       Initialized (Ctx);

   function Read_Buffer_Size (Ctx : Context'Class; Chan : Channel) return RFLX_Types.Length with
     Pre =>
       Initialized (Ctx)
       and then Has_Data (Ctx, Chan);

   procedure Read (Ctx : Context'Class; Chan : Channel; Buffer : out RFLX_Types.Bytes; Offset : RFLX_Types.Length := 0) with
     Pre =>
       Initialized (Ctx)
       and then Has_Data (Ctx, Chan)
       and then Buffer'Length > 0
       and then Offset <= RFLX_Types.Length'Last - Buffer'Length
       and then Buffer'Length + Offset <= Read_Buffer_Size (Ctx, Chan),
     Post =>
       Initialized (Ctx);

   function Needs_Data (Ctx : Context'Class; Chan : Channel) return Boolean with
     Pre =>
       Initialized (Ctx);

   function Write_Buffer_Size (Ctx : Context'Class; Chan : Channel) return RFLX_Types.Length with
     Pre =>
       Initialized (Ctx)
       and then Needs_Data (Ctx, Chan);

   procedure Write (Ctx : in out Context'Class; Chan : Channel; Buffer : RFLX_Types.Bytes; Offset : RFLX_Types.Length := 0) with
     Pre =>
       Initialized (Ctx)
       and then Needs_Data (Ctx, Chan)
       and then Buffer'Length > 0
       and then Offset <= RFLX_Types.Length'Last - Buffer'Length
       and then Buffer'Length + Offset <= Write_Buffer_Size (Ctx, Chan),
     Post =>
       Initialized (Ctx);

private

   type Private_Context is
      record
         Next_State : State := S_Proxy_Receive_Request;
         Emu_Packet_Ctx : SPDM_Emu.Platform_Port.Context;
         SPDM_Packet_Ctx : SPDM_Proxy.Packet.Context;
         Slots : SPDM_Proxy.Proxy_Allocator.Slots;
         Memory : SPDM_Proxy.Proxy_Allocator.Memory;
      end record;

   function Uninitialized (Ctx : Context'Class) return Boolean is
     (not SPDM_Emu.Platform_Port.Has_Buffer (Ctx.P.Emu_Packet_Ctx)
      and not SPDM_Proxy.Packet.Has_Buffer (Ctx.P.SPDM_Packet_Ctx)
      and SPDM_Proxy.Proxy_Allocator.Uninitialized (Ctx.P.Slots));

   function Global_Initialized (Ctx : Context'Class) return Boolean is
     (SPDM_Emu.Platform_Port.Has_Buffer (Ctx.P.Emu_Packet_Ctx)
      and then Ctx.P.Emu_Packet_Ctx.Buffer_First = RFLX_Types.Index'First
      and then Ctx.P.Emu_Packet_Ctx.Buffer_Last = RFLX_Types.Index'First + 4095
      and then SPDM_Proxy.Packet.Has_Buffer (Ctx.P.SPDM_Packet_Ctx)
      and then Ctx.P.SPDM_Packet_Ctx.Buffer_First = RFLX_Types.Index'First
      and then Ctx.P.SPDM_Packet_Ctx.Buffer_Last = RFLX_Types.Index'First + 4095);

   function Initialized (Ctx : Context'Class) return Boolean is
     (Global_Initialized (Ctx)
      and then SPDM_Proxy.Proxy_Allocator.Global_Allocated (Ctx.P.Slots));

   function Active (Ctx : Context'Class) return Boolean is
     (Ctx.P.Next_State /= S_Proxy_Shutdown);

   function Next_State (Ctx : Context'Class) return State is
     (Ctx.P.Next_State);

   function Has_Data (Ctx : Context'Class; Chan : Channel) return Boolean is
     ((case Chan is
          when C_Emu_Transport =>
             (case Ctx.P.Next_State is
                 when S_Proxy_Send_Response | S_Proxy_Send_Shutdown =>
                    SPDM_Emu.Platform_Port.Structural_Valid_Message (Ctx.P.Emu_Packet_Ctx)
                    and SPDM_Emu.Platform_Port.Byte_Size (Ctx.P.Emu_Packet_Ctx) > 0,
                 when others =>
                    False),
          when C_SPDM_Transport =>
             (case Ctx.P.Next_State is
                 when S_Proxy_Send_Request =>
                    SPDM_Proxy.Packet.Structural_Valid_Message (Ctx.P.SPDM_Packet_Ctx)
                    and SPDM_Proxy.Packet.Byte_Size (Ctx.P.SPDM_Packet_Ctx) > 0,
                 when others =>
                    False)));

   function Read_Buffer_Size (Ctx : Context'Class; Chan : Channel) return RFLX_Types.Length is
     ((case Chan is
          when C_Emu_Transport =>
             (case Ctx.P.Next_State is
                 when S_Proxy_Send_Response | S_Proxy_Send_Shutdown =>
                    SPDM_Emu.Platform_Port.Byte_Size (Ctx.P.Emu_Packet_Ctx),
                 when others =>
                    RFLX_Types.Unreachable),
          when C_SPDM_Transport =>
             (case Ctx.P.Next_State is
                 when S_Proxy_Send_Request =>
                    SPDM_Proxy.Packet.Byte_Size (Ctx.P.SPDM_Packet_Ctx),
                 when others =>
                    RFLX_Types.Unreachable)));

   function Needs_Data (Ctx : Context'Class; Chan : Channel) return Boolean is
     ((case Chan is
          when C_Emu_Transport =>
             (case Ctx.P.Next_State is
                 when S_Proxy_Receive_Request =>
                    True,
                 when others =>
                    False),
          when C_SPDM_Transport =>
             (case Ctx.P.Next_State is
                 when S_Proxy_Receive_Response =>
                    True,
                 when others =>
                    False)));

   function Write_Buffer_Size (Ctx : Context'Class; Chan : Channel) return RFLX_Types.Length is
     ((case Chan is
          when C_Emu_Transport =>
             (case Ctx.P.Next_State is
                 when S_Proxy_Receive_Request =>
                    SPDM_Emu.Platform_Port.Buffer_Length (Ctx.P.Emu_Packet_Ctx),
                 when others =>
                    RFLX_Types.Unreachable),
          when C_SPDM_Transport =>
             (case Ctx.P.Next_State is
                 when S_Proxy_Receive_Response =>
                    SPDM_Proxy.Packet.Buffer_Length (Ctx.P.SPDM_Packet_Ctx),
                 when others =>
                    RFLX_Types.Unreachable)));

end RFLX.SPDM_Proxy.Proxy;
