/*
 * SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES.
 * All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#pragma once
#include <stdint.h>

#include "pdk-spdm-app-res-ada-library.h"

namespace pdk::spdm::app::res::measurements {
#ifdef __cplusplus
extern "C" {
#endif

constexpr uint8_t MaxNumMeas = 254u;
uint8_t           spdm_platform_get_number_of_indices(
              pdk::spdm::platforms::res::ada::library::PlatformContext* instance);

void spdm_platform_get_nonce(pdk::spdm::platforms::res::ada::library::PlatformContext* instance,
                             void*                                                     nonce);

void spdm_platform_get_dmtf_measurement_field(
    pdk::spdm::platforms::res::ada::library::PlatformContext* instance,
    uint32_t                                                  index,
    uint32_t*                                                 representation,
    uint32_t*                                                 type,
    uint32_t*                                                 size,
    void*                                                     buffer);

void spdm_platform_get_meas_opaque_data(
    pdk::spdm::platforms::res::ada::library::PlatformContext* instance,
    void*                                                     data,
    uint32_t*                                                 size);

/**
 * Register a new transcript with the platform.
 *
 * The returned ID must be used on all subsequent operations on the same
 * transcript.
 *
 * @param instance Platform instance.
 * @param kind Transcript kind enum with the following values:
 *             Session transcript     => 0
 *             Measurement transcript => 1
 * @return 32 bit transcript ID. On success spdm_platform_valid_transcript_id
 *         must return true on this ID.
 */
uint32_t spdm_platform_get_new_transcript(
    pdk::spdm::platforms::res::ada::library::PlatformContext* instance, uint8_t kind);

/**
 * Indicate whether a transcript ID is valid.
 *
 * @param instance Platform instance.
 * @param transcript Transcript ID.
 * @return True if transcript ID is valid.
 */
uint8_t spdm_platform_valid_transcript_id(
    pdk::spdm::platforms::res::ada::library::PlatformContext* instance, uint32_t transcript);

/**
 * Reset an already registered transcript.
 *
 * This operation may change the transcript kind, too. The returned transcript
 * ID may be different from the provided one. It has the same behaviour as
 * spdm_platform_get_new_transcript except that it allows reusing an existing
 * resource.
 *
 * @param instance Platform instance.
 * @param transcript Old transcript ID.
 * @param kind Transcript kind for the new transcript.
 * @return New 32 bit transcript ID.
 */
uint32_t spdm_platform_reset_transcript(
    pdk::spdm::platforms::res::ada::library::PlatformContext* instance,
    uint32_t                                                  transcript,
    uint8_t                                                   kind);

/**
 * Append a chunk of data to the transcript.
 *
 * @param instance Platform instance.
 * @param transcript Transcript ID.
 * @param data Transcript data to be appended.
 * @param offset Offset in data.
 * @param length Length of data to be appended to the transcript,
 *               length + offset is less or equal to the size of data.
 * @return Success.
 */
uint8_t spdm_platform_update_transcript(
    pdk::spdm::platforms::res::ada::library::PlatformContext* instance,
    uint32_t                                                  transcript,
    void*                                                     data,
    uint32_t                                                  offset,
    uint32_t                                                  length);

/**
 * Append the latest generated nonce to the transcript.
 *
 * Append the latest nonce generated by spdm_platform_get_nonce to the
 * transcript. The nonce must be marked as invalid after this operation.
 * If the nonce is already marked as invalid when this function is called
 * the operation must fail.
 *
 * @param instance Platform instance.
 * @param transcript Transcript ID.
 * @return Success.
 */
uint8_t spdm_platform_update_transcript_nonce(
    pdk::spdm::platforms::res::ada::library::PlatformContext* instance, uint32_t transcript);

/**
 * Generate signature from current transcript.
 *
 * Generate the signature from the current state of the transcript. This
 * does not invalidate or reset the transcript.
 *
 * @param instance Platform instance.
 * @param transcript Transcript ID.
 * @param slot Slot ID of the signing key.
 * @param signature Signature buffer.
 * @param length Signature buffer length. The initial value contains the maximum
 * length of the signature buffer. On return the value shall be the correct
 *               length for the signature algorithm selected in
 * Negotiate_Algorithms. On error length can be set to 0.
 */
void spdm_platform_get_signature(
    pdk::spdm::platforms::res::ada::library::PlatformContext* instance,
    uint32_t                                                  transcript,
    uint8_t                                                   slot,
    void*                                                     signature,
    uint32_t*                                                 length);

#ifdef __cplusplus
}
#endif

}  // namespace pdk::spdm::app::res::measurements