/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define PCR_DSE_dse1 0x01u /*!<@brief Drive Strength Enable: High */
#define PCR_IBE_ibe1 0x01u /*!<@brief Input Buffer Enable: Enables */
#define PCR_PE_pe1 0x01u   /*!<@brief Pull Enable: Enables */
#define PCR_PFE_pfe0 0x00u /*!<@brief Passive Filter Enable: Disables */
#define PCR_PS_ps1 0x01u   /*!<@brief Pull Select: Enables internal pullup resistor */
#define PCR_PV_pv1 0x01u   /*!<@brief Pull Value: High */

/*! @name PORT4_12 (coord T6), GA_GPIO9_IROT_ERROR_N
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_IROT_ERROR_GPIO GPIO4                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_IROT_ERROR_GPIO_PIN 12U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_IROT_ERROR_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_IROT_ERROR_PORT PORT4                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_IROT_ERROR_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_IROT_ERROR_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORT4_13 (coord T7), GA_GPIO10_IROT_AP_BOOT_COMPLETE
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_IROT_BOOT_GPIO GPIO4                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_IROT_BOOT_GPIO_PIN 13U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_IROT_BOOT_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_IROT_BOOT_PORT PORT4                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_IROT_BOOT_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_IROT_BOOT_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORT4_15 (coord T8), THERM_OVERT
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_THERM_GPIO GPIO4                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_THERM_GPIO_PIN 15U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_THERM_GPIO_PIN_MASK (1U << 15U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_THERM_PORT PORT4                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_THERM_PIN 15U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_THERM_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORT4_20 (coord T10), PS_BOARD_PGOOD
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_PGOOD_GPIO GPIO4                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_PGOOD_GPIO_PIN 20U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_PGOOD_GPIO_PIN_MASK (1U << 20U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_PGOOD_PORT PORT4                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_PGOOD_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_PGOOD_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
