# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES.
# All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


ifneq (,$(filter unittest coverage,$(MAKECMDGOALS)))
include $(UBS_PATH_ROOT)/ubs-cmn.mk

# the unittest suffix file-test.cpp file-test.adb
UBS_UNITTEST_SUFFIX ?= -test

ifneq (,$(filter unittest,$(MAKECMDGOALS)))
# remove main entrypoint files and replace with unittests harness
# coverage case will use the main of project
UBS_SRCS := $(filter-out $(UBS_MAIN),$(UBS_SRCS))
UBS_MAIN := $(UBS_PATH_GEN)/ubs-unittest-main.cpp
UBS_UNITTEST_SOURCES := $(wildcard $(UBS_PATH_ROOT)/unittest/*.*) $(UBS_PATH_ROOT)/ubs.ads
else
#coverage case, use project main
UBS_UNITTEST_SOURCES := $(filter-out $(UBS_PATH_ROOT)/unittest/ubs-unittest-main.cpp, $(wildcard $(UBS_PATH_ROOT)/unittest/*.*) $(UBS_PATH_ROOT)/ubs.ads)
endif

# update SRCS
UBS_SRCS += $(UBS_UNITTEST_SOURCES)

# locate all unittest files and add to SRCS 
# this also creates GD_UBS_UNITTEST_CPP_COUNT
UBS_UNITTEST_TEST_FILES := $(ubs_find_unittests '$(UBS_SRCS)')
UBS_SRCS += $(UBS_UNITTEST_TEST_FILES)

# add spec files for all unittests for auto-generation
UBS_UNITTEST_ADA_SPECS := $(filter %.adb,$(UBS_UNITTEST_TEST_FILES))
UBS_UNITTEST_ADA_SPECS := $(addprefix $(UBS_PATH_GEN)/, $(UBS_UNITTEST_ADA_SPECS:.adb=.ads))
UBS_SRCS += $(UBS_UNITTEST_ADA_SPECS)

# add in console module requirement
UBS_SRCS += $(UBS_CMN_CONSOLE) $(UBS_CMN_CONSOLE_CPP) $(UBS_CMN_FLOWCONTROL)

# -- global defines ---------------------------------------------------------------------------
GD_UBS_UNITTEST := 1

# -- Detect if mcu unittest failures ----------------------------------------------------------
UBS_MCU_DETECTOR = if grep -E -q '<failure[^>]*>FAIL ' $(UBS_PATH_REPORTS)/junit.xml; then \
                        printf "$(ubs-error-fmt) Found Unittest Failures\n"; \
                        exit 1; \
                   fi

# -- UBS awk filter (prints to stderr, exits 1 on fail) ----------------------------------------
UBS_UTS_FILTER := $(UBS_AWK) '\
BEGIN { pass = 0; warn = 0; fail = 0; printf "$(ubs-info-fmt) unittest: [" > "/dev/stderr" } \
/^P:[^:]+:[0-9]+/ { if (pass % 99 == 98) printf "]\n$(ubs-info-fmt) unittest: [" > "/dev/stderr"; else printf "." > "/dev/stderr"; pass++; print; next } \
/^W:[^:]+:[0-9]+/ { printf "$(ubs-warn-fmt) %s\n", $$0 > "/dev/stderr"; warn++; print; next } \
/^F:[^:]+:[0-9]+/ { printf "]\n$(ubs-error-fmt) %s\n", $$0 > "/dev/stderr"; fail++; print; exit 1 } \
END { if (fail == 0) printf "]\n" > "/dev/stderr"; printf "$(ubs-info-fmt) unittest: %d pass %d warnings %d fails\n", pass, warn, fail > "/dev/stderr" }'

# -- Unittest rule ------------------------------------------------------------------------------
unittest: | build
	@$(ubs_banner_str 'UNITTEST')
	@$(call ubs-create-folder, $(UBS_PATH_REPORTS))
	if [ "$(MAKECMDGOALS)" = "coverage" ]; then \
		$(UBS_TARGET) | $(UBS_PATH_ROOT)/mcu-to-junit-xml.py --tee --project mcu $(UBS_PATH_REPORTS)/junit.xml; \
		$(UBS_MCU_DETECTOR); \
	else \
		echo "$(UBS_SRCS)" > $(UBS_PATH_GEN)/sources; \
		echo "Step 1: running UBS_TARGET through filter"; \
		$(UBS_TARGET) 2>&1 | $(UBS_UTS_FILTER) > $(UBS_PATH_GEN)/filtered.log; \
		echo "Step 2: converting filtered.log to junit.xml"; \
		$(UBS_PATH_ROOT)/to-junit-xml.py --sources $(UBS_PATH_GEN)/sources \
			$(UBS_PATH_REPORTS)/junit.xml < $(UBS_PATH_GEN)/filtered.log; \
	fi

# -- Autogens ----------------------------------------------------------------------------------
# turn the filename into a ada package name
ubs-unittest-file2pkg = $(subst -,.,$(notdir $(basename $(1))))

# auto-generate the spec files for each ada unittest
$(UBS_PATH_GEN)/%$(UBS_UNITTEST_SUFFIX).ads:
	$(ubs-build) "GEN" "$@"
	$(call ubs-create-target-folder)
	@echo "-- Autogenerated unittest spec --" > $@
	@echo "package $(call ubs-unittest-file2pkg,$@) is" >> $@
	@echo "pragma elaborate_body;" >> $@
	@echo "end;" >> $@

.PHONY: unittest
.SILENT:
.NOTPARALLEL: unittest
endif
