# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES.
# All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import ubs
import ubs_gmk
import re
import os
import filecmp

def ex(x) : return ubs_gmk.expand(f'$(strip $({x}))')

# evaluate and expand differently for a string and value
def _ubs_expand_var(var):
    noexpand = ubs_gmk.expand(f'$(strip $(value {var}))')

    # string
    if re.match(r'[\'"]([^\'"]+)[\'"]', noexpand):
        def func(m):
            val = ubs_gmk.expand(m[0])
            # issue a warning if this is undefined 
            if val == "":
                fmt = ubs_gmk.expand('$(ubs-warn-fmt)')
                print(f"{fmt} undefined variable: {m[0]}")
                return val
            return str(eval(val))

        val = re.sub(r'\$\(.+\)', func, noexpand)
    # value
    else:
        val = ex(var)
        val = eval(val)

    return val

def _ubs_expand_feature(var):
    val = ex(var)
    val = int(eval(val))

    if re.match(r'FEATURE_([A-Za-z][A-Za-z0-9_]+)', var):
        id = var[8:]
    else:
        ubs.ubs_error(f"invalid feature name: '{var}'\n")
        ubs.ubs_error(f"  format is FEATURE_Name\n")
        ubs.ubs_error(f"    c   ==> (enum)                  UbsFeaturesName\n")
        ubs.ubs_error(f"    c++ ==> (namespace + constexpr) ubs::features::Name\n")
        ubs.ubs_error(f"    ada ==> (module + constant)     Ubs.Features.Name\n")
        ubs.ubs_fatal(f"  aborting...")

    return id,val

def write_if_changed(filename, content):
    os.makedirs(os.path.dirname(filename), exist_ok=True)
    #genereate target_file_new first to compare
    temp_filename = f"{filename}_new"
    with open(temp_filename, "wt") as fout:
        fout.write(content)

    # if the target file does not exist or different, replace it
    if not os.path.exists(filename) or not filecmp.cmp(temp_filename, filename, shallow=False):
        ubs.ubs_info(f"autogenerating global-defines: {filename}\n")
        os.replace(temp_filename, filename)
    else:
        os.remove(temp_filename)


def ubs_global_defines():

    # import all the global defines
    vars = ubs_gmk.expand('$(filter GD_%,$(.VARIABLES))').split()

    for var in vars:
        # add to the global in ubs module
        ubs.global_defines[var[3:]] = _ubs_expand_var(var)

    # import all features
    feats = ubs_gmk.expand('$(filter FEATURE_%,$(.VARIABLES))').split()

    for var in feats:
        # add to the global in ubs module
        id,val = _ubs_expand_feature(var)
        ubs.global_features[id] = val

    # dump to ada def file
    fname_def = ex('UBS_ADA_GLOBAL_DEFINES')
    fname_ada = ex('UBS_ADA_GLOBAL_DEFINES_LIST')
    fname_feats_ada = os.path.join(ex('UBS_PATH_GEN'),"ubs-features.ads")

    if not os.path.exists(os.path.dirname(fname_def)):
        os.makedirs(os.path.dirname(fname_def))

    fname_def_content = "-- UBS: autogenerated global defines\n"
    fname_def_content += f'* "{os.path.basename(fname_ada)}"\n'
    write_if_changed(fname_def, fname_def_content)

    fname_ada_content = "-- UBS: autogenerated global defines\n"
    for var,val in ubs.global_defines.items():
            fname_ada_content += f'{var} := {val}\n'
    write_if_changed(fname_ada, fname_ada_content)
    
    # ubs features file for ada
    fname_feats_ada_content = "-- UBS: autogenerated global features\n"
    fname_feats_ada_content += "package Ubs.Features is\n"
    for var,val in ubs.global_features.items():
        fname_feats_ada_content += f'   {var} : constant boolean := {"True" if val else "False"};\n'
        fname_feats_ada_content += f'    -- @private\n'
    fname_feats_ada_content += f'   Count: constant Integer := {len(ubs.global_features)};\n'
    fname_feats_ada_content += f'    -- @private\n'
    fname_feats_ada_content += "end;\n"
    write_if_changed(fname_feats_ada, fname_feats_ada_content)

    # dump to C/C++ defines file
    fname_cpp = ex('UBS_CPP_GLOBAL_DEFINES_LIST')
    fname_cpp_content = "// UBS: autogenerated global defines C\n"
    for var,val in ubs.global_defines.items():
        fname_cpp_content += f'#ifndef {var}\n'
        fname_cpp_content += f'#define {var} {val}\n'
        fname_cpp_content += f'#endif\n'
    # keep define versions for use in LD/ASM files
    fname_cpp_content +="// UBS: autogenerated global features C\n"
    for var,val in ubs.global_features.items():
        fname_cpp_content += f'#ifndef UBS_FEATURES_{var}\n'
        fname_cpp_content += f'#define UBS_FEATURES_{var} {val}\n'
        fname_cpp_content += f'#endif\n'
    write_if_changed(fname_cpp, fname_cpp_content)

     # dump to C/C++ features file
    fname_feats_cpp = os.path.join(ex('UBS_PATH_GEN'),"ubs-features.h")
    fname_feats_cpp_content = "\n#ifndef UBS_GEN_FEATURES_H\n"
    fname_feats_cpp_content += "#define UBS_GEN_FEATURES_H\n"
    fname_feats_cpp_content += "\n// NOLINTBEGIN\n"
    fname_feats_cpp_content += "\n#ifndef __ASSEMBLER__\n"   # don't include for .S
    fname_feats_cpp_content += "\n// UBS: autogenerated features C\n"
    fname_feats_cpp_content += "typedef enum { \n"
    for var,val in ubs.global_features.items():
        fname_feats_cpp_content += f'    UbsFeatures{var} = {val},\n'
    fname_feats_cpp_content += f"    UbsFeaturesCount = {len(ubs.global_features)}\n"
    fname_feats_cpp_content += "} UbsFeatures;\n"

    fname_feats_cpp_content +="\n// UBS: autogenerated features C++\n"
    fname_feats_cpp_content +="#ifdef __cplusplus\n"
    fname_feats_cpp_content +="namespace ubs::features {\n"
    for var,val in ubs.global_features.items():
        fname_feats_cpp_content +=f'    constexpr auto {var} = {val};\n'
    fname_feats_cpp_content += f'    constexpr auto Count = {len(ubs.global_features)};\n'
    fname_feats_cpp_content += "}// namespace ubs::features\n"
    fname_feats_cpp_content += "#endif // __cplusplus\n"
    fname_feats_cpp_content += "#endif // __ASSEMBLER__\n"
    fname_feats_cpp_content += "\n// NOLINTEND\n"
    fname_feats_cpp_content += "\n#endif // UBS_GEN_FEATURES_H\n"
    write_if_changed(fname_feats_cpp, fname_feats_cpp_content)

    # add preproc files to flags
    ubs_gmk.eval(f'UBS_CC_FLAGS  += --include={fname_cpp} --include={fname_feats_cpp}') 
    ubs_gmk.eval(f'UBS_CXX_FLAGS += --include={fname_cpp} --include={fname_feats_cpp}') 
    ubs_gmk.eval(f'UBS_CPP_FLAGS += --include={fname_cpp}') # don't add C/C++ for ld/s files
    ubs_gmk.eval(f'UBS_ADA_FLAGS += -I$(UBS_PATH_GEN) -gnatep={fname_def}')

    return None

ubs_global_defines()
