/*
 * SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES.
 * All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "nv/volt_mon/adc.h"

#include NV_IPC_CONFIG_H

namespace nv::volt_mon {

using namespace nv::ipc::voltage_monitor_config;

namespace {
// VoltMon dispatches results from a single FIFO per ADC instance; see Adc class
// header comment for the FIFO0-only design contract.
constexpr uint8_t kResultFifo = 0;
}  // namespace

bool Adc::inited = false;

/**
 * @brief Initialize shared ADC resources for voltage monitoring
 *
 * @note ADC command chains are generated by the Config Tool. This function only enables the
 *       selected ADC instances and binds the sampling software trigger to the chain entry CMD1.
 */
void Adc::init()
{
    if (inited) {
        return;
    }

    sys::adc::ADC::enable_vref();

    if constexpr (SensorOnAdc0) {
        sys::adc::ADC::enable_adc(static_cast<uint32_t>(AdcInstance::_0), true);
        sys::adc::ADC::set_adc_trigger(static_cast<uint32_t>(AdcInstance::_0),
                                       static_cast<uint32_t>(AdcSamplingTriggerSrc),
                                       static_cast<uint32_t>(AdcCommand::_1));
    }
    if constexpr (SensorOnAdc1) {
        sys::adc::ADC::enable_adc(static_cast<uint32_t>(AdcInstance::_1), true);
        sys::adc::ADC::set_adc_trigger(static_cast<uint32_t>(AdcInstance::_1),
                                       static_cast<uint32_t>(AdcSamplingTriggerSrc),
                                       static_cast<uint32_t>(AdcCommand::_1));
    }

    inited = true;
}

/**
 * @brief Trigger one ADC sampling round.
 *
 * Resets FIFO0 before re-arming the software trigger so we always start the
 * round from an empty FIFO. The drain loop in the timer callback runs to
 * completion before this point under normal operation; the reset is a defensive
 * safeguard against half-drained leftovers from a missed tick or a previous
 * pre-emption.
 */
void Adc::trigger_sampling(AdcInstance adcId)
{
    const auto peripheral = static_cast<uint32_t>(adcId);
    sys::adc::ADC::reset_fifo(peripheral, kResultFifo);
    sys::adc::ADC::trigger_read(peripheral, 1 << static_cast<uint32_t>(AdcSamplingTriggerSrc));
}

/**
 * @brief Pop one ADC result from FIFO0.
 *
 * @return true if one result was popped, false if FIFO0 is empty or the read failed.
 *
 * @note Non-blocking; the caller owns the drain loop and dispatch context.
 *       VoltMon is FIFO0-only — see adc.h class comment for the design contract.
 */
bool Adc::pop_result(AdcInstance adcId, sys::adc::ADC::AdcConvResult& result)
{
    const auto peripheral = static_cast<uint32_t>(adcId);

    if (sys::adc::ADC::get_fifo_count(peripheral, kResultFifo) == 0) {
        return false;
    }

    return sys::adc::ADC::get_adc_reading(peripheral, result, kResultFifo);
}

}  // namespace nv::volt_mon
